### ISSUE TITLE
React Native cannot find variable self

### ISSUE THREAD

**Issue by jasonkuhrt** [apollographql/apollo-client#1956] opened 2017-07-27 20:31 UTC
**Intended outcome:**

I started a new React Native project via `yarn create react-native-app` and then `yarn add apollo-client`. I try to import it like so:

```js
import ApolloClient, { createNetworkInterface } from "apollo-client"
```

**Actual outcome:**

![image](https://user-images.githubusercontent.com/284476/28690929-fe5d0870-72e8-11e7-94ad-462b6fc0f9b3.png)

**How to reproduce the issue:**

**Version**
- apollo-client@1.9.0-1

**Comment by aryo** [comment] 2017-07-28 03:38
Same here

**Comment by acomito** [comment] 2017-07-28 11:51
downgrade to apollo-client@1.9.0 worked for me, for now.

**Comment by c316** [comment] 2017-07-31 18:34
1.9.0 doesn't exist. Deleted the node_modules directory, then removed apollo-client from the package.json file. I then did a `npm install apollo-client@1.9.0-0 --save` and it is working for me.

**Comment by jbaxleyiii** [comment] 2017-07-31 18:45
@evanshauser this will be fixed with the link-core PR yes?

**Comment by jbaxleyiii** [comment] 2017-07-31 18:45
This should be fixed via https://github.com/apollographql/apollo-client/pull/1955

**Comment by LilyMGoh** [comment] 2017-08-01 21:55
I just upgraded to 1.9.0-1. It seems like the issue is still not fixed.

**Comment by evanshauser** [comment] 2017-08-03 22:32
@jbaxleyiii Yes this should be fixed in 1.9.0 with the move to `apollo-link-core`

@LilyMGoh @jasonkuhrt @aryo Let us know if it still fails. I have tested `yarn create react-native-app` and `yarn add apollo-client` on an android successfully

**Comment by aryo** [comment] 2017-08-03 23:23
@evanshauser yup just tried 1.9.0, all is well.

**Comment by evanshauser** [comment] 2017-08-03 23:44
@aryo Awesome thank you for confirming!

**Closed by evanshauser** 2017-08-03 23:44 UTC

**Comment by jasonkuhrt** [comment] 2017-08-05 01:22
Thanks guys
