### ISSUE TITLE
Uncaught ReferenceError: exports is not defined at version 3.3.18 and Parcel

### ISSUE THREAD

**Issue by irenlian** [apollographql/apollo-client#8675] opened 2021-08-20 09:41 UTC
**Intended outcome:**

The version of `@apollo/client` is upgraded from 3.3.17 to 3.3.18 safely and the built application is running without issues. 

**Actual outcome:**

After upgrade and build without issues, the application fails from the start with a blank page and an error in console:
```
Uncaught ReferenceError: $24a7145fde937c9e5b0a055eaa64c5e1$exports is not defined
```

**How to reproduce the issue:**

- Set dependencies:
```
"@babel/core": "^7.10.1",
"@parcel/config-default": "^2.0.0-beta.1",
"@parcel/transformer-typescript-tsc": "^2.0.0-beta.1",
"@parcel/validator-typescript": "^2.0.0-beta.1",
"parcel": "^2.0.0-beta.1",
"@apollo/client": "3.3.18",
```
- Parcel config `.parcelrc`:
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```
- tsconfig.json
```
{
    "compilerOptions": {
        "target": "es6",
        "resolveJsonModule": true,
        "module": "commonjs",
        "jsx": "react",
        "outDir": "./dist",
        "rootDir": "./src",
        "strict": true,
        "moduleResolution": "node",
        "baseUrl": "./src",
        "paths": {
            "~/*": ["./*"]
        },
        "types": [
            "./src/models",
            "node",
            "jest"
        ],
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "skipLibCheck": true
    },
    "exclude": ["dist/**", "node_modules/**.*"]
}
```
- Run build command `npx parcel build src/index.html`
- Run with Nginx (if it matters) and open in browser

**Versions**

```
System:
    OS: macOS 11.5
  Binaries:
    Node: 16.6.1 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/stockX/viper/node_modules/.bin/yarn
    npm: 7.20.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @apollo/client: 3.3.18 => 3.3.18 
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3 
    apollo: ^2.31.0 => 2.32.1 
    react-apollo: 3.1.5 => 3.1.5
```

I assume that [this PR](https://github.com/apollographql/apollo-client/pull/8213) that corresponds this patch may still miss some side effects and should include some dependencies to avoid their truncation.
Since I have the same error but on other line of code if upgrading to 3.4.8, I assume that there could be more side effects.

**Comment by benjamn** [comment] 2021-08-20 16:37
@irenlian Can you share the stacktrace leading to that `ReferenceError`?

**Comment by irenlian** [comment] 2021-08-25 10:38
Unfortunately, there is not much information in the stacktrace here.

Here are screenshots from the console.

<img width="1676" alt="Screenshot 2021-08-20 at 12 36 34" src="https://user-images.githubusercontent.com/45939370/130776020-9496dd7a-40e2-4761-9166-0aef1852a305.png">
<img width="601" alt="Screenshot 2021-08-20 at 12 36 50" src="https://user-images.githubusercontent.com/45939370/130776034-83d704da-316e-40c4-9a75-d3d2ff8d173b.png">

Let me know if I can attach anything additionally.

**Comment by benjamn** [comment] 2021-08-25 14:52
It's strange there's no long `$...$exports` variable visible in the code where the red squiggly line appears. Can you try temporarily [disabling JS source maps](https://stackoverflow.com/a/35004929/128454) to see if there's more to this code than meets the eye?

Alternatively, if your application is using `client.onClearStore` to register `client.clearStore` callbacks, I guess there's some possibility one of those callbacks might trying to refer to the `$...$exports` variable, and for some reason the error is reported here rather than in the function itself?

**Comment by irenlian** [comment] 2021-08-31 12:27
For anyone who are searching for a workaround, here is what works for me:
Replace import from 
```
import { ApolloProvider } from "apollo/client"
```
with
```
import * as apolloClient from '@apollo/client';
const { ApolloProvider } = apolloClient;
```

**Comment by phryneas** [comment] 2024-08-05 11:03
I believe this is a quirk of Parcel, not a bug in how Apollo Client is packaged. Since nobody else has reported encountering this in a very long time and a workaround is available, I'm going to close this issue.

**Closed by phryneas** 2024-08-05 11:03 UTC
Labels: 🌤 has-workaround, 🏓 awaiting-team-response
