### ISSUE TITLE
useQuery with inline onError function causes infinite loop

### ISSUE THREAD

**Issue by dmin** [apollographql/apollo-client#6416] opened 2020-06-09 03:54 UTC
**Intended outcome:**
Using an `onError` function with `useQuery` allows a component to recover from network errors:
```javascript
  const {data, loading} = useQuery(QUERY, {
    onError: (e) => { // do something with e },
  });
```

**Actual outcome:**
When a network error occurs and an inline `onError` function is defined (as show above), an infinite loop occurs, causing `useQuery` to make repeated requests indefinitely.

Note: This issue does not occur when a "stable reference" to a function is supplied as a value for `onError`.
```javascript
// This version works without issue.
const onError = () => {};
function Component() {
  const {data, loading} = useQuery(QUERY, {
    onError,
  });
  // ...
}
```

**How to reproduce the issue:**

[Reproduction on CodeSandBox](https://codesandbox.io/s/winter-cdn-6j75x?file=/src/index.js)

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import {ApolloClient, HttpLink, InMemoryCache, ApolloProvider, gql, useQuery} from '@apollo/client';

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: new HttpLink({
    uri: 'https://forceNetworkError',
  }),
});

const QUERY = gql`
  query {
    aField
  }
`;

const Root = () => {
  return (
    <ApolloProvider client={client}>
      <Component />
    </ApolloProvider>
  );
};

// Replacing the inline version of onError (in useQuery below) with this fixes the issue.
// const onErrorStableReference = () => {}; 

let renderCount = 0;

function Component() {
  renderCount++;
  if (renderCount === 100) {
    throw new Error("That's enough :)");
  }

  const {loading, error} = useQuery(QUERY, {
    onError: () => {},
    // onErrorStableReference,
  });

  if (error) return <p>Error loading query :(</p>;
  else if (loading) return <p>Loading query...</p>;
  else return <p>We'll never get here</p>;
}

ReactDOM.render(<Root />, document.getElementById('root'));
```

**Versions**
```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
  npmPackages:
    @apollo/client: 3.0.0-rc.2 => 3.0.0-rc.2
    react: 16.13.1
```

**Comment by IgorPieruccini** [comment] 2020-06-10 11:50
Using useQuery with "network-only" fetch policy also triggers a loop.

**Comment by RadoslavK** [comment] 2020-06-14 17:28
I get this behavior only for a specific query. It's a simple query without any options. Its returning array of normalized objects. Then I have another query that also returns array of normalized objects without causing the infinite re-render loop.

Why does it happen?

**Comment by RadoslavK** [comment] 2020-06-14 17:42
It happens only for a specific query. This query returns an array of objects that are normalized in the cache. It's a simple `useQuery` hook without any options. Although I have other queries that returns arrays of normalized objects and od not cause infinite re-render.
If I use `no-cache` fetchPolicy for the query, it does not cause re-renders but I need the data from the server.

**Comment by tpict** [comment] 2020-06-16 21:42
The combination of an inline error handler and `cache-and-network` fetch policy seems to cause this too.

**Comment by Pymossy** [comment] 2020-06-17 11:07
If you use `useCallback` like this [code](https://codesandbox.io/s/icy-resonance-1yyru), the problem will be resolved!
Btw I'll look into the code and find the reason ASAP.

**Comment by lukeramsden** [comment] 2020-06-23 11:20
I think the same issue happens with onCompleted too.

**Comment by supermonkeybrainz** [comment] 2020-06-26 06:06
I just encountered this and put together an [example](https://codesandbox.io/s/suspicious-joliot-e8ypy?file=/src/App.js) as well before I discovered this issue.  As it turns out, if you return any `false-y` value from your `onError` handler then the infinite loop occurs, but any `truth-y` thing will break the infinite loop.

**Comment by bwhitty** [comment] 2020-07-07 16:37
Can confirm that this happens with `onCompleted` as well, and the above suggestion to use a stable reference from `useCallback` fixes the issues. We're on `rc.8`.

**Comment by supermonkeybrainz** [comment] 2020-07-08 16:32
> I just encountered this and put together an [example](https://codesandbox.io/s/suspicious-joliot-e8ypy?file=/src/App.js) as well before I discovered this issue. As it turns out, if you return any `false-y` value from your `onError` handler then the infinite loop occurs, but any `truth-y` thing will break the infinite loop.

This no longer works in latest stuff, but the `useCallback` solution does. 👍

**Comment by Ericnr** [comment] 2020-07-22 02:19
This is still happening even with the official v3 release. The component infinitely rerenders and fetches if I pass an onCompleted fn.

**Comment by mtt87** [comment] 2020-07-22 14:41
I believe the fix will land in the next version as it was merged only 2 days ago
https://github.com/apollographql/apollo-client/pull/6588

**Comment by Tautorn** [comment] 2020-07-24 14:27
Update to `@apollo/client@3.1.0-pre.0` version while `v3.1.0` is not published.

**Comment by proutek** [comment] 2020-07-27 15:37
I can confirm that with @apollo/client@3.1.0-pre.2 this is fixed. Thank You.

**Comment by hwillson** [comment] 2021-05-03 14:33
As mentioned in https://github.com/apollographql/apollo-client/issues/6416#issuecomment-664470321, this has been fixed. Thanks!

**Closed by hwillson** 2021-05-03 14:33 UTC
Labels: 🛬 fixed-in-prerelease

**Comment by ilya-bmi** [comment] 2021-06-08 14:51
Same here. onError doesn't fire on error. It keeps sending retrying requests to the server indefinitely.
