### ISSUE TITLE
Query call twice with fetchPolicy: no-cache

### ISSUE THREAD

**Issue by clementloridan** [apollographql/apollo-client#10540] opened 2023-02-10 17:01 UTC
### Issue Description

On a simple page, my `useQuery` or `useLazyQuery` will be fetch twice with fetchPolicy: 'no-cache'.
Maybe because of `ssrForceFetchDelay`.

Should I miss something about fetchPolicy: no-cache and ssrForceFetchDelay?

Why no-cache? Because I don't manage a lot of data with apollo/client, performance issue.

Thk to helping me :) 

### Link to Reproduction

https://github.com/clementloridan/react-apollo-error-template

### Reproduction Steps

```jsx
const [fetch] = useLazyQuery(QUERY, {
        fetchPolicy: 'no-cache',
        nextFetchPolicy: 'no-cache',
 });

React.useEffect(() => {
        fetch();
}, []);
```

My apollo config:
```
ssrMode: typeof window === 'undefined',
ssrForceFetchDelay: 100,
defaultOptions: {
    watchQuery: {
        fetchPolicy: 'cache-and-network',
        nextFetchPolicy: 'cache-first',
        errorPolicy: 'all',
    },
    query: {
        fetchPolicy: 'cache-and-network',
        nextFetchPolicy: 'cache-first',
        errorPolicy: 'all',
    },
    mutate: {
        errorPolicy: 'all',
    },
},

```
<img width="344" alt="CleanShot 2023-02-10 at 19 36 04@2x" src="https://user-images.githubusercontent.com/15263596/218145859-64ff9860-7aa9-43e8-b65e-58091b051be4.png">

**Comment by clementloridan** [comment] 2023-02-10 17:24
Hi @jerelmiller, I have the same issue on the react-apollo-error-template. And this template is based already on React 18.
I sync my repo on codesandbox: https://codesandbox.io/s/github/clementloridan/react-apollo-error-template for check quickly

**Comment by jerelmiller** [comment] 2023-02-10 17:26
@clementloridan I'm so sorry, I totally missed your reproduction link when I posted that earlier comment. I could have answered my own question 🤣 . We will take a look at this when we get a chance!

**Comment by clementloridan** [comment] 2023-02-10 17:40
+ More info
Working well on `@apollo/client@3.4.16`
https://codesandbox.io/s/tender-golick-q9ru50

**Comment by phryneas** [comment] 2023-03-06 13:10
This gets stranger and stranger - with this change, the double-fetch doesn't occur as well:

```diff

const container = document.getElementById("root");
const root = createRoot(container);
+setTimeout(() => {
  root.render(
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>
  );
+}, 500);
```

**Comment by phryneas** [comment] 2023-03-06 14:02
Which results to a fix for this in userland (for now):
```diff

const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: "https://swapi-graphql.netlify.app/.netlify/functions/index",
  ssrMode: typeof window === "undefined",
-  ssrForceFetchDelay: 100,
+  ssrForceFetchDelay: typeof window === "undefined" ? 100 : 0,
  defaultOptions: {
    watchQuery: {
      fetchPolicy: "cache-and-network",
      nextFetchPolicy: "cache-first",
      errorPolicy: "all",
    },
    query: {
      fetchPolicy: "cache-and-network",
      nextFetchPolicy: "cache-first",
      errorPolicy: "all",
    },
    mutate: {
      errorPolicy: "all",
    },
  },
});
```

In a non-SSR-scenario, both `ssrMode` should be `false` and `ssrForceFetchDelay` should be `0`.

**Comment by phryneas** [comment] 2023-03-06 15:02
## Issue Writeup #10540

Description:
An ApolloClient is rendered with a positive `ssrForceFetchDelay` on the client. That means, the client wil stay in `disableNetworkFetches` mode for 100ms.  
After that, `disableNetworkFetches` switches over to `false`.  
Generally, a positive `ssrForceFetchDelay` essentially implies `ssrMode` for a certain time, with the purpose of skipping `network-only` and `cache-and-network` fetches within that first time window. ([See docs](https://www.apollographql.com/docs/react/performance/server-side-rendering/#overriding-fetch-policies-during-initialization))  
In this case, a query is made with `useQuery` and `fetchPolicy: "no-cache"`. That will cause a network request to occur, even if `disableNetworkFetches` is `true`.
As `disableNetworkFetches` is taken into account for the dependency array used in `useQuery`s `useSyncExternalStore` effect, switching `disableNetworkFetches` after 100ms triggers that effect a second time.  
Since the value is first unsubscribed and then resubscribed and not stored in the cache, it is discarded and a second request is made.

### Questions

* should `no-cache` queries happen in the `disableNetworkFetches` time-window?  
  Probably yes?
* should switching from `disableNetworkFetches: false` to `disableNetworkFetches: true` ever re-execute a query?
  Probably not if data is already present? On the other hand, what about `cache-and-network`?
* As this was caused by [4a0e8dd](https://github.com/apollographql/apollo-client/commit/4a0e8dddc9be08e6158fc65859bc0bdcf5e22ca5): is that change a bug, or did it just surface a bug that should be fixed elsewhere?
  I would argue that this is an underlying bug that was just surfaced by that change.

### Follow-up questions (may go off into other tangents)
* should changing `disableNetworkFetches` from `false` to `true` rerender components? Right now, it seems pretty accidental: if there is no rerender after `disableNetworkFetches` was set to `true`, a request is potentially never made, even if it should have only been skipped temporarily by that option. According to [8644](https://github.com/apollographql/apollo-client/issues/8644), this is not only used in SSR scenarios on the server, but also in rehydration scenarios on the client, where it is not impossible that necessary data is not rehydrated, so a fetch call might still be necessary.

## Potential fix
Delaying the "unsubscribe" for a tick gives the "next subscription" an option to latch onto an existing non-cache in-memory value. That resolves this specific scenario, but I am not sure if there are other scenarios, where we might need another fix.
```diff
- return () => subscription.unsubscribe();
+ return () => setTimeout(() => subscription.unsubscribe());
```
Coincidentally, this fixes also a bug with polling and `StrictMode`: [#9819](https://github.com/apollographql/apollo-client/issues/9819)

@jerelmiller @alessbell @benjamn I would need some feedback on this. Is my analysis here okay - is that fix enough, or do we need more? What about the follow-up-question?

**Comment by bignimbus** [comment] 2023-03-13 17:44
Hi all, the fix for this was merged and should be released with the next patch, probably sometime this week 🚀

**Closed by bignimbus** 2023-03-13 17:44 UTC
Labels: ⚛️ React-related, 🔍 investigate, 🏓 awaiting-team-response
