### ISSUE TITLE
fetchMore with default fetchPolicy options `no-cache`

### ISSUE THREAD

**Issue by vreality64** [apollographql/apollo-client#4136] opened 2018-11-13 13:13 UTC
Hello, I'm using default options of Apollo Client like below. It's very simple and intuitive. However weird things come out when `fetchMore` requested

```js
const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'no-cache'
  }
}
```

The problem is that response was cached after called `fetchMore`. I figure out [what code](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/ObservableQuery.ts#L335) is reason. 

**Is this intended**? If then, I think it's would be better to notify in document. This makes me so confused 😢

**Comment by jasonpaulos** [comment] 2019-07-09 23:07
Hi @vreality64, thanks for reporting this. Unfortunately I can't tell exactly what the problem is, and there hasn't been any activity here in quite some time, so we're going to close this issue for now. If there is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Closed by jasonpaulos** 2019-07-09 23:07 UTC
