### ISSUE TITLE
MockLink doesn't strip undefined values | error message doesn't show undefined variables

### ISSUE THREAD

**Issue by willrax** [apollographql/apollo-client#6771] opened 2020-08-04 17:49 UTC
**Intended outcome:**
When making a request against a live GraphQL endpoint any `undefined` values in the variables object are removed from the payload. 

When testing using the MockedProvider, the variables that were `undefined` remain in the request. This leads to the [equality](https://github.com/apollographql/apollo-client/blob/dce4170689025c2a32265915c28cc95b7566f1d0/src/utilities/testing/mocking/mockLink.ts#L80) check failing (which it should). 

The problem comes when you see the error message that Apollo throws.

The error message [`No more mocked responses were found etc` ](https://github.com/apollographql/apollo-client/blob/7993a778ef5a9e61bfee72b956f4c179fce691f4/src/utilities/testing/mocking/mockLink.ts#L92) uses `JSON.stringify` which excludes any values that were undefined. This behavior makes it tricky to debug because you're essentially seeing the exact mock you provided to the test.

**Actual outcome:**
* The query shown in the network request is the same as the query received by the MockedProvider.
* The error messages shows the query with all the values it's using to look for a mocked request.

**How to reproduce the issue:**

[Codesandbox](https://codesandbox.io/s/sad-galois-hge92?file=/test/variables.test.js)

To reproduce:

* Run the tests and check the browser page.

In `App.js` note that the mutation has a value with undefined in the variables payload. Note that the mock in the test has the payload without the undefined value. This is the same request you would see get sent in the network tab.

Note that the error message excludes the undefined variable (see image) and that the query it's showing matches our mock exactly.

<img width="827" alt="AOahOdkn@2x" src="https://user-images.githubusercontent.com/94960/89326792-c2efca80-d63f-11ea-99ec-9833d2749542.png">

**Versions**

@apollo/client@3.0.2

Chrome: 84.0.4147.105
Jest: 25.2.3

**Comment by willrax** [comment] 2020-08-04 17:53
One solution i can think of is using a replacer function on `JSON.stringify to attach another message the those values that are present in the request but are not present in the mock.

**Comment by pleunv** [comment] 2020-08-07 09:58
Ran into this just now as well when migrating from 2 to 3, a large part of our apollo tests suddenly started failing and I just couldn't figure out what was going wrong. I think a rollback to the previous behavior (stripping undefined) would probably be desirable as right now it is a massive pain to debug and fix.

**Comment by vedrani** [comment] 2020-08-10 09:10
The problem is because MockLink is not using [fast-json-stable-stringify](https://www.npmjs.com/package/fast-json-stable-stringify) to stringify variables and compare it.

[Here](https://github.com/apollographql/react-apollo/blob/142fe1c816b1776d7ea8aed8dae23fb391834746/packages/testing/src/mocks/mockLink.ts#L68-L70) is v2 MockLink equality check

[Here](https://github.com/apollographql/apollo-client/blob/master/src/utilities/testing/mocking/mockLink.ts#L80) is v3 MockLink equality check

`fast-json-stable-stringify` basically strips undefined values.

I'm interested is this a bug in v3 or intentional change?
I cannot find breaking change in Changelog for MockedProvider or MockLink.

**Comment by denieler** [comment] 2020-08-10 09:24
it looks like I also have this issue ☝️

**Comment by stephenh** [comment] 2020-08-23 20:32
@benjamn looks like `MockLink` is using your new `@wry/equality` package but it's a regression for a) not stripping undefined keys and also b) not `.toJSON`-ifying both sides (i.e. a feature of apollo-client is that you can pass in variables that aren't strictly JSON, but it will `.toJSON` them, i.e. during something like `class MyDateUserType` into "2020-08-23" by implicitly calling `MyDateUserType.toJSON` during the previous `fast-json-stable-stringify`).

**Comment by benjamn** [comment] 2020-10-01 18:04
This behavior should be fixed/improved in `@apollo/client@3.3.0-beta.9` (just published to npm), thanks to #7108. Please give it another try after updating!

**Comment by willrax** [comment] 2020-10-01 22:39
Thanks! I'll update and try it out.

**Comment by mrogelja** [comment] 2020-12-04 10:18
Tell me is I'm wrong but this regression seems to remain in @apollo/client@3.3.2 ?

**Comment by hwillson** [comment] 2021-05-04 15:52
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Closed by hwillson** 2021-05-04 15:52 UTC
