### ISSUE TITLE
Query with filter overwriting other query results that used a different filter

### ISSUE THREAD

**Issue by HummingBird24** [apollographql/apollo-client#4973] opened 2019-06-19 15:11 UTC
Hi so I have a query that looks like so:

UserGroups(first: 5, id: "2348329349usf"){
{
    users{
       name
       email
    }
}

The "first" parameter helps to return the first n users that are a part of a specific group. Problem: If I make two separate queries with a different value for first, they overwrite each other's results because the same UserGroup is returned but with a different set of users.

For example, if I call the query with first=5 and then call it again with first=2, then the results for the queries with first=5 gets overwritten and I only see 2 users instead of 5.

The way I got around this was by saving the max "first" value so that I can always use that max number for queries. For example, say I have Group A, if I query with first=5, I save 5 as my max number. Then later if I try to query first=2 for Group A, I look and see if I already queried with a higher number (in this case 5) and use that value instead. In my code, I just take the original number of users that I wanted (in this case 2) enough though I used a query that asked for more (results of the high query should already be in cache).

Question: Is there another way around this? Is there something wrong with my design?

**Comment by healqq** [comment] 2019-06-20 08:00
the problem is you get group with same id, and by default apollo cache uses id to match entities. You can write custom rule for entity type. Check this article: https://www.apollographql.com/docs/react/advanced/caching/#normalization

**Comment by HummingBird24** [comment] 2019-07-25 18:36
@healqq Ahh so there's no way I could utilize the query results of the other query without accessing the cache directly? Like in the case where I know I already have the first 5 users, I could utilize those results when I ask for the first 2 users?

Also, I appreciate your response. Sorry for my delay. I thought I had responded

**Comment by healqq** [comment] 2019-07-26 08:05
@HummingBird24 hey, I think it is possible to do using cache redirect feature combined with custom query ids. First assign some unique id so apollo treats queries as different(creating different named queries should also work). Then define cache redirect for smaller query. Doc on cache redirect is here: https://www.apollographql.com/docs/react/advanced/caching/#cache-redirects-with-cacheredirects

**Comment by HummingBird24** [comment] 2019-07-30 20:03
@healqq Okay, I'll try it out and post my results here.

**Comment by dizzersee** [comment] 2019-10-18 21:50
@HummingBird24 Did you solve the issue?

**Comment by designalchemy** [comment] 2019-12-19 00:36
I fixed this issue like this 

`
const store = new InMemoryCache({
  dataIdFromObject: object => {
    return object._id + object.__typename || null
  },
  freezeResults: true,
})
`

the issue was i was only using _id before, but i had things with the same id so i added type name to make it uniq

**Comment by oriana4r** [comment] 2020-09-07 13:58
Is there a way to solve this without using `dataIdFromObject` option key? Documentation says that this parameter is deprecated. Anyway, I don't understand why (because there's no even a warning message when `dataIdFromObject` is used), but solves my issue.

**Comment by benjamn** [comment] 2020-09-09 17:02
@oriana4r We won't be removing `dataIdFromObject` until we have something that can fully replace its use cases (it's a dynamic catch-all version of `keyFields`, and sometimes that's exactly what you need!). The actual removal of `dataIdFromObject` won't happen until AC4 at the earliest, so I would encourage you to keep using it where necessary (using `keyFields` where possible, preferably) despite what the documentation currently claims.

**Comment by carlosgonzalezmendoza** [comment] 2021-04-18 23:39
@healqq Im interested in your suggestion of using custom query ids. I'm running into a similar problem but using the proposed solution of adding `__typename`and `_id` dont solve the problem for me since both of those match. I have one `getConversations` query that returns a "full" entity (a Conversation with an array of message Ids), and another `getUnseenMessages` query that returns the Conversation with the same id but the array of message ids is a subset (the messages that havent been seen). How can I keep the results from those queries separated?

**Comment by healqq** [comment] 2021-04-20 05:59
@carlosgonzalezmendoza hey, maybe for your case setting fetch policy to no-cache(https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy) for  `getUnseenMessages` makes sense? Your issue is different from original, so that answer won't work for you

**Comment by hwillson** [comment] 2021-04-27 14:48
Since this isn't an Apollo Client bug, I'll close this off. Thanks!

**Closed by hwillson** 2021-04-27 14:48 UTC
