### ISSUE TITLE
writeFragment causes container data to be null.

### ISSUE THREAD

**Issue by ashah888** [apollographql/apollo-client#2571] opened 2017-11-15 20:57 UTC
I have a container that hooks data by the normal Apollo way (graphql(...)).

That container is connected to a component that has data from the graphql(...) and also a manual client.query(...) which sets the second data into this.state.

When I update hte manual state data using client.writeFragment, the data from the container graphql(...) becomes null for some reason (even though they are 2 completely differnet query and fragments.

**Comment by jbaxleyiii** [comment] 2017-11-15 22:15
@ashah888 yep! I'm working on it now! closing as this is a duplicate of https://github.com/apollographql/apollo-client/issues/2570

**Closed by jbaxleyiii** 2017-11-15 22:15 UTC
