### ISSUE TITLE
typePolicies exisitngData arg is incorrect or missused

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client#5872] opened 2020-01-29 02:19 UTC
Based on the example in point 3 [here](https://blog.apollographql.com/previewing-the-apollo-client-3-cache-565fadd6a01e), to replace the cache redirect in apollo-client v3 we need go from this

```js
const cache = new InMemoryCache({
  cacheRedirects: {
    Query: {
      book: (_, args, { getCacheKey }) =>
        getCacheKey({ __typename: 'Book', id: args.id })
    },
  },
});
```

to this

```js
const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        book(existingData, { args, toReference }) {
          return existingData || 
            toReference({ __typename: 'Book', id: args.id });
        }
      }
    },
  },
});
```

But I'm not sure that's correct. 

If I load a list of books, and then I go to book with id 1, the first time existingData will be `undefined`.
Now if I try to load book with id 2, existing data has `{__ref: "books:1"}` not undefined, so it will load the incorrect book.

What is the purpose of the existingData arg?

**Comment by benjamn** [comment] 2020-01-29 22:40
This will be fixed with #5862, which restores the default behavior of storing `existingData` separately by `args.id` (the default behavior) unless you have _both_ a `read` function and a `merge` function. I've just released that change in `@apollo/client@3.0.0-beta.30`, if you want to give it a try!

In general, if you never plan on writing actual data for the `book` field (that is, you don't include it in queries sent to the server), `existingData` will always be `undefined`, and this code will work as expected. You can write this code in a style that mirrors the `cacheRedirects` pattern, where you don't even look at `existingData`, if you like. However, there are cases where you want to simulate a field on the client before it has been requested from the server, but you want to treat the server result as authoritative after that, so preferring `existingData` is an option.

**Comment by tafelito** [comment] 2020-01-29 23:38
ok so existingData is always the data that the server returned for that particularly query, but if the server was never called, then existingData will be undefined

So I jus tested beta.30 and this is actually working now, but now the types for the Context links when using `from` are broken.

```js
const setAuthorizationLink = setContext((_, { accessToken }) => ({
  headers: {
    Authorization: `Bearer ${accessToken}`,
  },

const client = new ApolloClient({
  link: from([
    setAuthorizationLink, --> `Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'`
    new HttpLink({
      uri: `${process.env.REACT_APP_GRAPHQL_ENDPOINT}`,
      credentials: 'include',
    }),
  ]),
  cache,
});

**Comment by benjamn** [comment] 2020-01-30 23:33
@hwillson Do you have any ideas about those link-related type errors?

**Comment by hwillson** [comment] 2020-01-31 01:05
@tafelito Using `@apollo/link-context@beta` will help. See this [section](https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/#apollo-link-) of the migration guide for more details. The `@apollo/link-X` packages will be launching at the same time as `@apollo/client`.

**Comment by tafelito** [comment] 2020-01-31 15:08
@hwillson the types issues are happening using the new packages 

```js
"@apollo/link-context": "^2.0.0-beta.3",
"@apollo/link-error": "^2.0.0-beta.3",
```

**Comment by hwillson** [comment] 2020-01-31 15:11
Hmmm that's odd @tafelito - could you post the output of running `npx envinfo@latest --preset apollo` in your project?

**Comment by tafelito** [comment] 2020-01-31 15:51
```
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
  npmPackages:
    @apollo/client: ^3.0.0-beta.31 => 3.0.0-beta.31
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3
```

**Comment by tafelito** [comment] 2020-01-31 16:02
Maybe this helps

`Types of property 'split' are incompatible.`
` Types of parameters 'left' and 'left' are incompatible.`

Since the split function is declared as
`split(test: (op: Operation) => boolean, left: ApolloLink | RequestHandler, right?: ApolloLink | RequestHandler): ApolloLink;`

**Comment by hwillson** [comment] 2020-01-31 16:20
Thanks @tafelito - would you mind also posting the result of `npm ls @apollo/client` from your app root?

**Comment by tafelito** [comment] 2020-01-31 16:23
```
├── @apollo/client@3.0.0-beta.31
├─┬ @apollo/link-context@2.0.0-beta.3
│ └── @apollo/client@3.0.0-beta.29
└─┬ @apollo/link-error@2.0.0-beta.3
  └── @apollo/client@3.0.0-beta.29
```

What's interesting is that I created a repo to reproduce the other issue, and that one does not complain about that, and they both uses the same TS version, same tsconfig, same everything, and when I run the same command I get

```
├── @apollo/client@3.0.0-beta.31
├─┬ @apollo/link-context@2.0.0-beta.3
│ └── @apollo/client@3.0.0-beta.31  deduped
└─┬ @apollo/link-error@2.0.0-beta.3
  └── @apollo/client@3.0.0-beta.31  deduped
```

**Comment by tafelito** [comment] 2020-01-31 16:28
I removed the `yarn.lock` and `node_modules` and now it works!

**Comment by hwillson** [comment] 2020-01-31 16:35
Glad to hear it's working @tafelito! This is great feedback - I think we should consider changing `@apollo/client` to be a peer dep in the `@apollo/link-X` packages, instead of a dep. I've made a note - thanks!

**Comment by atbtechgit** [comment] 2020-02-17 23:34
I seem to be having a somewhat similar issue, except I can't seem to even hit my cache redirect. I updated my cacheRedirects to the same setup as above.

From this:
`const cache = new InMemoryCache({
  cacheRedirects: {
    Query: {
      book: (_, args, { getCacheKey }) =>
        getCacheKey({ __typename: 'Book', id: args.id })
    },
  },
});`

To This:
`const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        book(existingData, { args, toReference }) {
          return existingData || 
            toReference({ __typename: 'Book', id: args.id });
        }
      }
    },
  },
});`

I've tried to throw a debugger and console.log in the 'book' function but it never gets hit.

I can create a new topic if necessary.

**Comment by benjamn** [comment] 2020-02-18 00:25
@atbtechgit A [reproduction](https://github.com/apollographql/react-apollo-error-template) in a new issue would be great, unless either of these questions leads somewhere:

* Do any other `read` functions get called correctly? Is this problem specific to `Query.book`?
* Are you using `query { book @client }` in your query, or just `query { book }`?

**Comment by atbtechgit** [comment] 2020-02-18 06:34
@benjamn It seems to be anything inside of Query. I have another one called `accountById` that also doesn't get hit. I was able to get individual fields to work:
` 
Account: {
    fields: {
      accountName: {
        read(name = 'UNKNOWN NAME') {
          console.info(`${name}`);
          return name;
        },
      },
    },
  },
`

**Comment by atbtechgit** [comment] 2020-04-20 16:52
@benjamn The caching redirect issue seemed to be fixed with the latest beta version.

**Comment by hwillson** [comment] 2020-06-12 20:28
No longer an issue - thanks!

**Closed by hwillson** 2020-06-12 20:28 UTC
Labels: ✔ confirmed, 🐞 bug, 📟 regression, 🛬 fixed-in-prerelease
