### ISSUE TITLE
Prior `variables` are being merged into subsequent queries

### ISSUE THREAD

**Issue by AkiraJ48** [apollographql/apollo-client#9736] opened 2022-05-18 04:46 UTC
**Intended outcome:**
In version `3.5.10` if you executed the same query on a subsequent render with different variables, it'd only use those variables. For example:
- On first render, you do `useQuery(query, { variables: { first: 10 } })`
- On second render, if you do `useQuery(query, { variables: { last: 10 } })`, you'd expect the query to only execute with the variables `{ last: 10 }`.

**Actual outcome:**
In version `3.6.0` if you execute the same query on a subsequent render with different variables, it'll merge the previously used variables. For example:
- On first render, you do `useQuery(query, { variables: { first: 10 } })`
- On second render, if you do `useQuery(query, { variables: { last: 10 } })`, the variables that actually get used in the query are  `{ first: 10, last: 10 }`.

**How to reproduce the issue:**
To reproduce the issue, please reference this [repo](https://github.com/AkiraJ48/react-apollo-error-template). There's fairly simple steps to reproduce the issue in the README.

Please let me know if I should provide any additional details, from a quick preliminary investigation, I believe the issue may have been introduced in this [PR](https://github.com/apollographql/apollo-client/pull/9563), but I could be wrong.

**Versions**
@apollo-client: 3.6.0

**Comment by yura3d** [comment] 2022-05-18 06:12
Duplicate of #9671

**Closed** 2022-05-19 18:22 UTC

**Comment by benjamn** [comment] 2022-05-19 23:35
@AkiraJ48 My proposed fix #9741 can be tested now by running `npm i @apollo/client@beta` to get version `3.7.0-alpha.6`. Please let us know if that version seems to help (over in #9671). Thanks!

Note: while that version says 3.7, PR #9741 is targeting the `main` branch, implying a 3.6.x patch release (not 3.7).

**Comment by 72636c** [comment] 2022-05-24 03:29
3.6.5 is looking good for us, thanks for the quick fix!

**Comment by AkiraJ48** [comment] 2022-05-24 05:52
Thanks @benjamn! That's working now 🙇

**Comment by danyhiol** [comment] 2022-09-25 09:32
I am not sure about this, but it looks like fetchmore behavior has changed as well. According to the [doc](https://www.apollographql.com/docs/react/pagination/core-api/#the-fetchmore-function), the variables in fetchmore get merged with those in the original query. But in my case (`"@apollo/client": "3.6.9"`) this is not happening both on the network tab as on the server. Variables are always those defined in fetchmore only.
