### ISSUE TITLE
Apollo client catching Connection Refused on page load. 

### ISSUE THREAD

**Issue by Az-r-ow** [apollographql/apollo-client#10759] opened 2023-04-12 19:49 UTC
My apollo client set up like this : 

```js
const errorLink = onError(
      ({ operation, graphqlError, networkError, forward }) => {
        if (networkError) {
          console.log("A network error has been found : ", networkError);
        } else {
          console.log("There has been an error : ", graphqlError);
        }
      }
    );

    const httpLink = new HttpLink({
      fetchOptions: {
        mode: 'cors',
      },
      uri: 'http://localhost:4000/graphql',
    });

    const link = ApolloLink.from([errorLink, httpLink]);

    const cache = new InMemoryCache();

    const client = new ApolloClient({
      link,
      cache,
    });
```

And server setup like this : 

```js
async function start() {
  const app = express();

  // our http server handles incoming requests to our Express app
  // Below, we tell apollo to "drain" this httpServer,
  // enabling our servers to shut down gracefully
  const httpServer = http.createServer(app);

  const armor = new ApolloArmor({
    maxDepth: {
      n: 10,
      onAccept: [],
      onReject: [], // Callbacks that are ran whenever a Query is rejected
      propagateOnReject: true,
    },
  });

  // Generate gql schema from types
  const typeDefs = [scalarTypeDefs, ...types.map((type) => type.typeDefs)];

  // Generating the resolvers
  const resolvers = types.reduce((o, type) => _.merge(o, type.resolvers), {});

  const schema = makeExecutableSchema({ typeDefs, resolvers });

  const protection = armor.protect();

  const corsOptions = {
    origin: ["http://localhost:3000", "http://localhost:24678"],
    optionsSuccessStatus: 200,
  };

  const apolloServer = new ApolloServer({
    schema,
    ...protection,
    plugins: [ApolloServerPluginDrainHttpServer({ httpServer })],
  });

  // Ensure we wait for our server to start
  await apolloServer.start();

  // Setup our express middleware to handle CORS, body parsing,
  // and our expressMiddleware function
  app.use(
    "/graphql",
    cors(corsOptions),
    bodyParser.json(),
    expressMiddleware(apolloServer, {
      context: async ({ req }) => new ContextValue({ req, apolloServer }),
    })
  );

  await new Promise((resolve) => httpServer.listen({ port: 4000 }, resolve));

  console.log(`🚀 Server ready at http://localhost:4000/graqhql`);
}

(async () => start())();
```

The following query is in a setup script of a nuxt page  : 

> For the people that are not familiar with nuxt, a setup script in a page is basically a js script that runs before the page is mounted. 

```js
const incomeQuery = gql`
  query getIncomes() {
    incomes() {
      from
      date
      description
    }
  }
`;

const data = client.query({query: incomeQuery, fetchPolicy: 'no-cache' }).then(r => {
  console.log(r.data)
}).catch(e => {
  console.log(e)
})
```

Whenever a page loads the first time, the query is executed and the data is returned (after around `15s`) without any problem. 
However, if I reload the page this script catches the following network error :

And then returns the data (check last line of logs). 

```
ApolloError: request to http://localhost:4000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4000
     at new ApolloError (/app/node_modules/@apollo/client/errors/index.js:33:28)
     at /app/node_modules/@apollo/client/core/QueryManager.js:670:19
     at both (/app/node_modules/@apollo/client/utilities/observables/asyncMap.js:17:53)
     at /app/node_modules/@apollo/client/utilities/observables/asyncMap.js:10:72
     at new Promise (<anonymous>)
     at Object.then (/app/node_modules/@apollo/client/utilities/observables/asyncMap.js:10:24)
     at Object.error (/app/node_modules/@apollo/client/utilities/observables/asyncMap.js:18:49)
     at notifySubscription (/app/node_modules/zen-observable/lib/Observable.js:140:18)
     at onNotify (/app/node_modules/zen-observable/lib/Observable.js:179:3)
     at SubscriptionObserver.error (/app/node_modules/zen-observable/lib/Observable.js:240:7) {
   graphQLErrors: [],
   clientErrors: [],
   networkError: FetchError: request to http://localhost:4000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4000
       at ClientRequest.<anonymous> (file:///app/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:6371:11)
       at ClientRequest.emit (node:events:525:35)
       at Socket.socketErrorListener (node:_http_client:494:9)
       at Socket.emit (node:events:513:28)
       at emitErrorNT (node:internal/streams/destroy:157:8)
       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
     type: 'system',
    errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     erroredSysCall: 'connect'
  },
   extraInfo: undefined
 }
 { incomes: [Array] }
```

Thank you in advance for the people that are gonna take their time to help me out.

**Comment by jerelmiller** [comment] 2023-04-12 20:00
Hey @Az-r-ow 👋 

It's really difficult to tell what might be happening here without a reproduction. There could be any number of things going on.

That being said, it looks like perhaps there might be an issue in your server. It's odd that you'd be getting both a "connection refused" error along with data. I'd recommend taking a look at the network tab in your browser to see if the request is failing in some way. See if you're able to trace back the issue to your server in some way.

---

FYI this _might_ be an issue for [apollo-server](https://github.com/apollographql/apollo-server) in the event you discover there is a bug in some way. Feel free to leave this issue open for now until you discover if this is in fact a server issue instead of an Apollo client issue.

**Comment by Az-r-ow** [comment] 2023-04-12 20:14
Hey @jerelmiller, I really appreciate your fast reply. 
I thought about trying to reproduce it, but I don't think I could cause I'm not doing anything complicated there nor using some deep concepts of apollo. Idk if you get me. 

I checked in my network tab and there was nothing alarming, the prefetch returned 204 (I think it's normal since its a prefetch) and the fetch returned a 200 with the data. 

I tried debugging the server, but nothing seemed to be malfunctioning. I was wondering if there was a way to log rejected connections to the server with express 🤔.

**Comment by jerelmiller** [comment] 2023-04-12 21:27
@Az-r-ow `ECONNREFUSED` typically indicates that the client isn't able to connect to the server, so unfortunately adding any kind of debugging to the server wouldn't help.

You mentioned you were using `nuxt` for this app. I'm not super familiar with it. I'm curious, does this script run in the server at some point in time? If so, its possible `http://localhost:4000` is not available inside the server itself when the script is running, but works totally fine on the client. This could explain why you're seeing that error along with data.

**Comment by jerelmiller** [comment] 2023-04-12 21:32
One other tidbit that noticed is the stacktrace inside that `networkError` property. Notice this line:

```
 at ClientRequest.<anonymous> (file:///app/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:6371:11)
```

Notice this is going through [`node-fetch-native`](https://github.com/unjs/node-fetch-native), which might be a clue that its likely not executed in the browser (since the browser implements a native `fetch` function).

**Comment by Az-r-ow** [comment] 2023-04-13 14:53
> @Az-r-ow `ECONNREFUSED` typically indicates that the client isn't able to connect to the server, so unfortunately adding any kind of debugging to the server wouldn't help.
> 
> You mentioned you were using `nuxt` for this app. I'm not super familiar with it. I'm curious, does this script run in the server at some point in time? If so, its possible `http://localhost:4000` is not available inside the server itself when the script is running, but works totally fine on the client. This could explain why you're seeing that error along with data.

The script is only running on the client side. However, I forgot to mention that both the apollo server and the nuxt app are running in two containers whose ports are mapped to the machine's respective ports. But I don't think that could be causing the issue since I've done this before and I never had any problems with it. 

I was thinking earlier could it be because of long fetch time ? Which means that because the query takes around 20 seconds to return the data, reloading before that is causing some interference with the client's connection. Does this make sense or apollo queries do not interfere with one another ?

**Comment by Az-r-ow** [comment] 2023-04-13 16:58
> One other tidbit that noticed is the stacktrace inside that `networkError` property. Notice this line:
> 
> ```
>  at ClientRequest.<anonymous> (file:///app/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:6371:11)
> ```
> 
> Notice this is going through [`node-fetch-native`](https://github.com/unjs/node-fetch-native), which might be a clue that its likely not executed in the browser (since the browser implements a native `fetch` function).
> 
> It also looks like some `node` native modules are used in that stacktrace:
> 
> ```
> at ClientRequest.emit (node:events:525:35)
> at Socket.socketErrorListener (node:_http_client:494:9)
> at Socket.emit (node:events:513:28)
> at emitErrorNT (node:internal/streams/destroy:157:8)
> at emitErrorCloseNT (node:internal/streams/destroy:122:3)
> at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```

I don't know what you mean by that, I didn't change the default fetch function.

**Comment by Az-r-ow** [comment] 2023-04-13 19:37
> Hi, I'm not part of the apollo team but I try to help out with issues here sometimes. In my opinion it is extremely unlikely that this error is caused by apollo client. I am almost positive that it is coming from your server.

Hey, 
I sent a link of this issue on the `apollo server` channel of the discord server hoping i get a reply 🤞. 
Do you happen to know if it's possible that this could be caused by the queries taking around 20seconds to resolve and the fact that I'm reloading before the data get returned is interfering with the client connection ?

**Comment by dylanwulf** [comment] 2023-04-13 21:11
> Do you happen to know if it's possible that this could be caused by the queries taking around 20seconds to resolve and the fact that I'm reloading before the data get returned is interfering with the client connection ?

I suppose it's possible if your server is configured to only allow one active connection at a time, but most servers don't have defaults like that

**Comment by jamie0xgitc0decat** [comment] 2023-04-13 23:27
I'm facing the same issue where I've tried three different methods to fetch data - default, cross-fetch, and node-fetch - but none of them seem to be working. I've also made sure to allow all origins, methods, and headers in my backend, and have confirmed that the port is open. Interestingly, I had an another project frontend project with the same configuration that worked just fine. I'm not sure why I'm experiencing this issue with my new project.

"@apollo/client": "^3.7.12",


nc -zv localhost 4000
Connection to localhost (127.0.0.1) 4000 port [tcp/*] succeeded!

Backend setup

```
const corsOptions = {
    origin: "*",
    methods: "*",
    allowedHeaders: "*",
  };

  app.use(cors(corsOptions));
app.use(
    "/graphql",
    cors<cors.CorsRequest>(corsOptions),
    json(),
    expressMiddleware(server)
  );


```

frontend setup

```
import { ApolloClient, createHttpLink, InMemoryCache } from '@apollo/client';

const httpLink = createHttpLink({
  uri: 'http://localhost:4000/graphql',
  fetch: fetchMethod
});
const client = new ApolloClient({
  ssrMode: true,
  link: httpLink,
  cache: new InMemoryCache(),
});

export default client;

```


here is the error
`ApolloError: request to http://localhost:4000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4000
    at new ApolloError (C:\xxxxxxxx\node_modules\@apollo\client\errors\errors.cjs:31:28)
    at C:\xxxxxxxx\node_modules\@apollo\client\core\core.cjs:1863:19
    at both (C:\xxxxxxxx\node_modules\@apollo\client\utilities\utilities.cjs:1072:53)
    at C:\xxxxxxxx\node_modules\@apollo\client\utilities\utilities.cjs:1065:72
    at new Promise (<anonymous>)
    at Object.then (C:\xxxxxxxx\node_modules\@apollo\client\utilities\utilities.cjs:1065:24)
    at Object.error (C:\xxxxxxxx\node_modules\@apollo\client\utilities\utilities.cjs:1073:49)
    at notifySubscription (C:\xxxxxxxx\node_modules\zen-observable\lib\Observable.js:140:18)
    at onNotify (C:\xxxxxxxx\node_modules\zen-observable\lib\Observable.js:179:3)
    at SubscriptionObserver.error (C:\xxxxxxxx\node_modules\zen-observable\lib\Observable.js:240:7)
    at C:\xxxxxxxx\node_modules\@apollo\client\utilities\utilities.cjs:1055:68
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (C:\xxxxxxxx\node_modules\@apollo\client\utilities\utilities.cjs:1055:25)
    at Object.error (C:\xxxxxxxx\node_modules\@apollo\client\utilities\utilities.cjs:1159:21)
    at notifySubscription (C:\xxxxxxxx\node_modules\zen-observable\lib\Observable.js:140:18)
    at onNotify (C:\xxxxxxxx\node_modules\zen-observable\lib\Observable.js:179:3)
    at SubscriptionObserver.error (C:\xxxxxxxx\node_modules\zen-observable\lib\Observable.js:240:7)
    at handleError (C:\xxxxxxxx\node_modules\@apollo\client\link\http\http.cjs:323:67)
    at C:\xxxxxxxx\node_modules\@apollo\client\link\http\http.cjs:624:48
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  graphQLErrors: [],
  protocolErrors: [],
  clientErrors: [],
  networkError: FetchError: request to http://localhost:4000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4000      at ClientRequest.<anonymous> (C:\xxxxxxxx\node_modules\next\dist\compiled\node-fetch\index.js:1:65756)
      at ClientRequest.emit (events.js:400:28)
      at Socket.socketErrorListener (_http_client.js:475:9)
      at Socket.emit (events.js:400:28)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    type: 'system',
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED'
  },
  extraInfo: undefined
}`

**Comment by jamie0xgitc0decat** [comment] 2023-04-13 23:52
I was able to resolve the issue by switching from Node 14 to Node 18. This resolved the problem

**Comment by jerelmiller** [comment] 2023-04-14 00:08
@jamie0xgitc0decat thats great to hear! 

@Az-r-ow could you try upgrading Node to see if that resolves your issue as well?

---

> I don't know what you mean by that, I didn't change the default fetch function.

Regarding this statement, I was merely trying to say that it looks like this script is executing in a non-browser environment, likely in a place where it can't connect to `localhost:4000`, which would explain the error you're seeing. The stacktrace indicates this is executing in Node somewhere. I don't think this is an issue with `@apollo/client`, but rather the environment that is executing the fetch to your server. Eventually it makes it to the browser (where it succeeds), but somewhere in there, something is executing this in a Node environment, and thats where you're seeing the failures.

**Comment by Az-r-ow** [comment] 2023-04-14 06:24
> I was able to resolve the issue by switching from Node 14 to Node 18. This resolved the problem.

I just tried switching them up to node 18, nada. However I ran both of them out of docker and the error was gone. 
So I'm thinking it should just be a question of configuration.

**Comment by Az-r-ow** [comment] 2023-04-14 06:26
> @jamie0xgitc0decat thats great to hear!
> 
> @Az-r-ow could you try upgrading Node to see if that resolves your issue as well?
> 
> > I don't know what you mean by that, I didn't change the default fetch function.
> 
> Regarding this statement, I was merely trying to say that it looks like this script is executing in a non-browser environment, likely in a place where it can't connect to `localhost:4000`, which would explain the error you're seeing. The stacktrace indicates this is executing in Node somewhere. I don't think this is an issue with `@apollo/client`, but rather the environment that is executing the fetch to your server. Eventually it makes it to the browser (where it succeeds), but somewhere in there, something is executing this in a Node environment, and thats where you're seeing the failures.

Yes actually, I don't know how and where vue runs it's scripts exactly but as you said it should be in a node environment.

**Comment by jerelmiller** [comment] 2023-04-14 19:37
> I ran both of them out of docker and the error was gone.

Awesome! Glad to hear this!

At this point I think we are a bit beyond the scope of Apollo Client, so I'm going to go ahead and close this issue. Since that script runs in some kind of node environment, my best advice is to either make sure you're able to access `localhost` inside that environment, or you'll need to use some kind of other address (I know docker and `localhost` are tricky sometimes).

I hope you're able to get this to work!

**Closed by jerelmiller** 2023-04-14 19:37 UTC
Labels: ⁉️ question
