### ISSUE TITLE
Why is it always making requests? Next js

### ISSUE THREAD

**Issue by eleviven** [apollographql/apollo-client#7382] opened 2020-11-27 22:17 UTC
I want to read it from the cache for the second time

![alt text](https://media.giphy.com/media/m1ODKvoQEyniorK5mm/giphy.gif)

```js
  const snaps = useQuery(GET_SNAPS, {
    partialRefetch: true,
    fetchPolicy: 'cache-first'
  });
```

**Comment by grantmontgomery** [comment] 2020-11-29 18:02
Same issue, but this seems to only be happening with my useLazyQuery hook, but not my useMutation hook.

**Comment by eleviven** [comment] 2020-11-30 10:05
> Same issue, but this seems to only be happening with my useLazyQuery hook, but not my useMutation hook.

I used this way and fixed my issue:  [with-apollo](https://github.com/vercel/next.js/blob/canary/examples/with-apollo/lib/apolloClient.js)

**Comment by jcreighton** [comment] 2021-02-05 18:29
Because this was a misconfiguration, closing this issue. (If you're still experiencing an issue, feel free to re-open with a reproduction!)

**Closed by jcreighton** 2021-02-05 18:29 UTC
