### ISSUE TITLE
fetchMore with variables doesn't update field policy read args

### ISSUE THREAD

**Issue by jmmendivil** [apollographql/apollo-client#7496] opened 2020-12-18 17:50 UTC
Hi guys. 
I'm trying to get used to using `typePolicies`, it's awesome to have the logic in a single point instead of every `updateQuery`, but when I do a `fetchMore()` it seems like the _args_ from the `read()` aren't updated like the `merge()` and I need them to do a Paginated view as in [Paginated read functions](https://www.apollographql.com/docs/react/pagination/core-api/#paginated-read-functions).

**Intended outcome:**
Get the same _args_ in `read()` as in `merge()` on every update with `fetchMore()` .

**Actual outcome:**
_args_ in `read()` doesn't  update with `fetchMore()`.

**How to reproduce the issue:**

TypePolicy:

```
    {
      ProductsType: {
        fields: {
          getPackProducts: {
            keyArgs: false,
            read(exists, { args }) {
              // args.skip and args.first are the same
              // as the original query, always. Not ok
              return exists && exists.slice(args.skip, args.first + args.skip);
            },
            merge(existing, incoming, { args }) {
              // args.skip and args.first are the original values (first)
              // and updates (skip) on each fetchMore. OK
              const merged = existing ? existing.slice(0) : [];
              const start = args ? args.skip : merged.length;
              const end = start + incoming.length;
              for (let i = start; i < end; ++i) {
                merged[i] = incoming[i - start];
              }
              return merged;
            }
          }
        }
      }
    }
```
Query:

```
const GET_PACKS = gql`
  query($first: Int, $skip: Int) {
    myProducts {
      getPackProducts(first: $first, skip: $skip) {
        id
      }
    }
  }
`;
```

useQuery hook:

```
const { loading, error, data, fetchMore } = useQuery(
  GET_PACKS,
  {
    variables: {
      skip: 0,
      first: 10
    }
  }
);
```

fetchMore

```
<button onClick={() => {
  fetchMore({
    variables: {
      skip: 20
    }
  })
}}>Next</button>
```
**Versions**
```
System:
  OS: macOS 10.15.7
Binaries:
  Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
  Yarn: 1.22.10 - /usr/local/bin/yarn
  npm: 6.14.9 - ~/.nvm/versions/node/v10.15.1/bin/npm
Browsers:
  Chrome: 87.0.4280.88
  Firefox: 84.0
  Safari: 14.0
npmPackages:
  @apollo/client: ^3.3.6 => 3.3.6
```

**Comment by benjamn** [comment] 2020-12-21 16:09
@jmmendivil The `fetchMore` query only writes new data to the cache. If you want the variables of the original `useQuery(GET_PACKS, ...)` query to be updated, you have to update them yourself, as explained in [the `setLimit` example](https://www.apollographql.com/docs/react/pagination/core-api/#read-functions-for-paginated-fields) in the [pagination docs](https://www.apollographql.com/docs/react/pagination/overview/). Please note that the variables you pass to `fetchMore` are not always the variables you would want for the original query, which is why it does not make sense to use the `fetchMore` variables to update the original query automatically.

**Comment by stevenmusumeche** [comment] 2021-04-13 20:30
This is really surprising behavior.  Why wouldn't you want the updated query variables in your read function?

**Comment by sergiidiak** [comment] 2021-05-16 10:59
Given above, you don't really need `fetchMore` then. But..
`read` examples in pagination docs might be confusing for newcomers who follow the given examples. For me, I couldn't understand why Apollo doesn't make any requests when I update query variables (as suggested above) only (without fetchMore). 
Turned out you also need to check if `existing.slice(...)` has some data in it, because if there is no data then it means you haven't loaded this page yet so you need to return `undefined` to trigger network request. It's only a problem for `cache-first` network policy.

**Comment by hwillson** [comment] 2021-05-18 15:08
It doesn't sound like there is an outstanding issue here, so closing. Thanks!

**Closed by hwillson** 2021-05-18 15:08 UTC

**Comment by FezVrasta** [comment] 2021-07-24 17:31
How should I go about implementing a cursor based pagination where I can also preserve the index of the items like in this example (https://www.apollographql.com/docs/react/pagination/cursor-based/#using-list-element-ids-as-cursors) if the `fetchMore` call doesn't provide the cursor used to fetch the additional items? I can't update the cursor on the `useQuery` variables, it doesn't make any sense to me.

**Comment by rossm6** [comment] 2021-10-09 12:39
Ah...

I've been using apollo for months and can't believe I've only just discovered this.

In fact two recent discoveries which struck me as odd together now make sense.

The first discovery was the following query will execute again when the variables passed to the hook change.  Hitherto I'd always assumed that fetchMore was the only way of getting further data for the original query set up in the hook.  In fact questioned whether this was intended behaviour here because I couldn't understand why this would be - https://github.com/apollographql/apollo-client/issues/8847

```
function SomeComponent () {
    const { data, loading, fetchMore } = useQuery(GET_YOUR_LISTINGS, {
        fetchPolicy: 'network-only',
        nextFetchPolicy: 'cache-first',
        variables: {
            filters: {
                ...args.filters
            },
            orderBy: getOrderingForServer(args.orderBy),
            first: PAGE_SIZE,
            after: ''
        }
    });
}
```

Today I stumbled upon this issue because I too noticed that args passed to read did not reflect variables passed to fetchMore.

So my first discovery is the solution for ensuring the correct args are passed to read.

Together I now have something like this -

```
function SomeComponent () {
    const [args, setArgs] = useState();
    const [fetchInitial, { data, loading, fetchMore, called }] = useLazyQuery(GET_YOUR_LISTINGS, {
        fetchPolicy: 'network-only',
        nextFetchPolicy: 'cache-first',
        variables: {
            filters: {
                ...args.filters
            },
            orderBy: getOrderingForServer(args.orderBy),
            first: PAGE_SIZE,
            after: ''
        }
    });

   const fetchCount = useRef(0);
   if(called) fetchCount.current = 1;

    useEffect(() => {
       if(!args) return
       if(!fetchCount.current){
         fetchInitial();
       }
    }, [args, fetchInitial]);

    // fetchMore is then passed to a child infinite scroll component

    return (
     null
    )
}
```
