### ISSUE TITLE
updateQuery merging different data when changing query while fetchMore is not yet finished

### ISSUE THREAD

**Issue by denichodev** [apollographql/apollo-client#2813] opened 2018-01-04 03:03 UTC
Hi, I've read https://github.com/apollographql/apollo-client/issues/2499 and I don't know if it this issue I'm having is related or not.

I am having this issue where `prev` and `result` on `updateQuery(prev, result)` having different context on the data to merge. It happens when I changed query (changing search term) while fetchMore is not yet finished, resulting in items with different query being merged.

**How to reproduce the issue:**
Case: 
1. I am currently on search result page with term `pillow` already have some data, and calling fetchMore.
2. Before fetchMore is done, I quickly changed the term with `iphone`.
3. The `iphone` search query data are merged in `updateQuery` with `pillow` fetchMore result. 

Sorry, I am currently unable to provide the repository to reproduce this. I will provide it later if it's necessary.

**Intended outcome:**
I think the intended outcome is obvious, the `pillow` fetchMore result should be merged according to its search term (fetched earlier in step 1).

This is the code I've been using:
```
fetchMore: (nextPage = 0, listview, additional_params) => {
    return data.fetchMore({
      variables: {
        page: nextPage,
        per_page: listview ? LIST_VIEW_PER_PAGE : GRID_VIEW_PER_PAGE,
        additional_params,
      },
      updateQuery: (prev,  res) => {
        console.log('prev: ', prev); 
        console.log('res: ', res);
        if (!res.fetchMoreResult) {
          return prev;
        }

        const newData = res.fetchMoreResult.search_results_product;

        return {
          ...prev,
          search_results_product: {
            ...prev.search_results_product,
            total_data: newData.total_data,
            items: [...prev.search_results_product.items, ...newData.items],
          },
        };
      },
    });
  },
```

**Actual outcome:**
The data from `pillow` fetchMore are merged in updateQuery with `iphone`, resulting in wrong search result displayed.

Weirdly, the `res.variables` in `updateQuery(prev, res)` showing that the query is for `iphone` instead of the actual query for fetchMore, which is `pillow`.

**Version**
- apollo-client@2.1.0

**Comment by protyze** [comment] 2018-02-09 09:27
I'm experiencing the same behaviour. When the variables for the query are changed while fetchMore is in flight, the results of "fetchMore" (for the old variables) will be merged with the results of the query with current variables.

Example: You have a list with 2 tabs (changing tabs will change the "category"-variable for the query). So fetchMore is in progess while having tab 1 selected (category 1). Now the users switches to tab 2 and later the fetchMore results for tab 1 will be appended to tab 2.

The updateQuery-Function should provide the "previosResults" for the initial variables so we can merge accordingly.

**Comment by denichodev** [comment] 2018-04-03 12:05
Is there any update regarding this issue?

**Comment by mefjuu** [comment] 2018-04-05 09:33
Any chances to fix it? It seems to be quite significant disfunction. A bit funny considering an activity of Apollo team on various React conf and theirs effort on promoting Apollo integrations...

**Comment by jakwuh** [comment] 2019-05-03 17:01
Should be fixed by https://github.com/apollographql/apollo-client/pull/4640

**Comment by dylanwulf** [comment] 2019-06-03 15:51
@jakwuh Thank you. Hopefully that gets reviewed soon. Do you know of any workarounds I could use in the meantime?

**Comment by jakwuh** [comment] 2019-06-03 21:31
@dylanwulf yes, you can implement your own `graphql` enhancer

**Comment by hogiyogi597** [comment] 2019-07-02 21:37
@jakwuh I am not quite sure I follow how to implement a custom graphql enhancer to solve this problem. Maybe I am too deep into trying different implementations to see clearly but could you give a little insight on how this could be accomplished?

**Comment by glennpatrickryan** [comment] 2019-10-07 21:12
Any update on the status of this issue?

**Comment by wosephjeber** [comment] 2020-05-07 16:53
I'm also very interested in the progress of this. My company has been struggling with bugs for some time now caused by this issue, and we've been unsuccessful in multiple attempts to work around it. Any update on if/when #4640 might be merged?

**Comment by hwillson** [comment] 2021-04-27 13:55
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Closed by hwillson** 2021-04-27 13:55 UTC
