### ISSUE TITLE
ES Modules

### ISSUE THREAD

**Issue by msf-caesar** [apollographql/apollo-client#10319] opened 2022-11-29 17:51 UTC
I am using Svelte with apollo, everything works fine, the problem is that I have to pass the .cjs to carry out my build and it is not comfortable.

**Development:**

`import { ApolloClient } from '@apollo/client/core';`

**Production**

`import { ApolloClient } from '@apollo/client/core/core.cjs';`

**Comment by alessbell** [comment] 2022-11-29 21:11
Hi @msf-caesar 👋 Is there a reproduction you can share? If not, can you try importing from `@apollo/client/core/index.js` and let me know if that helps?

[Here's an example](https://github.com/benmccann/sveltekit-apollo-build-bug/blob/working-version/src/routes/__layout.svelte#L2) from a demo app [shared by a community member](https://github.com/apollographql/apollo-client/issues/8218#issuecomment-1205689277) using Apollo Client + SvelteKit.

**Comment by alessbell** [comment] 2022-12-05 15:43
I'm going to close this out as a duplicate since there is an existing discussion in https://github.com/apollographql/apollo-client/issues/8218, but feel free to post additional info in that thread. Thanks!

**Closed by alessbell** 2022-12-05 15:43 UTC
Labels: ⁉️ question, 🏓 awaiting-contributor-response, 👯‍♂️ duplicate
