### ISSUE TITLE
After refetch fails, successful fetchMore sends updateQuery undefined previousResults

### ISSUE THREAD

**Issue by treyp** [apollographql/apollo-client#5169] opened 2019-08-14 05:49 UTC
**Intended outcome:**
After server downtime, during which a call to `refetch` fails, I would expect future successful queries using `fetchMore` to call the `updateQuery` function with `previousResults` from before the downtime.

**Actual outcome:**
After failed calls to `refetch`, successful calls to `fetchMore` call the `updateQuery` function with a first argument (`previousResults`) value of `undefined`. At that point, there is no way to use the existing results.

A log looks something like this:
```
Server online, screen loading
Component rendering with data: {loading: true, networkStatus: 1, error: undefined}
Component rendering with data: {names: ["a", "b", "c", "d", "e"], loading: false, networkStatus: 7, error: undefined}
Server going offline
Attempting to sort (using `refetch` with variables as a promise)
Component rendering with data: {names: ["a", "b", "c", "d", "e"], loading: true, networkStatus: 2, error: undefined}
Component rendering with data: {names: ["a", "b", "c", "d", "e"], loading: false, networkStatus: 7, error: "Error: GraphQL error: ..."}
Sort failed
Server going online
Attempting to paginate
fetchMore's updateQuery method called with previousResults: undefined
```

**How to reproduce the issue:**
Set up a repo that uses both `refetch` for sorting and `fetchMore` for pagination.
1. Load the initial results successfully
2. Go offline
3. Try sorting the results (which should fail)
4. Go online
5. Try paginating
The `updateQuery` method is called with a first argument, `previousResults`, of `undefined`.

I've created a branch to demonstrate the behavior:
https://github.com/treyp/react-apollo-error-template/tree/previousresults-undefined

This can also be found on CodeSandbox: 
https://codesandbox.io/s/github/treyp/react-apollo-error-template/tree/previousresults-undefined

Follow the steps above, just like the screen recording here, to reproduce.

![apollo-updatequery](https://user-images.githubusercontent.com/49319/62997021-79094580-be2c-11e9-8733-16f96099a9ae.gif)

**Versions**
```
  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    npm: 6.10.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Safari: 12.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-link-batch-http: ^1.2.12 => 1.2.12 
    react-apollo: ^3.0.0 => 3.0.0 
```

**Comment by kl4n4** [comment] 2019-09-04 22:33
I ran into the same issue - would appreciate to know how to properly handle occasional network-outages (= error states). Since reloading (using refetch) and after a successful reload to paginate (using fetchMore) does not work.

**Comment by emanuelschmitt** [comment] 2019-09-21 09:13
Having a similar issue here. Apollo throws the exact same error when running a local @client query in between a same server-side query using `fetchMore`. The callback parameter `previousResults ` of updateQuery is then `undefined`. Running `react-apollo@3.1.1`

**Comment by Tautorn** [comment] 2020-01-04 00:31
Same problem here. I'm using `fetchMore` and `updateQuery`. Ref return undefined

**Comment by richardscarrott** [comment] 2020-01-22 16:07
I've noticed that errors from `fetchMore` aren't returned as an error in the hook, e.g.

```js
const { networkStatus, error, data, fetchMore } = useQuery(QUERY)

console.log(error); // error only exists if the initial query fails, not if fetchMore fails?

<button onClick={() => fetchMore({ ... })}>
```

Not sure if this is expected behaviour?

**Comment by cidevant** [comment] 2020-01-29 14:46
same error +1, anyone has fix for this?

**Comment by XiaohengLiu** [comment] 2020-02-10 20:31
similar issue, but not exactly the same. in my case, for some of my queries, the fetchMore works fine, but there are one or two, the `prevResult` is undefined.

Can anyone provide what can be the cause to make prevResult undefined?  eg: update the query result object directly (mutate queryResult)?

**Comment by ManAnRuck** [comment] 2020-02-15 09:09
i have the same issue, that fetchMore is for some queries very buggy.

when I fetch more directly it's undefined. 
after ignoring this and run refetch the and then fetchMore/updateQuery it works fine. 🧐

**Comment by langrafik** [comment] 2020-02-15 13:16
same error after call fetchMore 2 times to different queries; example:
`graphql(query1, {
    options: () => {
      return {
        variables: {
          limit: itemsLimit,
          after: 0
        },
        fetchPolicy: 'cache-and-network'
      };
    },
    props({ data }) {
      const { loading, error, feed, fetchMore } = data;
      const loadData = (after, dataDelivery) => {
        return fetchMore({
          variables: {
            after: after
          },
          updateQuery: (previousResult, { fetchMoreResult }) => {
            //some code

            return {
              feed: {
                totalCount,
                edges: displayedEdges,
                pageInfo,
                __typename: 'Contents'
              }
            };
          }
        });
      };

      return { loading, feed, loadData };
    }
  }),
  graphql(query2, {
    options: () => {
      return {
        variables: {
          filters: {
            registration: true,
            types: []
          },
          limit: 10
        },
        fetchPolicy: 'network-only',
        notifyOnNetworkStatusChange: true
      };
    },
    props({ data }) {
      const { refetch, eventsWithFilters, fetchMore } = data;

      const loadMore = after => {
        return fetchMore({
          variables: {
            limit: 10,
            after: after
          },
          updateQuery: (previousResult, { fetchMoreResult }) => {
            //some code
            return {
              eventsWithFilters: {
                totalCount,
                edges: displayedEdges,
                pageInfo,
                __typename: 'Events'
              }
            };
          }
        });
      };

      return {
        refetch,
        eventsWithFilters,
        loadMore
      };
    }
  })`
any thoughts?

**Comment by hiroyalty** [comment] 2020-06-22 00:10
Same problem after it query return over 20 products, either during useQuery or refetch

**Comment by ManAnRuck** [comment] 2020-07-22 17:08
still happens with **@apollo/client:3.0.2** 😢

**Comment by hwillson** [comment] 2021-04-27 15:03
Can someone confirm if this is still an issue with `@apollo/client@latest`? I'll close this for now, but happy to re-open if this is still happening. Thanks!

**Closed by hwillson** 2021-04-27 15:03 UTC
