### ISSUE TITLE
subscribeToMore updateQuery ineffective for existing data

### ISSUE THREAD

**Issue by pennyandsean** [apollographql/apollo-client#3480] opened 2018-05-19 01:48 UTC
It looks like `subscribeToMore`'s callback `updateQuery` behaves differently depending whether the inbound record is already existing in the client cache. That is, for new records (as in every example on the web) you are required to return a new version of the cache based on previous and subscriptionData. Great for manually merging new records into the local cache.

BUT, if the inbound record already exists (by id), the new record is instantly merged (into `previous`) and there is nothing `updateQuery` callback can do about it.  `updateQuery` is still called, but the new data comes into `updateQuery` already merged into the `previous` parameter.

Ideally, I’d like to modify inbound records in the case of insert or update.  This may be intended behaviour, since we are talking about something called `subscribeToMore`, rather than _subscribeToChanges_.  Either way the documentation is silent of what happens when the record already exists and there seems to be no way to programatically intervene for those inbound records.

**Intended outcome:**
I would expect the `updateQuery` callback parameter `previous` to contain only previous data.

**Actual outcome:**
 `updateQuery` callback parameter `previous` to contains previous data and new data for any existing ids in the cache.

**How to reproduce the issue:**
Setup a query with subscribeToMore and push an updated record with an id already in the cache.

**Version**
- apollo-client@2.3.1

**Comment by lipsotiko** [comment] 2018-09-21 05:44
Hi have been witnessing the same. I have an sample code base here the reproduces the issue: https://github.com/lipsotiko/demo_spring_grapghql_apollo

**Comment by lipsotiko** [comment] 2018-09-21 05:51
Just found a working example and I also updated my repo with the same updateQuery syntax as I found here: https://stackoverflow.com/questions/42492943/issue-with-automatic-ui-updates-in-apollo-updatequery-not-working-properly-wi

**Comment by asabhaney** [comment] 2019-02-01 08:19
I can confirm that this is still happening in `apollo-client@2.4.12`.

The example below exemplifies this (using React):

```js
@graphql(getNoteList, {
   options: ownProps => ({
      fetchPolicy: 'network-only',
      notifyOnNetworkStatusChange: true,
      variables: {}
   }),
   props: ({
      data: {
         noteList = { items: [], listInfo: {} },
         error,
         fetchMore,
         networkStatus,
         refetch,
         subscribeToMore
      }
   }) => ({ noteList, error, fetchMore, networkStatus, refetch, subscribeToMore })
})

export default class NotesMenu extends Component {
   componentDidMount() {
      this.props.subscribeToMore({
         document: onNoteChanged,
         variables: {},
         updateQuery(prev, { subscriptionData }) {
            // `prev` already contains the new data
            return prev
         }
      })
   }

   ...
}
```

The`getNoteList` returns a list of type `Note`, and the subscription `onNoteChanged` receives an object of type `Note`. The `Note` item in the cache seems to be automagically updated before the `updateQuery` function is executed.

Using:
- apollo-cache-inmemory@1.4.2
 - apollo-client@2.4.12
- apollo-link@1.2.6
- apollo-link-ws@1.0.12
- react-apollo@2.4.1

**Comment by nuragic** [comment] 2019-03-14 09:30
I almost died when I hit this one! :feelsgood: 

The good news is that there's an (hopefully for you) easy workaround here: as you may know, Apollo do an automatic cache update based on the `id` field, so, if you **need** fully control of the update right now you can just _rename_ the `id` field from the response of the subscription; yeah, you need to have fully control of your schema in order to do so. I did so and it worked for me. Here's a simplified example (kind of pseudocode, sorry if any error, not intended to compile out of the box but the approach is the following):

```js
// Somewhere in your server (Schema)…
type Query {
  tweets: [Tweet]
}

type Subscription {
  editOnTweets: Tweet
}

type Tweet {
  // The real Tweet id: used for Query, Mutation…
  id: String
 // This is a mirror/copy of the "id": it will be ONLY returned from the Subscription
  idFromSubscription: String
  content: Whatever
}
```

```js
// Somewhere in your server (Subscription publish)…
pubsub.publish('TWEET_EDIT_TOPIC', {
  editOnTweets: {
    idFromSubscription: 'same_value_as_id',
    content: { /* whatever */ },
  },
});
```

```js
// Somewhere in your client…
const TWEETS_ALL_QUERY = gql`
  query {
    tweets {
      id
      content {
        #whatever
      }
    }
  }
`;

const TWEETS_ALL_SUBSCRIPTION = gql`
  subscription {
    editOnTweets {
      idFromSubscription
      content {
        #whatever
      }
    }
  }
`;
```

```js
<Query query={TWEETS_ALL_QUERY}>
// …
subscribeToMore({
  document: TWEETS_ALL_SUBSCRIPTION,
  updateQuery: (prev, { subscriptionData }) => {
    if (!subscriptionData.data) { return prev; }
    const newTweet =  subscriptionData.data.editOnTweets;
    const tweets = [ ...prev.tweets];
    // do your merge MANUALLY based on "idFromSubscription"
    const index = findIndex(tweets, { id: newTweet.idFromSubscription });
    merge(tweets[index], newTweet);
    // delete "idFromSubscription", it was only useful here and it may cause further bugs
    delete tweets[index].idFromSubscription;
    return {
      tweets,
    };
  },
})
```

The bad news unfortunately are (IMHO®) that this bug raise **FUD**, because there is still no response from the Apollo team (bug reported in May 2018) and this is a _critical_ feature for enterprise products that rely heavy on real-time data. I guess a lot of people are in the same situation or perhaps share the same feelings. Cc @peggyrayzis

Thanks anyway for the great stuff you keep doing! Let us known if we could do anything to help. 👋

**Comment by tsaiDavid** [comment] 2019-03-20 18:54
Running into this issue as well!

**Comment by dmi3y** [comment] 2019-03-20 23:47
In our case the combo is:

- SSR via nextjs
- Error on server side because no cache implemented there

Solution:

Conditionally use subscriptions only in browser e.g.

> process.browser && this._subToMore(subscribeToMore);

**Comment by nateq314** [comment] 2019-04-04 16:59
Running into this here too. Just wasted hours debugging an "update" subscription handler in client code only to realize that the cache has already been updated prior to the handler ever getting called! In my case the end result isn't bad, more a feature than a bug. What I don't like is it's too "magical" and there doesn't seem to be any reason for it. No explanation anywhere in the docs. Nice workaround @nuragic but it shouldn't be necessary to do this in the first place! Any word on this Apollo team?

**Comment by jbaxleyiii** [comment] 2019-07-09 21:23
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Closed by jbaxleyiii** 2019-07-09 21:23 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage

**Comment by gabsprates** [comment] 2019-08-06 22:33
Has this been fixed?

**Comment by StefanSmith** [comment] 2019-08-12 13:12
I like the default behaviour of updating the cache if the item already exists, however, this is now causing me issues where an item on version=2 is wound back to version=1 because the subscription messages arrived out of order (version 2 arrived before version 1). I'd like the ability to apply my own logic to never overwrite a newer version of an item with an older version but there is no way to do this with `subscribeToMore()` and `updateQuery()`. Any workarounds you would recommend today?

**Comment by seandearnaley** [comment] 2019-09-09 14:36
+1 looking for a workaround, would also like to be able to prevent the cache being updated by a real time update

**Comment by TLevesque** [comment] 2019-11-05 15:59
Hi, I'm facing the same problem, I just want to build real-time CRUD app with Apollo, and maybe I'm missing something, but from what I'm seeing here is that only CRD is possible in a clean way? 
(Out of the smart workaround suggested by @nuragic, because I don't want to add extra "renamed Id" into the schema to handle this Apollo's behavior issue, because on a large app it will be too messy). 

I've built a "Todo app" to test Apollo's subscription with react hooks to illustrate the problem: https://github.com/TLevesque/todo-app/tree/master

And I don't see a clean way to have the "updatedTask" subscription to work to update the query from subscribeToMore, to render the page with useEffect to display the updated task, without having user refreshing their page, does someone have a best practice? 

`useEffect(() => {
    subscribeToMore({
      document: TaskUpdated,
      updateQuery: (prev, { subscriptionData }) => {
        if (!subscriptionData.data) return prev;
        const newTask = subscriptionData.data.taskUpdated;
        const tasks = [...prev.tasks];
        const index = tasks.findIndex(task => task.id === newTask.id);
        tasks.splice(index, 0, newTask);
        tasks.splice(index + 1, 1);
        const newQuery = {
          ...prev,
          tasks
        };
        return tasks;
      }
    });
...
`

Or @jbaxleyiii can you reopen the ticket? Because for me it is a big issue to build a real-time app with apollo...

Thanks for your help!

**Comment by wbeuil** [comment] 2019-12-20 21:46
Still having this issue. Any workaround in the beta ?

**Comment by OttoTS** [comment] 2020-01-15 22:38
Still having this issue as well.

**Comment by bantingGamer** [comment] 2020-05-05 09:10
After playing around a bit with my own message app im working on, i found that when receiving new messages with a new **id** I have to return the merged data myself. But when im updating the chatRooms to display which chatRoom should be at the top of my screen (which one has the newest message), then my update happens automatically and I just return prev.

so maybe this is the expected behavior one is looking for.

**Comment by DelToney** [comment] 2020-05-12 15:29
running into this issue as well. I dont understand the idea of this feature in terms of the subscription. Like, I understand that it takes more off of the developers hands, but this seems like software 'magic' is pulling the veil over things that should be available to the developer. 

whats even more strange is that in my environment **SOMETIMES** I get the behavior that I had originally wanted, but sometimes I dont. it seems like theres some sort of function thats async and being run and isnt awaited upon before running the updateQuery handler

**Comment by airstance** [comment] 2020-05-13 07:54
It gets worse.  The previousResults parameter contains the results from the mutation that caused subscription to fire.  If the person who made the mutation only asks for a few fields, then only those fields will be in the cache now.  In other words, the client isn't merging but overwriting the object before updateQuery is even called.  

The merge workaround above doesn't work because the prevRes is not actually the previous results, but the response of the mutation.

**Comment by deafult2010** [comment] 2020-06-03 17:33
Just check whether the id of the user is equal to the id of the incoming comment/post from the subscription. If it is then ignore the incoming feed if it isn't add it to the array of  comments/posts

e.g.: 

  const { subscribeToMore, ...result } = useQuery(FETCH_POSTS_QUERY);
  const { user } = useContext(AuthContext);

  useEffect(() => {
    subscribeToMore({
      document: SUB_POSTS,
      updateQuery: (prev, { subscriptionData }) => {
        if (!subscriptionData.data) return prev;
        const newFeed = subscriptionData.data.newPost;
        console.log(newFeed);
        console.log(prev);
        console.log(user);
        if (user == null || newFeed.user.id !== user.id) {
          return Object.assign({}, prev, {
            getPosts: [newFeed, ...prev.getPosts],
          });
        }
        return Object.assign({}, prev, {
          getPosts: [...prev.getPosts],
        });
      },
    });
  }, []);

**Comment by Valdenirmezadri** [comment] 2020-09-09 20:40
Hello i'm having the same issue

**Comment by rickco75** [comment] 2020-11-01 20:30
I had no issues when adding a post however I was getting the error when removing a post i seem to resolve it by spreading the previous posts as well as the updated cache
`    subscribeToMore({
      document: DELETE_POST_SUBSCRIPTION,
      updateQuery: (prev, {subscriptionData}) => {
        if (!subscriptionData.data) return prev
        const newFeedItem = subscriptionData.data.deletePostSub
        const newPosts = [...prev.getPosts].filter(post => post.id !== newFeedItem.id)
        return Object.assign( {}, prev, {
          getPosts: [...newPosts, ...prev.getPosts]
        })
      }
    })`

**Comment by daniel-bischoff** [comment] 2021-09-12 11:41
Just ran into this after debugging (for an hour) why my app "magically" contains the updated item in the "prev" object even after entirely removing my own merging logic. At least there should be an explanation about that behaviour in the documentation: https://www.apollographql.com/docs/react/data/subscriptions/#subscribing-to-updates-for-a-query

**Comment by ryancrunchi** [comment] 2022-02-18 13:19
I have this issue with latest version : 3.5.9
The previous parameter contains the newly data and not the previous one.

pseudo code :

```javascript
// default fetch policy
// initial user name is "foo"
const userGetResult = useQuery(gql(query { userGet { name ... } }))


// later in time, server updates name to "bar" and subscription update is called :
useEffect(() => {
  return userGetResult.subscribeToMore({
    document: gql(subscription OnUserUpdate { onUserUpdate { name ... } }),
    updateQuery: (prev, { subscriptionData }) => {
      const oldUser = prev.userGet
      const newUser = subscriptionData.data?.onUserUpdate
      console.log('oldUser', oldUser.name) // "bar"
      console.log('newUser', newUser.name) // "bar"
      // ⚠️ oldUser and newUser always have the same fields value.
      // oldUser should have name: "foo", but already has name "bar" from server update
      ...
    }
  })
}, [])
```

**Comment by tuanalumi** [comment] 2023-01-03 04:36
> The previous parameter contains the newly data and not the cached one.

To be precise, I think the `prev` already contains the cached result, because when I tried to get the cached result using `readQuery`, it's the same. Just the cached result is already updated with the newly one, before sending to `updateQuery`. That's... a strange behavior IMHO.
