### ISSUE TITLE
Apollo Client (Cache?) Strips port number on page refresh

### ISSUE THREAD

**Issue by Owchzzz** [apollographql/apollo-client#4692] opened 2019-04-11 16:59 UTC
When creating a new instance of apollo client for the first time my query works. However for subsequent calls after a page refresh the client returns an Unexpected token < JSON at line 0 error. 

Which i thought was something to do with the cache, and i guess im partially (correct?) lol. okay so for some reason, the client stips the port number from the url that was provided.

my graphql url: http://localhost:3000/graphql
After first initial load w/query, my graphql url becomes: http://localhost/graphql

here is the code used to initialize the apollo client
```
initialize() {
        if(!this.token) {
            console.error("Can not initialize a track manager because no token was set with setToken(token) funciton");
            return false;
        }

        this.cache = new InMemoryCache();
        this.link = new HttpLink({
            uri: this.url,
            headers: {authorization: this.token}
        })
        this.client = new ApolloClient({
            cache: this.cache,
            link: this.link,
            onError: (e) => {
                console.log('graphQLErrors', e);
              }
        })
    }

```

**Comment by abernix** [comment] 2019-07-12 18:02
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already, but it's hard to tell without a runnable reproduction of the problem.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to a runnable CodeSandbox reproduction using the latest versions and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by abernix** 2019-07-12 18:02 UTC
