### ISSUE TITLE
Error: Could not connect to the server | Unhandled Runtime Error

### ISSUE THREAD

**Issue by Utkarsh-Kumar384** [apollographql/apollo-client#7823] opened 2021-03-11 08:10 UTC
**Intended outcome:**
Apollo to work without any issues both on mobile devices as well as desktop. However, there is this weird issue that causes Apollo to not work on mobile devices.

**Actual outcome:**
Errors out like the one mentioned below:
https://i.stack.imgur.com/In94i.png
https://i.stack.imgur.com/zMnUp.jpg
**How to reproduce the issue:**

As for reproducing the issue, it's almost impossible. As I need to share pretty much everything that I have in my project. However, I'll try to give almost all the information required to fix the issue. I also have a custom apollo client setup as done in the following website [https://www.apollographql.com/blog/building-a-next-js-app-with-apollo-client-slash-graphql/](URL)

I have the following code:
```
import { useMemo } from "react";
import {
  InMemoryCache,
  ApolloClient,
  HttpLink,
  NormalizedCacheObject,
} from "@apollo/client";

let apolloClient: ApolloClient<NormalizedCacheObject>;

const createApolloClient = () => {
  return new ApolloClient({
    ssrMode: typeof window === "undefined",
    link: new HttpLink({
      uri: process.env.API_ENDPOINT,
    }),
    cache: new InMemoryCache(),
  });
};

export function initializeApollo(initialState: object | null = null) {

  const _apolloClient = apolloClient ?? createApolloClient();

  // If your page has Next.js data fetching methods that use Apollo Client,
  // the initial state gets hydrated here
  if (initialState) {
    // Get existing cache, loaded during client side data fetching
    const existingCache = _apolloClient.extract();

    // Restore the cache using the data passed from
    // getStaticProps/getServerSideProps combined with the existing cached data
    _apolloClient.cache.restore({ ...existingCache, ...initialState });
  }

  // For SSG and SSR always create a new Apollo Client
  if (typeof window === "undefined") return _apolloClient;

  // Create the Apollo Client once in the client
  if (!apolloClient) apolloClient = _apolloClient;

  return _apolloClient;
}

export function useApollo(initialState: object) {
  const store = useMemo(() => initializeApollo(initialState), [initialState]);

  return store;
}
````
I almost always use the `initializeApollo()` function with the getServerSideProps and getStaticProps method of Next js
**Versions**

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD (I use Yarn for this project)
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.45) 
  npmPackages:
    @apollo/client: ^3.3.7 => 3.3.11

**Comment by hwillson** [comment] 2021-05-12 00:46
@Utkarsh-Kumar384 this error could be caused by numerous things, many of which wouldn't be Apollo Client's fault. Without some form of runnable reproduction, there isn't much we can do to help here. Maybe start with your full application and start to pull things out until you have the least amount of code possible, that still demonstrates this problem? I'll close this for now since there isn't much we can do to help, but we'll be happy to re-open this issue if you're able to provide a small runnable reproduction. Thanks!

**Closed by hwillson** 2021-05-12 00:46 UTC

**Comment by Utkarsh-Kumar384** [comment] 2021-05-12 05:37
@hwillson oh sorry for not closing the issue, it’s resolved. It was because my backend endpoint was a http local server. Therefore, using the link provided by services like ngrok solved the issue. 

Never knew Apollo needed https even while developing. Will this in mind!

Thanks for the help though!
