### ISSUE TITLE
Can't find variable: module

### ISSUE THREAD

**Issue by kations** [apollographql/apollo-client#4835] opened 2019-05-17 13:08 UTC
Seems to have something todo with immutable-tuple
module.exports = __webpack_public_path__ + "static/media/tuple.e6b50867.mjs";

used in a expo web project
https://github.com/expo/web-examples/tree/master/expo-managed-workflow

**Comment by abernix** [comment] 2019-07-12 18:27
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already, though it's difficult to determine quickly if that's the case or not without a runnable or cloneable reproduction of the problem.

If this is still a problem, we welcome anyone who is experiencing the problem (or anyone who comes across this issue and is able to assist) to build a reproduction of the problem into a runnable CodeSandbox reproduction](https://codesandbox.io/), using the latest versions of the appropriate packages, and sharing the link to that reproduction in this issue.

I'm happy to re-open if this is still occurring and someone can provide a reproduction!

**Closed by abernix** 2019-07-12 18:27 UTC
