### ISSUE TITLE
Allow async onCompleted & onError callbacks

### ISSUE THREAD

**Issue by pieterjandebruyne** [apollographql/apollo-client#11571] opened 2024-02-05 13:21 UTC
### Issue Description

Passing async functions is not typed correctly
Could we change the types of onCompleted and onError to also allow for async functions?

Current:
```
onCompleted?: (data: TData) => void;
onError?: (error: ApolloError) => void;
```

Expected:
```
onCompleted?: (data: TData) => void | Promise<void>;
onError?: (error: ApolloError) => void | Promise<void>;
```

### Link to Reproduction

not-applicable

### `@apollo/client` version

3.9.2

**Comment by jerelmiller** [comment] 2024-02-05 14:59
Hey @pieterjandebruyne 👋 

`void` should allow async functions just fine. We just don't do anything with the return value, so we don't need to have your function return a promise.

Check out [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCyyYEMbAQB2ANChgIrLpQCeZA5gI4A2cAvnAGZQQhwByAAK5ILFhAD0AYxbB0RGAIDcAKFXTiqeBQCqAUQBKATTgBeOMxYADaxq3xMugCoBBZwEkA8gDlzl1lt1NHQqGloACj0jYzIEVTg4YgBhPjAWdBh0ABMALjhcVFoiaTgIgEpzAD5EdhIEpKJ9KF4ofMLi0orq2tV2cuCMbDwCYginN09fOIaUtIysvIKikrLKsxqEOtmmluh2la71zfY+8qA). You can see `async` functions work with `useMutation` and `useQuery` just fine.

Are you seeing something different? If so, could you put together a TS playground, or some other form of reproduction where you're not seeing this work correctly?

**Comment by pieterjandebruyne** [comment] 2024-02-05 16:32
Hi @jerelmiller . Thanks for the quick response. Everything working as intended but because of the mistype some ESLint rules are not being respected, in particular `TypeScript rule S6544`.
https://typescript-eslint.io/rules/no-misused-promises/#checksvoidreturn
Should have included this in my initial message..

It is possible to disable in eslint configs but I see no issues with changing it inside Apollo code (as you no not do anything with the return types anyways) eg. I know a lot of people use sonarcloud for some eslinting on ci/cd and they have the rule enabled by default so it would show up as a bug when passing promises to onCompleted.

**Comment by jerelmiller** [comment] 2024-02-05 17:07
@pieterjandebruyne thanks for that helpful info! I'm going to add this as an agenda item for our next team meeting to chat about. I suspect if we adopt this change, we'll probably want to do a more complete sweep of the codebase to apply it to more areas where returned promises would be acceptable. I'd like to discuss with the team though to best understand what direction we'd like to go. Thanks!

**Comment by phryneas** [comment] 2024-02-06 09:53
I have a clarifying question here:

As far as I understand it, the purpose of the ESLint plugin is to catch situations where an error thrown inside an `async` function would not be handled, meaning when there is no `.catch` called on the resulting promise and it would cause an uncaught promise rejection.

We do call `onCompleted` and `onError`, but if you throw an error in your own code in there, we won't catch that - it would result in an uncaught promise rejection.

Isn't the ESLint plugin doing it's job perfectly here?  
I feel if we added those `Promise<void>` return types, we'd indicate to ESLint that we actually handle that resulting promise - cheating you ESLint rule out of an actual positive finding.

**Comment by pieterjandebruyne** [comment] 2024-02-06 20:35
An async functions return type will always be Promise<ReturnType> regardless of handling errors correctly or not?
````
const mockedApiCall = async () => {
    return Promise.resolve(true)
}

const asyncFc = async () => {
    try {
        await mockedApiCall()
    } catch (error) {
        console.error('Error caught', error)
    }
}
````
I made this[ TS codepen](https://www.typescriptlang.org/play?ssl=11&ssc=2&pln=1&pc=1#code/MYewdgzgLgBAtiYBrApgEwIIAcCWBhAQwBsiYBeGAiATzGBgAoBKcgPhgG8AoGXmAJxRQArvzAwACvxBwcEFADpBEEEQBuKBlH7CUTLgF8uXUJFhVawAGL0KFuoxZl23PjG3VOPN3wIB3AhxYBGR0bHxiImZvXgMYYAIoYAALRhR+aX4WVx9eUxUiRXTMhgByAFEMkH54gmEAc2SoUoAaGGLq-TcjAyA) so you can check the types, even if you would catch the errors, the type of the "asyncFc" will always be Promise<void>

Same would be true when using then/catch syntax, if we would pass this "asyncFc" to the onCompleted callback the eslint error would popup because we pass type () => Promise<void> to a property that expects () => void.

**Comment by phryneas** [comment] 2024-02-07 09:41
Yes, that's one of the limitations of this ESLint rule - it just looks at types and not info functions.  
That's why ESLint is adding a way to specify ["safe promises"](https://github.com/reduxjs/redux-toolkit/pull/4102) for their [no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises/) rule.

The main question would be here: why do you have it's rule? What it it's meaning? What should it actually *prevent*?

My assumption here is "it should prevent you to pass Promises into places where their errors are not being handled" - and if that's the intention, the rule is currently doing the right thing. We certainly do not handle those promise rejections.

If it is in your code base to do something other than that, please tell me - we can't get to the point of making a decision on this without knowing what this rule is actually meant for. 

We don't want to break the intended functionality of ESLint on accident. (I'm also pinging @JoshuaKGoldberg here, maybe he can enlighten us a bit on the intention of that rule).

**Comment by JoshuaKGoldberg** [comment] 2024-02-07 17:05
👋 thanks for the ping! If I'm reading this right, what is being asked for here is centered around the [`no-misused-promises`](https://typescript-eslint.io/rules/no-misused-promises) rule (so, +1 to https://github.com/apollographql/apollo-client/issues/11571#issuecomment-1927392718). To recap, `no-misused-promises` enforces that if a location is typed as a function returning `void`, a function that returns a `Promise` isn't provided to that location. We can think of that as a kind of sibling to [`no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises): it's not that a Promise is floating, it's that code is set up in a way that will likely create floating Promises later on.

[Here's a reduction of the code in question](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=CYUwxgNghgTiAEAzArgOzAFwJYHtXwHcsMALAeVQGEcBbABwhAxGAB4ARKDKAPgAoAUPHjAuUAFzxO3ADRD4eavUbNgkvqO6TpUAJTwAvD3gA3HFmADdksxYDcAgaEiwEKdNjzwaATwpKGJhYNMUkAZwwYLFQAc2t4AAUYWiwwkFZbYB4HASJSf1pA1T4AIgA6CpKZbz8qQpUWXQcAembhdo7OrvgAPz7%2Bgf6BVsTkmlSEOAxkGFQWeGikNExcfFgY5BoQVAxCEhA4eChTc2B4KZn8Aigw%2BBAADzpwVTKgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFtLlZkiACa1i0Dr0GoMkRNHHRI4MAF8QKoA&tsconfig=&tokens=false):

```ts
declare function withOnCompleted<Data>(
  data: Data,
  onCompleted: (data: Data) => void
): void;

declare function myOnCompleted(data: string): Promise<void>;

withOnCompleted("...", myOnCompleted);
//                     ~~~~~~~~~~~~~
// Promise returned in function argument where a void return was expected.
```

If the contents of `withOnCompleted` call `onCompleted(data)`, they wouldn't know to handle the created Promise.

So, yes, +1 from me on this types request 😄. If an API is meant to take in a function that's allowed to return a Promise, then it'd be better (from the linting perspective) to mention that in the types. That way the lint rules can let folks know when they're passing a Promise-returning function in a place that _can't_ handle it appropriately.

Is that what you're looking for @phryneas?

**Comment by JoshuaKGoldberg** [comment] 2024-02-07 17:19
Oh! Yes you're right and my interpretation of the API was wrong 😄 awesome. `no-misused-promises` is right to complain then!

**Comment by phryneas** [comment] 2024-02-07 17:31
I think on that basis I'd say that we should not be changing our types, as it would imply some kind of security to our users that actually isn't the case.

We also can't just handle promise rejections on these functions in our code base since there's just not a "right thing to do" for us - if that functions throws, it's very unclear how we should go about it and what the result should be.

I guess if you don't want the ESLint rule to trigger in these situations, you'll need to disable it - or you'd have to write code that won't trigger it.

So in this case, instead of
```js
onCompleted: async () => {
  // code
}
```
you'd have to write some kind of IIFE
```js
onCompleted: () => {
  (async () => {
    // code
  })().catch(e => {
    // handle errors
  })
}
```

I know that's kind of a pain, but you have enabled this ESLint rule because you *want* it to be strict here - if we were to change our types here, it would just be "cheating around the eslint rule", but not actually help you solve the issue that it points at.

=> I'm going to close this issue, since there is nothing on our side that we really can do about this. 
You'll have to make the decision on which route to take and how strict you want to be in your code base with your team.

**Closed by phryneas** 2024-02-07 17:31 UTC
Labels: ⛑ TypeScript, ✍️ working-as-designed
