### ISSUE TITLE
useQuery - missing initial payload on subsequent deferred chunks

### ISSUE THREAD

**Issue by sinfantino** [apollographql/apollo-client#10555] opened 2023-02-13 14:45 UTC
### Issue Description

When `useQuery `hook first resolves, the `data` variable has an initial payload of data.

When subsequent chunks of deferred data arrive, `useQuery `will re-render but the `data` variable will **only** include the deferred data. 

### Link to Reproduction

https://codesandbox.io/s/hardcore-resonance-5ytuuj?file=/src/index.jsx

**Comment by bignimbus** [comment] 2023-02-13 16:45
Hi @sinfantino 👋🏻  thanks for opening this issue!  I could be doing something incorrectly here, so I apologize in advance if I'm missing something obvious.  I'm having trouble making sense of the reproduction: in the console, `data` appears to be `undefined` throughout.  Here's what I see:

https://user-images.githubusercontent.com/3976692/218518460-74c94cad-dcdb-4ff9-b803-5ccf8a61d034.mov

I wanted to share since it seems a little different from what you wrote in the Issue Description.  Thanks, looking forward to hearing from you 🙏🏻

**Comment by sinfantino** [comment] 2023-02-14 07:30
Hi @bignimbus You right. The example I provided is not 100% in line with the issue description.
In the example, I cannot get deferred data at all. Maybe due a wrong setup of the schema... I am not sure. Sorry for that.

The issue in the description is what I am experiencing. In my code base, I use deferred fragments. When subsequent chunks of deferred data arrive, useQuery will re-render but the data variable will only include the deferred data.

According to the [documentation](https://www.apollographql.com/docs/react/data/defer/), I am expecting `usequery` to return all the data (initial + deferred) at some point.

Thanks for looking into it :)

**Comment by bignimbus** [comment] 2023-02-14 14:25
Ok thanks!  Can you help us narrow down what might be going on?  For starters hat server are you using and what is the content of the multipart response you're seeing?  Also if you could share a reproduction that reflects the issue you're seeing I'm sure we could expedite a recommendation

**Comment by alessbell** [comment] 2023-02-14 16:03
Hi @sinfantino 👋 Thanks for the additional info. Based the multipart response you've shared above, I can see the issue: Apollo Client has implemented `@defer` support based on the defer/stream spec proposal as of **August 24, 2022** and expects an `incremental` array of objects with `data` and `path` keys on [incremental result](https://github.com/apollographql/apollo-client/blob/issue-8694-useBackgroundQuery/src/link/core/types.ts#L39:L39) chunks (all chunks that arrive after the initial chunk, which alone has a `data` property).

In the second chunk of the data you've shared, the `data` and `path` keys are present at the top level and `incremental` is missing. Indeed, Hot Chocolate [v12.12.1](https://github.com/ChilliCream/graphql-platform/releases/tag/12.12.1) was released July 14, so it appears to have implemented an earlier version of the spec. I'm not sure which version of Hot Chocolate implements the August spec, but testing newer versions of Hot Chocolate should resolve this. I'm going to close this as resolved but do let us know if you run into any other issues with `@defer`. Thanks!

**Closed by alessbell** 2023-02-14 16:03 UTC
Labels: 🏓 awaiting-contributor-response, ⏩ @defer

**Comment by sinfantino** [comment] 2023-02-14 16:14
@alessbell I'll try to update Hot Chocolate. Thanks! :)
