### ISSUE TITLE
skip option fails when assigned a variable that flips from false to true

### ISSUE THREAD

**Issue by sirugh** [apollographql/apollo-client#6670] opened 2020-07-22 00:31 UTC
**Intended outcome:**

`skip: true` results in no network request.
The `error` property in the result of the useQuery hook reflects the current running query.

**Actual outcome:**
`skip: true` results in a network request.
The `error` property displays for the previous result.

**How to reproduce the issue:**
1) Go here: https://codesandbox.io/s/apolloclient-v3-skip-bug-ov1z3?file=/src/app.js
2) Click the button and observe the `400` from the graphql endpoint.
3) Click the button again and observe the successful response but the logged error message.

[![Image from Gyazo](https://i.gyazo.com/f83c69512570efe012c26b6e4533ee38.gif)](https://gyazo.com/f83c69512570efe012c26b6e4533ee38)

**Versions**
[![Image from Gyazo](https://i.gyazo.com/6f5d05500cc94450b355b77aef2927fe.png)](https://gyazo.com/6f5d05500cc94450b355b77aef2927fe)

**Related Issues**
https://github.com/apollographql/apollo-client/issues/6190
https://github.com/apollographql/apollo-client/issues/6572
https://github.com/apollographql/apollo-client/issues/6507

**Comment by sirugh** [comment] 2020-07-22 01:40
I traced all the way into the [fetchQueryByPolicy function](https://github.com/apollographql/apollo-client/blob/master/src/core/QueryManager.ts#L929) introduced in #6221. I believe it has something to do with the skip option not being passed to the `resultsFromLink` call:

https://github.com/apollographql/apollo-client/blob/2de0e23a8350ddf49634110f5e8e880092c2bb53/src/core/QueryManager.ts#L999-L1005

**Comment by sirugh** [comment] 2020-07-22 15:45
@benjamn I'd like to learn more about the inter-workings of ApolloClient, and would be happy to try and fix this but I'm not sure what I'm looking for. I know the options are identified as differing here:

https://github.com/apollographql/apollo-client/blob/7993a778ef5a9e61bfee72b956f4c179fce691f4/src/react/data/QueryData.ts#L241-L255

which calls to update the "current observable" on the query data class. I'm guessing that for some reason the thing that makes fetch/no-fetch decisions is not aware of this update.

**Comment by Ericnr** [comment] 2020-07-22 20:36
I'm having this same problem.

**Comment by vojto** [comment] 2020-07-23 09:43
Is this a duplicate of https://github.com/apollographql/react-apollo/issues/3492#issuecomment-644385154?

**Comment by sirugh** [comment] 2020-07-23 11:47
>Is this a duplicate of apollographql/react-apollo#3492 (comment)? Also related: #6342

Maybe? I wanted to create an issue with very simple/specific repro.

**Comment by vojto** [comment] 2020-07-23 12:10
Okay so `skip` has been working for a while. [This comment](https://github.com/apollographql/react-apollo/issues/3492#issuecomment-650248051) fixed it for me, until a new version is released:

> It actually broke in 3.0.0-beta.46. Last working release is **3.0.0-beta.45**!

**Comment by cdaz5** [comment] 2020-07-23 12:57
i'm surprised the major release (out of beta) was done with this still broken (since it was a known thing not a bug that popped after release).. it's a pretty widely used feature and I was a little shocked after I migrated to find the console error and this thread .. would of been nice if it was a known thing to make mention of it in the release/migration guide .. maybe its just me though?

**Comment by 3nvi** [comment] 2020-07-23 13:19
Funnily enough we migrated back to beta-43. It's more stable as of the moment of writing

**Comment by cdaz5** [comment] 2020-07-23 13:24
@3nvi is there any other things I should keep an eye on based on your comment sounds like there might be other unmentioned issues? .. we've been QA'ing the migration to 3.0.2 but a heads up if you know of anything specific would be great!

**Comment by 3nvi** [comment] 2020-07-23 13:27
> @3nvi is there any other things I should keep an eye on based on your comment sounds like there might be other unmentioned issues? .. we've been QA'ing the migration to 3.0.2 but a heads up if you know of anything specific would be great!

https://github.com/apollographql/apollo-client/issues/6603
https://github.com/apollographql/apollo-client/issues/6644
https://github.com/apollographql/apollo-client/issues/6636 (fixed in upcoming 3.1.0.)

**Comment by tafelito** [comment] 2020-07-26 02:24
related to #6572

**Comment by s-taylor** [comment] 2020-07-30 10:09
If anyone needs a work around, this is what I came up with.

```typescript
import { OperationVariables } from '@apollo/react-common';
import { DocumentNode } from 'graphql';

import { useEffect } from 'react';
import { useLazyQuery, LazyQueryHookOptions } from '@apollo/react-hooks';

const useSkippableQuery = <TData = any, TVariables = OperationVariables>(
  query: DocumentNode,
  options: LazyQueryHookOptions<TData, TVariables> & { skip: boolean }
) => {
  const { skip, ...rest } = options;

  const [lazyQuery, result] = useLazyQuery<TData, TVariables>(query, rest);

  useEffect(() => {
    if (!skip) lazyQuery();
  }, [skip]);

  /* On the first render cycle, lazy query always returns loading false because the useEffect has
   * not yet invoked the query. This ensures that the loading will be true on the first cycle
   * by checking the skip prop directly and checking the query has been called */
  const loading = result.loading || (!skip && !result.called);

  return { ...result, loading };
};

export default useSkippableQuery;
```

**Comment by sirugh** [comment] 2020-07-30 14:26
@s-taylor nice hook! I was going down the route of switching us to lazy query with effects/skip flags but I got hung up on the initial loading state. I'll give this hook a shot :) Thanks for the suggestion!

**Comment by tafelito** [comment] 2020-07-30 14:47
as a workaround, you might want to try this https://github.com/apollographql/apollo-client/issues/6572#issue-655006495

You don't need to use useEffect nor useLazyQuery and avoid having 2 render cycles

**Comment by sirugh** [comment] 2020-07-30 17:16
@tafelito does not work for us - query is still invoked when `skip` toggles from `false` to `true`.

**Comment by s-taylor** [comment] 2020-07-30 22:21
@sirugh nice thanks! I will update the snippet.

**Comment by hwillson** [comment] 2020-07-31 11:31
We're finalizing a fix for this and other `skip` related issues, and should have it ready today.

**Comment by hwillson** [comment] 2020-07-31 14:40
@sirugh would you be able to verify if `@apollo/client@3.1.2-pre.0` fixes your original issue?

**Comment by sirugh** [comment] 2020-07-31 14:59
@hwillson I'll give it a check after my morning meetings. Can you give me about two hours? If you publish pre's to npm you could also check the sandbox quickly, I believe.

**Closed** 2020-08-01 14:26 UTC
