### ISSUE TITLE
useQuery causes warning in strict mode

### ISSUE THREAD

**Issue by vdineva** [apollographql/apollo-client#7404] opened 2020-12-02 14:12 UTC
When I wrap my app in <React.StrictMode />, some of my components cause the following warning:

```
Warning:` Can't perform a React state update on an unmounted component. This is a
no-op, but it indicates a memory leak in your application. To fix, cancel all
subscriptions and asynchronous tasks in a useEffect cleanup function.
```
These warning disappear outside of Strict Mode and in production builds (which turn off the StrictMode behavior). The components in question don’t set state or use useEffect. They all use useQuery however.

The warnings disappear when I remove useQuery, i.e. by replacing this:

const { data: { preference = {} } = {} } = useQuery(PREFERENCE)
with an example response, like this:

```
const { data: { preference = {} } = {} } = {
  data: {
    preference: {
      id: 'dc1d27d7-c5fe-4de6-97c5-9db2bfaa7cd8',
      toc: false
    }
  }
}
```
and leaving the rest of the component unchanged.

I am using `"@apollo/client": "^3.3.2"`
This issue was originally reposted in react-apollo repo: https://github.com/apollographql/react-apollo/issues/3635

**Comment by jjalonso** [comment] 2020-12-18 02:52
+1 same here.

**Comment by graniczny** [comment] 2020-12-22 13:57
+1 and here

**Comment by BuntyBru** [comment] 2020-12-27 15:51
same here

**Comment by rushi444** [comment] 2021-01-11 21:12
+ 1

**Comment by Nightbr** [comment] 2021-01-21 16:40
Hey, I still have this issue with `3.3.7`. 

I though it was fixed here: https://github.com/apollographql/apollo-client/pull/6216

Any leads on this issue or a workaround? Thanks :+1:

**Comment by stevejay** [comment] 2021-01-21 16:49
@Nightbr #6216 had to be reverted because the fix broke SSR.

**Comment by MelodicsGreg** [comment] 2021-01-28 23:32
From what I can tell inspecting the cache state, useQuery watches are not being cleaned up when components unmount - it would make sense to me that resolving this would stop the broadcast of cache modifications throwing this error?

In my case, navigating back and forth between the same two pages using react router results in an ever growing list of watches for the same two queries.

This looks like a memory leak, though I haven't checked to see if there is some other mechanism for gc that happens based on some trigger other than components unmounting.

**Comment by shreyashc** [comment] 2021-02-01 06:18
+1

**Comment by f4z3k4s** [comment] 2021-02-05 09:31
+1

**Comment by jcreighton** [comment] 2021-02-09 18:22
The warnings should be silenced with the recent change in #7655. I do want to note though that this doesn't solve the actual issue: `useQuery` creates duplicate queries in React.StrictMode. A solution for this problem will take longer but in the meanwhile, you should see less warnings in the console.

**Closed by jcreighton** 2021-02-09 18:22 UTC
Labels: ⚛️ React-related

**Comment by macrael** [comment] 2021-06-27 03:59
@jcreighton is there an issue tracking fixing useQuery to be torn down correctly under StrictMode? I hit some unexpected behavior with refetchQueries that was different in dev and prod.

**Comment by dchenk** [comment] 2021-07-11 02:25
I'm still seeing this warning in strict mode at version 3.3.20

**Comment by brainkim** [comment] 2021-07-11 02:29
@dchenk Can you try the beta release (`npm i @apollo/client@beta`)? It might be fixed on there.

**Comment by bstro** [comment] 2021-07-21 22:05
The beta release cleared those warnings for me.

**Comment by DennieMello** [comment] 2021-07-27 21:20
Installing the beta really helped. When to wait for the release?

**Comment by brainkim** [comment] 2021-07-27 21:42
@DennieMello This week!

**Comment by yogesnsamy** [comment] 2021-08-06 09:46
> @DennieMello This week!

@brainkim I'm on version `3.3.20`. Should I be installing `@apollo/client@beta` to fix this issue?

**Comment by brainkim** [comment] 2021-08-06 12:32
@yogesnsamy Try 3.4.5!
