### ISSUE TITLE
Refetch returned cached data

### ISSUE THREAD

**Issue by dennislaupman** [apollographql/apollo-client#3243] opened 2018-03-30 19:09 UTC
Hi,

const getBookmarks = graphql(BookmarkedViewQuery, {
  options: ( props ) => {
    return { 
      fetchPolicy: 'network-only', // skip the cache
    } 
  } ,
});

After a mutation it seems like:
  componentWillReceiveProps(nextProps) {
    // console.log("refresh");
      this.props.data.refetch();
  }
will return cached data

**Comment by evans** [comment] 2018-04-06 01:09
Let's see if https://github.com/apollographql/react-apollo/pull/1901 fixes the issue when it is released. Could you create a small reproduction as well?

**Comment by vistriter** [comment] 2018-04-09 07:38
I have the same problem. Sometimes props.refetch return cached data to a child component.

**Comment by hwillson** [comment] 2018-08-05 00:44
This should no longer be an issue using a recent version of Apollo Client / React Apollo. Closing for now, but if anyone is still encountering this, please let us know (ideally with a small runnable reproduction). Thanks!

**Closed by hwillson** 2018-08-05 00:44 UTC

**Comment by aguzubiaga** [comment] 2018-08-30 18:38
@hwillson This still happens to me in the latest version. It's pretty particular because it doesn't happen always but in certain conditions. It seems to only happen when calling the `refetch` function passed to the component.

**Comment by aguzubiaga** [comment] 2018-08-30 18:49
It even happens when setting `fetchPolicy: no-cache`.

**Comment by aguzubiaga** [comment] 2018-08-30 19:41
Oddly enough, I wrapped the call in a timeout, and it worked properly:
```js
setTimeout(() => {
  this.props.refetch();
}, 0);
```
In my Network tab, this query is no longer being batched with the rest. I assume because it's deferred. I disabled batching by just using `apollo-link-http` (instead of `apollo-link-batch-http`), but it kept happening. So I don't think this is directly related to batching, but I'm not sure how Apollo works internally.

Hope that helps.

**Comment by justinmchase** [comment] 2019-08-24 15:48
I can see the call being made to the server but logging in the client shows the same data as the previous call. Too many layers to make a small repro yet but it does seem to be happening still.

**Comment by anmolchandra96** [comment] 2019-09-06 05:47
the refetch function called follows the fecthPolicy of its query function. If the fetchPolicy is set to cache-and-network refetch gets the data from the cache and returns it while simultaneously making a network call and subsequently sets the new data in the cache.

Is there a way for me to keep the fetchPolicy in the query as cache-and-network but make sure that refetch returns the data from the network call instead of from cahce

**Comment by Pajn** [comment] 2019-11-13 14:40
This is still an issue in fully updated versions, can we reopen this issue?

**Comment by Natteke** [comment] 2020-03-24 09:24
I think this is really important feature, usually you don't want to use "network-only" to prevent irrational network calls, but in 90% cases if user want to refetch a data, you want to show him a loader/spinner which will be hidden once refetch was complete, not instantly after it was shown.

**Comment by Nate-Wilkins** [comment] 2021-03-30 04:56
I dug into this a lot more and determined that this line of code was the culprit.
https://github.com/apollographql/apollo-client/blob/7a022e6d3463e37df8a9f1f85d1b0d0d83a9250a/src/core/QueryInfo.ts#L308
Its not really a bad assumption to make that if the result of the refetch is the same as the last query call result then don't update the cache. In my case this came up because I had a test that was mocking out an endpoint of resource types (ie a list of data types) and a patch call to update one of those data types. The problem arose when refetching but that refetch didn't provide the updated list of data types and instead had the same list with no changes - hence why the write was skipped and the cached data was returned. 

I really hope that helps someone else because this was a pain to track down.
