### ISSUE TITLE
Bug - use query is repeatly called when init component

### ISSUE THREAD

**Issue by unutoiul** [apollographql/apollo-client#6358] opened 2020-05-29 11:51 UTC
I've attached here the bug I am using 

```
 "@apollo/client": "^3.0.0-beta.50"
```
<img width="1680" alt="Screenshot 2020-05-29 at 14 49 18" src="https://user-images.githubusercontent.com/317535/83256821-d0aa4f00-a1bb-11ea-83c1-4ac68c7e57c0.png">
<img width="1680" alt="Screenshot 2020-05-29 at 14 50 49" src="https://user-images.githubusercontent.com/317535/83256827-d3a53f80-a1bb-11ea-8d77-4b786ea92cb8.png">

**Comment by bengal75** [comment] 2020-05-31 15:15
I am also running into this, using 3.0.0-beta.53. It happens immediately when using `useQuery`, but also happens once the query function has been called when using `useLazyQuery`. I've gone back to 3.0.0-beta.45 for now which doesn't seem to have the issue.

**Comment by unutoiul** [comment] 2020-05-31 15:53
I just notice the issue.. the load inside the component does the reloading all the time... very weird why I’m not sure what’s the reason

**Comment by c10h22** [comment] 2020-06-01 14:06
We have same same issue with v3.0.0-beta.43.

We are prefetching (for caching) some data with two independent queries during component init with `useQuery`. The problem disappear if we use only one query instead of two at the same time 
We are using `useLazyQuery` as well.

So to resume the situation here below the state logs:
```
component:adminSettings loading states +242ms {firstQuery: false, secondQuery: false}
component:adminSettings loading states +228ms {firstQuery: false, secondQuery: true}
component:adminSettings loading states +278ms {firstQuery: false, secondQuery: false}
component:adminSettings loading states +199ms {firstQuery: true, secondQuery: false}
component:adminSettings loading states +387ms {firstQuery: false, secondQuery: false}
component:adminSettings loading states +204ms {firstQuery: false, secondQuery: true}
component:adminSettings loading states +236ms {firstQuery: false, secondQuery: false}
component:adminSettings loading states +204ms {firstQuery: true, secondQuery: false}
component:adminSettings loading states +243ms {firstQuery: false, secondQuery: false}
```

**Comment by unutoiul** [comment] 2020-06-01 15:28
the issue is when you setup 

```
defaultOptions: {
        watchQuery: {
            fetchPolicy: 'network-only',
        },
    },
```

the version . "@apollo/client": "^3.0.0-beta.50" doesn't trigger onCompleted function anymore..

ANY Idea was is BROKEN?

is breaking all my project can Apollo CLIENT TEAM FIX THOSE ISSUES ?

**Comment by riccoski** [comment] 2020-06-04 14:05
I also get this with "network-only" and "no-cache" fetch policy and onCompleted not being called.
Works as expected with the default "cache-first" fetch policy.

version:
```
 "@apollo/client": "^3.0.0-rc.0"
```

**Comment by SmallHollow** [comment] 2020-06-06 07:09
I've had similar problems as described by others above, with 'no-cache' fetchPolicy and onCompleted not triggering. In my case I'm using useLazyQuery. This behaviour occurs on all releases since beta.46. The latest I've tried is rc.1. Like @bengal75  mentions, going back to beta.45 fixes this problem.

**Comment by bengal75** [comment] 2020-06-27 23:37
After some scouring of open issues, I believe what I was experiencing here is a duplicate of #6301 - the suggested fix there of memoizing the onComplete and onError callbacks has stopped my query requests from looping. The reproduction there is also accurate for my use case so I suggest this issue can be closed in favour of that one.

**Comment by hwillson** [comment] 2021-05-03 14:22
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!

**Closed by hwillson** 2021-05-03 14:22 UTC

**Comment by kfazinic** [comment] 2021-05-03 19:06
> 
> 
> This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!

@hwillson For me it occurs with 3.3.11.
