### ISSUE TITLE
Why doesnt apollo update cache after refetch ?

### ISSUE THREAD

**Issue by dukesx** [apollographql/apollo-client#6804] opened 2020-08-08 10:40 UTC
I am querying for articles from graphql with a particular field which should be either true or false depending on user input for example , filtering news feed with latest posts or featured posts. Now when i call refetch with variables having new value (old value: featured is false and new value has featured is true), the query does return new array of articles (as seen on console.log in onCompleted function) but Apollo fails to update the "data" object in result (in short, cache doesn't get updated)

What could be the issue ? i have tried on setting fetch policy to both network only and "network and cache" but "data" object doesn't get updated with new articles (type and fields remain same, because we are fetching the same type of object array, "articles"  but values on fields differ such as this time featured would be true ).

I am using
- ApolloClient 3.0 
- React 16.13
- Nextjs 9.5

**Comment by stLoiz** [comment] 2020-10-22 12:41
Is there any update on this? Having same issue. I have tried changing the policy to this: 
` fetchPolicy: 'cache-and-network',
    nextFetchPolicy: 'cache-first',` but still the server sends the right results, but UI after refetch is not changed, it shows the results that are cached.

**Comment by davazp** [comment] 2020-10-22 12:46
Could be related to the issue I reported recently  #7195 ?

**Comment by stLoiz** [comment] 2020-10-22 13:10
Yes it is the same, however I am not using mutation in my query, I am using `useQuery` and every time a `prop` is changed refetch is executed. When the result from the server is empty list, the cache are not updated. I do not know if there is any relation with Apollo not recognised a change in the cache when edges == null

**Comment by nhanpdnguyen** [comment] 2020-10-22 13:47
I guess it might be due to the way Apollo work with cache. Cache items are identified by 'id' are only updated by merging with existing items or being added as new items. I think you might want to define a custom merge function where you completely replace existing cache items with new incoming items. Or you could try to use `fetchPolicy: 'no-cache'`
https://www.apollographql.com/docs/react/caching/cache-configuration/#data-normalization
https://www.apollographql.com/docs/react/caching/cache-field-behavior/#the-merge-function

**Comment by stLoiz** [comment] 2020-10-22 17:57
`fetchPolicy: 'no-cache` will not work the `fetchMore` later on. I have tried `merge()` and is working, how can I add the relayStylePagination, to see if that is all working together. Previously I had this 
```
const client = new ApolloClient({
  uri: 'http://localhost:5000/graphql',
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          devices: relayStylePagination(),
        },
      },
    },
  }),
});
```
And the pagination was working well with FetchMore. Now that I have this: 

```
const client = new ApolloClient({
  uri: 'http://localhost:5000/graphql',
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          devices: {
            merge(existing = {}, incoming) {
              return { ...existing, ...incoming };
            },
          },
        },
      },
    },
  }),
});

```

Where do I apply the `relayStylePagination` ? I have tried multiple ways but I getting errors on how I place it inside `devices`

**Comment by stLoiz** [comment] 2020-10-22 18:05
If I add it like this: ``` const client = new ApolloClient({
  uri: 'http://localhost:5000/graphql',
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          devices: relayStylePagination(),
          merge(existing = {}, incoming) {
            return { ...existing, ...incoming };
          },
        },
      },
    },
  }),
});``` The pagination is not working and I still get the cached results from Apollo instead of the empty list.

**Comment by nhanpdnguyen** [comment] 2020-10-23 03:01
@stLoiz, if you're using Typescript, you will see the type definitions of `fields`, so you could know what and where to place your `relayStylePagination()` (which is a FieldReadFunction)
```js
// this is the type definition of `fields`, it accept either a FieldPolicy or a FieldReadFunction
fields?: {
        [fieldName: string]: FieldPolicy<any> | FieldReadFunction<any>;
    };

// this is type definition of a FieldPolicy
export declare type FieldPolicy<TExisting = any, TIncoming = TExisting, TReadResult = TExisting> = {
    keyArgs?: KeySpecifier | KeyArgsFunction | false;
    read?: FieldReadFunction<TExisting, TReadResult>;
    merge?: FieldMergeFunction<TExisting, TIncoming> | boolean;
};
```
To make it work:
```js
const client = new ApolloClient({
  uri: 'http://localhost:5000/graphql',
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          devices: {
            read: relayStylePagination(), // <- this should return a function
            merge: (existing = {}, incoming) { // <- `devices` I guess should be an array, so using {} and merging like this might be not correct
              return { ...existing, ...incoming };
            },
          },
        },
      },
    },
  }),
});
```

**Comment by stLoiz** [comment] 2020-10-23 08:13
@nhanpdnguyen Thank you for your response. 

I am not using typescript, however I can see from vs code the field policy: 
```(property) devices: FieldPolicy<Readonly<{
    edges: TEdge<Reference>[];
    pageInfo: TPageInfo;
}>, TIncomingRelay<Reference>, TIncomingRelay<Reference>>```

It is returning an {} as I am using edges and node to have relayPagination working. 

Now I have tried using Keyfields and is working, if the server returns empty list the cached results are updated and UI shows the  the empty list. However again the relayPagination is not working. The only way to have it work is to have it like: 

```const client = new ApolloClient({
  uri: 'http://localhost:5000/graphql',
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          devices: relayStylePagination(),
        },
      },
    },
  }),
});
```
If I have something like 
```fields: {
          devices: {
            read: relayStylePagination(),
            keyFields: [],
          }
        },
```
the pagination will not work.

**Comment by andycarrell** [comment] 2020-10-28 21:31
I have just run into the same issue - I got the following to work:

```js
const useQueryWithNetworkRefetch = (queryDefinition, options = {}) => {
	const queryResult = useQuery(queryDefinition, options);

	const { refetch: refetchFromNetwork } = useQuery(queryDefinition, {
		...options,
		// Ensure we get the latest data from the network
		fetchPolicy: "network-only",
		// Skip the default fetch, query only runs on refetch
		skip: true,
	});

	return {
		...queryResult,
		refetch: refetchFromNetwork,
	};
};
```

(Please note I am using an older version of the client, this should work on the latest version?)

**Comment by stLoiz** [comment] 2020-11-05 13:38
It did not work for me. Also I do not use refetch anymore on this, as on every update of the props the useQuery runs again so there was no need to call refetch. The main issue still exists,  if the returning list from the server is empty, then the cache are not refreshing and the user can only see the previous results and not an empty list.

**Comment by hwillson** [comment] 2021-05-05 15:01
The changes coming in https://github.com/apollographql/apollo-client/pull/8000 might be interesting here.

**Comment by ComputerCarl** [comment] 2022-02-01 16:29
I ran into this issue that `data` would not update if the query result was already in cache.

I found a solution in the Apollo [Queries documentation](https://www.apollographql.com/docs/react/data/queries/).

Simply include `notifyOnNetworkStatusChange: true` in the options: 


> Enabling this option also ensures that the value of `loading` updates accordingly, even if you don't want to use the more fine-grained information provided by the `networkStatus` property.

**Comment by altechzilla** [comment] 2022-04-06 20:46
Any updates here? Looks like a post-query `refetch` still doesn't update the original useQuery local cache.

**Comment by msalahz** [comment] 2022-04-19 18:37
Any updates here?

**Comment by dukesx** [comment] 2022-04-25 10:52
> Any updates here?
> 

Don't waste your time on Apollo. Their focus is different now. They have their federation to evolve. Everyone else moved on to URQL and so should you. Its easy, maintained since years and years, and extremely well documented. Oh and the refetch function actually works :)

P.S Most Api of urql is adopted from Apollo Client so it's easy to migrate.

**Comment by satvikpendem** [comment] 2022-09-23 19:15
> Oh and the refetch function actually works :)

Can confirm, I had an Apollo Client app that, whatever I tried, I could not get refetching to work properly. Based on @dukesx's recommendation, I moved to urql and refetching works exactly as expected.

**Comment by bignimbus** [comment] 2022-11-05 03:34
Thanks all for the discussion around this issue!  It sounds like @davazp's issue https://github.com/apollographql/apollo-client/issues/7195 is indeed the same as this, so I'll close this issue and ask that we merge this discussion into that issue since there's a reproduction scenario there 🙏🏻

**Closed by bignimbus** 2022-11-05 03:34 UTC
