### ISSUE TITLE
Reactive variables prevent cache from being garbage collected

### ISSUE THREAD

**Issue by kkgrigas** [apollographql/apollo-client#7622] opened 2021-01-27 17:15 UTC
**Intended outcome:**
`InMemoryCache` is garbage collected from memory after client stops.

This is similar to #7274, but I believe this is a separate issue. Similarly to the linked issue, `InMemoryCache` never gets evicted after apollo client has finished running during SSR. The client is stopped with `apolloClient.stop()` at the end. The new code introduced as a fix in #7279 is executed, but it doesn't fix the issue.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/60093124/106026866-fed98900-60d2-11eb-96fd-4df8477ca622.png">

**Actual outcome:**
`InMemoryCache` should be evicted from memory after running.

**How to reproduce the issue:**
I've made a minimal repo in https://github.com/kkgrigas/apollo-client-sample
Run it, and then make many requests to started server (i.e. using `siege`)

**Versions**

  System:
    OS: macOS 11.1
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/projects/web/node_modules/.bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Edge: 88.0.705.53
    Firefox: 85.0
    Safari: 14.0.2
  npmPackages:
    @apollo/client: 3.3.7 => 3.3.7 
    apollo: 2.31.1 => 2.31.1 
    apollo-link-logger: 2.0.0 => 2.0.0 
    apollo-link-persisted-queries: 0.2.2 => 0.2.2 
    apollo-upload-client: 14.1.3 => 14.1.3

**Comment by benjamn** [comment] 2021-02-05 00:20
@kkgrigas Do these `InMemoryCache` objects still have anything in their `cache.watches` sets? I ask because #7279 will only help if all watches are cancelled before the cache is discarded.

**Comment by kkgrigas** [comment] 2021-02-05 14:48
It doesn't look like it is relevant. I tried SSR'ing different pages which contain different queries, most of them had `watches` empty or emptied after rendering, one of them didn't.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/60093124/107048709-ea337a00-67d1-11eb-96eb-aa6455fd27ed.png">

Let me know if I can help somehow else.

**Comment by benjamn** [comment] 2021-02-09 16:56
@kkgrigas This should be fixed in `@apollo/client@3.3.9` (published earlier today), and we now have [a regression test](https://github.com/apollographql/apollo-client/tree/main/scripts/memory) that should prevent this kind of leak from happening in the future.

**Closed by benjamn** 2021-02-09 16:56 UTC
Labels: :racehorse: performance, :rose: has-reproduction, 💸 caching
