### ISSUE TITLE
Typescript build error Generic type 'ExecutionResult<TData>' requires between 0 and 1 type arguments with graphql@14

### ISSUE THREAD

**Issue by leereamsnyder** [apollographql/apollo-client#9166] opened 2021-12-09 02:10 UTC
**Intended outcome:**

After updating to the latest @apollo/client packages and following the migration guide, my Typescript build process should still work.

**Actual outcome:**

`tsc` fails with a Typescript error. 

Doing `tsc --check-types` gives the following error:

```
../../node_modules/@apollo/client/link/core/types.d.ts:19:134 - error TS2707: Generic type 'ExecutionResult<TData>' requires between 0 and 1 type arguments.

19 export interface FetchResult<TData = Record<string, any>, TContext = Record<string, any>, TExtensions = Record<string, any>> extends ExecutionResult<TData, TExtensions> {
```

Going into that types declaration file, I see this error:

<img width="951" alt="Screen Shot 2021-12-08 at 9 03 55 PM" src="https://user-images.githubusercontent.com/870668/145321297-1f926da9-1033-411d-b792-ca3009bdcbfb.png">

**How to reproduce the issue:**

**Versions**

```

  System:
    OS: macOS 11.6.1
  Binaries:
    Node: 12.22.7 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 95.0
    Safari: 15.1

```

The relevant package versions are 

- typescript@4.1.3
- @apollo/client@3.5.6 (also present with 3.5.5)
- graphql@14.7.0

**Comment by msventeriki** [comment] 2021-12-30 15:49
Hey, i am actually dealing with the same issue currently as I am ugrading versions. Did you manage to solve it? Happy new year!

**Comment by hwillson** [comment] 2022-01-04 01:38
Duplicate of https://github.com/apollographql/apollo-client/issues/9167.

**Closed by hwillson** 2022-01-04 01:38 UTC
