### ISSUE TITLE
Response array with null values is discarded

### ISSUE THREAD

**Issue by koenpunt** [apollographql/apollo-client#1277] opened 2017-02-09 14:24 UTC
We're using Apollo client with React, and for a certain query the graphql response contains `null` values in an array.

**Part of our schema:**

```graphql
union BodyElement = HtmlElement

type HtmlElement {
  name: String
  value: String
}

type Article implements Node {
  body: [BodyElement]
}
```

**Graphql response:**:

```json
"body": [
  {
    "__typename": "HtmlElement",
    "name": "p",
    "value": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  },
  null,
  {
    "__typename": "HtmlElement",
    "name": "p",
    "value": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  },
  {
    "__typename": "HtmlElement",
    "name": "h2",
    "value": "Lorem Ipsum"
  },
  null,
  {
    "__typename": "HtmlElement",
    "name": "p",
    "value": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  },
  {
    "__typename": "HtmlElement",
    "name": "p",
    "value": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  }
]
```

Where I expect the values being passed on as-is, so just `null` values, the response is discarded completely, without error.

Is this expected behaviour?

**Comment by calebmer** [comment] 2017-02-09 21:29
Is the entire response being discarded, or just those null items?

**Comment by koenpunt** [comment] 2017-02-09 21:31
I can see the response in the Redux devtools, but it is not passed to the graphql container.

**Comment by helfer** [comment] 2017-02-11 23:12
@koenpunt Could you make a PR with a failing test? I think that should be relatively straightforward and it would help us fix this quickly 🙂

**Comment by helfer** [comment] 2017-02-27 20:03
@koenpunt I'll close this issue here because you should file it on react-apollo. When you file it there, please make sure you include a reproduction with https://github.com/apollographql/react-apollo-error-template

**Closed by helfer** 2017-02-27 20:03 UTC
Labels: bug, needs-repro

**Comment by koenpunt** [comment] 2017-02-28 08:37
@helfer was thinking the same. But we worked around the issue by updating the data on the server, and have not had the time (and somewhat forgot 🙄), to create a reproduction case. 
However the error template is nice, and that'll probably get me going a bit quicker.
