### ISSUE TITLE
frequent cache writes don't propagate to some observers

### ISSUE THREAD

**Issue by lsnch** [apollographql/apollo-client#5552] opened 2019-11-06 09:07 UTC
reproduction:
https://codesandbox.io/s/apollo-client-frequent-cache-writes-lybjy
(if empty wait 20 sec for backend to spin up)

The button calls `writeFragment` twice in separate tasks. Cache looks good always. The issue is some observers don't get notified if updates come in too fast.

This happens in my app where you get a couple of WS messages with minimal interval. Some components get called twice and therefore have up-to-date cache data, while others get called only once, and their data is stale. This happens with any write method (I tried `writeQuery`, `writeData`, `writeFragment`). Also tried `@apollo/client` beta, same result.

If there's more `<Box />`es, all but the last two update as expected.

**Comment by alex3d** [comment] 2019-11-06 16:25
It seems that the root cause is in `QueryData.afterExecute` scheduled from `useEffect` in `useBaseQuery`.
Cache update notification is lost when cache update occurs between `useBaseQuery` call and `afterExecute` call.

Relevant source references:
[useBaseQuery](https://github.com/apollographql/react-apollo/blob/0901f4ac2b1800dab423b63bd9e041c863a2425f/packages/hooks/src/utils/useBaseQuery.ts#L54) -> useEffect(afterExecute)

[QueryData.afterExecute](https://github.com/apollographql/react-apollo/blob/551e7545ab6ca99b5b6acf1d00d6b236e299e1df/packages/hooks/src/data/QueryData.ts#L93) -> [handleErrorOrCompleted](https://github.com/apollographql/react-apollo/blob/551e7545ab6ca99b5b6acf1d00d6b236e299e1df/packages/hooks/src/data/QueryData.ts#L410) (Observable.getCurrentResult() updates Observable.lastResultSnapshot and prevents subsequent update notification in [ObservableQuery.next](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/ObservableQuery.ts#L632) )

I'm not sure if `afterExecute` permitted to be called directly from `useBaseQuery` (without `useEffect`), but this would solve the issue.
Also, as a workaround for 90% of use cases `onCompleted`&`onError` callbacks presence could be checked in `handleErrorOrCompleted` before `getCurrentResult` call.

**Comment by benjamn** [comment] 2019-11-11 20:53
Can I confirm your expectation that `Node:10` should end up with `{ v: 300 }` in both/all cases, because the second `setTimeout` wins? In other words, the key symptom of the problem is seeing `400` in one component and `300` in another?

If so, then, as luck would have it, this PR I opened this morning seems to solve this problem: https://github.com/apollographql/apollo-client/pull/5565

My hunch is that [this commit](https://github.com/apollographql/apollo-client/pull/5565/commits/7473ee37a20a2814227b39130bab1113c736aa5f) is responsible for the difference, though reverting just that commit does not reintroduce the problem, so perhaps the other commits are helping as well.

**Comment by alex3d** [comment] 2019-11-12 14:45
You are right.

**Comment by benjamn** [comment] 2019-11-12 16:35
@alex3d Ok, great, then please give `@apollo/client@3.0.0-beta.8` a try when you have a chance!

**Closed** 2019-11-12 16:39 UTC

**Comment by lsnch** [comment] 2019-11-14 10:56
Thanks, the new `@beta` seems to be working in sandbox, but I can't make it work in my app.

Hit a couple of roadblocks upgrading.. 
- Request redirection. We currently use `cacheRedirects`, but it seems to be missing in beta.
- Fragments. Some types of queries fail (maybe field names collide? I don't know).

Would you be able to expand migration guide on those areas so I can test it in a real app?
