### ISSUE TITLE
Nesting fragment spreads on union drops fields

### ISSUE THREAD

**Issue by chrbala** [apollographql/apollo-client#8177] opened 2021-05-09 05:34 UTC
**Intended outcome:**
With a schema like:
```graphql
  type BranchA {
    a: String!
  }
  type BranchB {
    b: String!
  }
  union UnionExample = BranchA | BranchB
  type Query {
    values: [UnionExample!]!
  }
```

Making a query like this in react-apollo:
```graphql
query PageQuery {
  values {
    ... on UnionExample {
      ... on BranchA {
        a
      }
      ... on BranchB {
        b
      }
    }
  }
}
```

Should return a value like this:

```json
{"values": [
    {
      "__typename": "BranchB",
      "b": "Hello World"
    },
    {
      "__typename": "BranchB",
      "b": "Hello World"
    }
  ]
}
```

**Actual outcome:**
Drops all the fields except the typename in the data returned from useQuery. Notably, the data does pass through the network tab (when using network as transport), so it appears to be an issue with data processing after it has arrived.

This may seem like an uncommon use case (it probably is), but this situation can come up when using external fragments in more complex schemas.

e.g.
```json
{"values": [
    {
      "__typename": "BranchB"
    },
    {
      "__typename": "BranchB"
    }
  ]
}
```

**How to reproduce the issue:**
https://github.com/chrbala/apollo-bug-repro

The repo was not created with the example template, but was created with a similar design. There's a bit of cruft hanging around in there from CRA, but it is still pretty slim.

Most relevant part: https://github.com/chrbala/apollo-bug-repro/blob/repro/src/App.tsx

**Versions**
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    @apollo/client: ^3.3.16 => 3.3.16

**Comment by benjamn** [comment] 2021-05-13 17:20
@chrbala Thanks for the reproduction (makes my job so much easier)!

In this case, I believe you need to configure `possibleTypes` via the `InMemoryCache` constructor, so the cache knows about the subtyping relationship between `UnionExample` and `BranchA` and `BranchB`:
```diff
diff --git a/src/index.tsx b/src/index.tsx
index e8b09a6..ffd1061 100644
--- a/src/index.tsx
+++ b/src/index.tsx
@@ -8,7 +8,11 @@ import { SchemaLink } from '@apollo/client/link/schema';
 import { schema } from './schema';
 
 const client = new ApolloClient({
-	cache: new InMemoryCache(),
+	cache: new InMemoryCache({
+		possibleTypes: {
+			UnionExample: ["BranchA", "BranchB"],
+		}
+	}),
 	link: new SchemaLink({ schema }),
 });
```
More explanation [here](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) (including recommendations about how to generate this `possibleTypes` information programmatically from your schema).

**Comment by chrbala** [comment] 2021-05-15 00:53
It seems like the library could communicate this need to developers in dev mode. For example, if something gets dropped from the query response, suggest that this configuration be added.

**Comment by Jammar** [comment] 2021-05-27 12:31
Thanks for this issue, I was going crazy having the same problem. [benjamn's workaround with `possibleTypes` ](https://github.com/apollographql/apollo-client/issues/8177#issuecomment-840707458) didn't do it for me. I'm stuck with a no-cache fetchPolicy for the specific query.

**Comment by dylanwulf** [comment] 2021-06-14 22:35
I ran into something similar except in my case i'm using a fragment on an interface instead of a union. I created a new issue (with reproduction) since I'm not sure if it's the same problem or not: #8389

**Comment by bignimbus** [comment] 2023-02-10 03:06
Hi folks, it's been a while since we've had activity on this issue and the linked PR has been closed.  Given the above I'm going to close this issue but please do feel free to ping the maintainers or open a new issue if you're still in need of support.  @Jammar I know it's been quite a while since your comment but I wanted to mention you in case you were still blocked 🙏🏻

**Closed by bignimbus** 2023-02-10 03:06 UTC
Labels: :rose: has-reproduction, ✍️ working-as-designed, 🌤 has-workaround, 💸 caching
