### ISSUE TITLE
Apollo Client throwing a `TypeError: options.headers.hasOwnProperty is not a function`  

### ISSUE THREAD

**Issue by raopg** [apollographql/apollo-client#11555] opened 2024-02-01 17:46 UTC
### Issue Description

This is the stack trace caught by Sentry. We are observing this for a few users while using the Safari 17.2.1.

```
TypeError: options.headers.hasOwnProperty is not a function. (In 'options.headers.hasOwnProperty(key)', 'options.headers.hasOwnProperty' is undefined)
  at ? (webkit-masked-url://hidden/:418:63)
  at <anonymous>(../../../node_modules/.aspect_rules_js/@apollo+client@3.8.8_1356184083/node_modules/@apollo/client/link/http/createHttpLink.js:127:13)
  at Subscription(../../../node_modules/.aspect_rules_js/zen-observable-ts@1.2.5/node_modules/zen-observable-ts/module.js:190:34)
  at _proto3.subscribe(../../../node_modules/.aspect_rules_js/zen-observable-ts@1.2.5/node_modules/zen-observable-ts/module.js:264:16)
  at <anonymous>(../../../node_modules/.aspect_rules_js/@apollo+client@3.8.8_1356184083/node_modules/@apollo/client/link/error/index.js:11:42)
```

### Link to Reproduction

I've included the stack trace above. We are unable to reproduce this ourselves, but we have Sentry capturing the stack trace with sourcemaps.

### `@apollo/client` version

3.8.8

**Comment by jerelmiller** [comment] 2024-02-01 17:56
Hey @raopg 👋 

That is very odd. For one, that line number makes no sense given the code. Here is the code for 3.8.8 in `createHttpLink`: https://github.com/apollographql/apollo-client/blob/89ec18eb97487594c2bc1e15bdef259ac46c2f06/src/link/http/createHttpLink.ts#L127

You'll see that its just an empty line. The closest thing I could maybe see is this one: https://github.com/apollographql/apollo-client/blob/e1794c4c1e7b9f90bdf855f1cce75031d2d7fcec/src/errors/index.ts#L45

I do see this file in that stack trace, but again, this line number doesn't line up with that stack trace above. That and this change has been here for what looks like [7 years](https://github.com/apollographql/apollo-client/blame/e1794c4c1e7b9f90bdf855f1cce75031d2d7fcec/src/errors/index.ts#L45), so I would have assumed we'd see something by now if this was the reason. All of our other usages of `hasOwnProperty` are pulled from [`Object.prototype` directly](https://github.com/search?q=repo%3Aapollographql%2Fapollo-client%20hasOwnProperty&type=code). 

Is there any more information you're able to give us? Is this specific to 3.8.8 and does downgrading to a specific version help in any way?

**Comment by raopg** [comment] 2024-02-01 18:03
Hi @jerelmiller,
I think the minification might have changed the line numbers, but here is the code captured by Sentry

```
            // #7832), or (if all else fails) the backupFetch function we saved when
            // this module was first evaluated. This last option protects against the
            // removal of window.fetch, which is unlikely but not impossible.
            var currentFetch = preferredFetch || maybe(function () { return fetch; }) || backupFetch;
            var observerNext = observer.next.bind(observer);
            currentFetch(chosenURI, options)
                .then(function (response) {
                var _a;
                operation.setContext({ response: response });
                var ctype = (_a = response.headers) === null || _a === void 0 ? void 0 : _a.get("content-type");
                if (ctype !== null && /^multipart\/mixed/i.test(ctype)) {
```

![Screenshot 2024-02-01 at 1 00 17 PM](https://github.com/apollographql/apollo-client/assets/21350405/015cda14-ebad-4c22-9536-c3484c6b94a0)

Here is a screenshot, so you can see the line numbers. It is a very odd case, since our engineering team is unable to reproduce it in a dev or prod environment. 2 of our customers are seeing this only on Safari (with all browser extensions disabled).

**Comment by raopg** [comment] 2024-02-01 18:05
We have been seeing this since Apollo 3.7.3, and upgrading/downgrading versions of Apollo has not helped

**Comment by jerelmiller** [comment] 2024-02-01 18:07
Awesome. Appreciate that context! Let me go and see what might have changed in that version to try and get a clue. Gotta love those cross browser quirks sometimes (if thats what it is 😆)

**Comment by jerelmiller** [comment] 2024-02-01 18:35
Interestingly I don't see anything changed having to do with `headers` in between [3.7.2 and 3.7.3](https://github.com/apollographql/apollo-client/compare/v3.7.2...v3.7.3). Here's a different view of it that shows the [diff between the compiled versions](https://diff.intrinsic.com/@apollo/client/3.7.2/3.7.3). Looking for changes to `headers` doesn't yield any changes to anything with `hasOwnProperty`, so I'm a bit at a loss.

Unfortunately I've got a few other priorities I've got to look at today, so I'll need to revisit later. If you have a revelation or spot it before I do, let me know and we'd be happy to address! PRs welcome as well 🙂

**Comment by jerelmiller** [comment] 2024-02-01 19:20
Adding a note here, this might be possibly related: https://github.com/apollographql/apollo-client/issues/10403

**Comment by jerelmiller** [comment] 2024-02-01 19:25
@raopg what does your link chain look like? Would you be able to provide what your `ApolloClient` initialization looks like (omitting any sensitive info if present)? #10403 looks very similar and I'm wondering if there is something buried inside the link chain as discussed in that issue.

**Comment by jerelmiller** [comment] 2024-02-01 19:51
@raopg see [this comment](`null` or `undefined`) in #10403 to see if this applies in your situation at all.

**Comment by raopg** [comment] 2024-02-02 11:31
```
    const errorHandler = onError(({ networkError, operation }) => {
      if (
        networkError &&
        (!("statusCode" in networkError) || networkError.statusCode >= 500)
      ) {
        Sentry.captureException(networkError, {
          extra: { graphQLOperation: operation.operationName },
        });
      }
      if (
        networkError &&
        "statusCode" in networkError &&
        networkError.statusCode == 403
      ) {
        navigate("/login");
      }
    });

    const requestContextMiddleware = new ApolloLink((operation, forward) => {
      operation.setContext(({ headers = {} }) => ({
        headers: {
          ...headers,
          "Request-ID": uuidv4(),
          ...(appContext.url_name
            ? { "Account-Uri": appContext.url_name }
            : {}),
        },
      }));

      return forward(operation);
    });
    
        return new ApolloClient({
      link: errorHandler.concat(requestContextMiddleware).concat(uri),
      cache,
    });
```

This is our link setup

**Comment by raopg** [comment] 2024-02-02 11:35
From what I gather in that comment, it doesnt seem like its the same issue. I will also investigate to see if there is anything I can spot

**Comment by jerelmiller** [comment] 2024-02-05 22:20
Bummer, worth a shot. Do let me know if you come up with anything!

The only other thing I can think of is perhaps to check the bundled output of the client and see if you spot anything in there with `options.headers.hasOwnProperty`? Perhaps the bundler is compiling the output of some expression into a `hasOwnProperty` call?

This is the only thing I can think of at this point 😕

**Comment by radu-nicoara-bayer** [comment] 2024-07-03 13:19
We are getting this from the preflight call, but I was unable to reproduce it in a code sandbox.
If we add "Access-Control-Max-Age": 600 on the server side, it works for 10 minutes, until the next preflight

**Comment by radu-nicoara-bayer** [comment] 2024-07-03 13:53
You can test the issue here:
https://codesandbox.io/s/funny-yonath-x5fgzz?file=/src/index.js
The UI: https://x5fgzz.csb.app
<img width="1552" alt="image" src="https://github.com/apollographql/apollo-client/assets/98585495/ec131de2-5297-402b-bf0e-6bf9655f2409">

**Comment by jerelmiller** [comment] 2024-07-03 16:11
Hey @radu-nicoara-bayer 👋 

Thanks for providing that reproduction! Unfortunately I'm still not able to reproduce the issue, even in Safari. Our best lead right now is that this might come from some kind of Safari extension. What Safari version are you using and what extensions do you have installed? I'd like to install them myself to understand if one of them might be at play here.

We had an internal report of something very similar as well. We noticed the stack trace of the error included something like the following:

```
(webkit-masked-url://hidden/:418:63)
```

From what we can find, this looks like something Safari does with extensions: https://bugs.webkit.org/show_bug.cgi?id=246010. Part of the stack trace also seems to point at the `currentFetch` call itself: https://github.com/apollographql/apollo-client/blob/1a9c68a4e6bc033498ce620681ae4a3720820ba4/src/link/http/createHttpLink.ts#L188

My guess is that an extension is trying to replace `window.fetch` with some wrapped version to be able to analyze the calls, but its got a bug that doesn't handle headers properly. Any more information you can provide would be super helpful!

**Comment by radu-nicoara-bayer** [comment] 2024-07-04 10:51
My safari version is Version 17.5 (19618.2.12.11.6), and it is running on a Mac M1 (Maybe that matters as well). As for extensions, I have nothing installed.
The user that reported this also has the default Safari on a Mac Book M1.

**Comment by phryneas** [comment] 2024-07-04 13:03
> My safari version is Version 17.5 (19618.2.12.11.6), and it is running on a Mac M1

That matches with the setup I have here - unfortunately I don't see the error in the CodeSandbox :/

> As for extensions, I have nothing installed.

Are you sure there's not maybe some plugin or extension installed by something like 1Password? 
I have to admit, apart from the "extensions" route, right now we're pretty much out of ideas - and the StackTrace is pointing to some "internals" that are hidden from page JS, so an extension would be the most obvious idea.

**Comment by radu-nicoara-bayer** [comment] 2024-07-05 08:15
You are correct. There is a security extension installed.
![image](https://github.com/apollographql/apollo-client/assets/98585495/a0179487-1ad9-4cea-bc5b-3f6a21c25aa5)
I opened an incognito, and the error is no longer there.

**Comment by phryneas** [comment] 2024-07-05 10:02
What annoyingly hidden bug - I'm glad we could find that!

I guess at this point, we can close the issue here and you make a bug report with the vendor of that extension? (If it ends up in a public bug tracker, I'd would be very thankful if you could link that here!)

**Comment by dotku** [comment] 2024-08-25 21:14
It seems all iOS has the issue :( social.dotku.us

**Comment by phryneas** [comment] 2024-08-26 07:50
@dotku Could you please provide your iOS version, browser version and a list of all installed browser extensions or other installed "privacy"-type apps?

**Comment by spnc-omz** [comment] 2024-09-03 16:37
I ran into this issue myself where the Forcepoint Safari Extension / Websense Endpoint Helper extension was forced on to my computer by corporate leaving me with no options but to dive in and see what is going on. 

Inside of the SafariExtension, they hijack the `window.fetch` and `XMLHttpRequest` and add what they need on top of them to monitor all requests. In this they have a block of code that checks options.headers and does some sort of reassignment for their monitoring use cases. In this, they expect the headers object to be a full object prototype with hasOwnProperty function but for some reason, only in Safari, only when doing a spread of the headers, this function doesn't exist. 

The right fix is for the plugin to do a, `Object.prototype.hasOwnProperty.cal(object, key)` because that uses the Object.prototype instead of hoping the thing being passed in has the prototype functions it wants. Eslint has been encouraging this behavior for ages now. https://eslint.org/docs/latest/rules/no-prototype-builtins . Sadly we can't change the vendor's code so I needed to find a workaround. 

What I ended up doing to get things to work, and mind you I'm not using this apollo client directly, I'm using `@nuxtjs/apollo` to handle a lot of the heavy lifting, but the parameters existed for me to get to what I needed. 

Apollo Client exposes `custom fetching` https://www.apollographql.com/docs/react/networking/advanced-http-networking/#custom-fetching , see also https://github.com/apollographql/apollo-client/blob/36d2caece4bcca7cf855ff8e82a9769df0ef405e/src/link/http/createHttpLink.ts#L185 . In the plugin I'm using it's part of the httpLinkOptions, I was able to pass it the following fetch to make things happy. 

```
httpLinkOptions: {
    fetch: async (uri, options) => {
      Object.assign(options, {
        headers: {
            "x-my-headers": "yes"
        }
      });
      
      return await fetch(uri, options);
    },
}
```

For whatever reason, the object assign of the headers object got me around the error. 

I hope this helps anyone else who stumbles upon this error. This is absolutely feels like a gross work around for someone else's bug. If anyone has a way to submit a bug to forcepoint, please do.

**Comment by dotku** [comment] 2024-09-03 18:31
> @dotku Could you please provide your iOS version, browser version and a list of all installed browser extensions or other installed "privacy"-type apps?

I have no idea, but somehow it is fixed automatically?!

**Comment by phryneas** [comment] 2024-09-04 11:24
@spnc-omz that puts enough puzzle pieces in place that we might also be able to work around it on our side.

Could you please give `npm i @apollo/client@0.0.0-pr-12054-20240904112316` a try and report back if it also solves the issue?

**Comment by spnc-omz** [comment] 2024-09-04 20:23
@phryneas  I was able to give this a look in my project in safari and I'm no longer seeing the issue. I did have a few hiccups getting there because of the layers of abstraction provided by frameworks, but was able to verify. 

Thanks for getting around to this so quickly! y'all are awesome.

**Comment by phryneas** [comment] 2024-09-05 08:14
@spnc-omz thank you for the feedback - I'm getting this released then :)

**Closed** 2024-09-05 08:30 UTC
Labels: :wilted_flower: needs-reproduction, 🔍 investigate

**Comment by phryneas** [comment] 2024-09-05 08:39
And it's out with https://github.com/apollographql/apollo-client/releases/tag/v3.11.8

**Comment by danielbucher** [comment] 2024-09-05 12:45
Thanks for that @spnc-omz and @phryneas.
