### ISSUE TITLE
Apollo Client does not convert object to the specific Type in useQuery

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [apollographql/apollo-client#11028] opened 2023-06-30 18:41 UTC
Consider I have a query such as,
```ts
const fooQuery = gql`query foo {
  id
  name
  bar {
    propA
    probB
  }
  }`;
```

I use apollo client tools to generate my client side types and i have something like,
```ts
export interface FooType {
  __typename: 'FooTypeName';
  id: number;
  name: string;
  bar: BarType;
}

export interface BarType {
  __typename: 'BarTypeName';
  propA: string;
  propB: string;
}
```

i make a query like this,
```ts
const { data, loading, error } = useQuery<FooType>(fooQuery);
```

Now I noticed that apollo is adding `__typename` field to my queries even if I did not ask them. I suppose this is an existing issue and i read some discussions around this but this is part of my problem but not entirely. 

I noticed that if the `__typename` is NOT sent from my backend server in the RESPONSE (for sub complex properties). Those properties are not available in the resulting `data` object.

`data. Bar` property is not there in the result when I debug on client side. I actually took the JSON from the backend and explicitly convert using oure typescript code like `JSON.paser(jsonStringFromBackend) as FooType` and it gives me back as expected even if there is no __typename on the JSON. 

This behavior is blocking me from achieving a functionality so if someone can shed some light on why this might be the case and how I can work around it, it would be much appreciated. 

I tried setting `addTypename` property in `InMemoryCache` to false but no luck.

**Comment by bignimbus** [comment] 2023-07-05 15:46
Hi @EmmanuelPonnudurai 👋🏻 as you noted, `__typename` is added to queries by default in Apollo Client - this is an important part of how we normalize data by default in the cache.  I'm not certain but it seems to me that a server should always have `__typename` data available for any object.  So it's likely that the backend you're querying is not entirely complying with the GraphQL spec.  But I think we can still work around this.

May I ask for a bit more information regarding the following:

> `data. Bar` property is not there in the result when I debug on client side. I actually took the JSON from the backend and explicitly convert using oure typescript code like `JSON.paser(jsonStringFromBackend) as FooType` and it gives me back as expected even if there is no __typename on the JSON. 

When you say "took the JSON from the backend," how did you do that?  I'm trying to understand whether the server is sending the requested data.  It sounds like it might be, so I might recommend one of the following:

1. Include `id` in the selection set for the `bar` field, e.g.:
    ```graphql
    query foo {
      id
      name
      bar {
        id # the id field helps create a unique cache id for a BarTypeName object
        propA
        probB
      }
    }
    ```
    For more info about why this could help, see [Caching > Overview > Data normalization](https://www.apollographql.com/docs/react/caching/overview/#data-normalization) in the docs
2. If an `id` isn't available, consider defining `keyFields` in a `typePolicies` entry for `FooTypeName`.  More on that in [Caching > Configuration > Customizing cache IDs](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids)

I'll close this issue for now but please feel free to open an issue if you think there's a bug happening.  Our [Discord](https://discord.gg/graphos) is a great place for Q&A like this as well! 🙏🏻

**Closed by bignimbus** 2023-07-05 15:46 UTC

**Comment by EmmanuelPonnudurai** [comment] 2023-07-11 03:23
Hello @bignimbus Sorry I missed your response. The server is compliant. I use graphql.net and it follows graphql spec. 

The server is capable of sending the __typename. Also, I understand that __typename field is used by apollo for caching.

My question is more about if this also impacts the casting process. 

If I don't request __typename (and server doesnt send it), `data.bar` is undefined. If i request __typename(server sends it) and then `data.bar` is populated correctly. So my question is why does __typename precense or absense impact this casting process?

**Comment by phryneas** [comment] 2023-07-11 10:04
One small "mindset adjustment" that will make the rest easier to understand: 
There is no "casting" happening anywhere here - TypeScript cannot cast, and you never have to "convert" anything to a TypeScript type. TypeScript types only exist in your IDE and compiler and are only concerned about "does it have this shape or not?". TypeScript doesn't exist in runtime, types also don't exist.

So, from a pure JavaScript perspective: 
If you omit the `__typename`, the cache doesn't know what it is seeing, what to make of it, and where to store it. 
This *can* work in certain conditions, but it will give you a worse experience with Apollo Client in general, and makes certain things (such as applying fragments on a type) completely impossible (since we don't know if something is of the type a fragment requested, or something else entirely).

Since I don't have an actual running code example, I can't tell you what exactly is going wrong in this case, but the general point is: don't skip `__typename`. It is really necessary.

If I might ask: what is your actual problem with it being present? An additional property on a JavaScript object usually shouldn't hurt anything.

**Comment by EmmanuelPonnudurai** [comment] 2023-07-11 15:32
@phryneas I used the term casting/conversion as a way to explain myself but yes there is no types concept in runtime. 

My question again is not with respect to importance of __typename and wanting to omit it. All i am saying is that if you omit typename, the resulting object is not correct based on the response from backend. 

The response from backend does have the correct shape for sure but the result that comes out of `useQuery` does not have few properties. That is what im saying. if __typename is not present on the result from backend JSON, not only does the caching not work but basically the `data` from `useQuery` is also not complete. Atleast that is what im seeing.

**Comment by phryneas** [comment] 2023-07-11 16:39
That is totally possible - omitting `__typename` is something that should always be in your queries and omitting it can have very severe consequences. If you give us a reproduction, I can take a look at it and we can see if there is something we can generally do about that use case with very small changes to the core - but we do expect `__typename` to be always present. 

If you take a look at the documentation for `addTypename`:

> If `true`, the cache automatically requests the `__typename` field for every object in your outgoing operations, which means you can omit `__typename` from your operation definitions.
> 
> By default, the cache uses the `__typename` field as part of the cache ID for every cached object, so it's helpful to guarantee that the field is always fetched.

It is worded in a way that it adds the `__typename` field for you, implying that if you don't use `addTypename`, you will always have to add it to all your queries by hand. The internal default implementations rely on that being present.  
The only way around that would be to specify your own `dataIdFromObject` function, which is also something we don't really want to encourage too much.  

> not only does the caching not work but basically the data from useQuery is also not complete.

The data from `useQuery` comes from the cache. So if it cannot possibly "fit" into the cache, we can also not deliver it to you in `useQuery`.
