### ISSUE TITLE
Fields Dropped when using a Fragment

### ISSUE THREAD

**Issue by dylanwulf** [apollographql/apollo-client#8389] opened 2021-06-14 21:41 UTC
**Intended outcome:**
When querying with a fragment, the fields specified by the fragment should not be `undefined`.

**Actual outcome:**
Fields specified by a fragment will get completely dropped after running the `merge` function. The rest of the query data is still there, even though `returnPartialData` is false.

**How to reproduce the issue:**
https://github.com/dylanwulf/react-apollo-error-template/tree/fragment-dropping-fields
Please use branch `fragment-dropping-fields`.

**Versions**
```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.101
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
  npmPackages:
    @apollo/client: ^3.3.20 => 3.3.20
```

**Comment by dylanwulf** [comment] 2021-06-14 22:22
Ok actually I just tried removing the interface and the problem is still there. So I guess I was wrong about the interface part, but still definitely something fishy going on here 🐟

**Comment by benjamn** [comment] 2021-06-16 22:37
@dylanwulf Thanks for the reproduction!

This took me a while to track this down, so I know your pain, but your `paginatedQueryMerge` function seems to be dropping the `__typename` field from any `FruitsQueryResult` or `VegetablesQueryResult` object, despite merging the rest of the fields successfully:
```diff
diff --git a/src/index.jsx b/src/index.jsx
index cc291a6..0915093 100644
--- a/src/index.jsx
+++ b/src/index.jsx
@@ -185,30 +185,31 @@ function App() {
 const paginatedQueryMerge = (
 	existing,
 	incoming,
 	{ args },
 ) => {
 	if (existing == null || args == null || args.page == null || args.page === 1) {
 		return incoming;
 	}
 
 	const mergedArray = [...existing.results];
 	const offset = (args.page - 1) * 3; // page size is hardcoded to 3 for this reproduction
 	incoming.results.forEach((val, index) => {
 		mergedArray[offset + index] = val;
 	});
 	return {
+		__typename: incoming.__typename || existing.__typename,
 		meta: { ...existing.meta, ...incoming.meta },
 		results: mergedArray,
 	};
 };
 
 const client = new ApolloClient({
   cache: new InMemoryCache({
     possibleTypes: { QueryResult: ['FruitsQueryResult', 'VegetablesQueryResult'] },
     typePolicies: {
       Query: {
         fields: {
           fruits: { keyArgs: [], merge: paginatedQueryMerge },
           vegetables: { keyArgs: [], merge: paginatedQueryMerge },
         },
       },
```
If the `__typename: "FruitsQueryResult"` field is lost, then when the client reads from the cache for the final results (after `fetchMore` finishes), the `...ResultFragment` in that query fails to match/spread, because the cache can't verify the `FruitsQueryResult` object is a subtype of `QueryResult` without knowing its `__typename`.

Maybe there's an opportunity for a warning here? Preserving `__typename` fields is probably worth some console noise. Let me know if you have any thoughts about how that might work!

**Comment by dylanwulf** [comment] 2021-06-16 23:02
@benjamn Wow, I feel dumb now 😅. Thank you for getting back to me so quickly! Really appreciate it. As for the warning idea, I definitely would be in support of something like that. Not really sure about the exact details of how it should work though.
I'll leave this issue open in case you want to use it to track the warning idea, but otherwise feel free to close! Thanks again!

**Comment by zanemcca** [comment] 2021-06-17 01:56
I have a similar issue based on the description but it sounds like it is likely being caused by something else.

Essentially my issue is that I have two queries that pull in the same item (lets call it `SomeItemType`). One of the queries returns a list and the other returns a single item. The query for the single item will always contain the full object along with all of it's properties but the list omits a few fields due to limitations in the underlying backend. The scenario would look something like this...

Fragment:
```
fragment SomeItemTypeFragment on SomeItemType {
    id
    someFieldThatWillBeThereForSingleItemQueriesOnly
    ...
}
```
List Query:
```
query ListItems() {
    items {
        ...SomeItemTypeFragment
    }
}
```
Item Query:
```
query GetItem($id: String!) {
    item(id: $id) {
        ...SomeItemTypeFragment
    }
}
```

What ends up happening is the fragments returned by the list will overwrite the fragment returned by the single item query. This results in `someFieldThatWillBeThereForSingleItemQueriesOnly` being `null` in the cache.

I had hoped that I could simply use `merge` on the `SomeItemType` to control how the list items are merged into the cache like so.

```
typePolicies: {
    SomeItemType: {
         merge: true,
    }
}
```
Or with a more manual merge function that does the same thing with special handling for `null` fields.

However this solution did not work as it appears the merging of the fragments is occurring before the `merge` is even called. Also it appears that `merge` is not called at all when results from `ListItems` come back. This is very unintuitive as I would expect `merge` for a type to allow me to control what is stored in the cache regardless of it's source.

**Am I missing something or is there some alternative `merge` function that allows control over normalized cache objects?**

If I did miss something I might suggest updating the docs for `merge` to make it explicitly clear that it cannot be used to control merging data that is normalized to save people hours of searching and debugging like I had.

**Workaround**
My workaround is to not request the missing fields for the `ListItems` call like so.
Fragment:
```
fragment SomeItemTypeFragment on SomeItemType {
    id
    ...
}
```
List Query:
```
query ListItems() {
    items {
        ...SomeItemTypeFragment
    }
}
```
Item Query:
```
query GetItem($id: String!) {
    item(id: $id) {
        ...SomeItemTypeFragment
        someFieldThatWillBeThereForSingleItemQueriesOnly
    }
}
```

**Comment by dylanwulf** [comment] 2021-06-17 05:02
@zanemcca That's expected behavior because your multi-item query is returning objects with the same `__typename` and `id` as the single-item query, so whichever query runs last will overwrite the data from the other. That's not a bug, it's just an effect of cache normalization.

**Comment by bignimbus** [comment] 2023-01-25 04:59
Thanks for the discussion here everybody - I'm doing some housekeeping and think this issue should be closed given the above.  Please do feel free to reach out if there's more we can do here!

**Closed by bignimbus** 2023-01-25 04:59 UTC
Labels: :rose: has-reproduction
