### ISSUE TITLE
Errors from `ObservableQuery.currentResult` are not referentially equal

### ISSUE THREAD

**Issue by dallonf** [apollographql/apollo-client#4354] opened 2019-01-21 21:17 UTC
NOTE: This is the same issue as https://github.com/apollographql/apollo-client/issues/2278, however, that issue is closed and I can't reopen it, and the bug still exists in the latest version of Apollo Client.

**Intended outcome:**
Using `react-apollo` (although I think the issue is in `apollo-client`, see below), I would like to trigger an imperative action (show an error notification) when a load error occurs. The most straightforward path to me is to compare `props.data.error` with `nextProps.data.error`, and if they are different, show the notification for the new error.

**Actual outcome:**

The `data.error` prop is actually a `new ApolloError` instance every time the component renders. Based on the stack trace, it appears to be created in `ObservableQuery.currentResult`, which in turn is called by `GraphQL.render`.

Because these errors are new for every render, the error notification will appear repeatedly. To get my intended behavior, I would have to compare `error.networkError` and `error.graphQLErrors` (which do seem to be referentially stable), which couples my generic error handling to implementation details of Apollo Client.

**How to reproduce the issue:**

Here is a sandbox:

https://codesandbox.io/s/oq3mw2rmyy

Note that whenever the `graphql` wrapper is re-rendered (with any new props, to bypass the `componentShouldUpdate` check), the error instance is new and so logs a new message, even though it is logically the same error.

**Version**

- apollo-client@2.4.12
- react-apollo@2.4.0

**Comment by danilobuerger** [comment] 2019-01-21 21:33
Duplicate of #2278. Reoping the old one.

**Closed by danilobuerger** 2019-01-21 21:33 UTC
