### ISSUE TITLE
useLazyQuery brakes the whole app

### ISSUE THREAD

**Issue by csotiMatyas** [apollographql/apollo-client#9336] opened 2022-01-21 08:08 UTC
I'm an absolute novice playing around in apollo client.

`  const [searchItems, { data, loading, error }] = useLazyQuery(
    SEARCH_PRODUCT_QUERY,
    { fetchPolicy: "no-cache" }
  );`

Simply declaring this in an empty component on a page makes every page load forever, no errors. Network activity is showing a single document with a name of "1",  and its pending for ever.

Edit: with or without any fetchPolicy options.

///////

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
  npmPackages:
    @apollo/client: ^3.5.7 => 3.5.7
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/react-ssr: ^4.0.0 => 4.0.0
    @apollo/react-testing: ^4.0.0 => 4.0.0
    apollo-upload-client: ^17.0.0 => 17.0.0
    next-with-apollo: ^5.1.1 => 5.2.1

**Comment by redeyes2015** [comment] 2022-01-25 07:35
Hi, this seems to be the same issue as #9108. Would you mind checking the discussion there?

(I am not a maintainer)

**Comment by brainkim** [comment] 2022-02-02 01:32
Closing as a duplicate of #9108. Thanks for opening the issue and sorry for the trouble.

**Closed by brainkim** 2022-02-02 01:32 UTC
