### ISSUE TITLE
Cache and Typed arrays

### ISSUE THREAD

**Issue by Banou26** [apollographql/apollo-client#6813] opened 2020-08-10 12:37 UTC
**Intended outcome:**
When trying to pass `TypedArray`s as a local-only field it should work

**Actual outcome:**
Apollo throws `Cannot freeze array buffer views with elements`

**How to reproduce the issue:**
Pass a non empty `TypedArray` to a local-only field.

**Comment by benjamn** [comment] 2020-08-10 14:17
Hmm, since the freezing happens only in development, and is intended to encourage immutable/non-destructive updates rather than strictly enforcing that discipline, maybe it should be best-effort, as the name [`maybeDeepFreeze`](https://github.com/apollographql/apollo-client/blob/master/src/utilities/common/maybeDeepFreeze.ts) suggests. I admit I was not aware of any object types that throw when frozen with `Object.freeze`, but since that's apparently a real possibility for `TypedArray`, I'm open to catching/silencing those exceptions, and just leaving the object unfrozen.

Out of curiosity, are you modifying these `TypedArray`s in place, or are they immutable? Are they just scalar values (field name without selection set), or do you treat them as GraphQL data?

**Comment by Banou26** [comment] 2020-08-10 15:54
I'm following the immutability mindset & replacing the entire `TypedArray` if i ever need to change its value(in my case this will practically never happen), and yes, i want to use them as scalar values without any selection, though, one thing that surprised me is that they are under an object's form in Apollo's devtools:
```
PackageBundle:{"version":"0.0.1","package":{"id":"5f316cb6fd847fcc5307f611"}}
archive: {"type":"Buffer","data":[4,0,0,0,148,0,0,0,144,0,0,0,139,0,0,0,123,34,102,105,108,101,115,34,58,123,34,109,97,110,105,102,101,115,116,46,106,115,111,110,34,58,123,34,115,105,122,101,34,58,49,50,52,44,34,111,102,102,115,101,116,34,58,34,48,34,125,44,34,105,110,100,101,1,...]}
```

So i'm not sure if in the end they'll be correctly handled by Apollo.

**Comment by kevin-lindsay-1** [comment] 2020-08-14 19:04
Getting the same issue only in development.

I generally use custom scalars for the sake of notation for these browser-side types and use immutability throughout.

**Comment by hwillson** [comment] 2021-05-05 15:03
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by Banou26** [comment] 2021-05-06 00:47
This is still an issue under `^3.3.16` which is current latest
Here is a runnable repro of exactly what i described to reproduce the error in the original comment:

> Set a typed array into a reactive variable and query it.

https://github.com/Banou26/apollo-client-bug-6813


As a side note, closing out issues that were left abandoned for months and are still valid issues isn't really respectful for the time we spent describing/making repros for issues that we reported. I'm still gonna double check all my active issues you closed. It's certainly not pleasant having to report the same issue multiple times.

**Comment by brainkim** [comment] 2021-05-06 01:31
> As a side note, closing out issues that were left abandoned for months and are still valid issues isn't really respectful for the time we spent describing/making repros for issues that we reported. I'm still gonna double check all my active issues you closed. It's certainly not pleasant having to report the same issue multiple times.

Sorry about that! We’ve been closing issues because there were so many which were referencing outdated versions and investigating each of them would be cost prohibitive. Of course, this is our fault for not tracking issues and closing them as they’re fixed, but we’ve found that closing issues

**Comment by hwillson** [comment] 2021-05-06 09:52
Thanks @Banou26 - as @brainkim mentioned, our intent is to get our issue backlog under control, so we can start being more effective at staying on top of and resolving issues. To get the hundreds of old issues under control, we have to make certain assumptions. Asking people to verify the issue with `@apollo/client@latest` and closing the issue really does help clear out the backlog, as there are hundreds of issues that are already fixed, and just haven't been closed. We're keeping an eye on comments on closed issues though, and as long as people can provide a reproduction (or update an existing reproduction), we're re-opening them. Again though, we're not trying to be disrespectful here - quite the opposite. Instead of letting an ~850 open issue count stagnate, meaning the core team is only really staying on top of new issues, we're going to clean up the entire backlog, and stay on top of all of them. This will lead to faster turn around times on issues.

**Comment by p-j** [comment] 2021-09-07 07:08
Hi,

any update on that issue? Is there a workaround beside changing the NODE_ENV? Any particular reason for this to throw instead of just print a warning in the console if that is for development only?

**Comment by p-j** [comment] 2021-09-08 07:13
I encountered this error yesterday as well. Two things that made it difficult to work with:
- it throws when really this should be a warning/error logged in the console with explanations and links to documentation/best practices since this behavior isn't blocking in production
- it doesn't tell me what's the issue: what object/array caused that error (neither the value, nor the type or its key are given).

in the end it was an issue with some shared code between frontend & backend that was producing ObjectId instead of their string representation; ObjectId internally uses an Uint8Array that was crashing the maybeDeepFreeze function.

**Comment by geekuillaume** [comment] 2021-09-19 12:14
I submitted a PR to fix this: https://github.com/apollographql/apollo-client/pull/8813. This simply ignores TypedArrays when freezing. We could also just wrap `Object.freeze` in a try/catch statement and trigger a warning on error to make this future-proof in case some other objects that are not freezable are added in the future.

**Closed** 2021-09-20 15:34 UTC
Labels: :rose: has-reproduction
