### ISSUE TITLE
The onCompleted callback of the useQuery hook executes on data mutations

### ISSUE THREAD

**Issue by krasai** [apollographql/apollo-client#9688] opened 2022-05-06 10:03 UTC
**Intended outcome:**
The `onCompleted` callback in the `useQuery` hook shouldn't be executed when data has changed by a mutation. The callback function needs to be called only once, after the data has been fetched.

**Actual outcome:**
The `onCompleted` callback of the `useQuery` hook executes on each data change. 

**How to reproduce the issue:**
https://codesandbox.io/s/mutations-oncompleted-callback-execution-2n2yic?file=/src/index.js

1. Add a todo
2. Update the todo 

Switch between `@apollo/client` versions to see the behavior of the `onCompleted` callback varies between `3.4.x` and `3.5.x`, `3.6.x` versions.
On version `3.4.x`, the `onCompleted` callback is called only once, when data fetches, while on versions `3.5.x` and `3.6.x`, the callback is executed two times, when data fetches and additionally after the mutation.

**Versions**
`3.4.14`: works as expected.
`3.5.x` and `3.6.x`: the `onCompleted` callback of the `useQuery` hook executes on data mutations.

**Comment by jpvajda** [comment] 2022-06-03 22:14
hello @krasai we've subsuently release several patch versions around some `useQuery` bugs we saw from our 3.6 release, would you be willing to try our latest version, 3.6.6 to see if your issue has been resolved? Here is the [change log ](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md)with all the fixed we releases. It's possible this was fixed in https://github.com/apollographql/apollo-client/pull/9740

**Comment by krasai** [comment] 2022-06-14 01:38
Hey @jpvajda, 
Thank you for taking care of this issue. 
I have just checked it on the newer version (3.6.8), and it seems that the issue still exists. 
In the sandbox I provided, when I update the todo, the onComplete callback is called twice (after the mutation and when data is fetched). 
On version 3.4.x the callback is called only once (only when the data is fetched). 
The issue also exists on the newest beta version (3.7.0-beta.5).

**Comment by jpvajda** [comment] 2022-06-15 19:42
@krasai thanks for confirming! I'm going to add @benjamn to this discussion now that we've confirmed it still an issue in `3.6.8`

**Comment by sanex3339** [comment] 2022-10-07 07:35
Are there any workarounds for this issue?

**Comment by eveevans** [comment] 2022-10-20 22:26
Same problem here, and I using Apollo 3.6.9

**Comment by alessbell** [comment] 2022-10-26 18:14
Appreciate the reproduction here, @krasai! I have https://github.com/apollographql/apollo-client/pull/10229 open with the fix, I'll update this issue again when it's merged and released. Thanks everyone 🙇‍♀️

**Comment by alessbell** [comment] 2022-12-12 17:59
The fix is now available in the current 3.8 `alpha` release which can be installed via `npm i @apollo/client@alpha`.

**Comment by alessbell** [comment] 2023-04-05 16:49
Closing this issue since this is fixed in a prerelease version; feel free to try out the 3.8 alpha for the fix 🚀

**Closed by alessbell** 2023-04-05 16:49 UTC
Labels: 🐞 bug, 🛬 fixed-in-prerelease, 🔍 investigate
