### ISSUE TITLE
useWindowDimensions in root App component causes Apollo to refetch. (RN)

### ISSUE THREAD

**Issue by ConnorMoodyDev** [apollographql/apollo-client#9548] opened 2022-03-23 02:31 UTC
**Intended outcome:**
The intended outcome is for Apollo to continue to use already fetched data when device orientation or size is changed.
**Actual outcome:**
Apollo refetches data each time the window dimensions are changed.

**How to reproduce the issue:**
1. Use the React hook useWindowDimensions in the component that renders ApolloProvider
2. Change the window dimensions

**Versions**
<!--
Run the following command in your project directory, and paste its (automatically copied to clipboard) results here:

  System:
    OS: macOS 12.0.1
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 1.22.17 - ~/Desktop/Defyre-App/defyre/node_modules/.bin/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Safari: 15.1

**Comment by bignimbus** [comment] 2022-12-12 21:56
Hi @ConnorMoodyDev 👋🏻  thanks for your patience.  I recommend posting this question in our [community forum](https://community.apollographql.com) since it's more about how to use Apollo Client in a specific scenario.  When you do, be sure to include some sample code and ideally a runnable reproduction so that the community can help you resolve the issue!  In an effort to keep the Issues actionable I will close this but am looking forward to seeing your post in the forum so others can learn from it :)

**Closed by bignimbus** 2022-12-12 21:56 UTC
