### ISSUE TITLE
Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.

### ISSUE THREAD

**Issue by chetankondawle** [apollographql/apollo-client#10146] opened 2022-09-30 12:54 UTC
Getting Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler' on 3.6.10 upgrade.
Code is throwing error on `httpLink` and `authLink`

```
const httpLink = new HttpLink({ uri: "/test" });

const authLink = new ApolloLink((operation, forward) => {
  // add the authorization to the headers
  const token = sessionStorage.getItem("token");
  operation.setContext(({ headers = {} }) => ({
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : "",
    },
  }));

  return forward(operation);
});

const middleWareLink = new ApolloLink((operation, forward) => {
  operation.setContext(({ headers = {} }) => ({
    headers: {
      ...headers,
      "Content-Type": "application/json"
    }
  }));

  return forward(operation);
});

const customApiClient = new ApolloClient({
  link: from([authLink, middleWareLink, httpLink]), // Provide required constructor fields
  cache: new InMemoryCache(),
});
```

**Intended outcome:** Should work as it was working with 3.6.9

**Actual outcome:**  Throwing `Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'` on 3.6.10 upgrade.

**Versions** : @apollo/client : 3.6.10

**Comment by bignimbus** [comment] 2022-09-30 21:08
Hi @chetankondawle 👋🏻 thanks for opening this issue!  I've set up a [codesandbox](https://github.com/apollographql/apollo-client/issues/10146) in an attempt to reproduce the type error you're seeing.  I haven't yet been successful.  Perhaps the type annotation of `middleWareLink` is relevant?  I don't see where it's defined in the code sample.  Let us know if you have additional information that could help us narrow things down 🙏🏻

**Comment by jerelmiller** [comment] 2022-09-30 21:31
@bignimbus looks like you might have accidentally used the issue URL for your codesandbox link 😆. Would you mind updating your comment to point to your codesandbox example?

**Comment by bignimbus** [comment] 2022-09-30 22:10
Updated - thanks for catching that @jerelmiller

**Comment by shshaw** [comment] 2024-11-13 22:26
This happened to me recently with @apollo/client 3.11.10. The issue _seemed_ to be due to another library with a `graphql-tag` or `graphql` package dependency that had a slight version mismatch. Updating `graphql-tag` and `graphql` packages to the latest versions in my dependencies seemed to resolve the problem.

**Comment by jerelmiller** [comment] 2024-11-13 22:32
Hey all 👋 

I've seen this a few times myself come up and this is usually a symptom that you have multiple versions of Apollo Client installed. The fix is to ensure you're only installing a single version. I've seen this come up when dependencies themselves depend on `@apollo/client` or you're working in a monorepo with multiple projects depending on `@apollo/client`. 

As such, there is not much we can do our our side, so I'm going to go ahead and close this.

**Closed by jerelmiller** 2024-11-13 22:32 UTC
Labels: ⏮ compatibility, 🏓 awaiting-team-response
