### ISSUE TITLE
Could not find "client" in the context of Apollo(MyComponent). Wrap the root component in an <ApolloProvider>

### ISSUE THREAD

**Issue by farzd** [apollographql/apollo-client#2042] opened 2017-08-12 20:39 UTC
Hello,
Using expo/react-native, I get this error when I try make a graphql-query from a modal. I.E the component only gets mounted when you click on a link [the modal slides in]. The graphql-query seems to work in any other component.

my root component is wrapped in a ApolloProvider
```
      <ApolloProvider client={client}>
        <View style={styles.container}>
          <Navigator navigatorViews={navigatorViews} routeConfig={routeConfig} />
        </View>
      </ApolloProvider>
```

I'm not quoting my query code as it works fine outside the modal, is there some gotchas for components that are mounted dynamically  ?
![screen shot 2017-08-12 at 21 34 00](https://user-images.githubusercontent.com/1423413/29244022-15a9b356-7fa6-11e7-9758-96caca944839.png)

**Intended outcome:** Execute graphql query from a component that is mounted dynamically 

**Actual outcome:** see error above

**How to reproduce the issue:** Make graphql query from a component that is mounted in dynamically

**Version**
- apollo-client@^1.9.1

**Comment by thierryskoda** [comment] 2017-08-30 17:47
Hi @farzd,

Have you solved this issue? I have the same thing right now.

**Comment by oakmad** [comment] 2017-09-05 12:40
I just encountered the same issue, anyone solved this?

**Comment by farzd** [comment] 2017-09-05 13:43
@thierryskoda @oakmad 
Sorry guys, i've not revisited this yet. But a work around would be to either import the client again 
https://stackoverflow.com/questions/40634872/do-i-need-to-bind-to-a-component-to-use-the-apollo-react-client-even-if-it-has-n

or use HOC from apollo
http://dev.apollodata.com/react/higher-order-components.html#withApollo

**Comment by oakmad** [comment] 2017-09-06 13:18
OK Thanks @farzd Honestly it's far from ideal in terms of solution, decorators cause me grief in other ways. I was under the impression that is I wrapped my app then client was available all the way down. I'll keep looking and post if I find anything, thanks again.

**Comment by farzd** [comment] 2017-09-06 16:15
@oakmad client should be available all the way through, can you post your code?
I was having an issue because i'm cloning my component etc [i'm assuming]

**Comment by oakmad** [comment] 2017-09-06 16:57
Yeah sure. I've trimmed some non pertinent code, I'm sure its a silly mistake. When I include the phone component in the form, I see the error "Warning: Failed context type: The context `client` is marked as required in `Apollo(Phone)`, but its value is `undefined`."

Parent Component:
```
import React, { Component } from 'react';
import { graphql, compose } from 'react-apollo';
import gql from 'graphql-tag';
import Phone from './phone';

const PersonSave = gql\`
  mutation PersonSave($id: String,
                      $firstName: String!,
                      $lastName: String!,
                      $phone: String!
                      $slug: String!) {
  PersonSave(id: $id,
            firstName: $firstName,
            lastName: $lastName,
            phone: $phone,
            slug: $slug) {
    id
    slug
    firstName
    lastName
    phone
  }
}`;

const Organizations = gql`query Organizations {
  organizations {
    id
    name
  }
}`;

class PersonForm extends Component {
  constructor(props) {
    super(props);
    this.state = this.props.person;
    console.log(this.state);
    this.handleChange = this.handleChange.bind(this);
    this.checkEmail = this.checkEmail.bind(this);
  }

  checkEmail(event) {
    const value = event.target.value;

    const emailRegex = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    let emailError;
    if (!emailRegex.test(value)) {
      emailError = 'Invalid email address';
    }
    this.setState({
      email: value,
      emailError,
    });
  }

  handleChange(event) {
    const target = event.target;
    const name = target.name;
    const value = target.type === 'checkbox' ? target.checked : target.value;
    this.setState({
      [name]: value,
    });
  }

  render() {
    return (
        <Form>
          <Phone
            phone={this.state.phone}
            handleChange={this.handleChange}
          />
          <FormField label="Email" help="" error={this.state.emailError}>
            <TextInput
              name="email"
              value={this.state.email}
              placeHolder="Required in order to login"
              onDOMChange={this.checkEmail}
            />
          </FormField>
        </Form>
    );
  }
}

export default compose(
  graphql(PersonSave, { name: 'PersonSave' }),
  graphql(Organizations, { name: 'OrganizationList' }),
)(PersonForm);
```

And the Phone Child:
```
import React, { Component } from 'react';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

import FormField from 'grommet/components/FormField';
import Notification from 'grommet/components/Notification';
import TextInput from 'grommet/components/TextInput';

const Unique = gql`
  mutation Unique(
                  $phone: String) {
  unique(
        phone: $phone) {
    id
  }
}`;

class Phone extends Component {
  constructor(props) {
    super(props);
    this.state = {
      phone: this.props.phone,
      intl: this.props.phone,
      inUse: false,
      phoneError: undefined,
    };
    this.checkPhone = this.checkPhone.bind(this);
  }

  checkPhone(event) {
    const name = event.target.name;
    const value = event.target.value.replace(/[^0-9]+/g, '');
    let intl = value;
    if (intl.charAt(0) === '0') {
      intl = `+44${intl.substring(0)}`;
    } else {
      intl = `+1${intl}`;
    }
    this.setState({
      [name]: value,
      intl,
      phoneError: value.length !== 10 && 'Please enter 10 digits including area code',
    });
    this.props.handleChange({ target: {
      name: 'phone',
      value: value.length === 10 ? intl : undefined },
    });
    this.props.mutate({
      variables: {phone},
    }).then((result) => {
       console.log(result);
    });;
  }

  render() {
    return (
      <FormField label="Phone" error={this.state.phoneError}>
        <TextInput
          id={'phone'}
          name="phone"
          value={this.state.phone}
          placeHolder="Phone number including area code"
          onDOMChange={this.checkPhone}
        />
      </FormField>
    );
  }
}

export default graphql(Unique)(Phone);
```

**Comment by farzd** [comment] 2017-09-07 14:29
@oakmad sorry i cant see anything wrong with your code, unfortunately - unless the client singleton is not setup right but then none of it would work.

**Comment by oakmad** [comment] 2017-09-08 15:09
Thanks @farzd - It seems to be working without issue elsewhere in the app, so I presume the client is OK. I'm relatively new to react and apollo (from Meteor) and suspect I've made some news error. I'll revisit it in future as I get more experience.

**Comment by Ardhimas** [comment] 2017-09-08 20:26
@oakmad I know this isn't helpful in any way, but I just started running into this issue today and I have no idea why. I'll report back if I figure it out, but it's definitely nothing to do with conditional rendering.

**Comment by johndanek** [comment] 2017-09-13 23:58
This is an issue for me as well. I think it's due to the fact that the component trying to use @withApollo is created as a property to a parent component. That's my hunch, at least.

**Closed** 2017-10-10 15:04 UTC
Labels: no-recent-activity

**Comment by austin43** [comment] 2017-11-29 04:27
I see this thread was closed but I'm having this exact issue with gatsby when building.  Development works just fine.

**Comment by 42void** [comment] 2018-03-07 17:39
+1

**Comment by shafqatdotnet** [comment] 2018-03-15 01:54
i having the exact issue

**Comment by austingray** [comment] 2018-03-23 02:45
I had this issue when I introduced server side rendering to an app. Here's how the problematic code was setup:

```javascript
...
import DisplayComponent from './DisplayComponent';

const client = new ApolloClient({ ...config });

function MyComponent() {
  return (
    <DisplayComponent
      queryVal="foo"
    />
  )
}

ReactDOM.render(
  <ApolloProvider client={client}>
    <MyComponent />
  </ApolloProvider>,
  document.getElementById('mount-div-id'),
);

export default MyComponent;
```

I got the error that is in the title of the issue. I fixed it by updating my code to this:
```javascript
...
import DisplayComponent from './DisplayComponent';

const client = new ApolloClient({ ...config });

function MyComponent() {
  return (
    <ApolloProvider client={client}>
      <DisplayComponent
        queryVal="foo"
      />
    </ApolloProvider>
  )
}

ReactDOM.render(
  <MyComponent />,
  document.getElementById('mount-div-id'),
);

export default MyComponent;
```

Hopefully that helps someone.

**Comment by farzd** [comment] 2018-03-23 10:01
i guess you can now just use ```<ApolloConsumer>```

**Comment by salahuddinqss** [comment] 2018-07-20 11:33
- 

- 

- [ ] @1.

**Comment by sampathsris** [comment] 2019-03-17 04:57
In case you got this error while using `react-apollo-hooks`, you may want to take a look at this sandbox: https://codesandbox.io/s/vnr2lqvrm0.

**Comment by jim-at-jibba** [comment] 2019-03-21 15:27
> In case you got this error while using `react-apollo-hooks`, you may want to take a look at this sandbox: https://codesandbox.io/s/vnr2lqvrm0.

You are a life saving, hours saved!!

**Comment by evert-smit** [comment] 2019-04-30 13:54
> In case you got this error while using `react-apollo-hooks`, you may want to take a look at this sandbox: https://codesandbox.io/s/vnr2lqvrm0.

I am using react-apollo-hooks and had the components set up just like the sandbox (Root, not BuggyRoot), but still got the error.

Reverting back to 2.5.2 'fixed' it for now. https://github.com/apollographql/react-apollo/issues/2900

**Comment by pencilcheck** [comment] 2019-06-27 00:07
Ditto, having issues with 2.5.6, fixed it after reverting to 2.5.2

**Comment by ptimson** [comment] 2019-07-08 00:13
I got this error when trying to use `@apollo/react-hooks`

The solution as suggested by @sampathsris is to wrap your app with both `ApolloProvider` from  both the new hooks lib and the original `react-apollo` lib

```
import { ApolloProvider } from 'react-apollo'
import { ApolloProvider as ApolloHooksProvider } from '@apollo/react-hooks'

<ApolloProvider client={client}>
  <ApolloHooksProvider client={client}>
   {/* App here! */}
  </ApolloHooksProvider>
</ApolloProvider>
```

**Comment by PainKKKiller** [comment] 2019-08-28 14:12
Have the same problem with react-apollo 3.0.0 and 3.0.1. Recipe @ptimson didn't work for me.

**Comment by tmaximini** [comment] 2019-08-28 14:13
2.5.2 works for me

**Comment by PainKKKiller** [comment] 2019-08-28 15:38
2.5.2 worked for me too. But I didn't used react-apollo,  solved it by creating HOC on hooks for classes)). 

`import React from 'react';
import { useQuery } from '@apollo/react-hooks';


export const Query = ({children, query, variables}) => {
  const graphqlState = useQuery(query, variables);
  return (
    <div>
      {
        React.Children.map(children, child =>
          React.cloneElement(child, { ...graphqlState })
        )
      }
    </div>
  )
};`

And then use it:
`import React, { Component } from 'react';
import gql from 'graphql-tag';
import { Query } from '@/utils/withApollo';

import MaterialsTable from '@/components/MaterialsTable';

const GET_CONTENT_UNITS = gql`
  query GetContentUnits($input: ContentUnitFilterInput) {
    getContentUnits(input: $input) {
      name
      id
      cover
      price
    }
  }
`;

export default class Dashboard extends Component {
  render() {
    return (
      <div>
        <h1>Dashboard</h1>
        <Query query={GET_CONTENT_UNITS}>
          <MaterialsTable />
        </Query>
      </div>
    );
  }
}`

**Comment by P48L0** [comment] 2019-10-08 14:23
Had the same issue, aparently you cant use tags and hooks at the same time. If you use hooks, dont use tags. Also, <ApolloProvider> should be imported from @apollo/react-hooks instead of "react-apollo"

Source:
https://spectrum.chat/apollo/react-apollo/error-using-hooks-beta-could-not-find-client~777fcc0e-d590-44f1-99e1-d709a7df5c35?m=MTU2MDMzNjkyNTA3NQ==

**Comment by dinesh-here** [comment] 2019-12-25 16:42
same issue on @apollo/react-hooks 3.0.0

    "@apollo/react-hooks": "3.0.0",
    "apollo-boost": "^0.4.7",
    "graphql": "^14.5.8"

shows the msg "**Unhandled Rejection (Invariant Violation): Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options**"

2.6 doc says we should install @apollo/react-hooks [Doc](https://www.apollographql.com/docs/react/get-started/) but none of the combination are working even tried with 3.1.x beta @apollo/client 

I really don't like to use 2.5 since 3.0 getting beta :(  ,  Anyone have any boilerplate or correct working package versions, Please share it

**Comment by dinesh-here** [comment] 2019-12-25 16:55
Tried with react-apollo too, no luck :( @ptimson 

    "@apollo/react-hooks": "3.0.0",
    "apollo-boost": "^0.4.7",
    "graphql": "^14.5.8",

Used all the version combinations from 3.0.0 to 3.1.x same error msg "
**Unhandled Rejection (Invariant Violation): Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options**."

[Doc](https://www.apollographql.com/docs/react/get-started/) says we should install @apollo/react-hooks and import ApolloProvider, none of this are working, 

I am just trying to setup hello world project for apollo client :( any one have boilerplate or working version combinations, Please share it.

Thanks!

**Comment by ajoslin103** [comment] 2020-01-14 22:26
Following these instructions: [https://www.apollographql.com/docs/react/get-started/](https://www.apollographql.com/docs/react/get-started/) I was dismayed when the error "Uncaught ReferenceError: client is not defined" showed up -- and I had exactly copied their code...

```
import React from 'react';
import { render } from 'react-dom';

import { ApolloProvider } from '@apollo/react-hooks';

const App = () => (
  <ApolloProvider client={client}>
    <div>
      <h2>My first Apollo app 🚀</h2>
    </div>
  </ApolloProvider>
);

render(<App />, document.getElementById('root'));
```

It took a while before I realized that they left out the client definition in their ApolloProvider example...

It works once you bring the client definition in:

```
import React from 'react';
import { render } from 'react-dom';

import { ApolloProvider } from '@apollo/react-hooks';
import ApolloClient from 'apollo-boost';

const App = () => {

    const client = new ApolloClient({
    uri: 'https://48p1r2roz4.sse.codesandbox.io',
    });

    return (
        <ApolloProvider client={client}>
            <div>
            <h2>My first Apollo app 🚀</h2>
            </div>
        </ApolloProvider>
    );

};

render(<App />, document.getElementById('root'));
```

cheers,
Al;

**Comment by NickLewry** [comment] 2020-03-25 16:21
> I got this error when trying to use `@apollo/react-hooks`
> 
> The solution as suggested by @sampathsris is to wrap your app with both `ApolloProvider` from both the new hooks lib and the original `react-apollo` lib
> 
> ```
> import { ApolloProvider } from 'react-apollo'
> import { ApolloProvider as ApolloHooksProvider } from '@apollo/react-hooks'
> 
> <ApolloProvider client={client}>
>   <ApolloHooksProvider client={client}>
>    {/* App here! */}
>   </ApolloHooksProvider>
> </ApolloProvider>
> ```

Why does this solution work? it feels wrong to have to import two different providers? can someone explain please.

**Comment by ajoslin103** [comment] 2020-03-25 17:00
I am now using the useQuery hook (it ROCKS!) 

wrapping thusly:
```
  import { ApolloProvider } from 'react-apollo-hooks';
  import ApolloClient from 'apollo-boost';

  const client = new ApolloClient({
    uri: process.env.BACK_END_URL,
    headers: { authorization: `Bearer ${process.env.READ_ONLY_JWT}` },
  });

  return (
    <ApolloProvider client={client}>
        {/* App here! */}
    </ApolloProvider>
```

and consuming thusly:
```
import gql from 'graphql-tag';
import { useQuery } from 'react-apollo-hooks';

export function ContactListView({ configuration, history, match }) {
  const presentersQuery = gql`
    {
      data: findEventPresenters(eventSerial: "${configuration.serial}") {
        contact { id name email phone contact_type_id }
      }
    }
  `;

  const contactTypeQuery = gql`
    {
      data: findContactType(name: "${match.params.kind}") {
        id name
      }
    }
  `;

  const {
    data: contactType,
    error: contactTypeError,
    loading: contactTypeLoading,
  } = useQuery(contactTypeQuery);

  const {
    data: presenters,
    error: presentersError,
    loading: presentersLoading,
  } = useQuery(presentersQuery);

  if (contactTypeLoading || presentersLoading) {
    return <LoadingIndicator />;
  }

  if (contactTypeError || presentersError) {
    return <Error>{contactTypeError || presentersError}</Error>;
  }

  const contacts = presenters.data
    .map(c => c.contact)
    .map(c => {
      c.contactTypeName = titleCase(contactType.data.name);
      return c;
    })
    .filter(c => c.contact_type_id === contactType.data.id);

  const contactListProps = { contacts };

[ and so on.. ]
```

**Comment by aappddeevv** [comment] 2020-04-13 15:35
I found that I had accidentally installed a version of @apollo/react-common that was 3.1.3 but @apollo/react-hooks needs 3.1.4 and @apollo/react-hooks has its own copy in its install dir--hence it can get out of sync. 

So there was a mismatch.

I manually removed the 3.1.3 version and a few other apollo libs that had accumulated independently of the dependencies from hooks, reinstalled @apollo/react-hooks and that cleared it up for me.

**Comment by IcanDivideBy0** [comment] 2020-05-14 08:56
In case anyone else stumble on this, `yarn why @apollo/react-common` can help you figure out why you have different version of `<ApolloProvider>` used by different packages.

**Comment by yashgkar** [comment] 2020-06-09 19:15
This might work
1. <code>rm -rf node_modules package-lock.json</code>
2. <code>npm install </code>

Maybe there is some issue with npm cache, if it still doesn't work try
<code>npm cache clean --force</code>

Note: this will clean all your your node dependencies, however the package.json file is not deleted. Use these commands at own risk.

**Comment by Kallirroi** [comment] 2020-07-20 23:34
Is anyone else running into this when trying to run the official [docs demo](https://www.apollographql.com/docs/react/get-started/) for hooks? From what I understand, everything has been now bundled into `@apollo/client`. Is that correct? I'm running `"@apollo/client": "^3.0.2""`

**Comment by gbsimon87** [comment] 2020-07-21 00:29
@Kallirroi I am also currently attempting this with `"@apollo/client": "^3.0.2",` and after going through this thread, I'm more confused than ever.  I got to this error when attempting to use the useLazyQuery hook, and after attempting the recipe offered by @ptimson I had no luck.  Please report back if you find anything as this appears to still cause some issues.

**Comment by kirisanth1993** [comment] 2020-07-31 05:57
keep the version  of **@apollo/react-hooks** as same as the version of **react-apollo**

"@apollo/react-hooks": "^3.1.5",
"react-apollo": "^3.1.5"

**Comment by Zhouhao-Rui** [comment] 2020-10-10 22:20
I have used the latest version following the official docs with "@apollo/client": "^3.2.3", and I went through the same problem.

**Comment by hanselabreu** [comment] 2020-12-01 23:34
> I have used the latest version following the official docs with "@apollo/client": "^3.2.3", and I went through the same problem.

same here. i'm on version `3.2.9`.

**Comment by ahmedbrandver** [comment] 2020-12-14 08:31
Havin same issue I am on 3.1.5

**Comment by hanselabreu** [comment] 2020-12-14 15:20
@ahmedbrandver I fixed my issue, what was happening to me was that I using the hooks from both `@apollo/client` and `@apollo/react-hooks`. What I did to fix it was remove the `@apollo/react-hooks` library and just import the hooks or anything GraphQL related from `@apollo/client`.

**Comment by JeremyEllingham** [comment] 2020-12-23 07:32
@hanselabreu this fixed it for me, nice one.

**Comment by petermikitsh** [comment] 2021-02-23 21:42
In my use case, this issue was caused by duplicate copies of `@apollo/client` in my bundle. The fix was to force webpack to resolve a single copy of the module:

```js
{
  resolve: {
    alias: {
      '@apollo/client': require.resolve('@apollo/client')
    }
  }
}
```

**Comment by JANHMS** [comment] 2021-03-09 16:54
Wrapping the test in with `<MockedProvider>` solved it for me using:

`import { MockedProvider } from "@apollo/client/testing";`

I am using the newer version ApolloV3

**Comment by mlescaudron** [comment] 2021-03-19 19:25
It works perfectly with version 3.1.3, 

When I upgrade to version 3.3.12 I have the error again.

**Comment by davidcostadev** [comment] 2021-03-22 20:33
@mlescaudron I'm not sure if this problem is happening to you, but if you are using `@apollo/hooks`, this is the problem, this lib was deprecated, try to replace to use @apollo/client instead.

More info: https://github.com/apollographql/react-apollo#readme

**Comment by yaxx** [comment] 2021-04-11 16:49
My issue was that i was importing useMutation from react-apollo instead of @apollo-client. 
changing that fixed the issue for me

**Comment by CX330-jiuxi** [comment] 2022-04-18 14:01
我遇到过，原因是在项目内混用了react-apollo和@apollo/client
