### ISSUE TITLE
Same query on multiple pages data get twice on nextjs?

### ISSUE THREAD

**Issue by siamahnaf198** [apollographql/apollo-client#10449] opened 2023-01-18 17:09 UTC
### Issue Description

Hello, I am using apollo client into nextjs. Here is `client.ts`-

```ts
import { useMemo } from 'react'
import { ApolloClient, InMemoryCache, HttpLink, NormalizedCacheObject } from '@apollo/client'
import merge from "ts-deepmerge";
import { getCookie } from "cookies-next";

//Initialize apolloClient
let apolloClient: ApolloClient<NormalizedCacheObject>;

//Creating link
function createIsomorphLink() {
    return new HttpLink({
        uri: "http://localhost:5000/piechat",
        credentials: 'same-origin'
    })
}

//Create apollo client
function createApolloClient() {
    return new ApolloClient({
        ssrMode: typeof window === 'undefined',
        link: createIsomorphLink(),
        cache: new InMemoryCache(),
        defaultOptions: {
            query: {
                errorPolicy: "all",
                context: {
                    headers: {
                        authorization: `Bearer ${getCookie("session")}`
                    }
                }
            },
            mutate: {
                errorPolicy: "all",
                context: {
                    headers: {
                        authorization: `Bearer ${getCookie("session")}`
                    }
                }
            }
        }
    })
}

//Initialize Apollo
export function initializeApollo(initialState = null) {
    const _apolloClient = apolloClient ?? createApolloClient()
    if (initialState) {
        const existingCache = _apolloClient.extract()
        const data = merge(initialState, existingCache)
        _apolloClient.cache.restore(data)
    }
    if (typeof window === 'undefined') return _apolloClient
    if (!apolloClient) apolloClient = _apolloClient
    return _apolloClient
}

//Use Apollo
export function useApollo(initialState: any) {
    const store = useMemo(() => initializeApollo(initialState), [initialState])
    return store;
}
```

I have to two pages in this project. I need to show conversation list into both pages in sidebar. That's why I create Layout-

```tsx
<Grid container>
    <Grid item {...{ md: 3.2 }}>
        <Sidebar />
    </Grid>
    <Grid item {...{ md: 8.8 }}>
        <Box sx={styles.Container}>
            {children}
        </Box>
    </Grid>
</Grid>
```

In sidebar component, I design conversation list.

like-

`const { data } = useQuery<GetConversationData>(GET_CONVERSATION_LIST);`

Here, I am fetching data in Serverside-

In both pages- (Page1 and Page2)

```ts
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const apolloClient = initializeApollo()
  await apolloClient.query({
    query: GET_CONVERSATION_LIST,
    context: { headers: { authorization: `Bearer ${ctx.req.cookies["session"]}` } }
  })
  return {
    props: {
      initialApolloState: apolloClient.cache.extract(),
    }
  }
}
```

Now, I am facing one problem. When I change page between both pages via route, conversation data get twiced.

In one page-

![image](https://user-images.githubusercontent.com/78312010/213247298-551391b7-41bc-4d46-acc5-da88d821b6a3.png)

If I go another page via next route then-
![image](https://user-images.githubusercontent.com/78312010/213247462-c7843339-5579-476a-bd05-f23f6aceab3e.png)

But When I refresh whole site, then it comes once. Can anyone tell me that where is the problem

### Link to Reproduction

https://github.com/siamahnaf198/apollo-next

**Comment by bignimbus** [comment] 2023-01-18 18:28
Hi @siamahnaf198 👋🏻  thanks for opening this issue!  Unfortunately I was unable to run the repo you shared.  When I `npm run dev` I get the following error in my terminal: `error - ApolloError: request to http://localhost:5000/piechat failed, reason: connect ECONNREFUSED 127.0.0.1:5000`.  The JS console in the browser shows this output:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/socket.io/?EIO=4&transport=polling&t=ON67_10. (Reason: CORS request did not succeed). Status code: (null).
```

Circling back to the issue at hand, the first place I was hoping to drop a debugger into was your `initializeApollo` function.  I wanted to verify that it was indeed only being called once in the UI lifecycle.

**Comment by siamahnaf198** [comment] 2023-01-18 18:31
This error comes, because I use local api.. but I am not provide backend projects into repo..

**Comment by siamahnaf198** [comment] 2023-01-18 18:33
If you need backend projects also, then please let me know?

**Comment by bignimbus** [comment] 2023-01-19 03:40
@siamahnaf198 thanks for offering, usually a reproduction is orders of magnitude more helpful than code snippets if it can be cloned and run with minimal setup.  So providing something runnable would definitely help reduce the amount of time myself and others need to invest into helping out.  What do you think about my idea RE: `initializeApollo`?

**Comment by siamahnaf198** [comment] 2023-01-19 04:02
But, in backend you need to setup postgres, nestjs, graphql. And you have to create some demo data. On other hand, I cant deploy backend now on cloud due to I do not know how to deploy it as I only learning frontend.

**Comment by siamahnaf198** [comment] 2023-01-19 09:32
Hello, can I get any solutions. Please help me..

**Comment by siamahnaf198** [comment] 2023-01-19 09:34
Here, I think 🤔 the main problem is in deep merge.

**Comment by siamahnaf198** [comment] 2023-01-19 12:14
Hello, @bignimbus, how can I solve this. Please give me further instructions.

**Comment by bignimbus** [comment] 2023-01-23 18:31
Hi @siamahnaf198 👋🏻 

I agree that the cache restoration inside `initializeApollo` might be something to look closer at, but I can't know for sure without being able to run your app.  Try adding a breakpoint there?

Since this is more of a "how do I fix this issue in my app" question and there's no clear action to be taken on the Apollo Client source code, I'm going to close this issue.  Our [discord](https://discord.gg/graphos) is a great place for Q&A with the community and Apollo staff!

**Closed by bignimbus** 2023-01-23 18:31 UTC
Labels: ⁉️ question, 🥓 Server-side rendering (SSR)
