### ISSUE TITLE
Improve warning about addTypename in the case of optimistic response

### ISSUE THREAD

**Issue by kishorevarma** [apollographql/apollo-client#929] opened 2016-11-17 05:57 UTC
Hi ,

I am getting following warning, even though I have added the option in my client, and I am getting __typename in all my fragment query results.

> You're using fragments in your queries, but don't have the addTypename:
true option set in Apollo Client. Please turn on that option so that we can accurately
match fragments.

my client code as follow

```javascript
const client = new ApolloClient({
  networkInterface: createNetworkInterface({ uri: '/graphql' }),
  queryTransformer: addTypename,
  addTypename: true,
  dataIdFromObject: result => {
    if (result.id && result.__typename) {
      return result.__typename + result.id;
    }
    return null;
  }
});
```

am I doing anything wrong ?

**Comment by helfer** [comment] 2016-11-17 09:09
@kishorevarma the warning comes from [here](https://github.com/apollostack/apollo-client/blob/d7d48aeba971a7256d61d242dc2937ec55640268/src/data/readFromStore.ts#L105-L116). It's not clear to me how that could get called if your results all had `__typename` on them, so it would be really useful if you could provide a link to a minimal reproduction of the issue. Please also make sure you have updated to the last version of Apollo Client and react-apollo 🙂 

Btw, you should remove the `queryTransformer` option. It is no longer supported. Just adding `addTypename` should do the trick. I don't think that's what's causing the issue, but it might be.

**Comment by kishorevarma** [comment] 2016-11-17 09:56
Thanks @helfer , I think I found the issue, its because of optimisticResponse  where I am missing the  __typename in the deep fragments. I am removing __typename's inside component before sending to mutation due to mutation error saying __typename is unknown field.  

In my component (its a simple Form) I am sending all the data that I got as a result of query including 
modified form data. it would be better if there is an option that ignores __typename in mutation 
any how its specific to my implementation, thank you

```javascript
props: ({ mutate }) => ({
    saveConnectionDetails: ({ connectionDetails }) => (
      mutate({
        variables: { connectionDetails },
        optimisticResponse: {
          __typename: 'Mutation',
          updateConnection: {
            __typename: 'ConnectionType',
            ...connectionDetails,
            id: '1',
            status: 'Disconnected'
          }
        )
      });
    }
```

**Comment by helfer** [comment] 2016-11-17 13:53
@kishorevarma sorry, I didn't quite follow your explanation. Were you able to find a solution or workaround? If so, is there something we can do to make this easier for people in the future?

**Comment by kishorevarma** [comment] 2016-11-17 22:43
@helfer sorry, I couldn't explained properly,  I will try to explain by giving an example. my application is similar to below example

**Example:** Assume there is a PersonComponent that shows name and gender and skills, and it is editable.

GraphQL query result would be as follow

```javascript
 {
  data: {
    Person: {
      __typeName: 'PersonType',
      name: 'Foo',
      gender: 'Male',
      skills: [{
        name: 'Javascript',
        experience: 'Medium',
        __typeName: 'SkillType'
      }]
    }
  }
}
```
When user adds a new skill assume `GraphQL`,  I am trimming all the __typeName from the query result and appending ` GraphQL' in the skills array and sending back to server using graphql mutation. 

```javascript
const modifiedPersonDetails =  {
  data: {
    Person: {
      name: 'Foo',
      gender: 'Male',
      skills: [{
        name: 'Javascript',
        experience: 'Medium',
      }, {
        name: 'GraphQL',
        experience: 'Beginner'
      }]
    }
  }
}
```

In my optimistic Response I am using as follow assume `PersonMutation` takes `modifiedPersonDetails` as argument

```javascript
 props: ({ mutate }) => ({
  savePersonDetails: ({ modifiedPersonDetails }) => (
    mutate({
      variables: { modifiedPersonDetails },
      optimisticResponse: {
        __typename: 'Mutation',
        updateConnection: {
          __typename: 'PersonType',
          ...modifiedPersonDetails
        }
    )
  });
});
```

there is a problem in above optimistic response I am not adding ` __typename(SkillType)` to skill, due to that its producing the warning.  I couldn't use the same `modifiedPersonDetails`  for both 
mutation and optmisticResponse.

I am not sure whether I am clear this time with the above example, and I hope this is not related to apollo client, may be server side graphql implementation(graphql.js) should accept dynamic fields like __typename in mutation (with out giving an error).

I am closing this ticket

Thanks

**Comment by helfer** [comment] 2016-11-18 10:13
Ah, okay, now I understand. Thanks for explaining! We should see if we can produce a better warning when `__typename` is missing in the optimistic response.

**Comment by codepunkt** [comment] 2016-12-27 22:13
@helfer I'm not sure why the outer __typename in the optimistic response has to exist at all. Aren't all optimistic responses of type `Mutation`? Wouldn't a syntax like this be sufficient?

```javascript
 props: ({ mutate }) => ({
  savePersonDetails: ({ modifiedPersonDetails }) => mutate({
    variables: { modifiedPersonDetails },
    optimisticResponse: {
      __typename: 'PersonType',
      ...modifiedPersonDetails
    }
  });
});
```

**Comment by helfer** [comment] 2017-05-03 18:46
This should be taken care of once #1638 is merged. Going to close this a bit prematurely because I'll definitely forget to do it afterwards...

**Closed by helfer** 2017-05-03 18:46 UTC
Labels: help wanted, usability

**Comment by oolekk** [comment] 2018-05-30 09:09
This warning can also show up if you missed some item in typdefs
