### ISSUE TITLE
[AC v3] - query still requesting the server even when using skip (sometimes)

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client#6572] opened 2020-07-10 20:01 UTC
I have a werid issue when using skip.

I have a query that is called only when a certain condition is met. This is how I'm doing the query

```js
const { data: subAreasData, loading: subAreasLoading } = useSubareasQuery({
    variables: {
      where: {
        areaId: { _eq: area?.id },
        companyId: { _eq: company?.id },
      },
    },
    skip: !area || !company,
  });
```

If I do that, the query is still being made. Even If I force the `skip` to true. `useSubareasQuery` is actually called twice because the values of the variables changes.

The first time, the value of the variables are this 

![image](https://user-images.githubusercontent.com/5973652/87193037-d0769680-c2c5-11ea-9b5b-ca000005f6f7.png)

Then one of the variables changes it's value, but the skip condition still true

![image](https://user-images.githubusercontent.com/5973652/87193083-eab07480-c2c5-11ea-941e-5752ba9d1238.png)

```js
 if (!ref.current || !equal(key, ref.current.key)) { <--- HERE
    ref.current = { key: key, value: memoFn() };
}
```

The `key` is actually not equal to `ref.current.key`

If I instead of doing the above I do this

```js
const skip = !area || !company;
  const subAreasFilters = !skip
    ? {
        areaId: { _eq: area?.id },
        companyId: { _eq: company?.id },
      }
    : {};
  const { data: subAreasData, loading: subAreasLoading } = useSubareasQuery({
    variables: {
      where: subAreasFilters,
    },
    skip,
  });
```

Then it does actually works and skips the network request. 

Should changing the underlying variables object affect the if the request being made?   

Any ideas what could the issue be?

**Versions**
```
System:
    OS: macOS 10.15.5
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
  npmPackages:
    @apollo/client: 3.0.0-rc.12 => 3.0.0-rc.12 
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3 
    apollo-upload-client: ^13.0.0 => 13.0.0 
  npmGlobalPackages:
    apollo-codegen: 0.20.2
```

**Comment by yngwi** [comment] 2020-07-11 10:38
It sounds a little bit similar to issue #6507 that I reported some time ago. There seems to be something really strange going on.

**Comment by tafelito** [comment] 2020-07-13 15:24
@yngwi yes I think they might be related. I think there are 2 different things happening. As I pointed out, the first issue (my not be an issue) is that the first time the code runs, it actually skipped the request, but as soon as the variables changed, even tho the skip it still true, this `!equal(key, ref.current.key))` becomes true and the `memoFn` is executed. That shouldn't be an issue if the skip was not ignored, and that's the 2 part of the issue. I couldn't find anywhere where the skip is actually used

**Comment by KamalAman** [comment] 2020-07-14 20:24
This issue is also referenced in [6190](https://github.com/apollographql/apollo-client/issues/6190). The suggested hack usually works. A very bad bug that keeps breaking many things and destroying the dependability of the library.

**Comment by hwillson** [comment] 2020-07-15 15:15
This should now be fixed in `@apollo/client@3.0.1`(reference: https://github.com/apollographql/apollo-client/pull/6589). Let us know if not - thanks!

**Comment by tafelito** [comment] 2020-07-15 15:59
@hwillson I just tested this with `@apollo/client@3.0.1` and the issue is still there. I think the issue that was fixed on #6589 is quite different than I reported here. 
The skip is ignored when the `useQuery` variables change, even if the skip is still true

Can we please re open this?

**Comment by gztomas** [comment] 2020-07-17 14:14
@hwillson I'm seeing the same issue. This is with `@apollo/client@3.0.2`
![image](https://user-images.githubusercontent.com/1714020/87793049-18903e80-c81b-11ea-94f9-0c8d6557961e.png)
See how `fetchQueryObservable` is called even with `skip: true`. I don't see any check for skip downstream after that.
See how `ObservableQuery.prototype.setOptions` is causing a fetch even though those options have `skip: true`.

Sharing more of what I'm seeing so you can repro:
This equality check is evaluating to false https://github.com/apollographql/apollo-client/blob/a928a1077510f0fb1d6ae18d4e8b1d5c2eb81a36/src/react/data/QueryData.ts#L242-L257

And this is how the options are changing
![image](https://user-images.githubusercontent.com/1714020/87794945-c00e7080-c81d-11ea-8772-edafd0e64de3.png)

I am skipping once the customerId is `undefined`, but `useQuery` fetches with the `undefined` variable anyways.

**Comment by sirugh** [comment] 2020-07-21 15:41
We're running into this as well but with `null` variables.

Is it possible to work around this issue by using lazy query in an effect?
I saw another thread with a suggestion to use `fetchPolicy: skip ? 'cache-only' : YOUR_POLICY`, which seems to work but it's pretty ugly.

**Comment by tafelito** [comment] 2020-07-21 16:45
@sirugh A workaround is to create the variables outside of the useQuery. Check my OP

**Comment by sirugh** [comment] 2020-07-21 16:58
Creating the `skip` argument outside of the object did not work nor did using `useMemo` to memoize it. I am using a `cache-and-network` fetch policy which probably has something to do with it.

**Comment by gandhiamarnadh** [comment] 2020-07-29 19:19
@hwillson the issue still exists (when variables changes) , please re-open this

**Comment by leonardoanalista** [comment] 2020-07-29 22:21
I am on APC 3.0.2 and I can confirm this is still a problem @hwillson @benjamn  

That was the PR: https://github.com/apollographql/apollo-client/pull/6589

**Comment by adrienharnay** [comment] 2020-07-31 13:32
@apollo/client 3.1.1, issue still occurs. Can we reopen this issue? Or should we open a new one?

**Comment by 3nvi** [comment] 2020-07-31 13:34
> @apollo/client 3.1.1, issue still occurs. Could we reopen this issue? Or should we open a new one?

Track it here https://github.com/apollographql/apollo-client/issues/6670#issuecomment-663927304

**Closed** 2020-08-01 14:26 UTC
