### ISSUE TITLE
useLazyQuery, onCompleted/onError, "no-cache"/"network-only", infinite loop.

### ISSUE THREAD

**Issue by itshallrun** [apollographql/apollo-client#6346] opened 2020-05-26 08:48 UTC
**Intended outcome:**
useLazyQuery in combination with onCompleted/onError should execute once.

**Actual outcome:**
Executing useLazyQuery in combination with onCompleted/onError leads to an infinite loop with loading === false.

**How to reproduce the issue:**
[Click here for a Codesandbox example](https://codesandbox.io/s/apollo-client-uselazyquery-example-f54yt?file=/src/Countries.js:309-327)

![useLazyQuery](https://user-images.githubusercontent.com/21173275/82878826-54560880-9f3c-11ea-992d-a5b35224272a.gif)

**Versions**
bug was introduced in  "@apollo/client": "3.0.0-beta.46", 
all versions above are affected by the issue

**Comment by fdev** [comment] 2020-05-26 09:36
Probably the same issue as #6301.

**Comment by hwillson** [comment] 2020-05-26 14:15
Confirmed duplicate of https://github.com/apollographql/apollo-client/issues/6301. We'll track progress in that issue. Thanks!

**Closed by hwillson** 2020-05-26 14:15 UTC

**Comment by joshuarobs** [comment] 2020-09-17 10:55
I got this same error if I have onCompleted as async, calling an async mutation, on apollo client 3.2.0. However, i fixed it by not using async in the onCompleted for the lazy query.
