### ISSUE TITLE
queryDeduplication not working as expected in apollo-client@2.0

### ISSUE THREAD

**Issue by manbropig** [apollographql/apollo-client#2463] opened 2017-11-02 22:20 UTC
**Intended outcome:**

The same graphQL query (same variables and query string), executed by different components on load of the app, should only result in one network request (visible in the network tab). Before upgrading to apollo-client 2.0, we would experience such behavior.

**Actual outcome:**

Now that we have upgraded to apollo-client 2.0 we see a network request for every time we execute a query.

The following code is what we have implemented using apollo-client 2.0 and shows 2 network requests in the network tab. Please note that we are not mentioning `queryDeduplication` since it is supposed to be set to `true` by default:
```
import ApolloClient from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { createHttpLink } from 'apollo-link-http';

import QUERY from 'gql/queries/query.js';

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: createHttpLink({ uri: '/graphql' })
});

client.watchQuery({
  // I've tried every fetch-policy except "cache-only"
  // just to see if any would actually dedup requests
  fetchPolicy: 'cache-and-network',
  query: QUERY,
  variables: { id: 'abcd' }
}).subscribe({
  error: error => {
    throw new Error (error);
  }
});

client.watchQuery({
  fetchPolicy: 'cache-and-network',
  query: QUERY,
  variables: { id: 'abcd' }
}).subscribe({
  error: error => {
    throw new Error (error);
  }
});

```

**Version**
- apollo-client@2.0.1
- apollo-cache@1.0.0
- apollo-cache-inmemory@1.0.0
- apollo-link-http@1.0.0
- graphql@0.11.7
- graphql-tag@2.4.2

Thanks for your help!

**Comment by jbaxleyiii** [comment] 2017-11-06 14:30
@manbropig that's no good! We have tests for this but if you are seeing the issue we clearly aren't testing everything! I'll see about improving those tests, but would you be able to create a reproduction of this?

We have a [template](https://github.com/apollographql/react-apollo-error-template) to make creating these easier

**Comment by manbropig** [comment] 2017-11-06 21:06
@jbaxleyiii here is the reproduction https://github.com/manbropig/react-apollo-error-template/tree/gh-pages/bug/no-query-dedup

**Comment by Wenzil** [comment] 2017-11-08 00:27
@jbaxleyiii Can you give us ETA on when we can expect a fix? 

Asking because it will factor into whether we will include the migration to v2 in our next app release

**Comment by rzane** [comment] 2017-11-09 15:33
I am definitely seeing this bug.

**Comment by malexandre** [comment] 2017-11-12 16:53
I'm also having this problem. I'm currently trying to switch to apollo-client 2 on my company main project, but I can't until this is fixed.

**Comment by jbaxleyiii** [comment] 2017-11-13 16:48
@manbropig  @Wenzil @malexandre this is first up on my bug squashing adventure this week!

Sorry for the delay, after the 2.0 launch + new sites + graphqlsummit, we took a week off at our company for a company wide hack week. I'm back on Apollo this week and am making a few milestones to work through. This is priority number one for me

**Comment by jbaxleyiii** [comment] 2017-11-13 20:31
This should be fixed via https://github.com/apollographql/apollo-link/pull/242

**Comment by jbaxleyiii** [comment] 2017-11-13 20:47
new version of dedup link is release as 1.0.1, I'm going to do a release of AC which removes the hard locked dependencies to make it easy to upgrade parts like this

**Comment by jbaxleyiii** [comment] 2017-11-13 22:34
The 1.0.1 build threw a lot of errors on AC tests, I've removed it for now and will keep this issue open until its fixed

**Comment by jbaxleyiii** [comment] 2017-11-16 00:11
The new dedup link will be part of the next release!

**Closed by jbaxleyiii** 2017-11-16 00:11 UTC
Labels: bug

**Comment by ManuViola77** [comment] 2022-08-08 22:47
I think maybe this is not working again, could it be? At least I feel I have this same problem
