### ISSUE TITLE
defaultOptions fetchPolicy: 'cache-and-network' has no effect

### ISSUE THREAD

**Issue by alicerocheman** [apollographql/apollo-client#9174] opened 2021-12-10 12:13 UTC
**Intended outcome:**
with default fetchPolicy set to 'cache-and-network', a simple useQuery without custom fetchPolicy should send a request to the API.

**Actual outcome:**
no request is sent to the api

**How to reproduce the issue:**
in apollo client config:
```
defaultOptions: {
      watchQuery: {
        fetchPolicy: 'cache-and-network',
      },
    }
```
in react app:
```
const { data } = useQuery(MyQuery)
```
=> no request is sent to the api

**Versions**
  System:
    OS: macOS 11.6.1
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 94.0.2
    Safari: 15.1
  npmPackages:
    @apollo/client: ^3.5.5 => 3.5.5

**Comment by InvisiBug** [comment] 2021-12-16 21:14
I'm also having this problem. 
Im using "@apollo/client": "^3.5.6",

[Here's where I create my client object](https://github.com/InvisiBug/kavanest-client/blob/dev/src/App.tsx#L18)

**Comment by InvisiBug** [comment] 2021-12-16 21:16
Possible duplicate of https://github.com/apollographql/apollo-client/issues/9105#issue-1060740168

**Comment by hwillson** [comment] 2022-01-04 01:35
Closing as a duplicate of https://github.com/apollographql/apollo-client/issues/9105.

**Closed by hwillson** 2022-01-04 01:35 UTC
