### ISSUE TITLE
Apollo not normalising cache items that are written by writeQuerry? (local state management) 

### ISSUE THREAD

**Issue by hwhh** [apollographql/apollo-client#6690] opened 2020-07-23 20:30 UTC
I am using apollo client for local state management, as well as using apollo in the backend. I am also using algolia for searching and want to cache the results returned by algolia. The objects returned by alogia are semantically the same as those returned by apollo in the backend, so I want to have the objects merge and be normalised, however when I use writeQuery the results are not normalised - is this expected and if so is there a way around this?

Here is an example of how I am writing the results to the cache and then reading as on the docs it says "Apollo Client stores the results of its GraphQL queries in a normalized" so wasn't sure if that would get the results to be normalised. 

(Using Apollo client v3.02)

```
client.writeQuery({
  query: searchResultsCached,
  data: {
    searchResultsCached: {
      ...result.hits.map((val) => {
        // console.log(val);
        const _id = val.objectID;
        const copy = _.cloneDeep(val);
        delete copy._highlightResult;
        delete copy.objectID;
        return {...copy, _id: _id, __typename: 'User'};
      }),
    },
  },
});
client
  .query({
    query: searchResultsCached,
  })
  .then((value) => {
    console.log(client.cache);
  });
```

**Comment by benjamn** [comment] 2020-07-23 23:54
Everything written to the cache is normalized by default, and any object with a `__typename` and either `id` or `_id` field should be default-normalizable. If normalization seems not to be happening, that's surprising.

I think I need a more complete example/[reproduction](https://github.com/apollographql/react-apollo-error-template) to diagnose your issue. What do you get from `client.cache.extract()` after writing the initial data?

**Comment by benjamn** [comment] 2020-07-23 23:58
Also, have you tried code like this?
```js
client.writeQuery({
  query: searchResultsCached,
  data: {
    // Maybe searchResultsCached just needs to be an array?
    searchResultsCached: result.hits.map((val) => {
      const copy = _.cloneDeep(val);
      delete copy._highlightResult;
      delete copy.objectID;
      return { ...copy, id: val.objectID, __typename: "User" };
    }),
  },
});
```

**Comment by hwhh** [comment] 2020-07-24 17:51
Hi @benjamn, 

Here is a repo of the issue: https://github.com/hwhh/react-apollo-error-template

In the repo, I also demonstrated that the result isn't merged i.e. the additional incoming fields aren't added to the existing object despite the field being defined in the schema 

The result of `client.cache.extract()` is: 

![image](https://user-images.githubusercontent.com/17745809/88420183-66d6ac00-cdde-11ea-89bd-b967f894e214.png)

I also tried the code you provided but to no avail.

**Comment by hwillson** [comment] 2020-07-24 23:46
Thanks for the reproduction @hwhh. Your `SEARCH_RESULT_CACHED` query doesn't provide a selection set, which is throwing off normalization. If you change it to:

```js
const SEARCH_RESULT_CACHED = gql`
  query searchResultsCached {
    searchResultsCached {
      _id
      name
      someOtherVal
    }
  }
`;
```

you should then end up with:

![Image 2020-07-24 at 7 45 46 PM png](https://user-images.githubusercontent.com/137740/88443428-47dc1800-cde6-11ea-9bf8-149a220a52ef.png)

Since this is working as designed, I'll close this off.

**Closed by hwillson** 2020-07-24 23:46 UTC
Labels: 🏓 awaiting-response
