### ISSUE TITLE
Using window.open causes app to freeze / crash with useQuery and React 16.x

### ISSUE THREAD

**Issue by dannycochran** [apollographql/apollo-client#8427] opened 2021-06-24 22:09 UTC
**Intended outcome:**
When using `window.open` to simulate re-authentication for a user, and the browser then returns to the original window, my app freezes / crashes with no helpful stack trace or obvious infinite loop locations. Removing the usage of "useQuery" fixes the issue in the reproduction repository below, so it's possible that it's an Apollo bug.

However, updating to React 17.0.1 fixes the issue entirely. So it's unclear if this is an Apollo bug or a React bug.

**Actual outcome:**
The app crashes / freezes.

**How to reproduce the issue:**

1. Clone this repository and checkout to `strangeReactBug` branch: https://github.com/dannycochran/usequery/tree/strangeReactBug

2. Open Chrome (not reproducible in Safari)

3. Click "Sign in and sign out", wait for the window to return.

4. Repeat step 2 until the app is crashed.

**Versions**

**Note:** also using React and react-dom 16.14.0. The issue disappears in React 17.0.1

```
  System:
    OS: macOS 11.2.2
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/npm-global/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.3.16 => 3.4.0-rc.14 
    apollo-upload-client: 14.1.3 => 14.1.3 
    apollo3-cache-persist: 0.9.1 => 0.9.1 
  npmGlobalPackages:
    apollo: 2.27.0
 ```

**Comment by brainkim** [comment] 2021-06-28 22:03
Thanks for opening this issue! Brow is mildly furrowed about the fact that this is only happening on 16 and not 17.

**Comment by phryneas** [comment] 2023-12-22 12:37
I believe this should be fixed since it was opened, as we use a completely different subscription mechanism in `useQuery` in newer Apollo Client versions.

Unfortunately, I cannot get the reproduction to run anymore, so I cannot validate it. 

@dannycochran is this still an issue for you, or are you okay with me closing this?

**Comment by dannycochran** [comment] 2023-12-22 16:18
We’ve migrated our apps to React 17 at this point so we no longer experience the issue, probably safe to close but it could still be happening with React 16.

**Comment by phryneas** [comment] 2023-12-22 16:37
Then I'll close it. We can still open it again if someone else starts experiencing this, although I suspect that in that case, it could only be fixed on the React side anyways.

Thank you :)

**Closed by phryneas** 2023-12-22 16:37 UTC
Labels: ⚛️ React-related, 🔍 investigate, 🏓 awaiting-team-response
