### ISSUE TITLE
ApolloError: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal

### ISSUE THREAD

**Issue by rishabhchhaparia** [apollographql/apollo-client#10785] opened 2023-04-19 23:36 UTC
### Issue Description

Facing this issue on starting the application

```
error - ApolloError: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
    at new ApolloError (/Users/rishabh_c/Desktop/React%20Flow/node_modules/@apollo/client/errors/errors.cjs:31:28)
    at /Users/rishabh_c/Desktop/React%20Flow/node_modules/@apollo/client/core/core.cjs:1863:19
    at both (/Users/rishabh_c/Desktop/React%20Flow/node_modules/@apollo/client/utilities/utilities.cjs:1072:53)
    at /Users/rishabh_c/Desktop/React%20Flow/node_modules/@apollo/client/utilities/utilities.cjs:1065:72
    at new Promise (<anonymous>)
    at Object.then (/Users/rishabh_c/Desktop/React%20Flow/node_modules/@apollo/client/utilities/utilities.cjs:1065:24)
    at Object.error (/Users/rishabh_c/Desktop/React%20Flow/node_modules/@apollo/client/utilities/utilities.cjs:1073:49)
    at notifySubscription (/Users/rishabh_c/Desktop/React%20Flow/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/rishabh_c/Desktop/React%20Flow/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/rishabh_c/Desktop/React%20Flow/node_modules/zen-observable/lib/Observable.js:240:7) {
  graphQLErrors: [],
  protocolErrors: [],
  clientErrors: [],
  networkError: TypeError [ERR_INVALID_ARG_TYPE]: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
      at Object.fetch (node:internal/deps/undici/undici:11413:11) {
    code: 'ERR_INVALID_ARG_TYPE'
  },
  extraInfo: undefined,
  page: '/'
}
```

### Link to Reproduction

N/A

### Reproduction Steps

package.json

```
{
  "name": "flowchart",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@apollo/client": "^3.6.9",
    "@neo4j/graphql": "^3.5.1",
    "@reactflow/core": "^11.5.5",
    "@reactflow/node-resizer": "^2.0.1",
    "@types/react-virtualized-auto-sizer": "^1.0.1",
    "apollo-server-micro": "^3.10.0",
    "classnames": "^2.3.1",
    "dante3": "^1.0.8",
    "graphql": "^16.5.0",
    "graphql-import-files": "^1.0.18",
    "graphql.macro": "^1.4.2",
    "memoize-one": "^6.0.0",
    "micro": "^9.3.4",
    "neo4j-driver": "^4.4.6",
    "next": "^12.2.2",
    "react": "^18.2.0",
    "react-arborist": "^1.1.0",
    "react-dom": "^18.2.0",
    "react-feather": "^2.0.10",
    "react-flow-renderer": "^10.3.17",
    "react-icons": "^4.4.0",
    "react-select": "^5.4.0",
    "react-tag-input": "^6.8.0",
    "react-virtualized-auto-sizer": "^1.0.6",
    "sharp": "^0.30.7",
    "tree-model-improved": "^2.0.1",
    "zustand": "^4.3.7"
  },
  "devDependencies": {
    "@types/node": "^18.0.4",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "autoprefixer": "^10.4.7",
    "eslint": "^8.19.0",
    "eslint-config-next": "^12.2.2",
    "postcss": "^8.4.14",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.12",
    "tailwindcss": "^3.1.6",
    "typescript": "^4.7.4"
  }
}
```

**Comment by jerelmiller** [comment] 2023-04-19 23:41
Hey @rishabhchhaparia 👋 

Would you be able to provide a runnable reproduction of this issue? Unfortunately its impossible for us to diagnose what might be the issue here without understanding how you've setup Apollo and what causes this. You can fork our `react-apollo-error-template` as a starting point to either via [GitHub repository](https://github.com/apollographql/react-apollo-error-template) or [CodeSandbox](https://codesandbox.io/s/github/apollographql/react-apollo-error-template).

FWIW, I see [`undici`](https://github.com/nodejs/undici) in your error stack trace, so perhaps there is something incompatible with the way you're fetching data using that library. Again, a reproduction would help us tremendously in order for us to help you. Thanks!

**Comment by sitoftonic** [comment] 2023-04-28 16:54
I also had this issue. It's a problem related to the fetch implementation. The strange part is that it was working a few days ago, so maybe any upgrade from undici server/nextjs is making this to break now.

@rishabhchhaparia To solve the issue, you just need to provide a cross-fetch implementation to the HttpLink like this:

```
import { ApolloClient, InMemoryCache, ApolloQueryResult, createHttpLink } from '@apollo/client';
import fetch from 'cross-fetch';

const link = createHttpLink({
  uri: API_URL,
  fetch,
});

export const gqlClient = new ApolloClient({
  cache: new InMemoryCache(),
  uri: API_URL,
  link,
});
```
This fetch implementation should work in different environments including node and browser.

**Comment by alessbell** [comment] 2023-04-28 17:06
It might be useful to know we also have a starter project for Next.js + Apollo Client for creating reproductions in the future: https://github.com/apollographql/next-apollo-example

Since this looks like an issue external to Apollo Client, I'm going to close this issue. Thanks!

**Closed by alessbell** 2023-04-28 17:06 UTC
Labels: :wilted_flower: needs-reproduction, 🏓 awaiting-contributor-response
