### ISSUE TITLE
 useQuery miss field value when console.log()

### ISSUE THREAD

**Issue by RobinYang11** [apollographql/apollo-client#10338] opened 2022-12-08 02:00 UTC
# In Response Inspector  the field do has value , but when console.log() , the is null !
![image](https://user-images.githubusercontent.com/20513480/206337740-7d66aea4-6d1e-464a-ab96-bfdda3fe8906.png)

**Comment by bignimbus** [comment] 2022-12-08 16:30
Hi @RobinYang11 👋🏻  sorry you're experiencing this.  I'm sure the community can help you narrow down the issue but more info will be necessary.  I recommend sharing a runnable reproduction via [this template](https://github.com/apollographql/react-apollo-error-template/generate) so we can see what you're seeing.  Thanks!

**Comment by jerelmiller** [comment] 2022-12-16 17:39
Hey @RobinYang11 👋!

By chance is the type of `creator` in this case a union type? I stumbled upon https://github.com/apollographql/apollo-client/issues/9965 that mentioned that `possibleTypes` fixes an issue where some data does not come back when trying to pull it from a union type. Try configuring `possibleTypes` to see if that resolves your issue. If not, as @bignimbus said, a reproduction would be really helpful to understand what's happening.

**Comment by jerelmiller** [comment] 2023-01-24 00:40
Hey @RobinYang11 👋 !

I'd advise trying the `possibleTypes` solution mentioned in [this comment](https://github.com/apollographql/apollo-client/issues/10338#issuecomment-1355288377) to see if that helps. Since this issue has been open for a bit, I'm going to go ahead and close this as completed. Let us know if you need additional help in case the solution provided in the comment doesn't help!

**Closed by jerelmiller** 2023-01-24 00:40 UTC
Labels: :wilted_flower: needs-reproduction, ⁉️ question, 🏓 awaiting-contributor-response
