### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-client#1880] opened 2017-07-11 12:03 UTC
Hi guys.

I can see infinity fetch requests when something went wrong with graphql. 
That means when graphql server sent back error or server is not responding.

I am using latest react-apollo and apollo with batched requests.

Here is my stacktrace from sentry
```
RangeError
Maximum call stack size exceeded
~/apollo-client/util/cloneDeep.js in value at line 1:0
~/apollo-client/util/cloneDeep.js in cloneDeep at line 9:0
~/apollo-client/util/cloneDeep.js in cloneDeep at line 3:42
~/apollo-client/util/cloneDeep.js in map at line 3:0
~/apollo-client/util/cloneDeep.js in cloneDeep at line 9:01
~/apollo-client/util/cloneDeep.js in cloneDeep at line 3:42
~/apollo-client/util/cloneDeep.js in map at line 3:0
~/apollo-client/util/cloneDeep.js in cloneDeep at line 9:01
~/apollo-client/util/cloneDeep.js in cloneDeep at line 3:42
~/apollo-client/util/cloneDeep.js in map at line 3:0
~/apollo-client/util/cloneDeep.js in cloneDeep at line 9:0
~/apollo-client/queries/queryTransform.js in doc at line 67:0
~/apollo-client/core/QueryManager.js in transformedDoc at line 602:0
~/apollo-client/core/QueryManager.js in getQueryParts at line 559:0
~/apollo-client/core/ObservableQuery.js in getCurrentQueryResult at line 72:0
~/react-apollo/lib/react-apollo.browser.umd.js in currentResult at line 410:0
~/react-apollo/lib/react-apollo.browser.umd.js in dataForChild at line 448:0
```

**Comment by cesarsolorzano** [comment] 2017-07-12 00:45
I'm quite sure this is a duplicate of #1717. If you have time to fix it, a PR will be welcome! 🙂

**Closed by cesarsolorzano** 2017-07-12 00:45 UTC
