### ISSUE TITLE
The "newly" added read/merge functions from typePolicies are not async like the old local resolvers

### ISSUE THREAD

**Issue by rpopovici** [apollographql/apollo-client#9895] opened 2022-07-08 07:19 UTC
We are trying to migrate from apollo client 2.x to 3.x. One of the challenges we are facing is the fact that the old local async resolves cannot be migrated to the newly added read/merge functions.

Potential solution: make read/merge async.

**Comment by alessbell** [comment] 2023-04-28 20:36
This is a duplicate of https://github.com/apollographql/apollo-feature-requests/issues/383 which contains more discussion/info. Please follow the other issue for updates on this topic, closing.

**Closed by alessbell** 2023-04-28 20:36 UTC
Labels: 🍪 feature-request
