### ISSUE TITLE
Apollo-Boost unable to resolve apollo-client

### ISSUE THREAD

**Issue by tbrooke** [apollographql/apollo-client#3339] opened 2018-04-19 03:23 UTC
**Intended outcome:**
 Initial Compile

**Actual outcome:**

Failed to compile

./node_modules/react-apollo/react-apollo.browser.umd.js
Module not found: Can't resolve 'apollo-client' in '/Users/tmb/msm/bridge-client/node_modules/react-apollo'

**How to reproduce the issue:**
Install with:

npm i apollo-boost graphql react-apollo@beta -S

then start with npm start
App was created with React-create-an app

**Version**
apollo-boost
- apollo-client@<version number>

**Comment by Shamar22** [comment] 2018-07-29 00:04
Run the following command: yarn add apollo-client.

Run the same command for anymore missing modules followed by the modules.  Add a space between each missing module.

**Comment by hwillson** [comment] 2018-08-10 19:56
I must be missing something obvious here, as I'm not quite sure why there are so many upvotes on this issue. Apollo Boost should definitely be able to find Apollo Client, since it's a dependency (and if this wasn't working it would be a major issue, and we'd hear about it from the community everywhere). I'm going to close this issue off, but if anyone is encountering this and is able to provide more details (or a runnable reproduction), that would be helpful. Thanks!

**Closed by hwillson** 2018-08-10 19:56 UTC
