### ISSUE TITLE
[bug] Uncaught (in promise) Error: Network error ApolloError.js:43

### ISSUE THREAD

**Issue by jmarceli** [apollographql/apollo-client#3921] opened 2018-09-15 18:02 UTC
Hi,
Some time ago I posted this issue on [apollo-link-state](https://github.com/apollographql/apollo-link-state/issues/282) but as I look again it seems to be related to apollo-client source code.

Here is a sandbox. Go and click on "Mutate" button.

https://codesandbox.io/s/pprlzol2oj

I would expect it to show some JSON.stringified error state inside page content and not:

```
ApolloError.js:43 Uncaught (in promise) Error: Network error: test
    at new ApolloError (ApolloError.js:43)
    at Object.error (QueryManager.js:217)
    at notifySubscription (Observable.js:130)
    at onNotify (Observable.js:161)
    at SubscriptionObserver.error (Observable.js:220)
```

in the browser console.
The error message is taken from my local dev env to show exact line numbers. The sandbox has a similar message if you open a browser console, just line numbers are meaningless (at least for me).

**In order to reproduce this issue it might be required to refresh browser emulator after entering codesandbox link.**

If there is anything that I'm doing wrong in my code I would be happy to know that. I that case sorry for wasting your time.

**Comment by jasonpaulos** [comment] 2019-07-09 21:20
Hi @jmarceli, thanks for reporting this. There hasn't been any activity here in quite some time, and I'm unable to reproduce the problem, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Closed by jasonpaulos** 2019-07-09 21:20 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage
