### ISSUE TITLE
CurrentFetch is Not a function

### ISSUE THREAD

**Issue by JoymenOpoyi** [apollographql/apollo-client#9587] opened 2022-04-07 18:14 UTC
$currentFetch is not a function. (In 'currentFetch(chosenURI, options)', 'currentFetch is false')
Few days ago everything was working properly in my react native app and then suddenly I get this issue in all of my queries

**Intended outcome:**
to get a data response from the query and the screen get loaded

**Actual outcome:**
![image](https://user-images.githubusercontent.com/94901078/162266753-790c5981-34b8-4e95-80d1-7aa45c095d65.png)
Whenever I run the app and I am getting this error on all the queries which are being fired in the app.

**How to reproduce the issue:**
I am using an IOS Emulator of iPhone X and it doesnt work over there, but strangely in my android device which i run through adb evrything just works fine

**Versions**
System:
    OS: macOS 12.2

  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    npm: 8.2.0 - /usr/local/bin/npm

  Browsers:
    Firefox: 98.0.2
    Safari: 15.3

  npmPackages:
    @apollo/client: ^3.3.6 => 3.5.7

**Comment by Ninad-Opoyi** [comment] 2022-04-07 18:16
yeah yeah same same nice nice

**Comment by VensonOpoyi** [comment] 2022-04-07 18:17
I have the same issue, plss someone provide the solution.

**Comment by Ninad-Opoyi** [comment] 2022-04-07 18:20
Yeah even I am facing the same issue, if you encounter upon any solution to this problem, do respond.

**Comment by JoymenOpoyi** [comment] 2022-04-08 04:37
@benjamn can you take a look?, I saw a previous issue where you had worked on currentFetch

**Comment by evenSosaAkido** [comment] 2022-06-01 17:06
Same error here with react-native. Anyone found a solution?

**Comment by armordog** [comment] 2022-06-01 18:58
fwiw, I have the same problem in node.

I have no idea if this will help for react native.


I included `cross-fetch` in the default HttpLink and it works for me.
It did not work using `node-fetch` which is annoying.

My fix was

```javascript
const fetch = require('cross-fetch');
//....
const client = new ApolloClient({
      cache: new InMemoryCache(),
      link: new HttpLink({
        fetch,
      })
});
```

**Comment by daniel-covelli** [comment] 2022-09-19 23:30
> 

Were you ever able to resolve this?

**Comment by daniel-covelli** [comment] 2022-09-19 23:31
@evenSosaAkido were you ever able to resolve this? Setting fetch is also not working.

**Comment by evenSosaAkido** [comment] 2022-09-20 16:45
@daniel-covelli the issue was resolved in a very unexplicable way for us. I don't know if you use okta. But it tuned out for us that the order we imported the libraries (okta and apollo) caused this error. 

So importing apollo BEFORE okta fixed the issue for us.

Sorry I can't give a better answer

**Comment by daniel-covelli** [comment] 2022-09-21 17:15
@evenSosaAkido yes I believe we are running into the same issue. In our codebase this manifested in our hooks subfolder, by exporting a hook that used @okta before a hook that used @apollo, this error would occur. Weird!

**Comment by alessbell** [comment] 2023-04-18 19:30
👋 If anyone has a runnable reproduction here, or can create one using our RN testbed https://github.com/apollographql/rn-apollo-client-testbed, that would be much appreciated!

**Closed** 2023-05-19 05:20 UTC
Labels: 🏓 awaiting-contributor-response, 🌐 React Native
