### ISSUE TITLE
Apollo Client - Disable window focus refetching

### ISSUE THREAD

**Issue by valentineezeh** [apollographql/apollo-client#10133] opened 2022-09-27 13:15 UTC
I'm creating an app that doesn't need data to be updated often and uses a Legacy API that has a higher response time. The default behavior of Apollo Client is to refetch all queries on window focus. Is there a way to disable this behavior?

**Comment by dylanwulf** [comment] 2022-09-27 14:28
I don't think apollo client has the capability to automatically refetch on window focus.

**Comment by dylanwulf** [comment] 2022-09-27 15:31
You can see here there is an issue to add this functionality which is still open: #9948. So it's not a current capability of apollo client.

**Comment by valentineezeh** [comment] 2022-09-28 09:04
Thanks for your response.

**Comment by jpvajda** [comment] 2022-09-29 21:55
Thanks @dylanwulf I'll close this as a duplicate of #9948. @valentineezeh feel free to put an emoji on that issue as it helps us measure interest in new functionality.

**Closed by jpvajda** 2022-09-29 21:55 UTC
