### ISSUE TITLE
Doesn't allow mutations without arguments

### ISSUE THREAD

**Issue by greduan** [apollographql/apollo-client#1544] opened 2017-04-04 16:00 UTC
**Intended outcome:**

With the following query:

```graphql
mutation acceptTos {
  acceptTos {
    tosAcceptedDate
  }
}
```

I expect an answer from GraphQL server. Using `/graphiql` confirms this is valid schema call.

```json
{
  "data": {
    "acceptTos": {
      "tosAcceptedDate": "2017-01-01"
    }
  }
}
```

**Actual outcome:**

I get error:
```
Error: Must contain a query definition.
    at getQueryDefinition (getFromAST.js:73)
    at QueryManager.watchQuery (QueryManager.js:347)
    at QueryManager.js:386
    at QueryManager.query (QueryManager.js:384)
    at ApolloClient.query (ApolloClient.js:129)
    at graphql.js:12
    at index.js:104
    at index.js:14
    at dispatch (applyMiddleware.js:35)
    at graphql.js:21
```

**How to reproduce the issue:**

I'm only the front end guy, so all I know is that I must try to make a query that contains a mutation that accepts no arguments.

Relevant schema bits:

```graphql
type AcceptTosResult {
  tosAcceptedDate: String!
}

type Mutation {
  acceptTos: AcceptTosResult!
}
```

**Comment by helfer** [comment] 2017-04-04 16:37
Duplicate of #1539. (you need to call `client.mutate` instead of `client.query`).

**Closed by helfer** 2017-04-04 16:37 UTC

**Comment by greduan** [comment] 2017-04-04 18:42
My bad >_<

**Comment by helfer** [comment] 2017-04-04 18:47
No worries! 🙂
