### ISSUE TITLE
Update store after mutation (create) unclear how to handle

### ISSUE THREAD

**Issue by lucfranken** [apollographql/apollo-client#1697] opened 2017-05-12 13:45 UTC
There are a lot of docs but one part seems to be totally unclear on how to approach.

I use GraphCool as backend and React Native as frontend so that's how the names of the queries are setup.

Say I have a list of invoices

- Invoice 1 Paid: true
- Invoice 2 Paid: false

I have 2 queries (I show 2 lists on the screen): All & unpaid

```
query allInvoices {
    allInvoices {
      id
      paid
    }
}
```

```
query allInvoices {
    allInvoices(filter: {paid: false }) {
      id
      paid
    }
}
```

I insert a new invoice:

```
mutation createItemType(
    $name: String!,
    $paid: Boolean,
  ) {
    createInvoice(
      name: $name,
      paid: $paid,
    ) {
       id
       paid
    }
  }
```

I do understand that Apollo is not magic in a sense that it would automatically update my 2 views: all & unpaid. The advice in the documentation at this moment seems to be that I should use: update()

So I do that:

```
@graphql(gql`
  mutation createInvoice(
    $name: String!,
    $paid: Boolean,
  ) {
    createInvoice(
      name: $name,
      paid: $paid,
    ) {
      id,
      paid,
    }
  }
`, {
  name: 'createInvoice',
  options: {
    update: (proxy, { data: { createInvoice } }) => {
      const allInvoicesQuery = gql`
        query allInvoicesQuery {
          allInvoices {
            id
            paid
          }
        }
      `;

      const data = proxy.readQuery({ query: allInvoicesQuery });
      data.allInvoices.unshift(createInvoice);
      proxy.writeQuery({
        query: allInvoicesQuery,
        data
      });
    },
  },
})
```

The problem: The All invoices list will get updated. The one with the paid filter does not.

It's totally unclear how to get this right. I even tried adding variables to the writeQuery and readQuery but it just doesn't seem to work out. The simple examples in the tutorials DO work but it seems the more complex cases don't.

Questions: 
1. Where to find correct examples about real-life situations where you do filter data?
2. Is all of this code really needed? It's a bug amount of code (I have many more fields) for just a create statement?

**Comment by saudpunjwani101** [comment] 2017-05-14 09:55
in my case the update function doesn't gets called.

**Comment by lucfranken** [comment] 2017-05-18 13:24
Got some interesting feedback on Slack which I think should be added:
https://apollographql.slack.com/archives/C0Z9ZBDF0/p1495109398114586

As far as I understand for now I would have to do this part for EVERY query?

```
    const data = proxy.readQuery({ query: allInvoicesQuery });
      data.allInvoices.unshift(createInvoice);
      proxy.writeQuery({
        query: allInvoicesQuery,
        data
      });
```

So every time I do a query on the same nodes I would have to change all update calls? So all code becomes strongly dependent on each other? That makes all code hardcoded connected?

For example: In my "View account" component I cannot see my total amount of unpaid invoices unless I hardcode a writeQuery in my invoices list to update that component?

**Comment by jaydenseric** [comment] 2017-05-19 09:09
Not a "proper" solution, but I have given up on attempting smart cache busting after running mutations. I just decorate the component with `withApollo` and in the mutation success callback run `this.props.client.resetStore()`. Mutations don't happen *that* often, so it's not too bad that users have to refetch everything; in my app it adds less than a second.

**Comment by lucfranken** [comment] 2017-05-19 10:07
While totally agreeing that this should not be needed it sounds like a very simple and effective fix for the time being!

**Comment by jurajkrivda** [comment] 2017-05-23 22:47
You can get all the invoices and then filter those that are paid. Then you can use the mutation recommended above with readQuery and writeQuery helpers.

**Comment by lucfranken** [comment] 2017-06-02 07:01
Thanks for the feedback @jurajkrivda ! 

I think if I understand you well:

      const data = proxy.readQuery({ query: allInvoicesQuery });

      data.allInvoices.push(createInvoice);
      proxy.writeQuery({
        query: allInvoicesQuery,
        data
      });

      // Then manually filter that array by paid = true and write it to 
      // allInvoices(filter: {paid: true })

      // Then manually filter that array by paid = false and write it to 
      // allInvoices(filter: {paid: false })

That's the logic? While I would hope that it seems duplicated logic (I already wrote that query) and very cumbersome if you get additional parameters as it will become a matrix? 

Let's say I have 3 boolean parameters that's already 2 * 2 * 2 = 8 manual filters I have to implement to update the data? If I have more it becomes a huge amount?

**Comment by lucfranken** [comment] 2017-07-17 05:13
@probot-stale[bot] actually this issue is still open and wondering whether there are any new strategies which have been developed recently.

**Comment by ctavan** [comment] 2017-07-17 14:36
@lucfranken first of all I believe that this is a duplicate of (or at least related with) https://github.com/apollographql/react-apollo/issues/708

In fact I ran into exactly the same issue and ended up calling _all_ queries in the `update` hook with all parameters as you describe. This is particularly bad since you don't really know which of all those queries are already in the store and actually need an update. So after an update you end up with a store that is much large than what would often be necessary.

I was hoping that I could at least simplify my case by using `refetchQueries` which would be a little less radical than resetting the entire store as suggested by @jaydenseric. When using `refetchQueries` with _just_ the query name it _should_ actually refresh all queries with a given name in the store, irrespective of the variables/parametrizations. Unfortunately it currently doesn't work as expected due to a race-condition which I have reported in: https://github.com/apollographql/apollo-client/issues/1821

So for now I'm stuck with the repeated store updates which works but really adds a lot of logic and code while I would find a simple refetch of all queries that are already in the store to be a good compromise between maintainability and client-side performance.

**Comment by lucfranken** [comment] 2017-07-24 09:14
@ctavan yes party it's related but this issue actually was created based on the recommendations in the documentation that the refetchQueries would be deprecated. Input from the Apollo team on the right direction is needed.

**Comment by pawsong** [comment] 2017-08-19 15:35
It would be helpful if there is a API like `readQueries` which returns all cached parameters of a parameterized query. Then I can manually update each query caches. My 2 cents :)

**Closed** 2017-09-23 17:07 UTC
Labels: no-recent-activity

**Comment by aunnnn** [comment] 2017-10-05 11:58
Hi, is there any updates on this issue? 

So now I have to either:
1. use 'refetchQueries' or,
2. use 'update' to update the store for all related queries,

Is that right?

**Comment by lucfranken** [comment] 2017-10-05 12:01
@aunnnn this issue got closed automatically. Asked about that here: https://github.com/apollographql/apollo-client/issues/1910 

As I wrote months ago:

> Input from the Apollo team on the right direction is needed.

No idea why there is no answer.

**Comment by adavia** [comment] 2018-01-03 20:06
I had experience a situation like this where i needed to update an item from a filtered list and i handled it using the componentWillReceiveProps lifecycle method.

Example

```
componentWillReceiveProps(newProps) {
    const { allInvoices, loading } = newProps.data;

    if (!loading) {
      const invoices = _.intersectionBy(allInvoices, this.state.invoices, 'id');
      this.setState({ invoices });
    }
  }
```

**Comment by Vitiell0** [comment] 2018-01-23 20:29
@jbaxleyiii I am still having this problem too. You 👍  the issue I posed back in September but it doesn't look like there is a solution yet. https://github.com/apollographql/react-apollo/issues/992

There doesn't seem to be a good way to access query variables in update after making a mutation. I have been stuck with manually retrieving query variables to update the apollo store for months and was hoping it would be fixed with Apollo 2.0. 

I like the idea @pawsong had for `readQueryWithVariables` where apollo would pull the variables that were used in the last query. It doesn't make sense that we have to manually extract them all. 

Here's what's happening when we have a large number of filter's included with the query that the mutation is trying to update. 😢 

(manually pulling query variables from the ROOT_QUERY)
![screen shot 2018-01-23 at 2 15 42 pm](https://user-images.githubusercontent.com/6282321/35298586-3edd926a-0048-11e8-8517-006b852bd50c.png)

Please let us know if we have missed something or what the plans are to fix this.

**Comment by Vitiell0** [comment] 2018-01-25 18:22
If anyone is still running into this problem, we have found a solution. Just pass the variables with submit and they will be available in update. 

![screen shot 2018-01-25 at 12 20 09 pm](https://user-images.githubusercontent.com/6282321/35404971-5047c5a6-01ca-11e8-9270-8ec1f2e25604.png)

**Comment by minardimedia** [comment] 2018-04-12 20:04
Why the Apollo team is ignoring this. It is a to common problem and they are no doing anything about it. Their may be maybe a way but there is nothing document about it really dissapointing

**Comment by lucfranken** [comment] 2018-04-17 13:30
It seems that refetchQueries is not deprecated anymore. All docs are shuffled around so it's not easy to find back the early mentions of this but it seems changed in the docs.

**Comment by DarKDinDoN** [comment] 2018-04-20 15:56
How am I supposed to know which argument I should use with refetchQueries ? refetchQueries doesn't seem to be solution either ...

**Comment by DarKDinDoN** [comment] 2018-06-04 12:31
@renato yes but am I supposed to know which argument I should provide to the query ? Especially, when the parameters are dynamic.

**Comment by renato** [comment] 2018-06-04 14:23
No, using strings. those queries will be refetched using their **current variables** - which may solve some situations.

I'll probably use it whenever possible or do some kind of cache invalidation (ideas on #621 #899) otherwise.

**Comment by minardimedia** [comment] 2018-06-08 00:40
@DarKDinDoN  I try it all I get your point their is no way you can know all the multiple dynamic queries that are being generated by the users. I still don't know why if is such a common thing they don't provide a way to refetch ALL. 

Anyway if works for something my solution was to Flush the whole cache, I know it's not a nice solution but works for me since I don't expect user will be adding and removing to much elements anyway. Also cache refresh more often that we think like for example if users recharge the page so it is no that big o a deal.

Here is how can you implement this.

`
import { withApollo } from 'react-apollo';

export default withApollo(YOURCOMPONENT);

//this will give you access to the client as a prop so inside your component, after the add or delete action you just call

this.props.client.resetStore();
`

**Comment by acomito** [comment] 2018-06-17 13:50
@minardimedia one issue I have with resetStore is it includes reseting my auth/user, which causes mayhem in apps that have an "authenticated" area (where user would get kicked back to login or content would flicker).

**Comment by minardimedia** [comment] 2018-06-18 23:53
Hi @acomito I just came to know about this repo apparently it works for this issue, I haven't try it but you can take a look at it (apollo-link-watched-mutation) https://github.com/haytko/apollo-link-watched-mutation

**Comment by yashwp** [comment] 2018-07-10 13:07
I'm working with this in apollo-angular - 
`
// QUERIES
export const ALL_COURSES = gql`
  query allCourses {
    allCourses {
      id
      author
      title
      url
    }
  }
`;

export const CREATE_COURSE = gql`
  mutation createCourseMutation($description: String!, $title: String!, $author: String!, $url: String!) {
    createCourse(
      description: $description,
      url: $url,
      title: $title,
      author: $author,
    ) {
      description
      url
      title
      author
    }
  }
`;

//Object which is posted
this.newCourse = {
      title: f.value.title,
      author: f.value.author,
      description: f.value.description,
      url: f.value.url
    };

this.apollo.mutate({
      mutation: CREATE_COURSE,   // creation query
      variables: this.newCourse,  // the data object you want to save
      update: (store, {data: {createCourse}}) => {   // "store" is the cache storage object, "createCourse" the new course object which is created after the "CREATE_COURSE" query successfully runs
          const data = store.readQuery({query: ALL_COURSES}); // Reading all the previous data
          data.allCourses.push(createCourse); // Pushing new data into the array of objects of courses
          store.writeQuery({query: ALL_COURSES, data}); // writing back the updated data in "store"
      }
    }).subscribe();`


I hope that helped you. :)

**Comment by DarKDinDoN** [comment] 2018-07-10 14:04
@yashwp thanks, your example covers a very simple example. Try it when ALL_COURSES has many filters/parameters.
Y'll that it is not scalable to cover every QUERY and their parameters by hand.

**Comment by vitaliy-ostapchuk93** [comment] 2019-06-03 19:43
@yashwp Thanks! Tried it out on my own models and it works! very simple and nice code :)

**Comment by expelledboy** [comment] 2019-10-04 06:18
Why is this still marked as closed? Clearly there hasnt been a satisfactory resolution to this issue. Can we disable the bot for this issue?

**Comment by MaxmaxmaximusGitHub** [comment] 2020-06-13 22:43
sooooo?

**Comment by mikeRChambers610** [comment] 2020-08-28 03:04
?????

**Comment by awlevin** [comment] 2020-12-03 16:05
Chiming in, but without a solution. Agree with the rest of you that mutation insertions on cached + paginated + sorted queries feels like a pretty common use-case, and it would be wonderful to see a more formal solution for this in Apollo.

**Comment by mindnektar** [comment] 2021-06-03 15:08
I've created a package in an attempt to solve these issues and make complex cache updates as painless as possible. https://www.npmjs.com/package/apollo-augmented-hooks

See https://www.npmjs.com/package/apollo-augmented-hooks and the linked caching guide in particular.

I've been using this in production for a while now and just made it open source so other people can benefit from it as well.
