### ISSUE TITLE
Unable to get cookies in requests

### ISSUE THREAD

**Issue by dawudarif** [apollographql/apollo-client#11106] opened 2023-07-27 15:52 UTC
I'm using this code to set up my nextJS app with apollo graphql,

`const client = new ApolloClient({uri: 'http://localhost:4000/graphql',cache,credentials: 'include',});`

But the issue is that im getting the cors error even when ive set it up in my backend. The cors error appears only in the network tab and not in the console. The code works when i don't use the credentials option. I've also tried this,

`const httpLink = new HttpLink({uri: 'http://localhost:4000/graphql',credentials: 'include',});const client = new ApolloClient({cache,link: httpLink,});`

I've looked up the documentation and everything but it just won't work with the credentials option in the configuration.

**Comment by jerelmiller** [comment] 2023-07-27 20:14
Hey @dawudarif 👋 

`HttpLink` uses plain `fetch` under the hood and forward most of these options directly to it. Can you try plain `fetch` and see if you're still running into the same issue? `HttpLink` makes a request roughly equal to the following:

```ts
import { print } from 'graphql';

const query = gql`
  query MyQuery { ... }
`;

fetch(uri, {
  method: 'POST',
  headers: {
    accept: '*/*',
    'content-type': 'application/json'
  },
  credentials: 'include',
  body: JSON.stringify({
    query: print(query),
    operationName: 'MyQuery', // replace with the operation name in the query you send
  })
})
  .then(res => res.json())
  .then(result => console.log(result))
```

See if you're still seeing issues with your request. If so, there might need to be some work on the server end to make this work in the browser as there is nothing Apollo Client itself can do to remedy this. Let me know what you find!

**Comment by dawudarif** [comment] 2023-07-28 05:44
> Hey @dawudarif 👋
> 
> `HttpLink` uses plain `fetch` under the hood and forwards most of these options directly to it. Can you try plain `fetch` and see if you're still running into the same issue? `HttpLink` makes a request roughly equal to the following:
> 
> ```ts
> import { print } from 'graphql';
> 
> const query = gql`
>   query MyQuery { ... }
> `;
> 
> fetch(uri, {
>   method: 'POST',
>   headers: {
>     accept: '*/*',
>     'content-type': 'application/json'
>   },
>   credentials: 'include',
>   body: JSON.stringify({
>     query: print(query),
>     operationName: 'MyQuery', // replace with the operation name in the query you send
>   })
> })
>   .then(res => res.json())
>   .then(result => console.log(result))
> ```
> 
> See if you're still seeing issues with your request. If so, there might need to be some work on the server end to make this work in the browser as there is nothing Apollo Client itself can do to remedy this. Let me know what you find!

I've tried this code it works and it send the cookies as well. I get the required query results.

**Comment by jerelmiller** [comment] 2023-07-28 07:37
Since you know that plain `fetch` is working, the next thing you might try is overriding the [`fetch` function](https://www.apollographql.com/docs/react/api/link/apollo-link-http#customizing-fetch) on `HttpLink` so you can log the options before passing it to `fetch`. This should hopefully reveal the difference between what you're sending in your app and the plain `fetch` you tried before.

```ts
new HttpLink({ 
  uri: '...',
  fetch: (uri, options) => {
    console.log(uri, options);
    return fetch(uri, options);
  }
});
```

**Comment by dawudarif** [comment] 2023-07-28 07:46
> Since you know that plain `fetch` is working, the next thing you might try is overriding the [`fetch` function](https://www.apollographql.com/docs/react/api/link/apollo-link-http#customizing-fetch) on `HttpLink` so you can log the options before passing it to `fetch`. This should hopefully reveal the difference between what you're sending in your app and the plain `fetch` you tried before.
> 
> ```ts
> new HttpLink({ 
>   uri: '...',
>   // ...other options
>   fetch: (uri, options) => {
>     console.log(uri, options);
>     return fetch(uri, options);
>   }
> });
> ```

```
uri:

  'http://localhost:4000/graphql'
 options:
body : "{\"operationName\":\"MyQuery\",\"variables\":{},\"query\":\"query MyQuery {\\n  tasks {\\n    id\\n    text\\n    __typename\\n  }\\n}\"}"
credentials : 
"include"
headers
: 
{accept: '*/*', content-type: 'application/json'}
method
: 
"POST"
signal
: 
AbortSignal
aborted
: 
true
onabort
: 
null
reason
: 
DOMException: signal is aborted without reason at eval (webpack-internal:///(app-client)/./node_modules/@apollo/client/link/http/createHttpLink.js:150:32) at cleanupSubscription (webpack-internal:///(app-client)/./node_modules/zen-observable-ts/module.js:92:7) at notifySubscription (webpack-internal:///(app-client)/./node_modules/zen-observable-ts/module.js:153:41) at onNotify (webpack-internal:///(app-client)/./node_modules/zen-observable-ts/module.js:180:3) at SubscriptionObserver.error (webpack-internal:///(app-client)/./node_modules/zen-observable-ts/module.js:233:5) at handleError (webpack-internal:///(app-client)/./node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.js:152:67) at eval (webpack-internal:///(app-client)/./node_modules/@apollo/client/link/http/createHttpLink.js:147:123)
stack
: 
(...)
code
: 
20
message
: 
"signal is aborted without reason"
name
: 
"AbortError"
get stack
: 
ƒ ()
length
: 
0
name
: 
""
arguments
: 
[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28)]
caller
: 
[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28)]
[[Prototype]]
: 
ƒ ()
[[Scopes]]
: 
Scopes[0]
set stack
: 
ƒ ()
length
: 
1
name
: 
""
arguments
: 
[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28)]
caller
: 
[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28)]
[[Prototype]]
: 
ƒ ()
apply
: 
ƒ apply()
arguments
: 
(...)
bind
: 
ƒ bind()
call
: 
ƒ call()
caller
: 
(...)
constructor
: 
ƒ Function()
length
: 
0
name
: 
""
toString
: 
ƒ toString()
Symbol(Symbol.hasInstance)
: 
ƒ [Symbol.hasInstance]()
get arguments
: 
ƒ ()
set arguments
: 
ƒ ()
get caller
: 
ƒ ()
set caller
: 
ƒ ()
[[FunctionLocation]]
: 
[[Prototype]]
: 
Object
[[Scopes]]
: 
Scopes[0]
[[Scopes]]
: 
Scopes[0]
[[Prototype]]
: 
DOMException
[[Prototype]]
: 
AbortSignal
[[Prototype]]
: 
Object
``` This is what i get in the console

**Comment by jerelmiller** [comment] 2023-07-28 07:48
This looks a bit weird given there is an abort signal that was aborted. What version of `@apollo/client` are you using?

**Comment by dawudarif** [comment] 2023-07-28 07:51
> This looks a bit weird given there is an abort signal that was aborted. What version of `@apollo/client` are you using?

i'm using  `"@apollo/client": "^3.7.17",`

**Comment by jerelmiller** [comment] 2023-07-28 07:58
At this point its really difficult to understand what's going on without a reproduction of the issue that we can dig into. Can you create a minimal reproduction for us so we can determine what is happening? You can use our [error template](https://codesandbox.io/s/github/apollographql/react-apollo-error-template) as a starting point, or alternatively send us a [Replay](https://docs.replay.io/workflows/recording-bug-reports). If you end up recording a Replay and aren't comfortable sharing the URL in this issue, feel free to email it to me at jerel.miller@apollographql.com.

**Comment by dawudarif** [comment] 2023-07-28 11:11
> At this point its really difficult to understand what's going on without a reproduction of the issue that we can dig into. Can you create a minimal reproduction for us so we can determine what is happening? You can use our [error template](https://codesandbox.io/s/github/apollographql/react-apollo-error-template) as a starting point, or alternatively send us a [Replay](https://docs.replay.io/workflows/recording-bug-reports). If you end up recording a Replay and aren't comfortable sharing the URL in this issue, feel free to email it to me at [jerel.miller@apollographql.com](mailto:jerel.miller@apollographql.com).

This is the link to repository https://github.com/dawudarif/todo-app

**Comment by bignimbus** [comment] 2023-07-28 14:48
Hi @dawudarif 👋🏻  I tried installing the dependencies and running your repo but the following error occurs:

```
/Users/jeffauriemma/temp-repos/todo-app/server/node_modules/mongoose/lib/connection.js:804
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
```

Unfortunately I can't invest the time to get it to run, let me know if there's a simple way to get unblocked.  Thanks a bunch!

**Comment by dawudarif** [comment] 2023-07-28 14:54
> Hi @dawudarif 👋🏻  I tried installing the dependencies and running your repo but the following error occurs:
> 
> 
> 
> ```
> 
> /Users/jeffauriemma/temp-repos/todo-app/server/node_modules/mongoose/lib/connection.js:804
> 
>     throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
> 
>           ^
> 
> 
> 
> MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
> 
> ```
> 
> 
> 
> Unfortunately I can't invest the time to get it to run, let me know if there's a simple way to get unblocked.  Thanks a bunch!

Its the authentication logic that works only when a database is connected. And I was still working on authentication logic when the error occurred so its the only thing that might work.

**Comment by bignimbus** [comment] 2023-07-31 13:52
Ok thanks @dawudarif - I'm running your app and applied the following changes.  I hope it helps unblock things, if not please let me know the expected vs. actual behavior:

```diff
diff --git a/client/app/components/Providers.tsx b/client/app/components/Providers.tsx
index d2647a1..0b1261c 100644
--- a/client/app/components/Providers.tsx
+++ b/client/app/components/Providers.tsx
@@ -32,7 +32,11 @@ const client = new ApolloClient({
     credentials: 'include',
     fetch: (uri, options) => {
       console.log(uri, options);
-      return fetch(uri, options);
+      return fetch(uri, {
+        ...options,
+        credentials: "include",
+        mode: "same-origin",
+      });
     },
   }),
 });
diff --git a/server/src/app.js b/server/src/app.js
index 50e2969..7a47d63 100644
--- a/server/src/app.js
+++ b/server/src/app.js
@@ -26,7 +26,7 @@ const server = new ApolloServer({
 });
 
 const main = async () => {
-  await connectDB();
+  // await connectDB();
 
   const { url } = await startStandaloneServer(server, {
     listen: { port: PORT },

```

**Comment by dawudarif** [comment] 2023-08-01 10:08
@bignimbus I've tried the changes you made but the code doesn't work and it still gives me the same error. It apparently gives me the same error whenever i use `credentials:'include'` otherwise it works.

**Comment by bignimbus** [comment] 2023-08-01 11:36
What does "it works" mean? What is the outcome in your sample app?

**Comment by dawudarif** [comment] 2023-08-01 11:40
It means that it fetches the data correctly from a simple query when i don't use the credentials option but I need the credentials to work too for authentication purposes.

**Comment by bignimbus** [comment] 2023-08-01 12:54
Ok how do I reproduce that without a database connection in the example given?

**Comment by dawudarif** [comment] 2023-08-01 13:33
The database connection is for storing users, just don't use it if you have another way of testing cookies. 

You can delete the files that require database connection. And if you've a way to create and send cookies over Graphql you're good to go for this problem.

**Comment by bignimbus** [comment] 2023-08-03 03:28
Hi @dawudarif - FWIW there's nothing in Apollo Client that's stripping cookies out of network requests.  Since you're able to get plain `fetch` working and Apollo Client uses `fetch` under the hood, you should be able to pass the same options there to get the same outcome.  See our [customizing fetch](https://www.apollographql.com/docs/react/api/link/apollo-link-http/#customizing-fetch) docs for more info.  Since there isn't a bug here for the maintainers to handle I'm going to close this but if you're in need of further support, please consider joining our [Discord](https://discord.gg/graphos) server and starting a thread in the `#frontend` channel 🙏🏻

**Closed by bignimbus** 2023-08-03 03:28 UTC
Labels: :wilted_flower: needs-reproduction, 🔍 investigate
