### ISSUE TITLE
Expose a way to turn off referential equality checking

### ISSUE THREAD

**Issue by Poincare** [apollographql/apollo-client#1242] opened 2017-01-30 15:51 UTC
I've been benchmarking how long it takes Apollo Client to read n items out of the cache with and without referential equality checking (added in #1136). Here are some of the results: 

![plot](http://i.imgur.com/YcbuLVv.png)

I'm sorry for the lack of a legend and error bars! There are two important lines here. The blue one is Apollo Client cache read times with referential equality checking (REC) and the pink one is with REC. As you can see there is a ~14ms difference for larger numbers of reads with and without REC.

Since REC is great for preventing React re-renders and makes `shouldComponentUpdate` easy to implement, I think we should keep it around, but, there should be an option to turn it off for users that care deeply about cache read performance (e.g. #1240).

Note: there's still significant constant cost associated with reading out of the cache with a simple query that should be investigated further but this feels like a step in the right direction.

**Comment by calebmer** [comment] 2017-01-30 16:31
REC should add no cost if a `previousData` object was not provided, effectively turning it off.

Can I see the exact tests you used? My first reaction is that this is an implementation bug because REC (even when enabled) should only add significant cost in specific situations, and we may be able to optimize those specific situations (I’m mainly thinking of out-of-order arrays).

**Comment by Poincare** [comment] 2017-01-30 16:35
It is definitely possible that REC isn't zero cost even if the previousResult object is empty because it calls functions that return immediately but are still called on every iteration of the loop. It could be an implementation bug within the benchmark, however; here's the benchmark: https://github.com/apollostack/apollo-client/pull/1159/files#diff-3bc6ae5cd90dcd8b2db974e94c8b8ca6R250

(Note: the count index was changed between tests; the implementation of the benchmark remained the same)

**Comment by wmertens** [comment] 2017-01-30 17:48
How about treating the 90% case by keeping a reference to the whole store on each active query, so that if the store hasn't changed, none of the query logic needs to run?

**Comment by helfer** [comment] 2017-01-30 21:53
@wmertens we already do that.

**Comment by wmertens** [comment] 2017-01-30 21:57
OK that's really odd - in my app, the components that use @graphql are part
of a bigger component that rerenders based on some props, but the props for
the @graphql components do not change. The refs for the gql query stay the
same, the string variable stays the same and the apollo part of the store
does not change; the elements are simply created again with the same props.

So if all the inputs to @graphql remain the same, why is it doing some very
heavy calculations?

**Comment by calebmer** [comment] 2017-01-31 01:28
@wmertens currently Apollo re-reads your query from the store whenever a write happens anywhere in the system. So an optimistic mutation, mutation result, or subscription result to name a few. This is so that we can make sure that if any data in your system has been updated then your component knows about the new data.

In the future, we may implement dependency tracking so that we don’t have to re-read on every action.

**Comment by stubailo** [comment] 2017-01-31 05:17
It could be that the components that use GraphQL inside your bigger component are actually being torn down and re-rendered, so they act as if they are appearing for the first time?

**Comment by wmertens** [comment] 2017-01-31 06:07
For sure there are no writes happening to the Apollo part of the store. I'm
sharing my own Redux store to have greater visibility in events.

The components are also not torn down.

**Comment by calebmer** [comment] 2017-01-31 14:31
@wmertens are arbitrary Redux actions being dispatched in your shared store?

**Comment by wmertens** [comment] 2017-01-31 16:04
@calebmer yes, but not always. If I just change some internal state of the parent component, causing it to rerender without changing query parameters or touching the store, I still get a bunch of apollo actions:

![image](https://cloud.githubusercontent.com/assets/54934/22472666/9c7ab80c-e7d6-11e6-8b48-0a0f99b26285.png)

In this case, I have only one `@graphql` child component for details and then one `@graphql` on the parent component for the list of items. Rerendering the parent results in both queries being invalidated and re-run with the same results.

Actually, some further testing shows that if I re-render an intermediate parent, it only updates the query for the detail component, and if I dispatch unrelated actions, the queries don't re-run.

So it seems that the query is being invalidated not because of the store changing, but because of the re-rendering with the same props.

**Comment by helfer** [comment] 2017-02-03 02:28
@wmertens do you think you could distill that down to a minimal reproduction? That would make it much easier to find out what the underlying problem is.

**Comment by wmertens** [comment] 2017-02-03 10:56
@helfer @Poincare Argh, a thousand apologies, this was a case of PEBCAK. I was creating an intermediate component on almost every render, causing the components to unmount and remount.

So now it is much faster and only re-requests when it has to, when existing data is needed again and the component is mounted with the relevant prop. Not sure if referential equality checks help in that case?

Again, apologies 🙇

**Comment by Poincare** [comment] 2017-02-04 15:48
I think @wmertens 's issue that the problem that this Github issue describes are totally distinct at this point so we should probably continue that discussion in another issue?

**Comment by helfer** [comment] 2017-02-04 22:07
@wmertens no worries, it happens to all of us. I'm glad it's faster now!

@Poincare yes, let's close this issue until we know for sure what the lowest hanging fruit is. I suspect it's not referential equality checking.

**Closed by helfer** 2017-02-04 22:07 UTC
Labels: perf

**Comment by Poincare** [comment] 2017-02-04 22:42
Hmm... I'm not sure if we should close the issue. Although REC isn't what @wmertens' issue ended up being, it's pretty clear from the benchmarks that REC does impose a reasonably significant cost (@calebmer mentioned it may be an implementation issue?) and I think it makes sense to keep the issue open until we either fix the REC implementation issue if it exists or determine that it is too small of a perf improvement to add an option to AC. In the meantime, I think the issue can should serve as a placemarker for an issue we should look into.

**Comment by helfer** [comment] 2017-02-05 00:16
@Poincare I agree that we shouldn't stop the conversation about REQ, but I would prefer to have an umbrella issue for benchmarks and performance improvements so we can weigh the different options there.

**Comment by Poincare** [comment] 2017-02-05 01:47
Sounds good to me!
