### ISSUE TITLE
Error: cache-and-network fetchPolicy can only be used with watchQuery

### ISSUE THREAD

**Issue by wzup** [apollographql/apollo-client#3880] opened 2018-09-04 16:43 UTC
Any update on that?
https://github.com/apollographql/apollo-client/issues/3130

> Error: cache-and-network fetchPolicy can only be used with watchQuery

**Comment by roisafirorichard** [comment] 2018-12-28 21:17
having same issue with `this.props.client.query`

**Comment by joelgetaction** [comment] 2019-02-06 01:06
Bump.  This is a serious issue for us and is preventing us from using Apollo properly ... Can somebody on the Apollo team please take a look at this?

Your documentation for `query` clearly states that `cache-and-network` ***is*** a valid value for this method, as per https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-fetchPolicy and https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.query .  However, your master source is clearly throwing an error here https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts#L283

Hey @hwillson any chance we can get some help with this?  Or @peggyrayzis ?  This is pretty urgent ... :-)

Thanks!

**Comment by oxbits** [comment] 2019-02-11 01:55
i am also having this issue, has anything changed?  is there a work around?

**Comment by zhangjing28** [comment] 2019-02-15 10:30
same issue +1

**Comment by EwanValentine** [comment] 2019-02-15 12:03
Same issue also +1.

**Comment by maziarz** [comment] 2019-02-18 09:30
Same here. `network-only` is really bad for optimistic UI.

**Comment by HummingBird24** [comment] 2019-02-21 21:38
Same issue +1

**Comment by ZikDead** [comment] 2019-02-23 09:11
Same issue +1

**Comment by mythfish** [comment] 2019-02-23 15:09
Same issue +1

**Comment by alexandrecanuto** [comment] 2019-02-25 18:31
Same issue +1

**Comment by yadianf** [comment] 2019-02-26 15:29
same issue +1 :(

**Comment by EwanValentine** [comment] 2019-02-26 16:12
I found you can use `watchQuery`, like the error suggests. Which works similarly to `query` anyway. But it'll let you do `cache-and-network` too.

**Comment by bahaa-al-deen** [comment] 2019-03-14 09:27
same issue

**Comment by dustinbrink** [comment] 2019-03-22 21:40
same issue +1

**Comment by rares-lupascu** [comment] 2019-03-28 19:10
same issue 👍  ... wtf :/

**Comment by Guiradi** [comment] 2019-03-29 01:56
Same issue +1

**Comment by PowerKiKi** [comment] 2019-04-01 01:23
@wzup please close this issue as it is an exact duplicate of #3130, which you mentioned yourself. The discussion should not be spread across different threads.

**Closed** 2019-04-30 17:46 UTC
Labels: 👯‍♂️ duplicate

**Comment by kismib** [comment] 2020-09-24 10:14
using this work for me
options: () => ({
   fetchPolicy: 'cache-and-network'
 })

**Comment by igorthurow** [comment] 2021-05-27 18:11
Thanks @kismib! Better than use `watchQuery` for my scenario.

**Comment by tarasov-gk** [comment] 2021-07-08 08:02
+ 1

**Comment by zhuhang-jasper** [comment] 2021-07-23 05:26
The reason why `cache-and-network` is not accepted for `query` is explained here:
https://github.com/apollographql/apollo-client/issues/3130#issuecomment-478409066
