### ISSUE TITLE
Next.js + 3.4 useQuery stuck on Loading

### ISSUE THREAD

**Issue by gvocale** [apollographql/apollo-client#8582] opened 2021-08-03 22:03 UTC
In Apollo Client 3.4.3 our `useQuery` hook stopped working correctly. On page load, useQuery will be stuck on `loading: true`. Refreshing the page will then let `useQuery` resolve correctly.

Reverting to 3.3 fixed the issue.

```json
 "@apollo/client": "^3.4.3",
"next": "11.0.1",
```

```tsx
  const { loading, error } = useQuery<CartQueryProps>(CART_QUERY, {
    onCompleted: (data) => {
      console.info("completed CART_QUERY", {
        data,
        loading,
        error,
      });
    },
    onError: (error) => {
      console.error(error);
    },
  });
  
  console.log({data, loading, error})
```

**Comment by gwyneplaine** [comment] 2021-08-04 01:00
Hello, we're also experiencing the exact same symptoms in the [Keystone project](https://github.com/keystonejs/keystone/issues/6254).
We leverage both Next.js and Apollo, and have pinned to `@apollo/client@3.3.21` temporarily to workaround this. 

Would appreciate any additional insight into why this might be happening 🙏 
Here's a minimal viable reproduction of the bug we're seeing in our project. 

https://github.com/gwyneplaine/keystone-apollo-bug-repro

**Comment by ihmpavel** [comment] 2021-08-04 14:45
We are experiencing same issue https://github.com/apollographql/apollo-client/issues/8575

**Comment by brainkim** [comment] 2021-08-04 16:35
@gvocale I’m sorry to hear this! Looking into this right now.

**Comment by brainkim** [comment] 2021-08-04 20:52
@gwyneplaine The keystone reproduction is fixed in 3.4.5.

@gvocale Can you check 3.4.5 and see if you’re still seeing a problem?

**Comment by kikoanis** [comment] 2021-08-05 03:27
@brainkim I can confirm 3.4.5 still has the issue. Even 3.5.0-beta.4 still has it. Only going back to 3.4.0 solved the issue for me.

**Comment by kikoanis** [comment] 2021-08-05 03:28
I must say lazy loading does not have the same issue.

**Comment by brainkim** [comment] 2021-08-05 06:09
@kikoanis This issue was a regression going from 3.3 -> 3.4. 3.5 doesn’t really have much work on it... If you’re seeing an issue you might be facing a different problem?

**Comment by kikoanis** [comment] 2021-08-05 12:56
@brainkim Deleting the whole folder of `node_modules` and `yarn.lock` file and reinstalling from scratch got the issue fixed for now. Thanks for your time.

**Comment by brainkim** [comment] 2021-08-06 16:49
Closing for housekeeping purposes. If it isn’t feel free to ping me.

**Comment by gvocale** [comment] 2021-08-09 15:31
> @gwyneplaine The keystone reproduction is fixed in 3.4.5.
> 
> @gvocale Can you check 3.4.5 and see if you’re still seeing a problem?

3.4.5 fixed the issue for me as well. Thank you!

**Comment by Woong25** [comment] 2021-08-10 01:48
Infinite loading with 'ssrForceFetchDelay' option in apollo settings.
Can anyone check this issue?

I used version 3.4.7

```
"@apollo/client": "^3.4.7",
```

```
export const client = new ApolloClient({
    ssrMode: typeof window === 'undefined',
    ssrForceFetchDelay: 100, // Infinite loading with this option
});
```

**Comment by brainkim** [comment] 2021-08-10 17:19
@Woong25 Is this issue what you’re seeing? https://github.com/apollographql/apollo-client/issues/5918 I’m not familiar with what `ssrforceFetchDelay` is to be honest.

**Comment by jrsakizci** [comment] 2021-08-10 17:33
I am having exactly the same issue. When I use client object directly I got an answer, but when I try to use useQuery, it stuck at loading. Using Next, and 3.4.7 for apollo client.

**Comment by tm1000** [comment] 2021-08-10 18:24
I can confirm what @Woong25 is saying. Having the option `ssrForceFetchDelay` set causes infinite loading. I'm not sure why i ever set this to begin with (probably some regression from next.js 9 and apollo 2.x YEARs ago) once I remove it everything works splendidly

**Comment by brainkim** [comment] 2021-08-10 18:52
😠 Okay let me do some comparing of 3.3 and 3.4 and see if I can get this old behavior for y’all 😄

> is a whole pandemic ago

👴 👴 👴 👴 👴 👴

**Comment by askurat** [comment] 2021-08-11 15:31
Same issue here for 3.4.7 except I am using UmiJS. All my queries just continually load. If I turn off `ssrMode`, everything seems to work. I was able to revert back to 3.4.2 for now.

**Comment by simplecommerce** [comment] 2021-08-11 19:38
I have a weird issue too mentioned here https://community.apollographql.com/t/cache-evict-and-usequery-ssr/1006 and I think it might be related to this, my login/logout code would no longer re-render after I used `client.resetStore` and some queries no longer refetch when I run `cache.evict` (those generated via SSR). 

Same as the people here, I can definitely pinpoint that it works up until 3.4.3, if I stay on 3.4.2 everything works fine.

**Comment by simplecommerce** [comment] 2021-08-13 10:06
@brainkim You probably know this already but `ssrForceFetchDelay` explanation can be found here https://www.apollographql.com/docs/react/performance/server-side-rendering/#overriding-fetch-policies-during-initialization
(I read a few posts above when you mentioned you wasn't sure what it was for)

In my initial tests, without `ssrForceFetchDelay`, I could see queries being executed in my network log in dev console on initial load, which shouldn't happen since I am using SSR and they are already fetched from the server. Adding this option prevents that.

In my previous post above, in case it helps, when I tested 3.4.3 I added a console log for the variables that changed in the if condition and I noticed that `this.client.disableNetworkFetches` always returned `true` but when I console.log `this.client` I could see it being set to `false`, which is why I pointed to the ApolloClient line, I think its related maybe, hope it helps.

Sorry if I am not clear.

**Comment by brainkim** [comment] 2021-08-13 15:42
I’m closing this issue because the poor OP (@gvocale) had his issue fixed and is now getting notifications about a separate issue. If your issues are not described in #8644, feel free to yell at me 👼

**Closed by brainkim** 2021-08-13 15:42 UTC
Labels: 🏓 awaiting-response, :rose: has-reproduction, 📟 regression, 2021-08

**Comment by alanionita** [comment] 2021-08-13 18:17
Still seeing this issue on `3.4.7` 

We're running two queries right after each other and the second query always appears to be loading. 

The server is resolving the query so it seems to be an issue with the client lib 

```
  const searchForStuff = useQuery(STUFF_QUERY);
  const findSomethingElse = useQuery(SOMETHINGELSE_QUERY);
```

**Comment by tm1000** [comment] 2021-08-13 22:47
@alanionita  I think you have a different issue. The issue encountered here is that the client never made a request to the server.

**Comment by brainkim** [comment] 2021-08-16 17:00
@alanionita I’m sorry to hear that you’re having problems and I’m happy to help! Can you open another issue with your commend, and provide a teensy bit more information like a runnable reproduction to help us confirm?
