### ISSUE TITLE
Best Practise: For deleting item(s) from new imperative store using update

### ISSUE THREAD

**Issue by TheoMer** [apollographql/apollo-client#1574] opened 2017-04-11 07:40 UTC
Is there one (code example(s)) available? An deleteFragment(options) would be nice.

**Comment by TheoMer** [comment] 2017-04-11 10:15
So, the workaround I have currently settled on is as follows:

**My Root Query**

```
export const All_Comments_Query = gql`
  query allCommentsQuery {
    allCommentses {
      __typename
      id
      text
      user
      posts {
        __typename
        id
      }
    }
  }
`;
```

**My Remove Comment Mutation**

```
export const Remove_Comment_MutationOld = gql`
  mutation removeComment ($id: ID!, $cid: ID!) {
    removeFromPostsOnComments (postsPostsId: $id, commentsCommentsId: $cid){
      postsPosts {
        __typename
        id
        comments {
          __typename
          id
          text
          user
          posts {
            __typename
            id
          }
        }
      }
    }
  }
`;
```

**My Remove Comments Code**

```
  removeCommentMutation(postID, commentID) {
    const cid = commentID;
    const id = postID;
    const postIndexID = this.props.postIndexID;
    
    this.props.client.mutate({
      mutation: Remove_Comment_MutationOld,
      variables: {
        id,
        cid,
      },

      update: (proxy, mutationResult) => {
        const query = All_Posts_Comments_Query;
        const data = proxy.readQuery({
          query,
        });
        
        data.allPostses[postIndexID].push(mutationResult.data.removeFromPostsOnComments.postsPosts.comments);
        proxy.writeQuery({
          query,
          data,
        });
      },
    })
    .catch(this.handleSubmitError);
  },
```

Even though the deletion takes place successfully, albeit a complete comments rewrite in the allPostes tree for the specified post id, I'm still getting the following error in devTools:

```
TypeError: data.allPostses[postIndexID].push is not a function
    at update (Comments.js:114)
    at apollo.umd.js:1524
    at tryFunctionOrLogError (apollo.umd.js:1408)
    at data (apollo.umd.js:1524)
    at apolloReducer (apollo.umd.js:1741)
    at combination (combineReducers.js:132)
    at computeNextEntry (<anonymous>:2:27051)
    at recomputeStates (<anonymous>:2:27351)
    at <anonymous>:2:30904
    at Object.dispatch (createStore.js:179)
    at dispatch (<anonymous>:2:31397)
    at apollo.umd.js:3164
    at index.js:14
    at Object.dispatch (applyMiddleware.js:45)
    at apollo.umd.js:2550
```

What's the issue here? And, yes, I welcome more effective solutions to achieving the same goal.

**Comment by PCreations** [comment] 2017-04-12 05:56
Great point, duplicate of #1570

**Closed** 2017-04-15 03:37 UTC
