### ISSUE TITLE
Source Code Links in Docs are Broken

### ISSUE THREAD

**Issue by evans** [apollographql/apollo-client#3266] opened 2018-04-04 22:11 UTC
The source code links in the apollo client documentation are broken, see: https://www.apollographql.com/docs/react/api/apollo-client.html#ObservableQuery

cc @abernix

**Comment by abernix** [comment] 2018-04-06 17:12
This is happening because the JSON file output by `typedoc` (which the docs read from `docs/docs.json` via the `npm run types` command in the `docs/package.json`) is referring to the `ApolloClient.ts` path inside `packages/apollo-client/src` instead of including that path when forming the link.

It's possible we can use something like https://github.com/gdelmas/typedoc-plugin-sourcefile-url to fix this (Seems like that's what it aims to fix), but I haven't had a chance to try yet.  The docs will use whatever is in `source[x].fileName` within the `docs/docs.json` file!

**Comment by hwillson** [comment] 2018-05-22 13:16
Just a quick update here - the https://github.com/gdelmas/typedoc-plugin-sourcefile-url plugin does do what we want, and it works, but NOT with the `typedoc --json` option (which we're using). The resulting `doc/docs.json` is not updated with the newly generated source `fileName`. I can see that the plugin is generating the proper path, but it's not being written to the `docs.json` file. The plugin is a bit out of date so this issue is likely caused by `typedoc` API changes. I'll look into either submitting a PR to fix this issue, forking/maintaining our own version, or another solution.

**Comment by hwillson** [comment] 2018-06-11 17:21
This was fixed by https://github.com/apollographql/hexo-typescript-api-box/pull/9. Thanks!

**Closed by hwillson** 2018-06-11 17:21 UTC
Labels: bug, confirmed, docs

**Comment by abernix** [comment] 2018-06-11 17:56
Awesome! Thanks for getting this fixed, @hwillson!
