### ISSUE TITLE
When cache is enabled, results of sub entities on different queries get overwritten

### ISSUE THREAD

**Issue by benesjan** [apollographql/apollo-client#8405] opened 2021-06-19 20:05 UTC
Hello,
whenever the cache is enabled on the Apollo client, the results of "subqueries" on different parent queries get overwritten. In the screenshot you can see that the derivedETH price is different in pool.token0 and poolOld.token0 entities and with cache enabled they are the same (incorrectly). In the attachement is a minimal, reproducible example which should make everything clear.

![image](https://user-images.githubusercontent.com/13470840/122654159-b1c18680-d149-11eb-88fe-046a334c30dd.png)

Thank you,
best regards,
Jan

[example.zip](https://github.com/apollographql/apollo-client/files/6681289/example.zip)

**Comment by ianlapham** [comment] 2021-06-24 17:43
I can confirm this is an issue for us at Uniswap as well.

**Comment by dylanwulf** [comment] 2021-06-24 18:10
The problem is that `token0.id` is the same value for both `pool` and `poolOld`. Apollo Client makes the assumption that any field named `id` is a globally unique identifier among all objects of the same type. In this case it appears that assumption is incorrect, since you have two different objects of the same type with the same id. This can be fixed by specifying [keyFields in the cache config](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-identifier-generation-by-type) for the `Token` type. If `Token` does not have any globally unique identifiers, then you can [disable normalization](https://www.apollographql.com/docs/react/caching/cache-configuration/#disabling-normalization) for the Token type.

**Closed** 2021-06-27 18:54 UTC
