### ISSUE TITLE
Cannot update cache after mutation with errors

### ISSUE THREAD

**Issue by ch-stephenzuniga** [apollographql/apollo-client#5582] opened 2019-11-14 17:21 UTC
**Intended outcome:**
I have a mutation which will fail when called with stale data. For example, if I had loaded the page with version 1 of a todo with an ID of 1, and while I was updating it a different user also updated the todo incrementing its version to 2, the server will respond with the following:
```json
{
  "data": {
    "todo": {
      "id": 1,
      "version": 2,
      "description": "The updated todo description."
    }
  },
  "errors": [
    {
      "message": "Todo has been updated",
      "extensions": {
        "staleData": true
      }
    }
  ]
}
```

The idea here is that the server is responding with an error indicating that our mutation failed. In addition, it's also providing the updated todo so the user can choose to cancel their edit or make it again. Since the server responds with the new `version` (and the rest of the latest todo information), the mutation will succeed the next time it's called.

With this server response, the intent is to update the `Todo:1` in the cache, and use the error details to trigger a "Are you sure you want to do this?" workflow.

**Actual outcome:**
The `update` method of my mutation is never called because the response contains `errors`. None of the available `errorPolicy` options change this outcome, and I've been able to trace it down to [this line of code](https://github.com/apollographql/apollo-client/blob/7eaf4132cd2cd6244260777799406aaa03fcf377/packages/apollo-client/src/data/store.ts#L119).

**How to reproduce the issue:**
https://codesandbox.io/s/apollo-client-error-template-1o8ix

In the above sandbox, nothing will be displayed in the UI and you'll have to open the console. Look for the two `INFO` comments for instructions on switches that can be toggled. When errors exist in the response, we don't see the `My response is:` console statement. When those errors don't exist, we do.

I would expect to be able to update the cache in either case, but the Apollo client is preventing me from doing so when the server responds with errors.

**Versions**
```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Firefox: 69.0
    Safari: 13.0.3
  npmPackages:
    apollo-cache: ^1.2.1 => 1.3.2 
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-link-context: ^1.0.19 => 1.0.19 
    apollo-link-error: ^1.1.12 => 1.1.12 
    apollo-link-http: ^1.5.16 => 1.5.16 
```

**Comment by WIStudent** [comment] 2019-11-21 16:56
I am having the exact same issue using `errorPolicy: 'all'`, with a similar scenario (2 clients try to send a mutation that trigggers an update, the second client will receive a response with an error and the current data on the server). 

Apollo's documentation says about `errorPolicy`

> all: Using the all policy is the best way to notify your users of potential issues while still showing as much data as possible from your server. It saves both data and errors into the Apollo Cache so your UI can use them.

but neither the update function in mutate will be called nor will the cache be updated with the server response.

**Comment by elhorowitz** [comment] 2019-11-27 15:43
I am having this problem as well. 

I noticed that, for queries, we check whether or not to update the cache based on errorPolicy in the [markQueryResult](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/data/store.ts#L36) function:
```
let writeWithErrors = !graphQLResultHasError(result);
if (ignoreErrors && graphQLResultHasError(result) && result.data) {
    writeWithErrors = true;
}
if (!fetchMoreForQueryId && writeWithErrors) {
    this.cache.write({ ... });
}
```

Any reason this logic isn't added to the [markMutationResult](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/data/store.ts#L110) as well?

**Comment by dyst5422** [comment] 2020-09-02 16:44
This is still an issue in apollo-client@2.6.10

**Comment by SeungsuKim** [comment] 2021-01-29 07:52
I'm having the same issue with `@apollo/client": "^3.3.7`. `update` function is not executed when the parent mutation results with errors.

**Comment by jcreighton** [comment] 2021-04-26 21:08
Closing this ticket as it's related to an older version of Apollo Client. If you're experiencing the issue with Apollo Client 3.+, please reopen with a runnable reproduction using either [this repo](https://github.com/apollographql/react-apollo-error-template) or [this CodeSandbox](https://codesandbox.io/s/github/apollographql/react-apollo-error-template).

**Closed by jcreighton** 2021-04-26 21:08 UTC

**Comment by cunisia** [comment] 2021-05-20 08:55
@jcreighton the new version of the issue is [here](https://github.com/apollographql/apollo-client/issues/5582)
