### ISSUE TITLE
writeQuery doesn't update/rerender/refetch the component(s) 

### ISSUE THREAD

**Issue by dennislaupman** [apollographql/apollo-client#3301] opened 2018-04-12 07:15 UTC
Hello,

writeQuery doesn't update/rerender/refetch the component(s) connected to the submitResponse query.

```
update: (proxy, { data: { submitResponse } }) => {
          const data = proxy.readQuery({
            query: ResponsesViewQuery,
            variables: { 
              id: params.castId,
            }            
          });
         data.responses.push(data.responses[
         
         console.log(data.responses);
   
         proxy.writeQuery({ query: ResponsesViewQuery, data });
}
```

Grtz Dennis

**Comment by mkrn** [comment] 2018-06-29 02:20
I think what seem to happen here, and what is not covered in documentation is use of variables with readQuery / writeQuery.
I've just had a similar situation, and it did not work until I got rid of variables.
Additionally, should you try to add same variables to writeQuery?

**Comment by hwillson** [comment] 2018-08-07 14:31
Any chance you could provide a small runnable reproduction that demonstrates this issue? Thanks!

**Comment by rosskevin** [comment] 2018-12-24 17:10
Duplicate of #2415

**Comment by danilobuerger** [comment] 2019-01-29 19:00
Closing as no reproduction was provided in one week. Feel free to reopen if you have a minimal reproduction.

**Closed by danilobuerger** 2019-01-29 19:00 UTC
Labels: reproduction-needed
