### ISSUE TITLE
 fetchPolicy: 'network-only' not working on client.query({...}) when  'ssrMode': true set on ApolloClient.

### ISSUE THREAD

**Issue by kapilpipaliya** [apollographql/apollo-client#2983] opened 2018-02-09 16:25 UTC
fetchPolicy: 'network-only' not working on client.query({...})

**Comment by dennislaupman** [comment] 2018-02-12 11:33
Facing weird problems. It seems that client is still reading from cach, after that the network is storing the data in the cache. What means that you always one step behind.

**Comment by fc** [comment] 2018-02-14 17:58
In apollo-client 2.2.2, a fetchPolicy of 'no-cache' was added which may fix this issue.

https://github.com/apollographql/apollo-client/pull/2934

**Comment by dennislaupman** [comment] 2018-02-19 13:30
const getDetails = graphql(DetailsViewQuery, {
  options: ( props ) => {
    return { 
      variables: { id: props.navigation.state.params._id },
      fetchPolicy: 'network-only', // skip the cache
    } 
  } 
});

Still gives cached results

**Comment by hwillson** [comment] 2018-05-12 18:43
The original issue here

> fetchPolicy: 'network-only' not working on client.query({...}) when 'ssrMode': true set on ApolloClient.

actually functions as designed:

https://github.com/apollographql/apollo-client/blob/ca5a21169670c5517b5dd6d8ca64a4b128b35444/packages/apollo-client/src/ApolloClient.ts#L239-L241

Setting `ssrMode` to `true` effectively sets `disableNetworkFetches` to `true`, which means your `fetchPolicy` is being changed to `cache-first`. You can read more about why this is happening in the [Server-side rendering > Server initialization](https://www.apollographql.com/docs/react/features/server-side-rendering.html#server-initialization) section of the `apollo-client` docs. In a nutshell - `network-only` is overkill with SSR, since we really only ever want to fetch each query result once. Closing for now - thanks!

**Closed by hwillson** 2018-05-12 18:43 UTC

**Comment by hwillson** [comment] 2018-06-01 10:28
Thanks @sea129 - https://github.com/apollographql/react-apollo/issues/556 is still open, so we'll get to it shortly.

**Comment by duwerq** [comment] 2019-01-27 18:47
@kapilpipaliya  I had issues with client.query also.  I solved it by chanaging:
```
  const { data: { getUser } } = await client.query({
        query: gql(queries.getUser)
      }, {
        options: {
          fetchPolicy: 'network-only'
        }
      });
```
to
```
const { data: { getUser } } = await client.query({
    query: gql(queries.getUser),
    fetchPolicy: 'network-only'
});
```

**Comment by jack1012t** [comment] 2019-02-07 13:43
thank you @duwerq

**Comment by spyshower** [comment] 2019-05-09 15:15
Thank you so much @duwerq !

**Comment by hmmhmmhm** [comment] 2019-05-30 15:05
thank you. you saved me at dawn. @duwerq

**Comment by lilrooness** [comment] 2019-05-31 09:50
Where is the use of client.query documented? It seems like we're all just debating the spec of the function here

**Comment by raajnadar** [comment] 2020-03-19 14:52
I used this config now the data is not cached. In my react native application.

```
export default new ApolloClient({
    ...
    defaultOptions: {
        watchQuery: {
            fetchPolicy: 'no-cache'
        },
       query: {
            fetchPolicy: 'no-cache'
       },
       mutate: {
            fetchPolicy: 'no-cache'
        }
    }
})
```

**Comment by Aarthysekar** [comment] 2020-06-15 13:12
For me, in graphql() HOC, when i changed the options to functions it worked. Its weird, but worked.

 graphql(SAMPLE_DATA_GQL, {
      name: 'sampleData',
      options: () => ({
        fetchPolicy: 'network-only'
      })
    })
