### ISSUE TITLE
apollo doesn't return values nor error when [Episode]! type has a null value

### ISSUE THREAD

**Issue by github0013** [apollographql/apollo-client#1658] opened 2017-05-05 10:08 UTC
Server setup may depend on preferences, but I do ruby on the server side, and here's the reproduction code.
https://gist.github.com/github0013/2bd68d7569d49533ab629ca05f3f8238

### this code above returns values like this in graphiql without errors.
![](https://gist.githubusercontent.com/github0013/2bd68d7569d49533ab629ca05f3f8238/raw/2fab005d53d92160ec14d8ebb236497779e4523f/GraphiQL.png)

As far as I checked [typename]! should return `[]` OR `[value, value]` BUT not `null` (no array at all)
http://graphql.org/learn/schema/
> [Episode]! represents an array of Episode objects. Since it is also non-nullable, you can always expect an array (with zero or more items) when you query the appearsIn field.

However, in my case, it is still an array where one of the elements has `null` value.

## here is the problem.

If I use this query running by apollo client ("apollo-client": "^1.2.0" in my package.json), it returns **no error** NOR **no return values** (`query.ArrayWithNullValue` in this case) 

<img width="837" src="https://cloud.githubusercontent.com/assets/809378/25731762/4ba67e64-3184-11e7-86b1-f8f0fb01c995.png">

Since graphiql is returning values as expected, I think the schema and types are correct.   This only happens when the array has `null` element in it.  If I change to return [value, value, value] (without null), apollo **will** return values (`query.ArrayWithNullValue`)

Is this because of my apollo-client setup issue or its internal problem?
Thanks

**Comment by helfer** [comment] 2017-05-05 18:04
Thanks for filing this issue @github0013! 🙂 
I think this is a duplicate of #1551 so I'll close it. I will look into it today!

**Closed by helfer** 2017-05-05 18:04 UTC
