### ISSUE TITLE
useQuery doesn't seem to use defaultOptions in 3.5

### ISSUE THREAD

**Issue by jtoar** [apollographql/apollo-client#9105] opened 2021-11-23 00:58 UTC
Hey, excited about the `v3.5.4` release! [RedwoodJS](https://github.com/redwoodjs/redwood) uses Apollo Client as its default GraphQL client. (Our implementation lives here: https://github.com/redwoodjs/redwood/blob/main/packages/web/src/apollo/index.tsx.) I recently moved the `useQuery` configuration up to the client, using `defaultOptions.watchQuery` as the docs say [here](https://www.apollographql.com/docs/react/api/core/ApolloClient/#example-defaultoptions-object) (here's the PR: https://github.com/redwoodjs/redwood/pull/3747). This was working great in v3.4.x but seemed to have broken in v3.5.x, as in `useQuery` doesn't seem to care about the client's `defaultOptions.watchQuery`.

**Intended outcome:**

Setting `defaultOptions.watchQuery` in Apollo Client configures all `useQuery` hooks.

**Actual outcome:**

useQuery hooks seem to ignore the `defaultOptions.watchQuery` configuration set in Apollo Client.

**How to reproduce the issue:**

Repo with reproduction (the readme has steps to reproduce): https://github.com/jtoar/apollo-client-default-options. And video walkthrough showing the behavior I'm seeing:

https://user-images.githubusercontent.com/32992335/142956267-8f845c71-dae5-428e-aedd-afa385205bb4.mp4

**Versions**

```
  System:
    OS: macOS 12.0.1
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Safari: 15.1
```

**Comment by gjvoosten** [comment] 2021-11-30 13:49
@brainkim At quick glance, something like this should fix it (diff against current main branch):
```
diff --git a/src/react/hooks/useQuery.ts b/src/react/hooks/useQuery.ts
index bdabb3e72..a5ea139ad 100644
--- a/src/react/hooks/useQuery.ts
+++ b/src/react/hooks/useQuery.ts
@@ -10,6 +10,7 @@ import {
   DocumentNode,
   TypedDocumentNode,
   WatchQueryOptions,
+  mergeOptions,
 } from '../../core';
 import {
   QueryHookOptions,
@@ -28,6 +29,9 @@ export function useQuery<
 ): QueryResult<TData, TVariables> {
   const context = useContext(getApolloContext());
   const client = useApolloClient(options?.client);
+  if (client.defaultOptions.watchQuery) {
+    options = mergeOptions(client.defaultOptions.watchQuery, options as any);
+  }
   verifyDocumentType(query, DocumentType.Query);
   const [obsQuery, setObsQuery] = useState(() => {
     const watchQueryOptions = createWatchQueryOptions(query, options);
```

Tested with my own application and it appears to work.
Probably needs some tests, and someone with more in-depth knowledge of Apollo Client should go over it to see if this is the correct approach.

**Comment by brainkim** [comment] 2021-12-02 16:45
@jtoar Took a brief look at this and will take another look soon. I disagree with the diagnosis that `defaultOptions` isn’t used, as that stuff is handled in the core. I confirmed this in the reproduction by adding the following hook according to Redwood docs on “cells,” which to my understanding, matches the `defaultOptions` passed to Apollo Client.


```
diff --git a/web/src/components/Post/PostCell/PostCell.js b/web/src/components/Post/PostCell/PostCell.js
index 00a1776..334fd8d 100644
--- a/web/src/components/Post/PostCell/PostCell.js
+++ b/web/src/components/Post/PostCell/PostCell.js
@@ -10,6 +10,14 @@ export const QUERY = gql`
   }
 `
 
+export const beforeQuery = (variables) => {
+  return {
+    variables,
+    fetchPolicy: "cache-and-network",
+    notifyOnNetworkStatusChange: true,
+  }
+}
+
 export const Loading = () => <div>Loading...</div>
 
 export const Empty = () => <div>Post not found</div>
```

The thing I’m trying to figure out is, is what was triggering the new request. Do you unmount and remount the `<PostCell />`? Or is the cell just mounted in the background? The context for this is that the `"cache-and-network"` fetch policy is kind of notorious for causing infinite loops, and we’ve been trying to make it more stable. So my question is, was there never any sort of mechanism which invalidated or caused the “cell” queries to get refetched on mutation?

**Comment by jtoar** [comment] 2021-12-02 19:02
Thanks for taking a look! I'll provide a bit more context that I may have omitted in the original post:

Providing `defaultOptions` to `beforeQuery` does indeed work. But `beforeQuery` is for configuring Apollo’s `useQuery` hook on a per-query basis. It's supposed to be for overriding the `defaultOptions` in Apollo Client as the docs say:

> You can override any default option you specify in this object by providing a different value for the same option in individual function calls.[^ds]

But specifying `defaultOptions` in Apollo Client is supposed to configure every `useQuery` hook out of the box, and that's what I don't see happening. In the reproduction I provided, the client is hidden in the `<RedwoodApolloProvider />`. [Here's it's source](https://github.com/redwoodjs/redwood/blob/4567f76c238cea6ba6e2f93499ae55f301bfa201/packages/web/src/apollo/index.tsx#L184-L211), but the relevant config is (I've removed the comments):

```js
const client = new ApolloClient({
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network',
      notifyOnNetworkStatusChange: true,
    },
  },
  link,
  ...rest,
})
```

So you shouldn't have to specify the same options in `beforeQuery`.

---

> So my question is, was there never any sort of mechanism which invalidated or caused the “cell” queries to get refetched on mutation?

That's right! Scaffolds (another Redwood term—it's just a CLI command to quickly "scaffold" a CRUD interface) don't have any invalidation logic. They depend on the `"cache-and-network"` fetch policy to show updated data. This is mainly because we're trying to manage the complexity of learning Redwood. We ask new users to learn a lot of new concepts/tooling—many don't know GraphQL. But once they've become more experienced, we expect them to prefer making cache updates by refetching queries or via `cache.updateQuery` / `cache.modify`.

While we haven't run into any infinite loops, if you think that this isn't the best approach, we could definitely introduce invalidation logic. Refetching a query is super simple.

[^ds]: https://www.apollographql.com/docs/react/api/core/ApolloClient/#example-defaultoptions-object

**Comment by jbanulso** [comment] 2021-12-03 11:10
Experiencing the same problem here.

**Comment by gjvoosten** [comment] 2021-12-03 12:35
@brainkim I'll explain our situation which *does* have the problem that queries are not executed because the `defaultOptions` are ignored, and which is solved by my patch above. Our client (which is provided through an `ApolloProvider`) has:
```
  const client = new ApolloClient({
    …,
    defaultOptions: {
      query: {
        fetchPolicy: "no-cache"
      },
      watchQuery: {
        fetchPolicy: "no-cache"
      },
      mutate: {
        fetchPolicy: "no-cache"
      }
    },
    fetchOptions: {
      credentials: "same-origin"
    }
  })
```
We have Edit pages that retrieve an object through `useQuery`, then mutate it, then redirect to the Show page, where the object is retrieved again through `useQuery`. We don't use caching in the client, as the object might have been edited by anyone at anytime, so we always need a fresh copy from the server.
With `@apollo/client` v3.4.17, the Show page does another network request, picking up the changes. With v3.5.5, the Show page does *not* do another query, and we get the outdated object.
When debugging this, it was clear to me that the `defaultOptions` were ignored (hence my proposed solution). Only if for v3.5.5 I change my query to `useQuery(q, { fetchPolicy: "no-cache" })`, i.e. *explicitly* set a policy on *each* request, do I see network requests flying again.
So I maintain that this is a bug in v3.5 that needs to be fixed. Please correct me if I'm wrong, but our tests pass with v3.4.17 and fail with v3.5.5, for the reasons outlined above.

**Comment by yasharzolmajdi** [comment] 2021-12-16 09:01
so I found the issue

so if the user doesn't pass in `fetchPoilcy` to `useQuery` function, the `fetchPoilcy` is defaulted to `cache-first`
https://github.com/apollographql/apollo-client/blob/bc6488c4eb02d41cd08d0f4dfaba7b45d707338e/src/react/hooks/useQuery.ts#L359

this is happens before the `defaultOptions` are merged with options that are passed to `useQuery` function
https://github.com/apollographql/apollo-client/blob/bc6488c4eb02d41cd08d0f4dfaba7b45d707338e/src/core/ApolloClient.ts#L303

so the flow is this
`useQuery`(no options passed) -> `createWatchQueryOptions`(set default fetchPoilcy to cache-first) -> `watchQuery`(option based on createWatchQueryOptions) -> `mergeOptions`(overwrite defaultOptions with options from createWatchQueryOptions)

**Closed** 2022-01-10 17:19 UTC
Labels: 🏓 awaiting-response
