### ISSUE TITLE
issue when composing multiple graphql decorators when one of them uses a field called id

### ISSUE THREAD

**Issue by AlexCLeduc** [apollographql/apollo-client#2856] opened 2018-01-12 02:52 UTC
I've found a bug when using `compose` on multiple graphql decorators, when one of the decorators involve a field named `id`.  

Take a simple schema of the form 

```graphql
type Query {
  people: [Person]
}
type Person {
  id: String
  name: String
}
```

then, create two `graphql` decorators, one fetching the `name` of each person and another fetching their `id`'s. Combine them using `compose`, using the [name option in config.options](https://www.apollographql.com/docs/react/basics/queries.html#graphql-name) so that the composed decorator namespaces both queries before passing down props.

```javascript
const first_query = gql`
  query {
    people {
      name
    }
  }
`;
const first_dec = graphql(first_query, { name: "first_query" })

const second_query =  gql`
query {
  people {
    id
  }
}
`;

const second_dec = graphql(second_query, { name: "second_query" });

const combined_decorator = compose(first_dec, second_dec);

const Component = ({ 
  first_query,
  second_query,
}) => {

  if(first_query.loading || second_query.loading){
    return "Loading..."
  }


  if(first_query.people && !second_query.people){
    //second_query.people should be defined 
    return "BUG IS HAPPENNING"
  }

  return "no bug"
};

const combined_decorator(Component);

```

What you end up with is that `second_query.people` is undefined even though it's done loading and the query gets executed properly (If you're using an http-link, you can see that the http response is what we expect it to be).

I've noticed this issue goes away if I rename the `id` field to anything else. Clearly, fields called `id` are being given special treatment. 

**How to reproduce the issue:**

To see the above in action, see the forked error template repo [here](https://github.com/AlexCLeduc/react-apollo-error-template). Just run `npm start` and wait for the debugger statement.

​
**Package Versions**
* all the same package versions from the error template repo

**Comment by hwillson** [comment] 2018-07-03 23:59
> I've noticed this issue goes away if I rename the `id` field to anything else. Clearly, fields called `id` are being given special treatment.

`id` fields are given special treatment by `apollo-client`'s `InMemoryCache`. You can read more about this in the [Normalization](https://www.apollographql.com/docs/react/advanced/caching.html#normalization) section of the docs. In a nutshell, `InMemoryCache` tries to use common primary keys like `id`, combined with `__typename`, as the unique identifier of an object in the cache.

After your reproduction runs, the `apollo-client` cache looks like this:

![screenshot 2018-07-03 19 19 00](https://user-images.githubusercontent.com/137740/42249787-2e9ca594-7efb-11e8-9490-b07add3dff11.png)

You can see that the results stored from running `first_query`, which didn't specify an `id` in the response, are stored under the computed keys of `ROOT_QUERY.people.0`, `ROOT_QUERY.people.1`, etc. So `InMemoryCache` created primary keys using its fallback algorithm. You can then see the results stored from running `second_query`, which did specify an `id` in the response. They're stored under primary keys like `Person:1`, `Person:2`, etc. So as far as `apollo-client` is concerned, your `first_query` and `second_query` results are different in the cache, since they don't have the same primary key. 

Now looking again at the above screenshot, envision what happens when a query is run against the cache. For the `first_query`, the incoming query is matched up against `ROOT_QUERY` -> `people`, then the id of those entries is used to find the normalized data. So `ROOT_QUERY.people.0` is matched up against the `ROOT_QUERY.people.0` entry, which includes a `name`. This means `first_query` returns data, since that data can be found under `ROOT_QUERY`. When the `second_query` comes in though, and attempts to be matched up against `ROOT_QUERY` -> `people`, the matching `ROOT_QUERY.people.0` entry doesn't have an `id`. The proper matching normalized data is under `Person:1`, which isn't linked back into `ROOT_QUERY`.

There are many different ways you can work around this:

1. Get into the habit of always using an `id` in your response, so response data can be properly normalized in the cache, and still be retrievable.

2. Look into passing a custom `dataIdFromObject` function into your `InMemoryCache` instance, that can take care of making sure you always have an appropriate primary key added to cache data. So even when you don't include one in your response, you can make sure one is generated as a fallback. For example, this is a total hack for demonstration purposes only (since `object.id - 1` is kinda arbitrary), but adding this would fix your repro by ensuring your `first_query` and `second_query` responses always have a matching primary key:

```js
...
const client = new ApolloClient({
  cache: new InMemoryCache({
    dataIdFromObject(object) {
      return object.id ? `ROOT_QUERY.people.${object.id - 1}` : null;
    }
  }),
  link,
});
...
```

3. You could consider by-passing the cache; e.g.:

```js
...
const first_dec = graphql(first_query, { name: "first_query", fetchPolicy: 'no-cache' });
...
```

4. Other options that involve manipulating the cache directly, but are probably more complex than needed here.

Since this isn't really a bug, I'll close this issue for now. If you have any questions about the above though, definitely post back and let us know. If you think any of this could be explained better in the docs, please also let us know (PR's encouraged! 🙂). Thanks!

**Closed by hwillson** 2018-07-03 23:59 UTC
