### ISSUE TITLE
read data from cache graphql apollo 2.0

### ISSUE THREAD

**Issue by dilipkumar2k6** [apollographql/apollo-client#3435] opened 2018-05-10 07:19 UTC
**Intended outcome:** Would like to reach existing data from cache

**Actual outcome:** Access data directly from `client.cache.data.data`

**How to reproduce the issue:** Following is code sample I am using to read data from cache directly
```
const data = get(client,'cache.data.data');
  const users = values(data).filter(obj=>(obj.__typename==='User' && obj.token));
  const token = get(users,'[0].token');

  // Make graphql call to validate sso
  const { data } = await client.query({
    query: GET_SSO_USER,
    variables: { token }
  });

  const authenticated = get(data, 'getSingleSignOnUser.user.userId');
```

**Version**
- apollo-client@2.3.1
- "apollo-boost": "^0.1.5",
- "apollo-cache-inmemory": "^1.2.1",
- "apollo-cache-persist": "^0.1.1",

**Comment by hwillson** [comment] 2018-06-10 12:58
I'm not quite sure what the issue is that you're reporting? Your actual outcome and reproduction both support your intended outcome. Closing for now, but I'll re-open if you can provide more details that help explain what the issue is that you're seeing. Thanks!

**Closed by hwillson** 2018-06-10 12:58 UTC
Labels: docs
