### ISSUE TITLE
FetchPolicy is not documented

### ISSUE THREAD

**Issue by bgentry** [apollographql/apollo-client#1626] opened 2017-04-26 14:37 UTC
**Intended outcome:**

I viewed the API reference for apollo-client, and discovered the new `fetchPolicy` option for queries. The option attempts to link to documentation for `FetchPolicy`, and I would expect that link to work and describe the feature in more detail (including the ramifications of each possible setting).

**Actual outcome:**

The documentation for `FetchPolicy` does not actually exist. I guess it should be here, but it's not: http://dev.apollodata.com/core/apollo-client-api.html#FetchPolicy

**How to reproduce the issue:**

View the apollo-client API docs (such as for [`watchQuery`](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient.watchQuery)) and click `FetchPolicy`. Note that the page doesn't update because the section doesn't exist in the docs.

**Comment by stevewillard** [comment] 2017-04-26 21:23
I've had similar issues finding this documentation. It does exist, but it's tough to get to:
http://dev.apollodata.com/react/api-queries.html#graphql-config-options-fetchPolicy

**Comment by bgentry** [comment] 2017-04-26 22:04
Ah, it's only documented in the React section :) thanks for sharing that link.

In either case it needs to be explained in the main API docs and the link in the docs should work too.

**Comment by cesarsolorzano** [comment] 2017-04-26 23:28
yeah, this is very unfortunate. Nevertheless, there's already an open issue in apollographql/core-docs#273 so I'm closing this in favor of it 🙂

**Closed by cesarsolorzano** 2017-04-26 23:28 UTC

**Comment by benmosher** [comment] 2018-08-02 20:06
Should this be re-opened since `core-docs` is deprecated? I still can't find any docs for it.

**Comment by wtrocki** [comment] 2019-04-05 09:43
I think the problem is that many developers often land on this page which is part of getting started guide:
https://www.apollographql.com/docs/react/api/react-apollo#query-props

Adding the link to actual API reference should resolve the problem.
https://www.apollographql.com/docs/react/api/react-apollo#graphql-config-options-fetchPolicy

**Comment by wtrocki** [comment] 2019-04-05 11:36
I think that we need to add the link to reference API from the main query page:
https://www.apollographql.com/docs/react/api/react-apollo#query-props

This page list options but on a very limited basis.

**Comment by petergaultney** [comment] 2019-04-09 01:52
I don't think this should primarily be documented in react-apollo at all, unless it's react-only?

**Comment by wtrocki** [comment] 2019-04-09 08:36
As far I see there is no documentation for plain js client and Apollo documents top level frameworks like React, Angular etc. Any documentation for common parameters will be duplicated across these platforms.

**Comment by klemenoslaj** [comment] 2020-04-17 07:30
Is `fetchPolicy` now documented? I can't find it anywhere sadly.

**Comment by Sunhat** [comment] 2020-05-31 10:02
lol. bozos.

**Comment by wtrocki** [comment] 2020-05-31 10:30
@Sunhat ??

**Comment by mulho** [comment] 2020-07-15 15:22
All links posted here seem to be broken, and I still can't find what each `fetchPolicy` does :(

**Comment by cesarsolorzano** [comment] 2020-07-15 20:23
@mulho https://www.apollographql.com/docs/react/api/react/hoc/#optionsfetchpolicy
