### ISSUE TITLE
preserve cache when device loses internet connection

### ISSUE THREAD

**Issue by michaelknoch** [apollographql/apollo-client#1681] opened 2017-05-08 16:45 UTC
I am developing a react native app with react-apollo for my clientside. Im experiencing a bug when the app disconnects from the internet. Data in some of the views will be deleted and data.error will be defined. 
Unfortunately I am not able to debug what data.error actually contains, because disabling wlan on my device kills the connection to the react native packager and causes errors and crashes. 
Any suggestions about this behaviour? I am thankful for any help.

edit:
i figured out that its possible to test this behaviour in development by disabling the js remote debugger which gives me the ability to receive warning and error boxes at least. I am receiving an console.error "unhandled (in react-apollo)" right before the cache gets deleted.

**Intended outcome:**
Preserve cached data, refetch after connection returns.
Do not rerender when connection drops, rerender when connection returns.

**Actual outcome:**
Data gets deleted from cache when losing internet connection and the query even does not refetch when the connection returns.

**How to reproduce the issue:**
put your react-native app using apollo in flightmode

**Comment by helfer** [comment] 2017-05-09 01:50
@michaelknoch Which versions of apollo-client and react-apollo are you using? If your components are using polling queries, this would be a duplicate of https://github.com/apollographql/apollo-client/issues/1210.

**Comment by michaelknoch** [comment] 2017-05-09 08:51
An update to the newest `1.2.2` version of apollo-client fixed the deletion of already cached data, but another bug existed in my render function:
```js
if (data.loading || data.error) return <Loading />;
```
removing `|| data.error` fixed the problem, but i am still a little confused. What would be the best approach for displaying a loading/error view? `data.loading` and `data.error` can both be true although data is available for rendering.

maybe like this:
```js
if (!data.queriedStuff && data.error) <Error />
if (!data.queriedStuff && data.loading) <Loading />
```

@helfer

**Comment by helfer** [comment] 2017-05-12 04:21
Hey @michaelknoch, I'm glad you were able to find a solution! I'm not sure how checking for `data.error` could break anything. Can you elaborate on what breaks when you include that?

**Comment by michaelknoch** [comment] 2017-05-12 07:52
it does not actually break the code, it breaks the expected behaviour of my views.
When i turn my device into offline mode after a query was successful and the fetched data already has been rendered, data.error contains an error, i guess its something like 'connection refused' but `data.queriedAndRenderedData`still contains the data because the previous query was already successful. 

I had to rewrite my loading from:
`if (data.loading || data.error) <Error />`
to: `if (!data.queriedAndRenderedData && data.error) <Error />`

I guess this behaviour should be mentioned in the docs.

**Comment by jurajkrivda** [comment] 2017-05-23 22:55
Hi. Why do you want to show Error component to the users while data is loading? 
You can check type of error. If it is a Network Error you should display Error component with "No internet connection"  message and you should allow the user to reload the data again.

**Closed** 2017-07-29 14:30 UTC
Labels: no-recent-activity
