### ISSUE TITLE
useReactiveVar with NextJS SSR throws warning regarding useLayoutEffect (v3.3.16)

### ISSUE THREAD

**Issue by brycefranzen** [apollographql/apollo-client#8155] opened 2021-05-06 21:19 UTC
**Intended outcome:**
The application should run without throwing SSR warnings (how it did previously in v3.3.15).

**Actual outcome:**
This previously worked in v3.3.15; however, with the update to v3.3.16 a warning is thrown when using useReactiveVar on NextJS (when running SSR).

This is related to the following change: https://github.com/apollographql/apollo-client/compare/v3.3.15...v3.3.16#diff-d18b4eb7cdd4643b2a8374ae5d066ae09ddb0d219965ac5744423e87432f3d5d

```bash
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
[0]     at Header (webpack-internal:///./components/Headers/Header/index.tsx:65:3)
[0]     at div
[0]     at ThreeColumnLayout (webpack-internal:///./components/Layout/ThreeColumn/index.tsx:33:5)
[0]     at Index (webpack-internal:///./pages/index.tsx:43:70)
[0]     at ApolloProvider (/home/bryce/www/nichehacks-ui/node_modules/@apollo/client/react/context/context.cjs.js:32:21)
[0]     at MyApp (webpack-internal:///./pages/_app.tsx:43:3)
[0]     at AppContainer (/home/bryce/www/nichehacks-ui/node_modules/next/dist/next-server/server/render.js:28:909)
```

**How to reproduce the issue:**
Create a new project on NextJS, integrate with apollo and utilize `useReactiveVar` in any file that will run on SSR. Start `next dev` then watch the console for the warning message.

**Versions**
```bash
System:
  OS: Linux 5.11 Pop!_OS 20.10
Binaries:
  Node: 12.18.2 - /usr/bin/node
  Yarn: 1.22.10 - ~/www/nichehacks-ui/node_modules/.bin/yarn
  npm: 6.14.8 - /usr/bin/npm
Browsers:
  Chrome: 90.0.4430.93
  Firefox: 88.0
npmPackages:
  @apollo/client: 3.3.16 => 3.3.16 
  apollo: 2.33.1 => 2.33.1 
  apollo-upload-client: 14.1.3 => 14.1.3 
```

**Comment by brainkim** [comment] 2021-05-06 22:16
Duplicate of https://github.com/apollographql/apollo-client/issues/8124. Should be fixed in the next minor version! Sorry about the warning!

**Closed by brainkim** 2021-05-06 22:16 UTC
