### ISSUE TITLE
Query containing only fragments does not work

### ISSUE THREAD

**Issue by rlotufo** [apollographql/apollo-client#3402] opened 2018-05-04 14:29 UTC
**Intended outcome:**
Trying to query using fragments, using a query like:

```
const frag = gql`
  fragment peopleFrag on Query {
    people {
      id
      name
    }
  }
`;

const query = gql`
 query ErrorTemplate {
   ...peopleFrag
 }
${frag}
`
```

**Actual outcome:**
The query never gets sent to the graphql server

**How to reproduce the issue:**
I reproduced this using the react-apollo-error-template. Just replace the query in App.js with:

```
const frag = gql`
  fragment peopleFrag on Query {
    people {
      id
      name
    }
  }
`;

export default graphql(
  gql`
    query ErrorTemplate {
      # people {
      #   id
      # }
      ...peopleFrag
    }
    ${frag}
  `
)(App);
```

If you uncomment the three lines above, the query will work.

**Version**
- apollo-client: 2.0.1

**Comment by Lorti** [comment] 2018-05-04 16:14
Declare your `frag` without the `gql` tag.

**Comment by rlotufo** [comment] 2018-05-04 17:04
That did not work. I'm now using this and it does not work:

```
export default graphql(
  gql`
    query ErrorTemplate {
      ...peopleFrag
    }
    fragment peopleFrag on Query {
      people {
        id
        name
      }
    }
  `
)(App);
```

**Comment by rlotufo** [comment] 2018-05-16 15:13
My peopleFrag is a fragment on Query, which, from my understanding is type. So it seems I'm am adhering to the GraphQL spec. Or am I mistaken?

**Comment by stubailo** [comment] 2018-05-17 01:13
Wow! This looks like it might be quite an oversight, but it should definitely work!

**Comment by abhiaiyer91** [comment] 2018-05-17 15:46
Assigning this to myself.

So i indeed reproduce this error in the error template project. I do not reproduce this in apollo dev tools querying from graphiql. 

I also tried to write a failing test for this in AC, but nothing fails. So I'm going to look at react apollo next and report back.

**Comment by rlotufo** [comment] 2018-05-17 15:54
Awesome! Thanks for looking into it :)

**Comment by abhiaiyer91** [comment] 2018-05-18 23:04
@stubailo Looks like it, im gonna work on this tomorrow and figure out why its broken

**Comment by abhiaiyer91** [comment] 2018-05-20 03:07
This is actually an apollo-client bug. And ill have some code to address this soon.

**Comment by abhiaiyer91** [comment] 2018-05-20 05:02
The reason this happens is when AC attempts to make a query when given a `fragment on Query` it will return this data: `{ [Symbol(id)]: 'ROOT_QUERY' }`. So if you're making cache based fetch policies, AC thinks it has data for this query in cache and returns it to you. Since network-only doesnt read from cache, this bug doesnt happen

**Closed** 2018-05-29 12:00 UTC
Labels: has-reproduction

**Comment by BrentLayne** [comment] 2018-06-26 23:41
Currently seeing this issue.  Are there any plans to fix this?

**Comment by vnenkpet** [comment] 2018-09-05 08:19
I also have this same issue. Using apollo-boost 0.1.15. This should definitely work right?

**Comment by zyqxd** [comment] 2019-02-17 04:20
It seems like this issue is still present (`apollo-cache-inmemory@^1.2.10`) when apollo client is using `IntrospectionFragmentMatcher`

The fix added a check [here](https://github.com/apollographql/apollo-client/blob/eccea006873a39625328bdb5c93be474194abbeb/packages/apollo-cache-inmemory/src/fragmentMatcher.ts#L35) for `HeuristicFragmentMatcher.match`, but neglected to do so for `IntrospectionFragmentMatcher.match` [here](https://github.com/apollographql/apollo-client/blob/eccea006873a39625328bdb5c93be474194abbeb/packages/apollo-cache-inmemory/src/fragmentMatcher.ts#L111-L129).

@abhiaiyer91 would your fix also work for `IntrospectionFragmentMatcher`?

**Comment by MargaretKrutikova** [comment] 2020-01-13 10:30
I am testing out `apollo-client` `3.0.0-beta` and it doesn't seem to call a query that only contains a fragment, seems like a regression?

**Comment by Gaia-Nutrition** [comment] 2020-01-22 08:38
Experiencing the same on `3.0.0-beta.24` but tried downgrading all the way to `3.0.0-beta.12`. Same issue. A query that contains only a fragment is not being called.
My current workaround is to add a random field to the queries in question that is also part of the fragment.

**Comment by MargaretKrutikova** [comment] 2020-03-23 13:17
Is there any plan to fix this? It seems to me like a pretty serious issue resulting in unexpected bugs that are extremely difficult to trace. Appreciate any help here! :)

**Comment by northout-muzammil** [comment] 2020-05-01 11:13
Anyone please provide fix for this issue I am also facing the same.

**Comment by mikeaustin** [comment] 2020-10-21 18:34
My issue is that it doesn't see a second fragment that I created, saying the fragment doesn't exist.
I just moved the fragment definition to an inline non gql string:

const GET_TASK_DETAILS = gql`
  query TaskDetails($taskId: String) {
    story(taskId: $taskId) {
      ${fragments.taskDetails}
    }
  }
`;

Maybe it's a little less performant, but it works.
