### ISSUE TITLE
fields contained in fragment are not being returned from mocks

### ISSUE THREAD

**Issue by GWSzeto** [apollographql/apollo-client#6599] opened 2020-07-15 05:53 UTC
**Intended outcome:**
I'm trying to write some tests that involve some queries that contains fragments in them. The fields in the fragments get retrieved just fine in the local environment, but when I try to run it through jest, I get back all the fields except for the ones in the fragment

This is the testing suite file
```javascript
const mocks = [
  {
    request: {
      query: GET_APPOINTMENT_TYPES,
      variables: {
        userId: 'testId'
      },
    },
    result: {
      data: {
        getAppointmentTypes: [
          {
            id: 'testAppointmentTypeId',
            type: 'testType',
            durationInMin: 30,
            durations: [15, 30, 45],
            methods: ['VIRTUAL', 'ONSITE'],
            users: [
              {
                id: 'userId',
                firstName: 'testFirstName',
                lastName: 'testLastName',
              }
            ]
          }
        ]
      }
    }
  }
]

const TestingComponent = () => {
  const { appointmentTypes } = useGetAppointmentGql('testId')

  if (!appointmentTypes) return null
  return (
    <div>
      {appointmentTypes.id}
    </div>
  )
}

describe('AddAppointment spec', () => {
  it('renders the appropriate appointment types', async () => {
    render(
      <ProviderWrapper mocks={mocks}>
        <TestingComponent />
      </ProviderWrapper>
    )

    await waitFor(() => screen.getByText('testAppointmentTypeId'))
  })
})
```

this is the file that holds the query
```javascript
import { useQuery, gql } from '@apollo/client'

export const appointmentTypesFragments = {
  info: gql`
    fragment AppointmentTypeInfo on AppointmentType {
      id
      type
      durationInMin
      durations
      methods
    }
  `
}

export const GET_APPOINTMENT_TYPES = gql`
  query getAppointmentTypes($userId: String!) {
    getAppointmentTypes(userId: $userId) {
      ...AppointmentTypeInfo
       users {
        id
        firstName
        lastName
      }
    }
  }
  ${appointmentTypesFragments.info}
`

const useGetAppointmentTypesGql = userId => {
  const { data: appointmentTypesData } = useQuery(GET_APPOINTMENT_TYPES, {
    variables: {
      userId,
    }
  })
  console.log("appointment types: ", JSON.stringify(appointmentTypesData, null, 2))

  const appointmentTypes = appointmentTypesData?.getAppointmentTypes

  return {
    appointmentTypes
  }
}

export default useGetAppointmentTypesGql
```

This is what the expected outcome from the console log should be
```javascript
    appointment types:  {
      "getAppointmentTypes": [
        {
         "id": 'testAppointmentTypeId',
          "type": 'testType',
          "durationInMin": 30,
          "durations": [15, 30, 45],
          "methods": ['VIRTUAL', 'ONSITE'],
          "users": [
            {
              "id": "testId",
              "firstName": "testFirstName",
              "lastName": "testLastName"
            }
          ]
        }
      ]
    }
```

**Actual outcome:**
This is what is actually outputted from the console log 
```javascript
    appointment types:  {
      "getAppointmentTypes": [
        {
          "users": [
            {
              "id": "testId",
              "firstName": "testFirstName",
              "lastName": "testLastName"
            }
          ]
        }
      ]
    }
```

**Versions**
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 78.0.1
  npmPackages:
    @apollo/client: ^3.0.0-beta.41 => 3.0.0-beta.41 
    apollo-link-context: ^1.0.19 => 1.0.19 
    apollo-link-error: ^1.1.12 => 1.1.12

**Comment by benjamn** [comment] 2020-07-15 14:44
I believe the issue is that your data objects don't have `__typename` fields, so fragments with type conditions (e.g. `fragment AppointmentTypeInfo on AppointmentType`) will never match, even though the objects in question probably do have `__typename: "AppoinmentType"` in reality.

Somewhat counterintuitively, you should be able to include the `__typename` field explicitly in the `AppointmentTypeInfo` fragment itself. That way, whenever you use that fragment, the `__typename` that it needs will be fetched from the server, and the fragment will match when it's processed by the client. Then make sure you include that field in the mock data you return (just like the server would), and you should be good to go.

Normally, the `InMemoryCache#transformDocument` method will automatically add `__typename` fields to all selection sets, which prevents this problem in most cases, but in this case I suspect the original (unmodified) query is what gets passed to the mocking utility.

As a general note, the Apollo Client testing/mocking utilities are due for a substantial update now that AC3 is out. While I hope my advice above is helpful, I would really love never to have to give this kind of advice again, once we improve the mocking utilities to be smarter about this.

**Comment by GWSzeto** [comment] 2020-07-15 19:50
It's exactly as you said, once I added in the typename, it worked perfectly. Thanks so much. Now I'm trying to understand how to recognize that the data from the query has returned. Is there by chance a `hasBeenCalled` method?

**Comment by hwillson** [comment] 2021-05-04 15:27
It doesn't sound like there is an outstanding issue here, so closing. Thanks!

**Closed by hwillson** 2021-05-04 15:27 UTC
