### ISSUE TITLE
updateQueries not trigger at version 0.5.24

### ISSUE THREAD

**Issue by luckyyang** [apollographql/apollo-client#1084] opened 2016-12-23 10:36 UTC
same code will trigger `updateQueries` at version 0.5.20, not at version 0.5.24

attach my code:

```js
// graphqlModule/updateQueries/providerList.js

export const providerList = {
  userList: (prev, { mutationResult }) => {
    const result = mutationResult.data.registerWithIdentification

    return update(prev, {
      userList: {
        data: {
          $unshift: [result]
        }
      }
    })
  },
}
```

======

```js
// container.js

import { providerList as updateQueries } from 'graphqlModule/updateQueries/providerList'

  async submit() {
        const res = await mutate({ variables, updateQueries })
  }
```

**Comment by helfer** [comment] 2016-12-23 16:14
Is this the same as #1085?

The explanation is that we now remove old queries and their update functions from the store. I considered this a bugfix, so it was released as a patch. The consequence of the bugfix is that `updateQueries` only runs for queries that have an active observer. Admittedly, that's not flexible enough, so we'll have to come up with a different solution to update the cache even when a query isn't active any more.

**Comment by luckyyang** [comment] 2016-12-24 04:48
They are different issues:
- this issue is: not triggering the updateQueries after mutate at version 2.5.24
- #1085 is at version 2.5.20, updateQueries will not update the cache data

**Comment by adambard** [comment] 2017-01-05 00:40
I'm going to go ahead and +1 this guy -- for my codebase at least this was definitely a breaking change (an SPA using react-apollo), I had to go back to forceRefetch-ing. Does apollo-client/react-apollo presently provide a way to update/cache-bust a query associated with a component that is not presently mounted?

**Comment by zth** [comment] 2017-01-06 10:40
I have the same issue, I am unable to access neither updateQueries nor reducer on queries that aren't presently mounted. Is this intended? I don't see how I'd be able to update my other queries now, since they belong to different routes (which means they'll need to be unmounted when not active). I use forceRefetch right now as well, but it's a rather expensive and entirely unnecessary query that gets run now as it fetches data that hasn't changed other than the addition that I'd be able to update manually through updateQueries.

Any clues/thoughts on how we can mitigate this? Thanks!

**Comment by zth** [comment] 2017-01-08 16:07
I can confirm this works for me when I downgrade to 0.5.21. I'll just remain at that version for now, I saw this issue was brought up in another issue as well :)

**Comment by helfer** [comment] 2017-02-02 04:59
I'm going to close this here so we can track it in #1129, which was filed first. We're discussing the best design to solve this in #1224.

**Closed by helfer** 2017-02-02 04:59 UTC
Labels: bug
