### ISSUE TITLE
[BUG] useQuery race-condition bug

### ISSUE THREAD

**Issue by hakonxxx** [apollographql/apollo-client#10587] opened 2023-02-21 09:51 UTC
useQuery race condition bug, not update cache when one of multi queries done which refer same cacheId.

## Root Cause
> maybe is the root cause of #10359 

![useQuery-race-condition-bug-when-multi-queries-refer-same-cacheid](https://user-images.githubusercontent.com/91516332/220309609-3540f5ee-376f-44f6-ab62-a7fd5b9ef9ea.png)

### Suggested
```ts
const typePolicies = {
  SchemaTest: { merge: true }
}
type SchemaTest = {
  a: any
  b: any
  c: any
  d: any
}
const doc1 = gql`query get1() {
  schemaTest {
   a
   b
 }
}`
const doc2 = gql`query get1() {
  schemaTest {
   a
   c
 }
}`
const doc3 = gql`query get1() {
  schemaTest {
   b
   d
 }
}`
```
### Usage
> More easily to reproduce if fill cache with partial mock `schemaTest` data when `ApolloClient` initiation.
```ts
// assume fetchPolicy is 'cache-and-network'
const useReproduction = () => {
  useQuery(doc1)
  useQuery(doc2)
  useQuery(doc3)
}
```
### Expected Behavior
After all requests done, the cache should be the merge of doc1, doc2 and doc3.
### Actual Behavior
After all requests done, the cache could be any combinations of doc1/doc2/doc3.

## Versions
@apollo/client: 3.6.9

**Comment by jerelmiller** [comment] 2023-02-22 00:07
Hey @hakonxxx 👋 

I tried to reproduce this as best I could given the same `@apollo/client` version and was unable to do so. Check out [this codesandbox](https://codesandbox.io/s/charming-lehmann-9hx4ht?file=/src/index.jsx) for a reproduction. 

I made an effort to:
* Use the same type names
* Use the same type policy
* Name the GraphQL queries using the same operation name for the 3 queries
* Use 3 `useQuery` hooks in the same component.
* Try and simulate the race condition by randomizing the time it takes to execute each request

As you can see, the cache appears to merge all the fields correctly, even as requests complete over time.

Would you be willing to try and provide a runnable example that demonstrates failing behavior? Given the information I have here, I'm not sure I have enough to go on to figure out what might be happening.

**Comment by hakonxxx** [comment] 2023-02-22 08:13
Hi @jerelmiller , thx for reply~~

i have fork a new [sandbox](https://codesandbox.io/s/hopeful-aryabhata-u88cvf?file=/src/link.js), changes:
1. `new InMemoryCache.restore` a mock data, which is different from resolver: `{
    ROOT_QUERY: {
      __typename: "Query",
      schemaType: { __typename: "SchemaType", a: "a", b: "", c: "", d: "" }
    }
  }`
2. documents have overlap fields, for example `Record<'a' | 'b', string>` and `Record<'a' | 'b' | 'c', string>`

refresh the page several times, and you will see some situations like:
<img width="703" alt="Screenshot 2023-02-22 at 16 05 51" src="https://user-images.githubusercontent.com/91516332/220559777-e22e1875-87f8-4806-b79c-d3ac4be89976.png">
the cache is expected to be `{ __typename: "SchemaType", a: "a", b: "b", c: "c", d: "d" }` right?

BTW:
1. once `markResult` would `broadcastWatches` which call `queryInfo.setDiff`
2. but only trigger `queryInfo.notify`(which would finally call `reobserveCacheFirst`) when the `oldDiff` is diff from `newDiff`
so i mock a different cache data when init  memoryCache instance.

**Comment by hakonxxx** [comment] 2023-02-22 08:43
I doubt the usage of multi queries with overlap fields, but sometimes we just do it indeed :(

So back to this case, maybe there are better solutions instead of just discarding the maybe-staled response(what a waste and may confuse users and FE), maybe we could partially update the cache?

Also there is bug even just discarding the response(sometimes we discarded, sometimes not), because of `setTimeout`.

**Comment by phryneas** [comment] 2023-02-22 14:05
Adding a [Replay](https://app.replay.io/recording/repro-10587--f6d3d063-75a6-4a51-913c-1eb59062953f) of the problem happening here.

**Comment by dylanwulf** [comment] 2023-02-22 16:03
@hakonxxx not sure if this is helpful, but your reproduction bug seems to get fixed if you change `nextFetchPolicy` from `cache-and-network` to `cache-first`.

**Comment by hakonxxx** [comment] 2023-02-23 08:57
> @hakonxxx not sure if this is helpful, but your reproduction bug seems to get fixed if you change `nextFetchPolicy` from `cache-and-network` to `cache-first`.

Yes:
1. `queryManager.fetchQueryObservable` would call `queryInfo.observableQuery.applyNextFetchPolicy` sync after `queryManager.fetchQueryByPolicy` and the `observableQuery.fetchPolicy` changed to `cache-first`
2. when cache broadcast watches, the `queryInfo.notify` would not trigger listeners, because `queryInfo.shouldNotify` would check current `fetchPolicy`
3. which means not trigger `reobserveCacheFirst `, not discard the inflight-response

So the behavior seems more weird...

**Comment by phryneas** [comment] 2023-02-23 15:21
https://github.com/apollographql/apollo-client/blob/f75de97322a70923ecd3db37c9ffca66be847324/src/core/ObservableQuery.ts#L844

This here is the culprit.

 We have a chain of
[incoming result]
-> QueryInfo.markResult
-> ... 
-> QueryInfo.setDiff 
-> [ for other impacted queries ] notify 
-> queryInfo.oqListener
-> ObservableQuery.reobserveCacheFirst
-> ObservableQuery.reobserve
-> removing the previous observable - that still waits for the network result
-> killing the concast for that
-> asyncMap will never run into the getResultsFromLink mapping function

![image](https://user-images.githubusercontent.com/4282439/220949684-76fce19c-78ec-4f32-817f-f20f055bc38b.png)

That said, having identified the reason and knowing how to fix it are two different things. I'm gonna dig a bit deeper.

**Comment by hakonxxx** [comment] 2023-02-24 02:31
I think two things need to consider:
1. maybe contributors could discuss about what behavior is expected here
2. `setTimeout` make the behaviors random

**Comment by phryneas** [comment] 2023-02-24 14:40
Oh, we'll definitely be discussing this internally to see what's going on, this is an excellent reproduction of a race condition that should (as far as I'm concerned) not be happening.

Thank you so much for this reproduction!

**Comment by hakonxxx** [comment] 2023-04-07 03:28
seems @3.7.11 fix this bug [codesandbox](https://codesandbox.io/s/agitated-oskar-yn0fc8), appreciated~ cc @phryneas

**Comment by bignimbus** [comment] 2023-04-07 03:34
Thanks @hakonxxx 🙏🏻 closing this as resolved 🚀

**Closed by bignimbus** 2023-04-07 03:34 UTC
Labels: 🐞 bug, ✔ confirmed, 🔍 investigate, 🏓 awaiting-team-response
