### ISSUE TITLE
error: Error: Unable to resolve module ../../../../../src/graphql when running the app

### ISSUE THREAD

**Issue by Bboyredstar** [apollographql/apollo-client#9739] opened 2022-05-18 15:34 UTC
react: 17.0.2 => 17.0.2
react-native: 0.68.1 => 0.68.1
After adding @apollo/client@3.6.4 I get such error:

 BUNDLE  ./index.js

error: Error: Unable to resolve module ../../../../../src/graphql from /Users/nikolay/webdev/wm-mobile/node_modules/@apollo/client/utilities/globals/globals.cjs:

None of these files exist:
  * src/graphql(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.cjs|.native.cjs|.cjs)
  * src/graphql/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.cjs|.native.cjs|.cjs)
> 1 | 'use strict';
  2 |
  3 | Object.defineProperty(exports, '__esModule', { value: true });
  4 |
    at ModuleResolver.resolveDependency (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async addDependency (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)

I've tried all available metro.config.js variants, as well as removing it.
For example:

 const defaultSourceExts =
 require('metro-config/src/defaults/defaults').sourceExts;
module.exports = {
 transformer: {
   getTransformOptions: () => ({
     transform: {
       experimentalImportSupport: false,
       inlineRequires: true,
     },
   }),
 },
 resolver: {
   sourceExts: process.env.RN_SRC_EXT
     ? [...process.env.RN_SRC_EXT.split(',').concat(defaultSourceExts), 'cjs'] // <-- cjs added here
     : [...defaultSourceExts, 'cjs'], // <-- cjs added here
 },
};

Still the error appears.

**Comment by benjamn** [comment] 2022-05-19 18:13
Likely duplicate of #9737

**Closed by benjamn** 2022-05-19 18:13 UTC
