### ISSUE TITLE
defaultOptions do not work

### ISSUE THREAD

**Issue by helios1138** [apollographql/apollo-client#2555] opened 2017-11-13 17:32 UTC
I tried setting `defaultOptions` like this:
```js
export const apolloClient = new ApolloClient({
  link,
  cache,
  connectToDevTools: true,
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network'
    },
    query: {
      fetchPolicy: 'cache-and-network'
    }
  }
})
```

and yet re-rendering of components does not trigger refetching, however manually setting `fetchPolicy` option on a particular component does achieve the intended result

**Comment by helios1138** [comment] 2017-12-04 19:12
@jbaxleyiii is it possible to get some updates on this?

**Comment by Dygerati** [comment] 2017-12-07 21:13
I'm interested in this as well--right now I have to set the `fetchPolicy` on every request.

**Comment by neekey** [comment] 2017-12-11 06:31
not working for me neither

**Comment by henrikhaugboelle** [comment] 2017-12-13 14:02
I'm not a fan of flooding github with +1's, but I have this exact issue as well.

**Comment by tgriesser** [comment] 2017-12-18 15:38
Just opened https://github.com/apollographql/apollo-client/pull/2748 which I think should address the issue described here.

**Comment by charleyw** [comment] 2018-02-26 07:07
@tgriesser Sorry I dont understand why this not working, even i only set this.
```
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network'
    }
  }
```

**Comment by pusiekwithgun** [comment] 2018-03-22 16:56
You have to declare defaultOptions as a constant like this: 

`const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'cache-and-network',
    errorPolicy: 'all',
  },
  query: {
    fetchPolicy: 'cache-and-network',
    errorPolicy: 'all',
  },
  mutate: {
    errorPolicy: 'all',
  }
}

const client = new ApolloClient({
  link: from([
    logoutLink,
    errorsLink,
    httpLink
  ]),
  cache: new InMemoryCache(),
  defaultOptions
});
`

**Comment by anselmdk** [comment] 2018-04-06 13:08
I am having the same issue.

**Comment by jon-thompson** [comment] 2018-04-09 14:38
I'm seeing the same issue with `network-only` as well.

If I use the following `defaultOptions`, the cache still seems to be in effect:

```JS
const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'network-only',
    errorPolicy: 'all',
  },
  query: {
    fetchPolicy: 'network-only',
    errorPolicy: 'all',
  },
  mutate: {
    errorPolicy: 'all',
  },
};
```

However if I supply `fetchPolicy: 'network-only'` as an option to an individual query, the cache is not used (as expected).

**Comment by ReggaePanda** [comment] 2018-04-11 06:40
+1

**Comment by rmoorman** [comment] 2018-06-28 10:32
I can confirm that the defaultOptions are still not working with apollo-client 2.3.5 (also see #3256 for a related/duplicate issue and some findings from @zamiang).

**Comment by alarstyle** [comment] 2018-07-27 15:38
Same here, `defaultOptions` doesn't work

**Comment by hwillson** [comment] 2018-08-03 17:52
Hi all - would anyone here be able to provide a small runnable reproduction that clearly demonstrates this issue? Thanks!

**Comment by sfilipov** [comment] 2018-08-22 10:11
@hwillson in terms of reproduction steps, I'd need to sanitise some of the production code we have, but long story short, when we try to do something like the following, it doesn't work for us - the cache is used:

```
const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'network-only',
    errorPolicy: 'ignore',
  },
  query: {
    fetchPolicy: 'network-only',
    errorPolicy: 'all',
  },
}

const apollo = new ApolloClient({
    defaultOptions,
    // I tried either initialising a cache like this:
    // cache: new InMemoryCache(),
    // or not defining the cache key on the object. Both don't work for me
    uri: '/graphql/',
})

// then try to run a query directly using the apollo client
// it does not do a new network request
// instead it uses the cache
const entity_id = 1
apollo.query({
    query: load_some_info_query,
    variables: { entity_id },
})

// it is possible to force a network request if fetchPolicy is set on each query
apollo.query({
    query: load_some_info_query,
    variables: { entity_id },
    fetchPolicy: 'network-only',
})
```

apollo-client version: 2.4.0
node version 8.11.3

**Comment by moonwa** [comment] 2018-10-25 04:16
+1

**Comment by kcvin94** [comment] 2018-11-15 05:37
are default props that hard to fix? its been 1 year and 1 day lol.

**Comment by stefanholzapfel** [comment] 2018-11-15 17:11
+1

**Comment by montogeek** [comment] 2018-12-07 15:08
@kcvin94 It sounds very easy for you to fix them. Mind send a PR?

**Comment by daryn-k** [comment] 2018-12-25 18:47
Same issue

**Comment by daryn-k** [comment] 2018-12-25 20:15
Okay, guys, I think the reason is you should provide all 3 properties together:

**This code works**
```
const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'cache-and-network',
    errorPolicy: 'ignore',
  },
  query: {
    fetchPolicy: 'network-only',
    errorPolicy: 'all',
  },
  mutate: {
    errorPolicy: 'all'
  }
}
```
This code doesn't affect to options:
```
const defaultOptions = {
  query: {
    fetchPolicy: 'network-only',
    errorPolicy: 'all',
  },
  mutate: {
    errorPolicy: 'all'
  }
}
```

**Comment by daryn-k** [comment] 2018-12-25 20:39
@hwillson I think it would be much better if I can specify only one property for default options. Because now I should provide all 3 necessary properties.

**Comment by zcfan** [comment] 2019-01-31 08:14
@daryn-k Confirm your code work🎉 seems you have to declare all three of those fields to make defaultOptions works.

**Comment by SydBal** [comment] 2019-02-14 20:14
I have no issues when defining `defaultOptions` as a const above the instantiation of the `AppoloClient`.

This is the code I'm using:
```
const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'network-only'
  },
  query: {
    fetchPolicy: 'network-only'
  }
}

const client = new ApolloClient({
  ...,
  defaultOptions,
})
```

**Comment by timplummer** [comment] 2019-04-15 04:02
I can't get `defaultOptions` to work for anything.

I went looking in the source code.  The options (specifically `context` in my case) get passed into the various methods of `QueryManager` and are included if `hasClientExports` rings true. 

```
    const updatedVariables: OperationVariables =
      hasClientExports(mutation)
        ? await this.localState.addExportedVariables(
            mutation,
            variables,
            context,
          )
        : variables;
```

Problem is, `hasClientExports` is also looking for the `@export` directive.

```
export function hasClientExports(document: DocumentNode) {
  return (
    document &&
    hasDirectives(['client'], document) &&
    hasDirectives(['export'], document)
  );
}
```

Or am I reading this wrong?

**Comment by helios1138** [comment] 2019-05-09 11:34
@daryn-k it seems that when we mean to set `fetchPolicy` for queries, we actually need to set `watchQuery.fetchPolicy`. I think it's a bit confusing and should be described better in the documentation, but it works.

My config currently only has
```ts
defaultOptions: {
  watchQuery: { fetchPolicy: 'cache-and-network' },
},
```

**Comment by jbaxleyiii** [comment] 2019-07-09 20:40
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Closed by jbaxleyiii** 2019-07-09 20:40 UTC
Labels: :wilted_flower: needs-reproduction, 🚧👷‍♀️👷‍♂️🚧 in triage

**Comment by verekia** [comment] 2019-10-06 12:16
Hi :)
The issue is still the same in the latest versions:
```json
"@apollo/react-hooks": "3.1.2",
"apollo-boost": "0.4.4",
```

The following **does** successfully use `network-only`:

```js
defaultOptions = {
    watchQuery: { fetchPolicy: 'network-only', errorPolicy: 'all' },
    query: { fetchPolicy: 'network-only', errorPolicy: 'all' },
    mutate: { errorPolicy: 'all' },
}
```

This (which would be much nicer) does not work and uses the cache:
```js
defaultOptions = {
    query: { fetchPolicy: 'network-only' },
}
```

**Comment by JClackett** [comment] 2020-04-14 16:34
Still have the same issue:

"@apollo/client": "3.0.0-beta.43"

 React client side app

```ts
const client = new ApolloClient({
  link: concat(authMiddleware, httpLink),
  cache: new InMemoryCache(),
  defaultOptions: {
    watchQuery: { errorPolicy: "all" },
    mutate: { errorPolicy: "all" },
    query: { errorPolicy: "all" },
  },
})
```

Default options not working

If if provide errorPolicy to the useMutation hook, then it works?

**Comment by mrjamesjcho** [comment] 2020-06-04 04:17
I also have the same issue:
"@apollo/client": "3.0.0-beta.41"

If I provide `errorPolicy` in `useMutation` and `useQuery` it works but it would be great if I didn't have to do it for every mutation and query.

This may be related but I would also want `refetchQueries` to use `defaultOptions`

**Comment by JClackett** [comment] 2020-06-04 08:45
@jbaxleyiii i think this needs to be reopened?

**Comment by jimwheaton** [comment] 2020-06-18 20:57
It's possible this PR introduced the error. 

https://github.com/apollographql/apollo-client/pull/5863/files

From what I can tell, if you do not define an `errorPolicy` on the mutation itself, then an object with 

```
{
   errorPolicy: undefined
}
```

gets passed in here (line 101 of MutationData.ts):
https://github.com/apollographql/apollo-client/pull/5863/files#diff-93aa5dbc2696fb1257210a16aeac6e82L101

In `ApolloClient`, it will merge `errorPolicy: undefined` with the default `errorPolicy` set on `ApolloClient`, effectively wiping out the top-level default:

ie. `options` passed to this function will be `{ ..., errorPolicy: undefined, ... }`
```
ApolloClient.prototype.mutate = function (options) {
        if (this.defaultOptions.mutate) {
            options = __assign(__assign({}, this.defaultOptions.mutate), options);
        }
        return this.queryManager.mutate(options);
    };
```

**Comment by jimdwyerdev** [comment] 2020-06-23 16:41
There seems to be an issue with the constructor. 
A "fix" is to assign the client.defaultOptions after the ApolloClient is created:

`	const client = new ApolloClient({
		credentials: 'include',
	})

	client.defaultOptions = {
		watchQuery: {
			fetchPolicy: 'network-only',
		},
	}
`

**Comment by electerious** [comment] 2021-05-02 17:32
2021 update: **This issue hasn't been fixed and it's still a problem.**

Settings defaults for all 3 properties—as suggested by @daryn-k—is still the preferred workaround: https://github.com/apollographql/apollo-client/issues/2555

**Comment by IsaacTrevino** [comment] 2021-12-08 17:40
+1 with @apollo/client@3.5.6

**Comment by chillyistkult** [comment] 2021-12-10 00:02
4 years later its still broken with latest apollo client.

**Comment by ApostleDreSong** [comment] 2021-12-10 17:55
This is still not working for Apollo client ^3.3.20
Default options we are using is: 
  const defaultOptions = {
    watchQuery: {
      fetchPolicy: "network-only",
      nextFetchPolicy: "network-only",
    },
    query: {
      fetchPolicy: "network-only",   // Used for first execution
      nextFetchPolicy: "network-only",
    },
    mutate: {
      fetchPolicy: "network-only",   // Used for first execution
      nextFetchPolicy: "network-only",
    }
  }
Despite having the defaultOptions, we have to add the network-only policy for each query which is not ideal

**Comment by jimdwyerdev** [comment] 2021-12-10 19:48
@ApostleDreSong see [this](https://github.com/apollographql/apollo-client/issues/2555#issuecomment-648280766)

I haven't tested in the latest apollo but it should prevent you from having to define network-only policy for each query

**Comment by ApostleDreSong** [comment] 2021-12-10 19:56
> ```
> 	const client = new ApolloClient({
> ```

@jimdwyerdev this is not working for me

**Comment by yasharzolmajdi** [comment] 2021-12-16 07:56
so looking at the code with the latest release
useQuery will eventually call the following function which will merge the option passed to useQuery with the default options
```
ApolloClient.prototype.watchQuery = function (options) {
  if (this.defaultOptions.watchQuery) {
    options = mergeOptions(this.defaultOptions.watchQuery, options);
  }
  if (this.disableNetworkFetches && (options.fetchPolicy === 'network-only' || options.fetchPolicy === 'cache-and-network')) {
    options = __assign(__assign({}, options), { fetchPolicy: 'cache-first' });
  }
  return this.queryManager.watchQuery(options);
};
```
the issue here is that if you don't define fetchPolicy in your options when you call `useQuery` it defaults to `cache-first` which then overwrites the default options on `mergeOptions` as shown above
the default value of `cacheFirst` is being set in `createWatchQueryOptions`
```
...
else if (!watchQueryOptions.fetchPolicy) {
  watchQueryOptions.fetchPolicy = 'cache-first';
}
...
```

**Comment by alxhotel** [comment] 2021-12-24 17:56
The problem that @yasharzolmajdi has mentioned is still occurring.

IMHO this bug is urgent.

**Comment by sgentile** [comment] 2022-01-03 17:39
Still a huge issue here

**Comment by benjamn** [comment] 2022-01-10 21:04
This should be fixed thanks to #9210 in `@apollo/client@3.5.7` (published earlier today)!

**Comment by markedwards** [comment] 2022-01-25 12:34
This does not appear to be fixed, at least in my case.  Using `@apollo/client@3.5.8` with NextJS and `useQuery`.  The client is created like this:
```
new ApolloClient({
  cache: new InMemoryCache(),
  defaultOptions: {
    watchQuery: {
      fetchPolicy: "network-only",
      errorPolicy: "all",
    },
    query: {
      fetchPolicy: "network-only",
      errorPolicy: "all",
    },
    mutate: {
      fetchPolicy: "network-only",
      errorPolicy: "all",
    },
  },
})
```
And then it is passed to `ApolloProvider`.  I can see that the defaultOptions are present in the client that is returned by `useQuery`, but the client uses `"cache-first"` instead of `"network-only"`.  The behavior is correct if I manually set `fetchPolicy` when calling `useQuery`.

**Comment by hoangbn** [comment] 2022-10-15 19:33
Still doesn't work in 3.6.6:

```
defaultOptions: {
    query: {
      errorPolicy: "all"
    }  
  }
```
