### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by jonatan-blossom** [apollographql/apollo-client#11259] opened 2023-09-28 21:26 UTC
### Issue Description

When my Query intentionally return a Error on the useLazyQuery, the mobile app crash.
error version "@apollo/client": "^3.8.4"
with the version "@apollo/client": 3.7.17 It works good.
![Screenshot 2023-09-28 at 4 22 41 PM](https://github.com/apollographql/apollo-client/assets/79993534/0a114a97-cff7-44c2-a7e0-f8e3299df782)
[](url)

### Link to Reproduction

withoutlink.com

**Comment by phryneas** [comment] 2023-09-29 09:03
Thanks for the bug report!

We are already aware of this one, and it will be fixed soon over in #11252.

Meanwhile, you can use the build from that issue in your application:

```sh
npm i @apollo/client@0.0.0-pr-11252-20230926140534
```

**Comment by phryneas** [comment] 2023-09-29 09:04
(Closing as duplicate of #11149 )

**Closed by phryneas** 2023-09-29 09:04 UTC
