### ISSUE TITLE
Cannot update cache after update an item.

### ISSUE THREAD

**Issue by phuongthuan** [apollographql/apollo-client#4055] opened 2018-10-25 09:13 UTC
Hi everyone,

I'm using apollo-client with react-apollo.
When update an item in form, I'm trying to update cache using `update` props in `Mutation` component like this:

Mutation:
```
const UPDATE_DAILY_REPORT_QUERY = gql`
  mutation UPDATE_DAILY_REPORT_QUERY(
      $id: ID!
      $title: String
      $emotion: String
      $achievement: String
      $plan: String
      $comment: String
  ) {
    updateDailyReport(
      id: $id
      title: $title
      emotion: $emotion
      achievement: $achievement
      plan: $plan
      comment: $comment
    ) {
      id
    }
  }
`;

```

I'm using `Formik`,  here is `update` function: 

```
update={(store, { data: { updateDailyReport } }) => {
            const data = store.readQuery({ query: DAILY_REPORTS_QUERY });

            data.userReports = data.userReports.map(report => report.id === updateDailyReport.id
              ? updateDailyReport
              : report
            );

            store.writeQuery({ query: DAILY_REPORTS_QUERY, data });
          }}
```

Output:

```

DailyReport before update 
(6) [{…}, {…}, {…}, {…}, {…}, {…}]
0: {id: "cjncwcph94ux70b94ez52slyi", emotion: null, title: "So many boring time. huhu", achievement: "ZXczxc", plan: "I have not done anything.", …}
1: {id: "cjncweexf4v0r0b940ocfitzk", emotion: null, title: "Give me energy, please.", achievement: "Nothing", plan: "Continue relax and play some online game.", …}
2: {id: "cjncwvhim4vzb0b94vwhh57ap", emotion: null, title: "Good day, good good day.", achievement: "NO thing", plan: "Do create report page.", …}
3: {id: "cjnd0bds253kn0b940ouh3ydq", emotion: null, title: "Today is a bad day. A black day", achievement: "Nothing", plan: "Continue fix bug.", …}
4: {id: "cjnjmz2tu90t70b945qukqgoo", emotion: null, title: "Daily report - 22/10/2018", achievement: "Completed create daily reporting in Server.", plan: "Create daily report form in Client.", …}
5: {id: "cjnjs8fvc9jvh0b9412co5vkc", emotion: null, title: "I feel like giving up", achievement: "Today, I've created new pull request for updating report and creating reporting.", plan: "Continue to build the next features.", …}
length: 6
__proto__: Array(0)

---------------

DailyReport after update 
(6) [{…}, {…}, {…}, {…}, {…}, {…}]
0: {id: "cjncwcph94ux70b94ez52slyi", emotion: null, title: "So many boring time. huhu", achievement: "ZXczxc", plan: "I have not done anything.", …}
1: {id: "cjncweexf4v0r0b940ocfitzk", emotion: null, title: "Give me energy, please.", achievement: "Nothing", plan: "Continue relax and play some online game.", …}
2: {id: "cjncwvhim4vzb0b94vwhh57ap", emotion: null, title: "Good day, good good day.", achievement: "NO thing", plan: "Do create report page.", …}
3: {id: "cjnd0bds253kn0b940ouh3ydq", emotion: null, title: "Today is a bad day. A black day", achievement: "Nothing", plan: "Continue fix bug.", …}
4: {id: "cjnjmz2tu90t70b945qukqgoo", emotion: null, title: "Daily report - 22/10/2018", achievement: "Completed create daily reporting in Server.", plan: "Create daily report form in Client.", …}
5: {id: "cjnjs8fvc9jvh0b9412co5vkc", __typename: "DailyReport"}
length: 6
__proto__: Array(0)

```

But I checked in cache. it didn't update.
![screen shot 2018-10-25 at 4 12 13 pm](https://user-images.githubusercontent.com/20045189/47489446-d833a480-d870-11e8-9c35-c92611f28a33.png)

What did I wrong here ?

**Comment by benjamn** [comment] 2018-11-01 13:44
Please try upgrading your packages to the latest versions (`apollo-client@2.4.5`, `apollo-utilities@1.0.25`, `apollo-cache-inmemory@`1.3.8`, etc.), and, if that doesn't help, create a reproduction in CodeSandbox. There's not much we can do to help you, otherwise.

**Comment by phuongthuan** [comment] 2018-11-06 07:47
@benjamn Thank for reply.
But I've solved this issue. This is what I've done:

In `UPDATE_DAILY_REPORT_QUERY`, before I got this problem, I just return an `id` when I update an item, like this:

```
const UPDATE_DAILY_REPORT_QUERY = gql`
  mutation UPDATE_DAILY_REPORT_QUERY(
  $id: ID!
  $title: String
  $emotion: String
  $achievement: String
  $plan: String
  $comment: String
  ) {
    updateDailyReport(
      id: $id
      title: $title
      emotion: $emotion
      achievement: $achievement
      plan: $plan
      comment: $comment
    ) {
      id
    }
  }
`;
```
And the `cash` not update. 

After that, I tried to return all field instead of just `id`, like this:
```
const UPDATE_DAILY_REPORT_QUERY = gql`
  mutation UPDATE_DAILY_REPORT_QUERY(
  $id: ID!
  $title: String
  $emotion: String
  $achievement: String
  $plan: String
  $comment: String
  ) {
    updateDailyReport(
      id: $id
      title: $title
      emotion: $emotion
      achievement: $achievement
      plan: $plan
      comment: $comment
    ) {
      id
      title
      emotion
      achievement
      plan
      comment
      createdAt
    }
  }
`;
```

And It worked. Could you please tell me that I correct or not?, Thank you.

**Comment by Eldavid** [comment] 2018-12-27 20:41
@phuongthuan you find another way to update cache? I mean return with all fields is quite repetitive.

**Comment by Eldavid** [comment] 2018-12-27 21:17
@phuongthuan you shouldn't return with all of your data. Here is my solution:
```js
<Formik onSubmit={async (values, { setSubmitting }) => {
    await updateUser.mutation({
    variables: values,
    update: (cache) => {
        const data = cache.readQuery({ query: CURRENT_USER_PROFILE_QUERY });
        data.me = values;
        cache.writeQuery({ query: CURRENT_USER_PROFILE_QUERY, data });
    },
    });
}}>
```

You can read more about updating cache after mutation [here](https://www.apollographql.com/docs/react/advanced/caching.html#after-mutations).

**Comment by danilobuerger** [comment] 2019-01-17 19:50
Closing since OP has resolved the issue:
> But I've solved this issue.

**Closed by danilobuerger** 2019-01-17 19:50 UTC
