### ISSUE TITLE
Uncaught TypeError: Cannot read property 'markMutationError' of undefined

### ISSUE THREAD

**Issue by lifeiscontent** [apollographql/apollo-client#4166] opened 2018-11-22 02:02 UTC
**Intended outcome:**
when running a query which returns 40x status code it works

**Actual outcome:**

this line 

https://github.com/apollographql/apollo-client/blob/c3561e73957799bbf0d7f87c4a3ebcfee6f40e3a/packages/apollo-client/src/core/QueryManager.ts#L219

is run and the function is `undefined`

**How to reproduce the issue:**

I created a mutation on the server which returns a statusCode of 409

**Versions**

    apollo-cache-inmemory: alpha => 1.4.0-alpha.1
    apollo-client: alpha => 2.5.0-alpha.1
    apollo-link-error: ^1.1.2 => 1.1.2
    apollo-link-http: ^1.5.5 => 1.5.6
    react-apollo: alpha => 2.3.0-alpha.0

**Comment by lawrenceforsytheiii** [comment] 2018-11-26 23:18
I've hit the same issue while following the fullstack-tutorial: https://github.com/apollographql/fullstack-tutorial

**Comment by pyramation** [comment] 2018-11-29 13:39
I'm also running into this issue, anyone from Apollo team have insights on this?

**Comment by hwillson** [comment] 2018-11-29 14:19
Can anyone here provide a small runnable reproduction that shows this happening? We're not seeing it in the [tutorial](https://github.com/apollographql/fullstack-tutorial), so any reliable steps we can follow to re-create this, would definitely help with troubleshooting. Thanks!

**Comment by lawrenceforsytheiii** [comment] 2018-11-29 20:38
@hwillson - So you're telling me you can take the final/server directly from the tut repo, without adding any further config, run `npx now`... and the graphql playground is running and available at the url returned by the now cli?

For me this just builds a directory at that url, no running graphql server. So when the client tries to communicate it can not.

I was able to actually get the server running on deployment by specifying Now v1 instead of the default v2. I assume this has something to do with the serverless/lambda function architecture of v2. 

I also assume that there is some form of now.json Builder magic that we can implement to get this to run as is in v2... I just haven't found it yet.

But if you say this works as is, I am at a loss and would like to know which version of the now cli you are running. I'm on 6.4.1.

Thanks

**Comment by hwillson** [comment] 2018-12-01 15:30
@lawrenceforsytheiii The original poster didn't mention `now`, so my request for a repro is relating to trying to pinpoint this error without introducing a third party we don't control (e.g. `now`). It sounds like this issue is happening outside of `now` integration, and if so let's track it down (and fix it) there.

**Comment by lifeiscontent** [comment] 2018-12-02 04:04
@hwillson do you have a suggestion of where I can create an example graphql server? It happens 100% of the time when I return a resolver with a statusCode of 40x

**Comment by lifeiscontent** [comment] 2018-12-02 04:04
@hwillson and the reason why you didn't see it in the example is because peggy didn't implement any edge cases on which there would be an error with status codes.

**Comment by lawrenceforsytheiii** [comment] 2018-12-03 18:07
@hwillson - The reason I mentioned it was because I was running into the exact same issue... and it was because the server wasn't deployed and running correctly in `now` v2. The error occurs when the client can't communicate with the server. I was able to get around this by specifying and deploying to `now` v1 instead (not `serverless`/`lambda` architecture). Since this is clearly a deployment issue with the tutorial and I can recreate directly from [final](https://github.com/apollographql/fullstack-tutorial/tree/master/final) and the tutorial uses `now`... Do you have a suggestion as an alternative to `now` v2 or can you update the tutorial with a proper [Builder](https://zeit.co/docs/v2/deployments/builders/overview#when-to-use-builders) to handle this specific deployment? Just trying to save people some headache. Thanks

**Comment by danilobuerger** [comment] 2019-01-29 18:40
Closing as no reproduction was provided in one week. Feel free to reopen if you have a minimal reproduction.

**Closed by danilobuerger** 2019-01-29 18:40 UTC
Labels: reproduction-needed
