### ISSUE TITLE
Testing query + mutation in MockProvider doesn't seem to update the cache

### ISSUE THREAD

**Issue by darryltec** [apollographql/apollo-client#8942] opened 2021-10-18 22:38 UTC
Hi, I'm having a bit of an issue with testing.

My query returns 2 messages which renders 2 elements on the UI. I have a mutation which removes 1 of the 2 messages on the UI. It works well on the browser and I can see that it is removing the message that I wanted to remove. 

However, when writing a test for the UI using the mock provider like so
```jsx
<MockProvider mocks={[query, mutation]} />
```
On first run, it does render what I want. However, firing the mutation fails the test as the element doesn't seem to be removed. I've confirmed on other tests that the mutation does fire and returns the value I want. It doesn't seem to update the cache after the mutation during the test.

**Intended outcome:**

- After the mutation, it should update the list of messages to be only 1

**Actual outcome:**

- After the mutation, it's still showing 2 messages from the original query

**How to reproduce the issue:**

```jsx
// Component.tsx

function Component() {
  const { data, error, loading } = useQuery(QUERY);
  const [handleRemove] = useMutation(MUTATION, {
    update(cache, { data }) {
      // update cache here
    },
  });

  if (error ?? loading) return <></>;

  return (
    <>
      {data.messages.map(data => (
        <p key={data.id}>
          {data.name}
          <button
            onClick={() => handleRemove({ variables: { id: data.id } })}
          />
        </p>
      ))}
    </>
  );
}
```

```jsx
// Component.test.tsx

const query = {
  request: { query: QUERY },
  result: {
    data: {
      messages: [firstMessage, secondMessage],
      },
    },
  },
};

const mutation = {
  request: {
    query: MUTATION,
    variables: {
      id: firstMessage.id,
    },
  },
  result: {
    data: {
      messages: {
        nodes: [secondMessage],
      },
      errors: [],
    },
  },
};

it("updates the list of messages after a mutation", async () => {
  const { getByText, queryByText, getAllByRole } = render(
    <MockRouted mocks={[query, mutation]} addTypename={false} cache={cache} defaultOptions={/*turn off the cache*/}>
      <Component />
    </MockRouted>,
  );

  // Assume we've done the await promise and waitFor

  expect(getByText("Message one")).toBeInTheDocument(); // pass
  expect(getByText("Message two")).toBeInTheDocument(); // pass

  fireEvent.click(getAllByRole("button")[0]); // run mutation

  expect(queryByText("Message one")).not.toBeInTheDocument(); // fail
  expect(getByText("Message two")).toBeInTheDocument(); // pass
});
```

**Versions**

@apollo/client: 3.3.16

**Comment by brainkim** [comment] 2021-10-20 15:35
@darryltec Can you show the definitions of `firstMessage` and `secondMessage`? Alternatively, do you have a reproduction of the misbehavior you’re seeing? One guess is that `__typename` isn’t in the mocked response data. The cache doesn’t really know how to normalize results without `__typename` properties in data, as you would receive from a well-formed server response.

**Comment by alessbell** [comment] 2023-12-18 19:45
Hi @darryltec 👋 I am not able to reproduce this issue - I know it's been quite some time since you've opened it, so I'll go ahead and close it for now. If you're still experiencing it and have a runnable reproduction or additional information to share, feel free to comment and I can reopen it 👍  Thanks!

**Closed by alessbell** 2023-12-18 19:45 UTC
Labels: :wilted_flower: needs-reproduction, 🔬 testing-utilities
