### ISSUE TITLE
Cannot read property 'data' of undefined when using `useLazyQuery`

### ISSUE THREAD

**Issue by stretch0** [apollographql/apollo-client#11251] opened 2023-09-26 11:01 UTC
### Issue Description

When using `useLazyQuery` and I expect an error to be returned from the server, ApolloClient appears to crash as it can't read `result.data`.

![image](https://github.com/apollographql/apollo-client/assets/66245546/26fbacaf-8727-4cf4-beab-7d67eb81d3ab)

You can see in the code, I am using SpaceX's API: https://spacex-production.up.railway.app/

I am then running a lazy query where I pass in an invalid query variable which causes the server to return an error (this works in the [explorer](https://studio.apollographql.com/public/SpaceX-pxxbxen/variant/current/explorer) all ok. 

When I click the button to trigger my query, it casues the apollo client error to be thrown. I would expect the error from the server to be surfaced from `useLazyQuery`. 

I am using 
node 20
"@apollo/client": "^3.8.4",

### Link to Reproduction

https://github.com/stretch0/apollo-client-native-sandbox

### Reproduction Steps

Setup app

Using node v20

```
npm install
npm run android
```

Once app loads, click the `PRESS ME` button.

Note Apollo Client throws an error complaining it can't read property `data` of undefined.

https://github.com/apollographql/apollo-client/assets/66245546/dc1abe17-0c95-4514-9b80-b22ef1106554

I have also tested this same query using the `useQuery` hook and it just seems to show `loading: true` the whole time, rather than returning an error. I would expect an error to be returned form the `useQuery` hook. 

Any help in understanding this issue with surfacing the correct error would be greatly appreciated. Thanks

**Comment by stretch0** [comment] 2023-09-26 11:08
I have just rolled back to version `"@apollo/client": "^3.6.9"` and it seems to work as expected. Is this a bug in newer version or expected behaviour?

**Comment by phryneas** [comment] 2023-09-26 11:43
This is a duplicate of #11149 and will be fixed in #11249

**Closed by phryneas** 2023-09-26 11:43 UTC
