### ISSUE TITLE
graphQLErrors not populated in thrown ApolloError during 400 NetworkError

### ISSUE THREAD

**Issue by ryall** [apollographql/apollo-client#6222] opened 2020-04-30 17:32 UTC
The `graphQlErrors` property of `ApolloError` is not populated with the error details when a schema required field is not supplied during a mutation. However, the error is sent correctly to `onError()`.

**Intended outcome:**
`ApolloError.graphQLErrors` to be populated with the GraphQL error information

**Actual outcome:**
`ApolloError.graphQLErrors` is an empty array 

**How to reproduce the issue:**
- Begin with the schema:
```gql
type Mutation {
  someAction(requiredParam: String!): Boolean
}
```
- Use `apolloClient.mutate(...)` to call `someAction` without specifying the `requiredParam`
- In the thrown `ApolloError`, only the `networkError` property is set. 
  - The `networkError` is: `ServerError: Response not successful: Received status code 400`.
  - The `graphQLErrors` is not set.
- However, when using `onError` in `apollo-link-error`, both the `networkError` and the `graphQLErrors` properties are populated correctly.

**Versions**

```
  System:
    OS: Linux 4.19 Ubuntu 18.04.3 LTS (Bionic Beaver)
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.12.0 - /usr/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
  npmPackages:
    apollo-cache-inmemory: ^1.6.5 => 1.6.5
    apollo-client: ^2.6.8 => 2.6.8
    apollo-link-error: ^1.1.13 => 1.1.13
    apollo-link-http: ^1.5.17 => 1.5.17
    apollo-server: ^2.12.0 => 2.12.0
```

**Comment by hwillson** [comment] 2020-05-21 12:46
@ryall Any chance you could try out `@apollo/client@beta` to see if this issue still occurs? If it does, could you please provide a small runnable reproduction?

**Comment by r0ughnex** [comment] 2020-10-26 06:22
I can confirm that this happens in version `3.2.5` as well. The `graphQLErrors` are present in custom the `onError(({ graphQLErrors, networkError })` link, but when it is read within the `error` object via a `useMutation` hook within a component, it is set to an empty array `[]` 😢
![graphQLErrors_Empty](https://user-images.githubusercontent.com/7619803/97139853-83083180-17af-11eb-9814-88fd7be5c225.png)

**Comment by dt665m** [comment] 2020-11-23 06:41
Confirmed here on ```3.3.0-rc.2``` using a ```400 status code``` useQuery hook.  I can access the graphql errors through ```error.networkError?.result.errors``` but ```error.graphQLErrors``` is an empty array.  Sorry I am unable to make a repro project at the moment.

**Comment by tlin108** [comment] 2021-02-18 17:41
Thanks @dt665m for that trick above
I was able to get my `graphqlErrors` that way. And it seems like the error object might be recreated here (https://github.com/apollographql/apollo-client/blob/main/src/core/QueryManager.ts#L227-L240) which might explains why graphQLErrors was empty because it re-assign that error to `networkError`?

**Comment by hwillson** [comment] 2021-04-30 18:54
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by TriPSs** [comment] 2021-05-03 14:03
This is still the case with `3.3.16` @hwillson.

**Comment by hwillson** [comment] 2021-05-04 00:04
Any chance you could provide a small runnable reproduction that shows this @TriPSs?

**Comment by TriPSs** [comment] 2021-05-05 06:53
@hwillson sorry not anytime soon, for now I changed that the backend wont throw the errors with an 4xx status code.

**Comment by ParallelUniv3rse** [comment] 2021-05-06 09:54
Bumped into the same issue. HttpLink rejects non-2xx responses with ServerError because of a failed `parseAndCheckHttpResponse` check. 
That rejection ServerError is then added as `networkError`, even though the response contains an `errors` field containing the GraphQLErrors, which should be added too.

**Comment by hwillson** [comment] 2021-05-06 09:55
@ParallelUniv3rse any chance you can provide a runnable repro?

**Comment by ParallelUniv3rse** [comment] 2021-05-06 10:31
@hwillson 
Here it is: https://codesandbox.io/s/hardcore-snyder-kifgs?file=/src/App.js

If you were to add an `ErrorLink` in to the ApolloClient you would also see that `GraphQLErrors` is correctly populated. 
It's only after the errors get basically wrapped by a `ServerError` in `HttpLink` they get lost deeper down in the error object.

**Comment by fabis94** [comment] 2021-07-16 15:32
I've ran into the same issue. Is it expected behaviour that if the response has a status code of 4xx the `graphqlErrors` field isn't filled? Or is it a bug?

**Comment by benjamn** [comment] 2021-07-16 20:36
Possibly related: #8503

**Comment by Leolik** [comment] 2021-09-17 13:53
still reproduced in `3.4.11`

**Comment by MrDoomBringer** [comment] 2022-06-30 23:08
I believe this issue is happening because the server's response to the useMutation call doesn't result in a `"data"` field, meaning it gets interpreted as a NetworkError. 

That would make this one of many issues related to #9870, so I plan to close this as a duplicate to try and keep discussion in a single place. If you think this issue is unrelated, please let me know and we can keep this open. Thanks a ton :)

**Closed** 2022-09-12 12:45 UTC
Labels: :wilted_flower: needs-reproduction
