### ISSUE TITLE
local `@client` field policy read function not triggered

### ISSUE THREAD

**Issue by wallzero** [apollographql/apollo-client#9053] opened 2021-11-12 23:25 UTC
**Intended outcome:**

[Following the documentation](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#the-read-function) I tried creating a read policy for local data. For example:

```gql
query Query {
	client @client {
		online {
			timestamp
		}
	}
}
```

I have setup read policies for each for example:

```ts
export default {
	ClientOnline: {
		fields: {
			online: {
				read () {
					/* return something */
				}
			}
		}
	}
}
```

Now I expect the read function to return the value to my components when queried.

**Actual outcome:**

Instead, my component receives `undefined` and the read function is never actually called. 

**How to reproduce the issue:**

It turns out if the cache is empty, the local `@client` read field policies are never triggered and silently ignored without error. If I preload my cache when the application loads using the query above - then the read function is called. For example, when setting up the Apollo Client:

```ts
cache.writeQuery({
	data: {
		client: {
			__typename: 'Client',
			online: {
				__typename: 'ClientOnline',
				timestamp: null
			}
		}
	},
	query: Query
});
```

Then read policies on local fields will be called.

Prepopulating the cache isn't the issue. Often when a user first loads an application there should be some sane defaults. 
The issue is a readQuery should always trigger the field policies even if the cache is empty - *or at least throw some error or warning*. I had to spend a lot of time troubleshooting why a new local item I was querying with `@client` wasn't triggering the field policy `read` function.

**Versions**

```
System:
	OS: Linux
Binaries:
	Node: 16.11.1
	Yarn: 1.22.17
	npm: 7.24.2
	@apollo/client: 3.4.17
Browsers:
	Firefox
```

**Comment by dylanwulf** [comment] 2021-11-14 20:10
The problem is that apollo client has no way of knowing that querying the `client` field should use the `ClientOnline` type policy. Try this for your type policy instead:
```javascript
export default {
	Query: {
		fields: {
			client: {
				read () {
					/* return something */
				}
			}
		}
	}
}
```

**Comment by DmitryMasley** [comment] 2021-11-25 21:17
Also, you defined `online` field in `ClientOnline` type. But when you write a query object
```
{
	__typename: 'ClientOnline',
	timestamp: null
}
```
it doesn't have `online` field.
Probably you wanted to define the field for `Client` type.

**Comment by bignimbus** [comment] 2022-12-02 15:26
Hi all, I'm doing some cleanup.  I recommend trying the suggestions above, that should resolve the issue.  Closing for now, let us know if you need more support 🙏🏻  Thanks a bunch!

**Closed by bignimbus** 2022-12-02 15:26 UTC
