### ISSUE TITLE
Query returns objects with different identities even though data hasn't changed

### ISSUE THREAD

**Issue by jsslai** [apollographql/apollo-client#4054] opened 2018-10-25 06:31 UTC
I have a query which returns array of objects. On the UI I'm skipping rendering if single object has same identity `oldObject === newObject`. Now ApolloClient seems to always return objects with different identities.

**Intended outcome:**
Query returns objects with same identities because nothing changed.

**Actual outcome:**
Objects have different identities.

**How to reproduce the issue:**
Small repro where objects are compared to previous result: https://codesandbox.io/s/4w73lqw097

**Versions**
apollo-client: ^2.4.3 => 2.4.3 
apollo-cache-inmemory: ^1.3.6 => 1.3.6 
apollo-link-state: ^0.4.2 => 0.4.2

**Comment by benjamn** [comment] 2018-10-26 19:58
This is likely a combination of https://github.com/apollographql/apollo-client/pull/4032/commits/e66027c5341dc7aaf71ee7ffcba1305b9a553525 (which clones the `lastResult` to protect against mutation) and the fact that we still pass that `previousResult` object into `InMemoryCache#diff` when broadcasting watches [here](https://github.com/apollographql/apollo-client/blob/d6a673fbc1444e115e90cc9e4c7fa3fc67bb7e56/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L345). This logic was updated recently in https://github.com/apollographql/apollo-client/pull/4032/commits/d6a673fbc1444e115e90cc9e4c7fa3fc67bb7e56 because the `===` check was not sufficient to establish that nothing has changed, but I can understand why it gets in the way of your design. In all likelihood, the `newData.result` object is `===` to your previous result, but the `previousResult` (which is only `isEqual` to `newData.result`) overrides it.

I believe we should be able to remove the `previousResult` logic altogether, but the last time we tried that some folks reported missing broadcasts. A lot has changed since then, so maybe it's time to try again… or possibly make this behavior configurable/opt-in.

**Comment by benjamn** [comment] 2018-10-26 21:00
@jsslai I can confirm that #4069 will fix your reproduction, though it seems to have broken some tests that expect the query observable `next` method to be fired a certain number of times. Not sure exactly what changed there, but I will figure it out.

**Comment by jsslai** [comment] 2018-10-29 06:43
Thanks! I think many React apps do shallow equality checks and this has affect on performance. Missing broadcasts is a problem but I can't think of a use case where app needs to get a broadcast when nothing changed (data, status or error).

**Comment by benjamn** [comment] 2018-10-30 15:29
This should be fixed by `apollo-client@2.4.5`!

**Closed by benjamn** 2018-10-30 15:29 UTC
