### ISSUE TITLE
Apollo client executes for 1000 milliseconds on React-Native worker thread during single mutation

### ISSUE THREAD

**Issue by petergaultney** [apollographql/apollo-client#4658] opened 2019-04-03 03:04 UTC
**Intended outcome:**
Have a performant React Native application that performs mutations without locking up the JS thread.

**Actual outcome:**
Apollo seems to block the main JS worker thread for ~1000ms any time I perform a mutation. It's obviously doing lots of things, most of which seem to have to do with trying to read and write the cache, but it's unclear to me why it would be necessary to do all this work for a single mutation, and why it is necessary to completely block the thread while doing so.

The following screenshot shows the "after-effects" of a single "updateJob" mutation. I'm using `cache-and-network`, which does mean two responses to the mutation, but the responses to the mutation don't come until the last 100 ms of this trace.

<img width="1643" alt="Screenshot 2019-04-02 21 50 19" src="https://user-images.githubusercontent.com/549720/55449505-6be06e00-5591-11e9-8867-b361a9f5cb19.png">

This is an example of the data item being updated, as returned from the mutation. 
[example_job_pp_json.txt](https://github.com/apollographql/apollo-client/files/3036700/example_job_pp_json.txt)

**How to reproduce the issue:**
Unfortunately I'm not clear on what, exactly, is going on in the bowels of the Apollo code, so I'm not sure how to reproduce it outside my own application. I'm simply executing a mutation and then watching as my app locks up for nearly a second. I'm hoping that these profiling screenshots will make it possible for someone who understands the codebase to at least theorize about it.

**Versions**
  System:
    OS: macOS 10.14.4
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.13.0 - ~/workspace/VisionNxMobile/node_modules/.bin/yarn
    npm: 6.2.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0.1
    Safari: 12.1
  npmPackages:
    apollo: 2.4 => 2.4.4
    apollo-client: ^2.4.13 => 2.4.13
    react-apollo: ^2.2.4 => 2.3.2

**Comment by petergaultney** [comment] 2019-04-03 16:09
Follow-up on this: I'm guessing this is a combination of the known issue of the default InMemoryCache not handling heavyweight objects very well, and whatever way we're making use of it that isn't 'expected'.  I've tried plugging in `apollo-cache-hermes` and it reduces the freeze to around 200 ms, which is still slower than it should be for user interface purposes, but is obviously a major improvement.

Perhaps someone will see this and be able to suggest what we could do to convince Apollo not to worry about whatever normalization it's doing, and treat our objects more as blobs in a lightweight key-value store? We don't depend on the normalization behavior at all, but I'm betting that's what's costing us all this time.

**Comment by benjamn** [comment] 2019-04-03 16:45
A reproduction would be really helpful here, and I'm happy to help you assemble it. The blob of response data you provided is interesting because it's honestly not that huge, so this isn't just a case of a gigantic query with tons of response data taking a long time to process.

Some starting questions:
1. What version of React Native? Android or iOS? I ask because React Native installs polyfills for `Map` and `Set` on older devices that are much slower than native, which could be compounding the problem.
2. Can you share the mutation code in question? There seem to be multiple (3) calls to `InMemoryCache.performTransaction`, each with their own round of `broadcastWatches`, so I'm hopeful we could get that down to just one, somehow.

From the perspective of the user, part of the problem here seems to be that the UI becomes unusable for the duration of the work. However long the work takes (and I do think we could be doing less work, to be clear), the user experience would be better if we could make it more asynchronous.

**Comment by petergaultney** [comment] 2019-04-03 19:07
we just upgraded to React Native 0.57 from 0.56, which anecdotally seemed to make things worse (and is when we started digging in to this). But I have no real reason to believe that anecdote. 

We only call the `updateJobMutation` once, but we do have an `update` callback on that that is doing some manual cache updating that someone else wrote and that I suspect we don't need. However, I've also tried pulling those out and the overall slowness still exists.   I'll see if I can find that branch and pull out a profile of the code without that extra update method.

```
              updateJobMutation({
                variables: inputData,
                optimisticResponse: {
                  updateJob: {
                    __typename: 'Mutation',
                    ...jobOptimisticResponse,
                  },
                },
                update: (dataProxy, { data: { updateJob }, errors }) => {
                  if (errors || !updateJob) {
                    captureMessage('AddDocumentation cannot update cache', {
                      errors,
                      updateJob,
                    })
                    return
                  }

                  // I suspect these force-updates to the cache aren't necessary
                  let data = { getJob: {} }
                  try {
                    data = dataProxy.readQuery({ query: GetJobQuery, variables: { id: job.id } })
                  } catch (err) {
                    console.log('Error reading existing job from cache for detail updates')
                    captureException(err)
                  }
                  data.getJob = { ...data.getJob, ...updateJob }
                  dataProxy.writeQuery({ query: GetJobQuery, variables: { id: job.id }, data })

                  data = { listJobs: { items: [] } }
                  try {
                    data = dataProxy.readQuery({ query: ListJobsQuery })
                  } catch (err) {
                    console.log('Error reading jobs list from cache')
                    console.log(err)
                  }

                  const filteredJobItems = _.filter(
                    data.listJobs.items,
                    item => item.id !== updateJob.id
                  )

                  filteredJobItems.push(updateJob)
                  data.listJobs.items = filteredJobItems
                  dataProxy.writeQuery({ query: ListJobsQuery, data })

                  FileSystemService.jobs = filteredJobItems
                  FileSystemService.cleanMedia().catch(err => console.log(err))
                },
              })```

Yeah, the user-facing issue is definitely the synchronicity, though obviously it would be nice to consume less battery than we are.  The thing is, we don't get much advantage from Apollo's bells and whistles (particularly the normalization), since we only deal with our data objects in business logic at a high level, as there are only meaningful IDs (from a backend perspective) at the top (Job) level. So partly I just wish we could turn off all the normalization and extra work and use the cache as a simple key-value store.

In the meantime, though, we guessed that having our major ListJobs-consuming component querying for the entire Job (which is simpler) might be causing Apollo to do extra work, so we did a manual prefetch of the Jobs and then changed that component to only request the specific fields it needs. That reduced our total JS Apollo runtime to about 400 ms, as seen in the following profile.

![Screenshot 2019-04-03 13 52 04](https://user-images.githubusercontent.com/549720/55505822-94ac4600-5619-11e9-8960-a290f8031ed8.png)

As you can see, the render portions are still less than half of the overall runtime. 

Here is a comparison profile of the same operation, but taken with the Hermes cache, where you can see that almost the entire 170 ms of the synchronous call is taken up by our own (admittedly very unoptimized) render performance.

![Screenshot 2019-04-03 13 53 20](https://user-images.githubusercontent.com/549720/55505895-be656d00-5619-11e9-87e1-8b3c1ee60e97.png)

**Comment by petergaultney** [comment] 2019-04-08 22:28
The way I read the docs, the reason we'd need to manually update the cache is if we are adding a new item to a list.  There *are* cases in the app where we do need to manually add an item to the list, so we can't avoid the manual updates regardless. 

Is it expected that direct cache updates to a list of 50 items of the size of the data given would take upwards of a second to run?

**Comment by benjamn** [comment] 2019-04-08 22:53
No, that's not the expected performance. I would still appreciate any sort of reproduction you can provide, as I'm sure there's something lurking here that isn't normal.

In the meantime, can you try using `apollo-client@2.6.0-beta.4` (which contains [this change](https://github.com/apollographql/apollo-client/pull/4586/commits/364814fd9ad9e44df8e63e855ac484c3abf05958)), and maybe put the body of that `update` function into a transaction?
```ts
dataProxy.performTransaction(dataProxy => {
  ...
  dataProxy.readQuery(...)
  ...
  dataProxy.writeQuery(...)
  ...
});
```

**Comment by brotzky** [comment] 2020-04-28 05:52
We're running into similar issues where adding an `optimisticResponse` to Mutations will block the JS thread and all UI updates are delayed and laggy. I've opened up a different issue but it could be a duplicate of this one: https://github.com/apollographql/apollo-client/issues/6201

Wondering if there are any known workarounds to this or possible solutions? I've tested Apollo v3@beta but we're currently on v2.6.8,

**Comment by hwillson** [comment] 2021-04-27 14:41
If anyone can provide the reproduction mentioned in https://github.com/apollographql/apollo-client/issues/4658#issuecomment-481036943, we'll take a closer look. Thanks!

**Closed by hwillson** 2021-04-27 14:41 UTC
