### ISSUE TITLE
signOut in afterware does not cancel apollo trying to consume the response JSON as a successful query response

### ISSUE THREAD

**Issue by TSMMark** [apollographql/apollo-client#1456] opened 2017-03-20 14:57 UTC
**Intended outcome:**
queries depending on response data should not try to consume the response JSON as a successful graphql query response.

**Actual outcome:**
If response has empty body, warn:

```
Possible Unhandled Promise Rejection (id: 0):
Network error: Unexpected end of JSON input
```

If response has JSON body, warn:

```
Possible Unhandled Promise Rejection (id: 0):
Network error: Server response was missing for query 'undefined'.
```

**How to reproduce the issue:**

Create a react-apollo connected component which makes any graphql query.

[Add an afterware which effectively unmounts the component:](http://dev.apollodata.com/core/network.html#networkInterfaceAfterware)

```js
import ApolloClient, { createNetworkInterface } from 'apollo-client';
import {logout} from './logout';
const networkInterface = createNetworkInterface({ uri: '/graphql' });
networkInterface.useAfter([{
  applyAfterware({ response }, next) {
    if (true /* && response.status === 401 */) {
      logout();
    }
    next();
  }
}]);
const client = new ApolloClient({
  networkInterface,
});
```

Mount the component and witness the warnings. Possibly related to #1319?

**Comment by helfer** [comment] 2017-03-21 19:38
Hi @TSMMark! Could you provide a reproduction of this using https://github.com/apollographql/react-apollo-error-template? That would help us find and fix the error.

**Comment by helfer** [comment] 2017-05-03 18:18
Closing since it's been a month without reproduction. If this is still an issue, please feel free to open a new issue!

**Closed by helfer** 2017-05-03 18:18 UTC
Labels: reproduction needed

**Comment by tnrich** [comment] 2017-07-21 19:33
I am hitting this issue as well @helfer. It is slightly difficult to set up an example using your error boilerplate because the mock network interface you're using doesn't use the actual createNetworkInterface exported from apollo-client

**Comment by tnrich** [comment] 2017-07-21 19:35
Specifically, I'm not sure how to add afterware to the mock networkInterface: 

```
export const networkInterface = {
  query({ query, variables, operationName }) {
    return delay(500).then(() => {
      return graphql(
        schema,
        print(query),
        null,
        null,
        variables,
        operationName,
      );
    });
  },
};
```

Maybe you should modify the error repo to use the actual createNetworkInterface function?

**Comment by rmariuzzo** [comment] 2018-11-11 03:17
@tnrich did you find a solution for that?

**Comment by TSMMark** [comment] 2018-11-12 23:29
@rmariuzzo I think there is an entirely new `apollo-link` api now, so you should probably use that
