### ISSUE TITLE
Update NPM version to 2.1.1, document split in apollo-client

### ISSUE THREAD

**Issue by liywjl** [apollographql/apollo-client#2752] opened 2017-12-19 10:53 UTC
Currently NPM shows that the latest version of the Apollo Client is 2.0.4, however v2.1.1 is already out. It would be good to keep this up to date.

Please document `split` in 'apollo-link', it is really handy to combine all the links in a nicer way.

**Comment by amitport** [comment] 2017-12-20 11:32
same as https://github.com/apollographql/apollo-client/issues/2742

**Comment by hwillson** [comment] 2018-05-11 21:39
Closing as a duplicate of https://github.com/apollographql/apollo-client/issues/2742 (which was resolved). Thanks!

P.S. > `split` is now documented here: https://www.apollographql.com/docs/link/composition.html#directional

**Closed by hwillson** 2018-05-11 21:39 UTC
