### ISSUE TITLE
mutation.refetchQueries does not invalidate cache for queries that have been unmounted

### ISSUE THREAD

**Issue by Azerothian** [apollographql/apollo-client#5522] opened 2019-10-29 02:28 UTC
**Intended outcome:**
Calling refetchQueries with a mutation should reload content for any query referenced on next mount/load if currently unmounted.

**Actual outcome:**
Calling refetchQueries does not invalidate cache on queries that have been previously called and and are currently unmounted.

**How to reproduce the issue:**
https://codesandbox.io/s/apolloclient-refetchqueries-bowpd

- select "Hide List"'
- submit the form with content
- select "Show List"
- lists have not been updated

- while show list is active everything works as normal

**Versions**
=< 3.0.0

**Comment by dylanwulf** [comment] 2019-10-29 14:24
This looks like a duplicate of #5422

**Comment by hwillson** [comment] 2021-04-28 15:12
Closing as a dupe of https://github.com/apollographql/apollo-client/issues/5422 - thanks!

**Closed by hwillson** 2021-04-28 15:12 UTC
