### ISSUE TITLE
apollo-link-error onError populates graphQLErrors object but ApolloClient thrown error only populates networkError

### ISSUE THREAD

**Issue by tomasikp** [apollographql/apollo-client#3441] opened 2018-05-11 10:25 UTC
**Intended outcome:**

The intended outcome would be to have the same behaviour observed in `apollo-link-error` `onError` function be produced by Apollo-Client's thrown error.

error.networkError and error.graphQLErrors should be populated.

**Actual outcome:**
error.networkError is populated but error.graphQLErrors is not.

**How to reproduce the issue:**
Apollo Client Setup:

    const {ApolloClient} = require('apollo-client')
    const { ApolloLink } = require('apollo-link')
    
    const {HttpLink} = require('apollo-link-http')
    const {onError} = require('apollo-link-error')
    const {InMemoryCache} = require('apollo-cache-inmemory')
    
    const errorLink = onError(({ graphQLErrors, networkError }) => {
      if (graphQLErrors) {
        graphQLErrors.map(({ message, locations, path }) =>
          console.log(
            `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
          ),
        )
      }
    
      if (networkError) console.log(`[Network error]: ${networkError}`)
    })
    
    const middleware = (req, ignored_res, next) => {
      const client = new ApolloClient({
        link: ApolloLink.from([errorLink, new HttpLink({ uri:'http://somegraphqlserver.com', fetch: require('node-fetch') })]),
        cache: new InMemoryCache(),
      })
    
      req.GQLClient = client
    
      return next()
    }
    
    module.exports = middleware

Calling apollo-server-express: 

    req.GQLClient
        .query({
          query: SOME_MALFORMED_QUERY,
        })
        .then((data) => {...})
        .catch((error) => {
          console.log('rawError', error)
          console.log('error.networkError.result.errors', error.networkError.result.errors)
          return next(error)
        })

Console Results:

    [GraphQL error]: Message: Cannot query field "blah" on type "CustomerList"., Location: [object Object], Path: undefined
    [Network error]: Error: Response not successful: Received status code 400
  

     rawError { Error: Network error: Response not successful: Received status code 400
       at new ApolloError (/.../node_modules/apollo-client/bundle.umd.js:121:28)
       at /.../node_modules/apollo-client/bundle.umd.js:1187:41
       at /.../node_modules/apollo-client/bundle.umd.js:1620:17
       at Array.forEach (<anonymous>)
       at /.../node_modules/apollo-client/bundle.umd.js:1619:18
       at Map.forEach (<anonymous>)
       at QueryManager.broadcastQueries (/.../node_modules/apollo-client/bundle.umd.js:1614:22)
       at /.../node_modules/apollo-client/bundle.umd.js:1114:31
       at process._tickCallback (internal/process/next_tick.js:178:7)
     graphQLErrors: [],
     networkError: 
      { Error: Response not successful: Received status code 400
       at throwServerError (/.../node_modules/apollo-link-http-common/lib/bundle.umd.js:33:21)
       at /.../node_modules/apollo-link-http-common/lib/bundle.umd.js:58:17
       at process._tickCallback (internal/process/next_tick.js:178:7)
        response: 
         Response {
           size: 0,
           timeout: 0,
           [Symbol(Body internals)]: [Object],
           [Symbol(Response internals)]: [Object] },
        statusCode: 400,
        result: { errors: [Array] } },
     message: 'Network error: Response not successful: Received status code 400',
     extraInfo: undefined }

    error.networkError.result.errors [ { message: 'Cannot query field "blah" on type "CustomerList".',
       locations: [ [Object] ] } ]

library versions:

**Version**
Server:

    "apollo-server-express": "^1.3.2"

Client:

    "apollo-cache-inmemory": "^1.1.12"
    "apollo-client": "^2.2.8"
    "apollo-link-error": "^1.0.9"
    "apollo-link-http": "^1.5.4"

**Issue Labels**

While not necessary, you can help organize our issues by labeling this issue when you open it.  To add a label automatically, simply [x] mark the appropriate box below:

- [x] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

[StackOverflow](https://stackoverflow.com/questions/50289878/graphql-error-handling-with-apolloclient-and-apollo-server-express)

**Relevant Issues**
* #2492
* #3386

**Comment by mrasoahaingo** [comment] 2018-10-09 09:07
Hi, any updates on this issue? I reproduced the same error since à remove Apollo server on graphql server...

**Comment by jbaxleyiii** [comment] 2019-07-09 21:16
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Closed by jbaxleyiii** 2019-07-09 21:16 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage
