### ISSUE TITLE
Better error for overwriting object with no id

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client#819] opened 2016-10-20 22:40 UTC
Rather than "the application attempted to write an object with no provided id"

**Comment by stubailo** [comment] 2016-10-20 22:41
Also, add path to these errors.

**Comment by helfer** [comment] 2017-03-28 18:20
This issue has never come up in the last 5 months, so I think we're good here.

**Comment by clayne11** [comment] 2017-06-17 18:25
I'm having a ton of trouble with this issue. It's extremely difficult to track down when the app gets large with a lot of fragments. I use a unique `nodeId` for each entity's ID field. If I forget to add a `nodeId` in any single entity anywhere inside any fragment, mutation, or query it causes Apollo to blow up with this error.

As suggested in the initial issue, adding a path would be **extremely** helpful.

**Comment by helfer** [comment] 2017-06-17 19:03
Thanks @clayne11, let's make sure we print a better error message here!

**Comment by clayne11** [comment] 2017-07-15 12:49
Keeping this open.

**Comment by hammadj** [comment] 2017-07-30 06:29
Having the same issues as @clayne11

**Comment by davidtran** [comment] 2017-08-17 01:06
I am still getting this issue.

**Comment by 0x80** [comment] 2017-08-18 16:41
Same here

**Comment by jad11v** [comment] 2017-08-18 18:12
also getting this issue!

**Comment by goldo** [comment] 2017-08-28 14:45
I'm having the same issue, for a request/object which has no id, how can I fix it ? Thx

**Comment by goldo** [comment] 2017-08-29 11:30
Ok here's what I found:

When we have this: 
- NO batching (because this problem doesn't appear when both requests are merged into 1)
- 1 of the 2 requests asks for an `id` field, and the other one doesn't, example :
```
// component 1
    config {
      id
      version
    }
// component 2
    config {
      updatedAt
    }
```

=> if the  component 1's request arrives first, apollo doesn't know how to handle the 2nd request. If not, it's OK.
=> if both of the components ask for an `id` field, its ok.
=> if none of the components ask for an `id` field, its ok.

**Comment by joint-song** [comment] 2017-09-25 03:32
I think apollo client should generate(or any other action) a unique id to resolve this issue, not throwing an error.
It's not a perfect solution as @goldo do, but really helpful for now.

**Comment by goldo** [comment] 2017-09-25 08:00
@joint-song if your data contains id field it means there should be several of them, right ? If it does, apollo will need to know how to handle them, and merge them.
If your data doesn't contains any IDs and is unique (like a global config query for example), the merge should be simple since there's only 1 element.
i don't know how apollo could handle them any otherway

**Comment by jbaxleyiii** [comment] 2017-10-10 15:23
I think we can improve this with the goal of better messages / error handling in the post 2.0 launch

**Comment by tizmagik** [comment] 2017-11-01 00:05
I just hit this error today. Haven't yet dug into the cause/why I'm seeing it, but a path to the error sounds like it might be useful. 😅

**Comment by jbaxleyiii** [comment] 2017-11-13 16:39
After some discussion, I think its best to adjust this to be an error. We've added some better logging around when this is happening as well

**Comment by nevir** [comment] 2017-12-06 18:23
👍 to error; we added it as one in Hermes, and it caught a _ton_ of bugs in our client apps

**Comment by hwillson** [comment] 2018-07-27 17:38
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Better%20error%20for%20overwriting%20object%20with%20no%20id&body=Migrated%20from:%20apollographql/apollo-client%23819) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2018-07-27 17:38 UTC
Labels: discussion, help-wanted, usability
