### ISSUE TITLE
Response without data when fetchPolicy: 'no-cache' isn't present

### ISSUE THREAD

**Issue by andfs** [apollographql/apollo-client#3272] opened 2018-04-05 19:49 UTC
**Version**
- apollo-client@2.2.8

- [x ] has-reproduction
- [ ] feature
- [ ] docs
- [x ] blocking
- [ ] good first issue
-->

I'm using apollo-client@2.2.8 with angular 4, and all responses of a query return with data = undefined when fetching without fetchPolicy: 'no-cache'. This error occurs in react too.

Response without fetchPolicy:
![without_cache](https://user-images.githubusercontent.com/16955808/38388257-1b0eae32-38f1-11e8-9bfa-012461fc824a.png)

Response with fetchPolicy: 'no-cache':
![no_cache](https://user-images.githubusercontent.com/16955808/38388286-2ed2e46a-38f1-11e8-8a04-7807652e245d.png)

**Comment by michaelknoch** [comment] 2018-04-20 09:39
experiencing the same issue on apollo-client@2.2.8

**Comment by n1ru4l** [comment] 2018-04-23 13:59
@michaelknoch @andfs Could you please clarify what exactly causes this issue? I am trying to figure out if my issue is also related to this issue..

For my Query components that use the `no-cache` policy do not update after the data was fetched form the server

**Comment by Azmos** [comment] 2018-04-23 14:05
What I'm doing to get around this bug is first asking with `fetchPolicy: cache-first`, then after I've got the data I ask for a `fetchPolicy: network-only`.

It isn't strictly related to 'no-cache', but I'm here to confirm that something's wrong with the cache handling.

**Comment by hwillson** [comment] 2018-08-02 18:44
Would someone here be able to provide a small runnable reproduction that shows this happening? Ideally with just Apollo Client (or React Apollo). Angular related issues should be opened in the https://github.com/apollographql/apollo-angular repo. Thanks!

**Comment by hwillson** [comment] 2018-08-03 17:09
Just to follow up here - the original issue does not sound like an Apollo Client issue. If this problem is still happening, please re-open this issue in the Apollo Angular repo. 

That being said, https://github.com/apollographql/apollo-client/issues/3272#issuecomment-383585292 is an Apollo Client issue. If you're passing a `fetchPolicy` of `no-cache` into your `Query` components, there's a good chance you were running into the issue https://github.com/apollographql/apollo-client/pull/3777 now fixes. Since https://github.com/apollographql/apollo-client/pull/3777 has been merged (and will be released shortly), I'll close this off. Thanks!

**Closed by hwillson** 2018-08-03 17:09 UTC
Labels: reproduction-needed
