### ISSUE TITLE
clearStore() and apollo-link-dedup prevent further queries

### ISSUE THREAD

**Issue by blissi** [apollographql/apollo-client#3792] opened 2018-08-08 10:09 UTC
Hallo,
I found the following bug that I would consider severe:
when you use clearStore() and apollo-link-dedup, queries may be stuck forever and never be sent anymore.

**How to reproduce the issue:**
Create a GraphQL backend that delays a query by several seconds. Then, immediately after sending the query, call clearStore(). In the browser console you should see the warning that there are still in-flight requests. Then try send the query again - it won't be sent to the server anymore! The previous result is also never received and this query is stuck forever until you reload the browser tab.

**Analysis so far**
The cleanup()-method of the dedup-link is never called and therefore the request observable is stored forever in the inFlightRequestObservables-variable. clearStore() cancels all requests and I think that's the reason why the dedup-link isn't subscribed to it anymore.

**Versions**
apollo-client 2.3.2
apollo-link-dedup 1.0.9

Does anybody have an idea what I could do to prevent this?

**Comment by nyanpasu** [comment] 2018-08-13 09:43
Sounds like a dupe of #3766

**Comment by hwillson** [comment] 2018-09-05 18:11
This issue is related to https://github.com/apollographql/apollo-client/issues/3555, https://github.com/apollographql/apollo-client/issues/3766 and https://github.com/apollographql/apollo-client/issues/2919. We'll address them all in one shot.

**Comment by cheapsteak** [comment] 2019-02-05 00:41
Having some trouble reproducing this
Here's a codesandbox that follows the reproduction steps:
https://codesandbox.io/s/q39x7kk4xq

It's hooked up to an endpoint that's set to delay a response by 1.5seconds

Without interruption:
![](https://cl.ly/bab88f83ac7e/Screen%20Recording%202019-02-04%20at%2007.38%20PM.gif)

With interruption:
![](https://cl.ly/05aa80152782/Screen%20Recording%202019-02-04%20at%2007.40%20PM.gif)

**Comment by jbaxleyiii** [comment] 2019-07-09 20:48
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Closed by jbaxleyiii** 2019-07-09 20:48 UTC
Labels: :wilted_flower: needs-reproduction, ✔ confirmed, 🐞 bug
