### ISSUE TITLE
Types missing for documented cache.retain() and cache.release() methods of client returned by ApolloConsumer component

### ISSUE THREAD

**Issue by sraisty1c** [apollographql/apollo-client#7563] opened 2021-01-10 21:46 UTC
The cache.retain() and cache.release() methods are documented here: https://www.apollographql.com/docs/react/caching/garbage-collection/#configuring-garbage-collection

You can also access cache.retain() and cache.release() from the browser console.  For example, this works:
`__APOLLO_CLIENT__.cache.retain('zHex:2440281')`

However, the types file at @apollo/client/cache/core/cache.d.ts does not contain these methods on the ApolloCache type, so Typescript complains if you write code that tries to call client.cache.retain() if you use the client returned from useApolloClient (as well as ApolloConsumer component).

**Actual outcome:**

**How to reproduce the issue:**

In your browser console, try to do this:
`__APOLLO_CLIENT__.cache.retain('zHex:2440281')`

**Versions**

apollo client 3.3.6.

**Comment by benjamn** [comment] 2021-01-11 16:19
@sraisty1c You're right about this! These methods are defined on the `InMemoryCache` subclass, but not the abstract `ApolloCache` superclass. So you could down-cast with `(__APOLLO_CLIENT__.cache as InMemoryCache).retain` in the meantime, but we should also be able to hoist these methods up to the superclass, and give them no-op default implementations for caches that don't need to implement them.

**Comment by phryneas** [comment] 2023-12-22 11:53
There's nothing we can change about that, since the `ApolloClient` could also be initialized with other `ApolloCache` subclasses than `InMemoryCache`.

If you know for sure that it's an `InMemoryCache` instance, you can do the type assertion that @benjamn suggested above - otherwise you could also save a reference to the `InMemoryCache` instance into a variable name you control.

Either way, this is not a bug, and I believe it has been solved for you, so I'm going to close the issue :)

**Closed by phryneas** 2023-12-22 11:53 UTC
Labels: ⛑ TypeScript
