### ISSUE TITLE
Use multiple endpoints easily

### ISSUE THREAD

**Issue by fandy** [apollographql/apollo-client#5544] opened 2019-11-02 23:59 UTC
For folks using the increasingly popular [JAM stack](https://jamstack.org/), being able to use Apollo with multiple third-party APIs is a must.

With ApolloServer, you can use [`datasources`](https://github.com/stubailo/schema-stitching-demo/blob/master/index.ts) to stitch together a schema and resolve conflicting query/mutations. There is no similar built-in capability in ApolloClient that makes it easy to work with different endpoints. The only one I can think of is using multiple clients and passing them around. Might there be a better solution?

_Disclaimer:_ I don't know enough to offer a solution but just wanted to bring up the discussion. I can see schema stitching being a performance problem on `ApolloClient`, so maybe it is the only way.

**Comment by joltmode** [comment] 2020-02-28 00:21
This appears to be a duplicate of: https://github.com/apollographql/apollo-client/issues/84

And there are already some solutions.

**Comment by in19farkt** [comment] 2020-04-13 13:22
Workaround for easy use of multiple endpoints https://github.com/apollographql/apollo-client/issues/84#issuecomment-557400283

**Comment by samuelcastro** [comment] 2020-08-18 19:01
Found out this library which easily solves the problem: https://github.com/habx/apollo-multi-endpoint-link

**Closed** 2021-04-28 15:13 UTC
