### ISSUE TITLE
RefetchQueries will only refetch the first query that is called when 2 with same name.

### ISSUE THREAD

**Issue by happylinks** [apollographql/apollo-client#4115] opened 2018-11-08 15:33 UTC
When there's two active queries in Apollo with the same name, refetchQueries will only refetch the first query that is called.

**Intended outcome:**
RefetchQueries always refetches the *last* query when there are more with the same name, not the first.

**Actual outcome:**
RefetchQueries always refetches the *first* query called when there are multiple with the same name.

**How to reproduce the issue:**
<img width="882" alt="image" src="https://user-images.githubusercontent.com/184774/48208814-eeaf2500-e373-11e8-872c-2ba5ddffd6da.png">

https://github.com/happylinks/react-apollo-error-template

I had an issue with publishing it to gh-pages ("Failed to get remote.https://github.com/happylinks/react-apollo-error-template.git.url (task must either be run in a git repository with a configured https://github.com/happylinks/react-apollo-error-template.git remote or must be configured with the "repo" option).
")

**Versions**

  System:
    OS: macOS 10.14.1
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v10.9.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.9.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 63.0.1
    Safari: 12.0.1
  npmPackages:
    apollo-cache-inmemory: ^1.2.2 => 1.2.2 
    apollo-client: ^2.3.2 => 2.3.2 
    apollo-link: ^1.2.2 => 1.2.2 
    apollo-link-schema: ^1.1.1 => 1.1.1 
    react-apollo: 2.1.4 => 2.1.4 
  npmGlobalPackages:
    apollo: 1.9.1

**Comment by happylinks** [comment] 2018-11-08 15:47
Digging a bit into the code I found this:
https://github.com/apollographql/apollo-client/blob/905001e40cfadf841aa5a78aa428ab09f8cdf108/packages/apollo-client/src/core/QueryManager.ts#L1194-L1206

So it seems that it should refetch *all* the queries, eventhough they have the same name. This is not what I see happening in my app though 🤔

**Comment by pl12133** [comment] 2018-11-09 16:46
This is a great detailed write up, I think you are facing https://github.com/apollographql/apollo-client/issues/3540.

**Comment by hwillson** [comment] 2019-07-09 23:15
Duplicate of https://github.com/apollographql/apollo-client/issues/3540.

**Closed by hwillson** 2019-07-09 23:15 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage
