### ISSUE TITLE
Clearing the client state using 'resetStore'

### ISSUE THREAD

**Issue by oavasilcai** [apollographql/apollo-client#1509] opened 2017-03-28 07:54 UTC
Not sure if this is actually a bug but more of behaviour issue, we use `resetStore` to clear the state on user logout. However, active queries on that page are being sent once `resetStore` is called.

The queries made require authentication on the backend, so once logout is made they respond with a 401.

I've already submitted a PR with a possible solution, just not sure how the apollo team wants to go about it: https://github.com/apollographql/apollo-client/pull/1487

**Comment by Poincare** [comment] 2017-03-30 05:55
This is currently intended behavior as far as I know.

If `resetStore` didn't refetch queries that are active on your page, then your cache would be left in state that may display information pre-resetStore. This is obviously bad (e.g. if you `resetStore` on logout).

**Comment by oavasilcai** [comment] 2017-03-30 07:00
There is no information in pre-resetStore - and I would prefer that over refetching queries and getting 403's because the token/cookies are invalid. 

The usecase makes it more difficult for us because this piece of our app is kind of a 'microservice' and logouts navigates away from it's own 'micro-domain'

**Comment by oavasilcai** [comment] 2017-03-30 08:10
@Poincare also, in the PR I've added an option to `resetStore` to be able to not refetch, default behaviour is still to run active queries. PR here: https://github.com/apollographql/apollo-client/pull/1487

**Comment by helfer** [comment] 2017-05-02 22:56
I think this should be fixed in react-apollo now, which was keeping the observable queries alive even when they weren't used any more.

**Closed by helfer** 2017-05-02 22:56 UTC

**Comment by oavasilcai** [comment] 2017-05-03 07:30
hi helfer, got a link to the PR ?

**Comment by helfer** [comment] 2017-05-04 18:52
@oavasilcai #1636 and the PR that references it in react-apollo. It should be in `react-apollo@^1.2.0`.
