### ISSUE TITLE
prev is empty {} in updateQuery at subscribeToMore

### ISSUE THREAD

**Issue by miguelacio** [apollographql/apollo-client#4465] opened 2019-02-19 01:16 UTC
Hello, right now I am developing an app with uses queries and subscriptions, but once subscribeToMore is triggered, the "prev" argument is _always_ empty, I can no longer update my query if there is not previous state, here's my code: 

```
class Prospects extends Component {
  render() {
    return (
      <SafeAreaView style={{ flex: 1 }}>
        <Container>
          <StatusBar barStyle="dark-content" backgroundColor="#efefef" />
          <Title>{strings('prospects.title')}</Title>
          <Query query={conversations} fetchPolicy={'network-only'}>
            {({ loading, error, data, subscribeToMore }) => {
              if (loading)
                return (
                  <LoadingContainer>
                    <CircleSnail
                      size={26}
                      thickness={2}
                      color={colors.primaryColor}
                    />
                  </LoadingContainer>
                )

              if (error) return <Text>Error</Text>
              const { getConversations } = data
              this.subscribeToConversations(subscribeToMore)
              return <ChatList items={getConversations} />
            }}
          </Query>
        </Container>
      </SafeAreaView>
    )
  }

  subscribeToConversations = async subscribeToMore => {
    subscribeToMore({
      document: subscriptionConversations,
      updateQuery: (prev, { subscriptionData }) => {
        //Here prev is empty
        if (!subscriptionData.data) return prev

        const { data: { conversations } } = subscriptionData
        const { mutationType } = conversations
        if (mutationType === UPDATED) {
          // TODO
        }
        //TODO
        return prev
      },
    })
  }
}`
```

**Versions**

  System:
    OS: macOS 10.14.3
  Binaries:
    Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.14.0/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Safari: 12.0.3
  npmPackages:
    apollo-cache-inmemory: 1.3.9 => 1.3.9
    apollo-client: 2.4.5 => 2.4.5
    apollo-link-context: 1.0.9 => 1.0.9
    apollo-link-http: 1.5.5 => 1.5.5
    apollo-link-ws: ^1.0.14 => 1.0.14
    react-apollo: 2.2.4 => 2.2.4

**Comment by pl12133** [comment] 2019-02-19 14:01
Is this the same as https://github.com/apollographql/apollo-client/issues/3864?

**Comment by miguelacio** [comment] 2019-02-19 18:06
@pl12133 i read the issue you tagged but it says that _prev_ is sometimes empty but in my case _always_ is empty

**Comment by SilvanCodes** [comment] 2019-04-02 16:50
I haven't tested anything nor am I a react programmer, but I suspect your problem is due to the `fetchPolicy={'network-only'}`. As I understand that, the query will never read from the cache so it can't have a previous value?

**Comment by miguelacio** [comment] 2019-04-02 23:30
I solved it by adding:

const client = new ApolloClient({
  link,
  cache: new InMemoryCache({
    dataIdFromObject: o => (o._id ? `${o.__typename}:${o._id}` : null),
  }),
})

at creating Apollos client

**Comment by SilvanCodes** [comment] 2019-04-03 07:15
That's great! Where you missing the cache in general or was it a problem with the dataFromId-function?

 

Would you like to comment the cause of your issue on GitHub and then close it? :)

 

Gesendet: Mittwoch, 03. April 2019 um 01:30 Uhr
Von: "Jesus Miguel Flores" <notifications@github.com>
An: apollographql/apollo-client <apollo-client@noreply.github.com>
Cc: SilvanCodes <SilvanBue@gmx.de>, Comment <comment@noreply.github.com>
Betreff: Re: [apollographql/apollo-client] prev is empty {} in updateQuery at subscribeToMore (#4465)


I solved it by adding:

const client = new ApolloClient({
link,
cache: new InMemoryCache({
dataIdFromObject: o => (o._id ? ${o.__typename}:${o._id} : null),
}),
})

at creating Apollos client

**Closed** 2019-04-12 00:39 UTC
