### ISSUE TITLE
Memory leak when using Reactive variables in SSR setup on the server

### ISSUE THREAD

**Issue by manojVivek** [apollographql/apollo-client#7274] opened 2020-11-02 08:08 UTC
**Intended outcome:**

Usage of reactive vars on the server-rendering shouldn't create a memory leak.

**Actual outcome:**

When an app, that uses reactive vars, is rendered on the server, it holds the query results in memory forever. Even though a new client, cache, and reactiveVar instances are created freshly for every request. 
Probably because the references to reactive vars are held in a global context? 

**How to reproduce the issue:**

We make use of the following function to create a new apollo client on every request to the serve:
```
export default function createCache() {
  const reactiveVars = {
    var1: makeVar({}),
    var2: makeVar({}),
    var2: makeVar({}),
  };

  return new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          field1() {
            return reactiveVars.var1();
          },
          field2() {
            return reactiveVars.var2();
          },
          field3() {
            return reactiveVars.var3();
          },
        },
      },
    },
  });
}
```
And we observed from heap-dumps that the cache data is held in the memory when we use the reactive-vars even after a GC. 
And if we remove the usage of reactive vars, the memory recovers back to normal after the GC.

Screenshot of a sample object(one of tons of similar ones) that were in memory:
<img width="1920" alt="Screenshot 2020-11-02 at 1 35 53 PM" src="https://user-images.githubusercontent.com/1283424/97844167-88fe9500-1d10-11eb-94b5-20c5d8b90699.png">

**Versions**

```
System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.18.0 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Edge: 81.0.416.68
    Firefox: 78.3.1
    Safari: 14.0
npmPackages:
    @apollo/client: ^3.2.5 => 3.2.5 
```

**Comment by benjamn** [comment] 2020-11-02 20:12
@manojVivek Thanks for opening this issue. I can see what the problem is, and how to fix it, though the solution will probably depend on you explicitly calling `client.stop()` after you finish using `client` during SSR (in case you're not already doing so).

**Comment by hwillson** [comment] 2021-05-15 10:41
Addressed by https://github.com/apollographql/apollo-client/pull/7279 - thanks!

**Closed by hwillson** 2021-05-15 10:41 UTC
Labels: 🐞 bug, 💸 caching, 🛫 in-progress, 🧩 implementation-detail

**Comment by choijungseon** [comment] 2021-06-10 06:25
npmPackages:
    @apollo/client: 3.3.19

we update to 3.3.19 version 
but it is still remain memory leak

is it solved this issue ?
