### ISSUE TITLE
useSuspenseQuery(QUERY, { errorPolicy: 'all' }) not stopping the error from bubbling up

### ISSUE THREAD

**Issue by mvolonnino** [apollographql/apollo-client#11156] opened 2023-08-21 14:43 UTC
``` 
const { data, error, ...rest } = useSuspenseQuery(GET_ORGANIZATIONS, { errorPolicy: 'all' });
```
 
 From the docs, this should not throw the error within useSuspenseQuery, an instead attach the error onto the returned error object from the query.
 
With a simulated error 
```
const simulateApolloError = (operation, forward) => {
  // console.log('operation', JSON.stringify(operation, null, 2));

  const throwError = Math.random() < 0.5;

  if (throwError) {
    throw new ApolloError({
      errorMessage: 'Simulated Apollo Error',
      extraInfo: 'This is a simulated error from the Apollo client',
    });
  }

  return forward(operation);
};
```
still having the error thrown, making it so i have to have an <ErrorBoundary> setup to catch that error, yet I would i want to handle the error within the component itself, not hoist the error all the way up to my <ErrorBoundary> which does not have access to the refetch for this component.

Want to use the `useSuspenseQuery` for full screen skeleton loading, while still having separated components for the different queries.

But because the { errorPolicy: 'all' } within the `useSuspenseQuery` doesn't seem to stop the error from bubbling to the closest <ErrorBoundary>, Im finding it difficult to utilize in my use case.

**Comment by jerelmiller** [comment] 2023-08-21 17:27
Hey @mvolonnino 👋 

As weird as this sounds, this is expected behavior for _network_ errors, since these may not be recoverable. Error policies are meant to control what happens when a _GraphQL error_ occurs in a request (i.e. the `errors` property returned in a GraphQL server response). According to the [docs](https://www.apollographql.com/docs/react/data/error-handling#graphql-error-policies):

> By default, Apollo Client throws away partial data and populates [the error.graphQLErrors array of your useQuery call](https://www.apollographql.com/docs/react/data/queries/#result) (or whichever hook you're using). You can instead use these partial results by defining an error policy for your operation.

See #10384 for more information on the reasoning behind this and #10401 for the implementation of this behavior.

Your example here creates a network error, hence why its being thrown.

You're right though that our docs aren't as clear as they could be about the behavior of network errors (both for `useQuery` or `useSuspenseQuery`). I'll see what we can do to make this more clear in the docs.

Could you describe a bit more about the nature of your network error? Is this something that comes from the server, or are you throwing an error yourself based on some runtime condition that triggers this? Perhaps I can recommend something that works for your use case.

**Comment by mvolonnino** [comment] 2023-08-21 18:26
hey @jerelmiller ! Thank you for responding, I appreciate it.

So the nature of that error was creating just a simple 'simulate error' through Apollo to trigger that error within a useSuspenseQuery for testing purposes.

```
 const { data, error, ...rest } = useSuspenseQuery(GET_ORGANIZATIONS, {
    errorPolicy: 'all',
    context: { simulateError: true },
  });
```
I was trying to test to see if the error would be attach here at the point of using the useSuspenseQuery, but with the `errorPolicy: 'all'`, it was still bubbling the error, and would either white screen (no error boundary) or be caught in the closet ErrorBoundary, which would not have access to the `refetch` to be able to give an option to try and refetch data.

Ya so some context in how I would like to use `useSuspenseQuery` (hopefully im thinking of this to use this query in the correct context that you guys intended).

Currently, the design choice for creating out React Native screens, the over arching screen is most likely a Flatlist, with the components to make up the screen made into an array of objects to pass to the FlatList.

The components handle all the queries themselves for separation of concerns (data, loading, errors, refetches, etc), so each component is self-aware, and only aware of the data that its fetching.

quick ex.
```
const Home = () => {
 // ... code related to the whole screen

  const HomeComponents = [
     {
       key: 'fake-comp-1'
       Component: FakeComp // uses its own useQuery (would want to make it a useSuspenseQuery to hoist the loading)
       props: {},
     },
     {
      key: 'fake-comp-2',
      Component: FakeComp2
      props: { id, ...etc },  // uses its own useQuery (would want to make it a useSuspenseQuery to hoist the loading)
     },
  ];
}

//... other code

return (
<Suspense fallback={HomeSkeletonUI}> // would be able to get a nice skeleton loader showing as the useSuspenseQuery in each component would hoist the loading
<FlatList data={HomeComponents} renderItem={renderItemFn} />
</Suspense>
)
}
```
Let me know if that makes sense for you but thats a basic idea of how I thought I would be able to utilize the `useSuspenseQuery`.

With this type of design tho, I would still want the option to handle errors within each component (in case i wanted to show an Error component with a retry option (refetch) within the component as the refetch is available within the component - which i thought the { errorPolicy: 'all' } could come into play.

Since the <ErrorBoundary> would not be available within the component to get the refetch method, im just trying to understand it a little better.

Im wondering if I now need to use some of the other new queries too, with the `useBackgroundQuery` and the other queries, but those queries seemed like it would be more suitable if I had the Home screen component with all the queries and passing down through props (which Im trying to avoid prop drilling as some components could be passing to multiple children down)

**Comment by jerelmiller** [comment] 2023-08-21 19:13
@mvolonnino appreciate the info here! This is helpful.

As mentioned, this should only be the case if your query results in a _network_ error. Just to re-iterate what a network error is, it's going to either be a non 200 status code returned by your server (i.e. 4xx or 5xx response) or any general purpose error thrown in your link chain (such as your simulated error here). If your server uses GraphQL errors for communicating errors from the server, `errorPolicy` is going to suit you just fine here.

If you want to try this out yourself using the simulated error like you did above, but with a GraphQL error instead, try this (warning untested):

```js
import { GraphQLError } from 'graphql';

const simulateApolloError = (operation, forward) => {
  // console.log('operation', JSON.stringify(operation, null, 2));

  return forward(operation).map((data) => {
    if (Math.random() < 0.5) {
      return { 
        data: null, 
        errors: [new GraphQLError('Simulated Apollo Error')] 
      };
    }

    return data;
  });
};
```

With this, I have a couple followup questions:

* How tolerant do you want to be of network errors in your application?

If network errors truly are exceptional, it might make more sense to treat these as exceptional and crash and/or fail more loudly since these errors might not be recoverable (i.e. for example, the user going offline). If you're aiming to treat network errors in the same class as GraphQL errors, the reasoning you provide makes sense.

* In your statement below, is this a design choice or limitation in your GraphQL schema?

> The components handle all the queries themselves for separation of concerns (data, loading, errors, refetches, etc), so each component is self-aware, and only aware of the data that its fetching.

We recommend using a single query as much as possible to fetch a list of data since a single network request is likely going to be the most performant, especially if the list of items is large. Totally understand if you're not able to achieve this given your schema and/or you don't have control over changing it, but I'd recommend trying to fetch the list of data in a single query if possible.

---

That said, if you're keen on this design choice, your intuition is right and I'd recommend `useBackgroundQuery` + `useReadQuery` to achieve this. `useReadQuery` is the hook that is going to be throwing the error, so it gives you a chance to wrap the component that uses it with an error boundary. The downside is it requires that extra component, but its a small tradeoff that I think is worth it if you're considering this particular component design.

Try something like the following to get what you're after while keeping the query hook in each list item component. This should work for both GraphQL errors as well as network errors:

```tsx
const Home = () => {
  const HomeComponents = [
    {
      key: 'fake-comp-1'
      Component: FakeComp,
      props: {},
    },
    {
      key: 'fake-comp-2',
      Component: FakeComp2,
      props: { id, ...etc },
    },
  ];

  //... other code

  return (
    <Suspense fallback={HomeSkeletonUI}>
      <FlatList data={HomeComponents} renderItem={renderItemFn} />
    </Suspense>
  );
}

const FakeComp = () => {
  const [queryRef, { refetch }] = useBackgroundQuery(query);

  // No suspense boundary here means it will render the `Home` suspense boundary.
  // Pass `refetch` to your `ErrorBoundary` to have access to it.
  return (
    <ErrorBoundary refetch={refetch}>
      <FakeCompWithData queryRef={queryRef} />
    </ErrorBoundary>
  );
}

const FakeCompWithData = ({ queryRef }) => {
  // will throw the error here and be caught be the `FakeComp` error boundary
  const { data } = useReadQuery(queryRef);

  return // do something with `data`
}

const FakeComp2 = ({ id }) => {
  const [queryRef, { refetch }] = useBackgroundQuery(query, { variables: { id } });

  // No suspense boundary here means it will render the `Home` suspense boundary.
  // Pass `refetch` to your `ErrorBoundary` to have access to it.
  return (
    <ErrorBoundary refetch={refetch}>
      <FakeCompWithData2 queryRef={queryRef} />
    </ErrorBoundary>
  );
}

const FakeCompWithData2 = ({ queryRef }) => {
  // will throw the error here and be caught be the `FakeComp2` error boundary
  const { data } = useReadQuery(queryRef);

  return // do something with `data`
}

// this component needs more code to work correctly, but this gets you a starting point
class ErrorBoundary extends React.Component {
  static getDerivedStateFromError(error) {
    return { hasError: true };
  }

  render() {
    const { children, refetch } = this.props;

    if (this.state.hasError) {
      return <button onClick={() => refetch()}>Retry</button>
    }

    return children;
  }
}
```

Let me know if that helps!

**Comment by mvolonnino** [comment] 2023-08-21 21:03
@jerelmiller - Thank you again. Let me take some time to understand what you have said here, and formulate a response. Just about to be out for the night, so figured I'd let you know that you'll get a response on this tomorrow!

Thanks again though, already understanding it a bit better with your explanations!

**Comment by mvolonnino** [comment] 2023-08-22 14:03
@jerelmiller - alright again really appreciate you taking the time to help me understand the new queries you guys came out with.

Okay so ill start off with this:

> We recommend using a single query as much as possible to fetch a list of data since a single network request is likely going to be the most performant, especially if the list of items is large. Totally understand if you're not able to achieve this given your schema and/or you don't have control over changing it, but I'd recommend trying to fetch the list of data in a single query if possible.

So in terms of design, the components are fetching unrelated data to each other with their own queries. Each component are separate in the fact that they don't rely on any of the data retrieved between each other.

So my thought process on components like that and overall screen design would be to separate them with their own queries as the parent component (in this case the Home screen (or any screen really)) does not need that data either - let the components handle their state / data retrevial that is pertinent for that component.

 Now with this structure, we are clearly able to have separated concerns in regards to component development. One area where that hinders though is having a clear and easy way to have a full screen loading UI (this way now introduces per component loading which is not as nice as having a full screen skeleton loader, compared to per component loaders etc.).
 
 Thats where i thought the `useSuspenseQuery` we be such a powerful tool in regards to each component can now utilize that, and the component itself will not have to worry about loading states, but instead can be more clean and only truly care about the data its retrieving, and the Home screen can be wrapped in a `<Suspense fallback={HomeSkeleton}>` allowing that beautiful screen loading + still having the separated concerns when it comes to each specific component fetching their own data that relates only to that component.
 
 ____

In regards to lists, our App does have one 'main query' that grabs a list of `ids` along with some other data points that the UI needs to display, but when utilizing a Flatlist, and we pass that data to the renderItem, the component that the renderItem utilizes does another fetch on that id to grab the component data needed.

In that regard, I have not tried utilzing`useSuspenseQuery` on that type of screen design. Albeit, I would like to understand more about what you said in terms of using one 'big' query (single list of items).

With the type of data my one screen fetches, that would be an extremely large list, with a bunch of data being returned on the items as well.

I would think separating them into smaller query that still grabs the list items ids (this is paginated as well through infinite scroll technique) and then each component itself would fetch the component data based on the provided id. This also helps in showing loading per item (which goes against what I was asking here about `useSuspenseQuery` 🤣)
____
I am going to try and implement your suggestions today in terms of updating the `ErrorBoundary` + utilizing the other new queries as well! (still a little hesitant tho if the extra layers needed to add to the components are worth it. if you have a good reason on that as well, I would love to hear it from a design perspective - just like to try and fully understand everything i would be implementing to make sure I have a really good grasp on it)

Thanks again!

**Comment by jerelmiller** [comment] 2023-08-23 16:13
Appreciate the additional info here! That helps a ton. Let me do my best to respond to this with my thoughts.

> the components are fetching unrelated data to each other with their own queries. Each component are separate in the fact that they don't rely on any of the data retrieved between each other.

This is totally fine! In fact, I'd argue this is what GraphQL is good for. Just because you are rendering components together doesn't mean they all need to operate on the same data set.

Something I'd highly recommend doing is utilizing [fragments](https://www.apollographql.com/docs/react/data/fragments) more to allow those components to describe their data needs. I'd argue we don't do a super great job of in our docs, but I'd encourage you to read through that docs page. This pattern allows a parent component to compose fragments together to create a query so that you only need to fetch the data in a single request, rather than splitting it into multiple requests.

You've asked what I mean by "big" query, and this is what I mean. Rather than separating each of those data concerns into smaller and smaller queries (extra network requests), compose them together using fragments to create a single query in a parent component.

Here is a totally contrived example that shows how you could have totally separate data in components but use fragments to compose a single query together.

```tsx
// parent.js
import CurrentUser from './CurrentUser';
import Author from './Author';

const QUERY = gql`
  query MyQuery {
    currentUser {
      id
      ...CurrentUserFragment
    }
    authors {
      id
      ...AuthorFragment
    }
  }

  ${CurrentUser.fragments.currentUser}
  ${Author.fragments.author}
`;

function Parent() {
  const { data } = useSuspenseQuery(QUERY);

  return (
    <>
      <CurrentUser currentUser={data.currentUser} />
      {data.authors.map((author) => (
        <Author key={author.id} author={author} />
      )}
    </>
  )
}

// CurrentUser.js
function CurrentUser({ currentUser }) {
  return <div>{currentUser.name}</div>
}

// Note: this is the convention used in our docs, but not required to take advantage
// of this pattern
CurrentUser.fragments = {
  currentUser: gql`
    fragment CurrentUserFragment on CurrentUser {
      name
    }
  `
}

// Author.js
function Author({ author }) {
  return (
    <>
      <div>{author.name}</div>
      <div>Wrote {author.booksWritten} books</div>
    </>
  );
}

Author.fragments = {
  author: gql`
    fragment AuthorFragment on Author {
      name
      booksWritten
    }
  `
};
```

Here each component rendered by `Parent` describes its data needs via a GraphQL fragment, which allows me to colocate that information with the component itself. Notice though that each of those child components don't need to fetch their own data to do so. Instead, we let `Parent` compose those fragments together in a single query, then pass that needed data down to the child components. 

I believe this helps with this concern of yours:

> So my thought process on components like that and overall screen design would be to separate them with their own queries as the parent component (in this case the Home screen (or any screen really)) does not need that data either

While the data is technically available in the parent, using fragments allows you to treat it like a black box: the parent doesn't need to know what each of those fragments are, just where to fetch it in the graph.

If you're curious more about seeing this pattern in a more complex app, check out our [Spotify Showcase](https://github.com/apollographql/spotify-showcase) which uses this pattern extensively.

> Now with this structure, we are clearly able to have separated concerns in regards to component development.

While yes, this makes a lot of sense, be careful not to sacrifice UX for DX. With HTTP 1.1 for example, you might hit [concurrent request limits](https://ishwar-rimal.medium.com/why-does-your-browser-limit-the-number-of-concurrent-network-calls-1ae5d50863dd) if you're making too many requests at once. While generally this isn't a huge issue (after all REST applications would face this as well), just be aware this might apply and could hurt performance unnecessarily (after all, we are using GraphQL which is good at allowing you to specify exactly what you need in a single request).

As with anything, measure measure measure and figure out what gives works the best in your situtation. Many small requests might individually be fast, but end up taking longer than a single request due to the added latency needed to execute each of those requests. I'd just recommend that you consider this structure through the lens of a performance benefit, rather than a DX concern, to ensure you're not accidentally hurting your UX to achieve it. This might totally be a valid solution in your application, and that is fine!

> In regards to lists, our App does have one 'main query' that grabs a list of ids along with some other data points that the UI needs to display, but when utilizing a Flatlist, and we pass that data to the renderItem, the component that the renderItem utilizes does another fetch on that id to grab the component data needed.

I'm curious, does this screen have some kind of loading UI? Or is it just blank until the the data loads? Definitely something you could consider using Suspense for 🙂.

> With the type of data my one screen fetches, that would be an extremely large list, with a bunch of data being returned on the items as well.

I'd argue here that you're fetching the same amount of data either way (after all, you're loading it in the query executed by the individual component), you're just doing this with multiple requests rather than one. As mentioned before, just be sure to measure measure measure to see what works best in your situation. You _do_ get some parallelization this way, but you're still waiting for a parent query to finish before you can kick off these individual requests, resulting in a request waterfall. Try the fragment approach mentioned above and see what kind of impact this has. You may find there to be a benefit to this approach.

> I would think separating them into smaller query that still grabs the list items ids (this is paginated as well through infinite scroll technique) and then each component itself would fetch the component data based on the provided id. 

Again, be careful of the request waterfall here 🙂 . You'll have one request that goes and gets the next page of data, then only when that finishes can you begin to fetch data for each list item. Fetching this data with the paginated query may prove to be more performant.

---

Does this help answer more of your question here?

**Comment by mvolonnino** [comment] 2023-09-22 21:46
@jerelmiller - wow, just realizing i never responded, went on a little vacation and thought i answered before!

I really appreciate your help and allowing me to understand the new updates to Apollo and the new queries. Started to implement them now with your help and I am loving how clean it makes the components!

I did figure out the issue of getting the errors how i needed them with your help as well, so I would assume this can be closed!

Thank you again!

**Comment by jerelmiller** [comment] 2023-09-22 21:58
@mvolonnino the number of times I've done that as well is... too many 😂. Glad to hear this helped and awesome to hear you're trying out the new updates!

I'll go ahead and close this then. Feel free to reach out anytime! Thanks!

**Closed by jerelmiller** 2023-09-22 21:58 UTC
Labels: 🏓 awaiting-contributor-response, ✍️ working-as-designed
