### ISSUE TITLE
useLazyQuery doesn't return cached data with "cache-and-network" fetchPolicy

### ISSUE THREAD

**Issue by ryanb-jobber** [apollographql/apollo-client#10386] opened 2022-12-22 22:08 UTC
**Intended outcome:**

I have a view that responds to user-changed date values by displaying appropriate data for the selected date. I have the query setup with the `useLazyQuery` hook. I rely on the `onCompleted` handler passed to the query options to update a local store with the expected data. 

When the data has been already been fetched for given variables, I would like to take advantage of the cached data to load the view faster, while still refreshing in the background. Thus I have set a fetch policy of `"cache-and-network"`. I would expect that even in a slow network, I'd be able to see the cached data immediately, because `onCompleted` would be immediately called with the data from cache, and then again when the network call completes.

**Actual outcome:**

The `onCompleted` handler is only run when the network operation completes. Thus, in a slow network environment, no data is shown for some time even though it exists in the Apollo cache.

If I instead use a fetch policy of `"cache-first"`, it works as expected, in that data is returned immediately. However, this is not acceptable for my use case as I need to ensure the view is kept up to date if possible.

**How to reproduce the issue:**

Reproducible using the code at:
https://github.com/ryanb-jobber/apollo-oncompleted-bug-repro

You can observe that when pressing the button to trigger the query, the data is cleared and does not populate until the call resolves, even after the query has been run once and cached.  Additionally, you can see that `onCompleted` is only called once per press, as shown by the displayed count.

If you change the `fetchPolicy` used in the `useLazyQuery` call to `"cache-first"` you will observe the data available immediately.

```
  const [load, { loading, data }] =
    useLazyQuery(ALL_PEOPLE, {
    fetchPolicy: "cache-and-network",
    onCompleted: (data) => {
      setPeople(data.people);
      setOnCompletedCount((prev) => prev + 1 ) }
  });
```

**Versions**

```
  System:
    OS: macOS 13.0.1
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.1
  npmPackages:
    @apollo/client: ^3.7.3 => 3.7.3 
    apollo-link-queue: ^3.1.0 => 3.1.0 
    apollo-link-rest: ^0.8.0-beta.0 => 0.8.0-beta.0 
    apollo-link-serialize: ^3.1.2 => 3.1.2 
    apollo3-cache-persist: ^0.14.1 => 0.14.1 
```

**Comment by jerelmiller** [comment] 2023-08-14 22:24
Hey @ryanb-jobber 👋 

This is an interesting one. The `onCompleted` callback is really meant to be used when the request completes, so I'd argue that the existing behavior makes sense. In the case of `cache-first`, the request is "complete" because its able to fully resolve the request from the cache and return immediately. In the case of `cache-and-network`, the request is not really "complete" until the network request has finished loading. This is the behavior I'm seeing demonstrated in your reproduction.

I'd like to press a little bit more on your example here. I see that you're running a `setPeople(data.people)` call in your `onCompleted` handler. Could you talk a little bit more about your use case here and what you're looking to achieve with this pattern?

Generally we recommend avoiding your own state setters in the `onCompleted` handler because they 1) duplicate the data returned from the `data` property and 2) cause an extra re-render unnecessarily due to both the `useLazyQuery` running a `set` and your own `set` call.

If I update your reproduction to read directly from the `data` property returned from the hook, I can see that the result is returned immediately from cache as expected when using `cache-and-network`. Is there something preventing you from reading from this property directly?

**Comment by ryanb-jobber** [comment] 2023-08-25 21:36
Hi @jerelmiller thanks for the reply and the additional context! The repro code was a trivial example to show the behaviour of `onCompleted`. In reality, we were doing some complex data processing with the result data rather than a simple state set. I can't recall the details now unfortunately, and we've since moved away from `useLazyQuery` for the functionality. 

If this is the expected behaviour of `onCompleted`, that's fine, it just wasn't what I was expecting (as it seemed inconsistent with the fact that the `data` property is updated immediately).

**Comment by jerelmiller** [comment] 2023-08-25 22:16
@ryanb-jobber ya unfortunately we've had a bit of churn with `onCompleted` as everybody seems to have their own interpretation of the "correct" behavior (some think it should be called for cache hits while others think that behavior is a bug).

In general, if you need to do data transformations (even for `useQuery`), we recommend making it a derived value to ensure you're working with up-to-date `data`. This make sure cache updates aren't missed. Use `useMemo` if referential integrity is important.

```tsx
const { data } = useQuery(query)

const derivedData = useMemo(() => transformData(data), [data])
```

Anyways, I'll go ahead and close this issue as it looks like it's "working as expected". Let me know if you need anything else and I'd be happy to reopen if you think there is more to do here. Thanks!

**Closed by jerelmiller** 2023-08-25 22:16 UTC
Labels: :rose: has-reproduction, ✍️ working-as-designed, 💸 caching
