### ISSUE TITLE
Sytax error on 0.1.15 apollo-boost

### ISSUE THREAD

**Issue by eviL-ivan** [apollographql/apollo-client#3853] opened 2018-08-26 17:52 UTC
**Intended outcome:**

All run nice on 0.1.15 version apollo-boost

**Actual outcome:**

/usr/src/app/node_modules/apollo-boost/lib/index.js:25
export * from 'apollo-client';
^^^^^^
 SyntaxError: Unexpected token export
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

Code in index.js at lines 26-35 not transpiled

![image](https://user-images.githubusercontent.com/27329923/44631288-82c34000-a972-11e8-8666-1ba54e439256.png)

**How to reproduce the issue:**

Just use 0.1.15

**Versions**

0.1.15

**Comment by hwillson** [comment] 2018-08-26 18:34
@eviL-ivan Can you provide an example of how you're using `apollo-boost`? `index.js` is now intentionally not transpiled, since it's no longer the main package entry point:

**package.json**

```js
...
  "main": "./lib/index.umd.js",
  "module": "./lib/index.js",
  "jsnext:main": "./lib/index.js",
...
```

By default your application should be using the `./lib/index.umd.js` entry point, which is es5 compatible. `./lib/indexjs` includes imports/exports to facilitate tree shaking approaches.

**Comment by eviL-ivan** [comment] 2018-08-26 18:52
@hwillson O, shure i just using apollo client, in my nextjs app:

`import { ApolloClient, InMemoryCache, HttpLink } from "apollo-boost"`;

like here:
https://github.com/zeit/next.js/tree/canary/examples/with-apollo-auth

**Comment by hwillson** [comment] 2018-08-26 19:06
Hmm - I just ran that test app with `apollo-boost` 0.1.15, and everything is working properly:

![screenshot 2018-08-26 15 04 57](https://user-images.githubusercontent.com/137740/44631957-7a9edc80-a941-11e8-991d-5c00c8c11082.png)

Any chance you could share a runnable reproduction that demonstrates the issue you're seeing?

**Comment by danilobuerger** [comment] 2019-01-29 18:42
Closing as no reproduction was provided in one week. Feel free to reopen if you have a minimal reproduction.

**Closed by danilobuerger** 2019-01-29 18:42 UTC
Labels: reproduction-needed
