### ISSUE TITLE
Add StoreProxy to optimistic response function form

### ISSUE THREAD

**Issue by blackxored** [apollographql/apollo-client#2445] opened 2017-10-31 19:35 UTC
IMHO it would be really helpful if `optimisticResponse` would take a StoreProxy (the object that allows `store.readQuery`, `store.readFragment`, etc, or in general allow a mechanism to read data from the store. Hopefully I'm not the only one that finds himself building partial optimistic responses and then adding the missing pieces in the `update` function, since I know we got all data we need to construct the optimistic response in the store, but no easy method to access it. I think `update` should be used for cases like add edge to fragment and the like, not to construct optimistic responses, and while both usually go in tandem it's really hard to reason about what's going on in the `update` function. Any thoughts?

**Comment by blackxored** [comment] 2017-11-22 10:02
Can someone other than a bot at least triage this? 🤕

**Comment by leosurwiki** [comment] 2018-01-17 02:01
Is this a dup of https://github.com/apollographql/apollo-client/issues/1802?

**Comment by hwillson** [comment] 2018-05-12 01:58
As mentioned in https://github.com/apollographql/apollo-client/issues/2445#issuecomment-358170441, this appears to be a duplicate of https://github.com/apollographql/apollo-client/issues/1802. Closing - thanks!

**Closed by hwillson** 2018-05-12 01:58 UTC
