### ISSUE TITLE
Fragment with only __typename is not transmitted, leading to an Unknown fragment error

### ISSUE THREAD

**Issue by KoltesDigital** [apollographql/apollo-client#6870] opened 2020-08-21 10:12 UTC
```js
fragment RetrieveErrorAll on RetrieveError {
	__typename
}
mutation {
	retrieve {
		errors {
			...RetrieveErrorAll
		}
		success
	}
}
```

**Intended outcome:**
Was working before upgrading to v3.

**Actual outcome:**
The HTTP request does not contain the fragment, it only contains the query which still references the fragment. Thus the response is an error with message `Unknown fragment "RetrieveErrorAll"`.

Adding another field in the fragment makes it work.

May be related to https://github.com/apollographql/react-apollo/issues/3650

**Versions**

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.125
    Edge: Spartan (44.19041.423.0), Chromium (84.0.522.63)

@apollo/client@3.1.3

**Comment by frantic1048** [comment] 2020-09-02 06:51
Met the exactly same issue with `@apollo/client@3.1.3`.

It looks related to apollographql/apollo-client#6311 (same symptom).

**Comment by hwillson** [comment] 2021-05-05 15:26
Duplicate of https://github.com/apollographql/apollo-client/issues/6311.

**Closed by hwillson** 2021-05-05 15:26 UTC
