### ISSUE TITLE
Using a setState inside a startTransition with a fetchMore cause Apollo to clear cached results when using a policy

### ISSUE THREAD

**Issue by Arno500** [apollographql/apollo-client#11642] opened 2024-03-05 00:35 UTC
### Issue Description

Hello,
I noticed that whenever I set a state based on the new data received, IF AND ONLY IF the incoming array is empty (???), it resets the results to an empty array for some reason

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-hswnfx?file=src%2Fcomponents%2FPaginatedQuery.tsx

### Reproduction Steps

1. Use an awaited `fetchMore` inside a `startTransition`
2. Continue to `fetchMore` until you get a perfectly empty array, signifying that you got to the end of the results
3. Set some state just after the awaited `fetchMore` (here we use a `hasMore`, similar to our own code base)
4. Observe the resulting merged array in `data` being 'reset'

### `@apollo/client` version

3.9.5

**Comment by jerelmiller** [comment] 2024-03-05 00:58
Hey @Arno500 👋 

I'll dig into this a bit more deeply, but as an FYI, something that stands out immediately is that React doesn't support async functions inside `startTransition`. From the [React docs](https://react.dev/reference/react/startTransition):

> The function you pass to `startTransition` must be synchronous. React immediately executes this function, marking all state updates that happen while it executes as transitions. If you try to perform more state updates later (for example, in a timeout), they won’t be marked as transitions.

Its possible something is happening here that gets React in a weird state. Transitions essentially render your component in 2 different states at the "same time", one with the new value, and one with the old value. Its possible the async function might be doing something weird here and confusing React.

I'll play around with your demo a bit to understand if this is the root issue, but just wanted you to know that React doesn't support async functions for `startTransition` 🙂

**Comment by Arno500** [comment] 2024-03-05 01:09
Thank you very much for that thorough explanation. Then how would you recommend reacting on only the new values?
I mean, in this case, I want to check that the incoming value (and not the total data) is empty. So how would it pan out with Apollo?

**Comment by jerelmiller** [comment] 2024-03-05 01:12
It would mostly be a matter of moving some code around.

Here is a version that uses a synchronous callback, but allows you to wait for the data to finish:

```ts
  const fetchMoreData = async () => {
    console.log('Probably have more data: ', hasMore);
    if (!hasMore) return;
    let promise!: Promise<ApolloQueryResult<any>>;

    startTransition(() => {
      promise = fetchMore({
        variables: {
          limit: 5,
          offset: data.histories.length,
        },
      });
    });

    const { data: newData } = await promise;

    console.log('Just received data: ', newData);
    if (newData.histories.length < 1) {
      console.log('Out of data, we consumed everything');
      setHasMore(false);
    }
  };
```

I threw this into my own [fork](https://stackblitz.com/edit/stackblitz-starters-12huk1?file=src%2Fcomponents%2FPaginatedQuery.tsx) of the reproduction, but looks like it doesn't really change much. So it seems like its likely an Apollo Client bug!

**Comment by DenisLaboureyras** [comment] 2024-03-08 09:27
I can reproduce this issue in my code as well.

I used this workaround of using readyQuery to solve temporarily this issue : 
https://github.com/apollographql/apollo-client/issues/11315#issuecomment-1966879780

**Comment by phryneas** [comment] 2024-03-08 11:59
@DenisLaboureyras can you please verify that you are still experiencing this in 3.9.6?

**Comment by DenisLaboureyras** [comment] 2024-03-08 14:57
@phryneas yes unfortunately i'm still experiencing this in 3.9.6.
As stated by @Arno500, the last fetchMore with an empty incoming array is reseting the cache

**Comment by jerelmiller** [comment] 2024-03-08 15:41
Some discovery notes:

I think I've narrowed this down to something in `QueryReference` itself. We are emmitting the wrong result on the `promise`. The cache seems fine and contains the full data set, we just are giving the wrong value from the hook.

**Comment by jerelmiller** [comment] 2024-03-19 21:35
Hey @Arno500 👋 

I've got a fix for this issue in #11706 and have confirmed this addresses the problem. See my [fork](https://stackblitz.com/edit/stackblitz-starters-12huk1?file=package.json,src%2Fcomponents%2FPaginatedQuery.tsx) of the reproduction which uses a snapshot build from that PR for a working example.

**Closed** 2024-03-20 18:01 UTC
Labels: :rose: has-reproduction, 🔍 investigate
