### ISSUE TITLE
related query result not updating after mutation

### ISSUE THREAD

**Issue by VinSpee** [apollographql/apollo-client#1293] opened 2017-02-13 17:49 UTC
**Intended outcome:**
I expect a component that is using a query to get its data would update that data following a mutation _if_ the mutation names that query in either `refetchQueries` or `updateQueries`. 

**Actual outcome:**
The component's data isn't updated unless `refetch()` is called explicitly, but `refetch()` also flushes the current data from the component.

**How to reproduce the issue:**

The flow should work like this:

1. User lands at QuestionsList (which could be empty)
2. User fills in form to add question (this occurs in the `AskQuestion` component)
3. Question is added to the QuestionsList

Here's the setup:
`allQuestions` query: 

```
  query allQuestions {
    allQuestions(orderBy: createdAt_ASC) {
      id
      createdAt
      content
      asker {
        id
        name
      }
      asked
      voters {
        id
        name
      }
    }
    _allQuestionsMeta {
      count
    }
  }
```

createQuestion mutation:

```
  mutation createQuestion(
    $content: String!
    $askerId: ID!
  ) {
    createQuestion(content: $content, askerId: $askerId, votersIds: [$askerId]) {
      id
      asked
      content
      asker {
        id
      }
      voters {
        id
        name
      }
    }
  }
```

The AskQuestion apollo graphql call:

```
  graphql(askQuestion, {
    name: 'askQuestion',
    props: ({ ownProps, askQuestion: doAsk }) => ({
      askQuestion(question) {
        doAsk({
          variables: {
            content: question,
            askerId: ownProps.currentUserID,
          },
          updateQueries: {
            allQuestions: (prev, { mutationResult: mut }) => {
              const newQuestion = mut.data.createQuestion;
              const newResults = {
                allQuestions: [
                  ...prev.allQuestions,
                  newQuestion,
                ],
                _allQuestionsMeta: {
                  count: prev._allQuestionsMeta.count + 1,
                },
              };
              return newResults;
            },
          },
        });
      },
    }),
  }),
```
(note, I've also tried with `refetchQueries`):

```
          refetchQueries: [{
            query: getAllQuestions,
          }],
```

and the QuestionsList query:

```
export default graphql(getAllQuestions)(QuestionsList);
```

I also have `dataIdFromObject` defined on client init: `dataIdFromObject: o => o.id || null,`.

Any idea what I'm missing here?

**Comment by calebmer** [comment] 2017-02-13 19:21
Does `QuestionsList` unmount during this time?

**Comment by VinSpee** [comment] 2017-02-13 19:24
No, it's in the same route as `AskQuestion` and rendered at the same time:

```jsx
  <App>
    <Header pathname={props.url.pathname} />
    <QuestionsList />
    <AskQuestion />
  </App>
```

**Comment by calebmer** [comment] 2017-02-13 19:45
Hmm, interesting. I don’t see any problems then. Could you put together a small reproducing use case by forking [`react-apollo-error-template`](https://github.com/calebmer/react-apollo-error-template)? It would go a long way in helping us debug the issue.

**Comment by VinSpee** [comment] 2017-02-13 20:35
In recreating with the error template, I found that `refetchQueries` worked but `updateQueries` was dispatching:
```js
{
  type: 'APOLLO_MUTATION_ERROR',
  error: {},
  mutationId: '7'
}
```

strange that it didn;t have an error, but I figured out it was because my `createQuestion` didn't return the `createdAt` field. Would have been nice to have some indication of that error somewhere, do you agree?

**Comment by calebmer** [comment] 2017-02-13 23:08
Definitely, there are a couple of cases where errors seem to be swallowed which is something we should clean up.

**Comment by cesarsolorzano** [comment] 2017-03-29 16:11
It looks like the problem described is the same as #973 and related to #1273. Closing in favor of #1273

**Closed** 2017-03-29 16:11 UTC
Labels: help wanted, warning
