### ISSUE TITLE
No typings when installing project via pnpm

### ISSUE THREAD

**Issue by JDansercoer** [apollographql/apollo-client#10808] opened 2023-04-26 14:48 UTC
### Issue Description

I just encountered a very strange bug and was stuck for half a day trying to figure it out. While I haven't found an exact solution yet, I was able to zoom in on what I think is the cause and wanted to see if there are smarter people that are able to determine what exactly is happening.

So the gist of the problem is that, when installing dependencies via `pnpm`, the typings of the `data` property of `useQuery` is determined as `any`, which shouldn't be correct. However, the strange this is that, when the dependencies are installed via `yarn`, the types are present (without changing anything else in the code).

PNPM
![CleanShot 2023-04-26 at 16 46 17](https://user-images.githubusercontent.com/11869830/234613190-49f6bcb3-5c5b-49f3-8281-feadf7962120.png)

YARN
![CleanShot 2023-04-26 at 16 45 41](https://user-images.githubusercontent.com/11869830/234613034-0bf90357-3527-4fd7-a358-6e5e4fcac26e.png)

While the `data` not being typed is the end-result, it starts earlier, with the result of `gql` being typed as `any` as well.

PNPM
![CleanShot 2023-04-26 at 16 41 41](https://user-images.githubusercontent.com/11869830/234611938-d6b7197e-c18e-49c6-88e2-7509fc0afb10.png)

YARN
![CleanShot 2023-04-26 at 16 45 06](https://user-images.githubusercontent.com/11869830/234612848-54f1f803-368a-4a57-b0a4-c597b501bdcc.png)

Some extra information:
- The repro has both lock files present for `yarn` and `pnpm`, but they were both generated just now from the same `package.json`
- `pnpm` version used locally is `7.30.5`, but was also tested with `v8`, but this had the same result
- `yarn` version is `1.22.19`

I really hope there's someone that can point me in the right direction!

### Link to Reproduction

https://github.com/JDansercoer/affectionate-lamarr-vgwgcx2

### Reproduction Steps

- Clone the repo
- Run `pnpm install`
- Check the inferred type of `data` in `src/Child.tsx`, line `17`
- See that the type is `any`
- Remove `node_modules`
- Run `yarn install`
- Check the inferred type of `data` in `src/Child.tsx`, line `17`
- See that the type is correct

**Comment by JDansercoer** [comment] 2023-04-26 17:14
I went ahead and created a bug report on the `pnpm` repository. I'll close this issue for now and see what their feedback is!

Thanks for the quick help!

**Comment by phryneas** [comment] 2023-04-27 08:25
@JDansercoer to be honest, I'm not sure it really is a bug. Apollo Client and GraphQL Codegen in your project can access `@graphql-typed-document-node/core` just fine.  

The problem is that after running the codegen, now *your* project has a direct dependency on `@graphql-typed-document-node/core` - and pnpm scopes it in a way that only Apollo Client and GraphQL Codegen have access to it - generally following the directions of your `package.json` in a valid interpretation.  
Maybe the codegen plugin would need a `peerDependency` on `@graphql-typed-document-node/core` instead? 🤔

**Comment by JDansercoer** [comment] 2023-05-09 13:53
@phryneas Yeah if you check the issue I raised on `pnpm`, it might make sense to indicate the `peerDependency` here.

**Comment by jerelmiller** [comment] 2023-05-10 17:04
Hey @JDansercoer 👋 

As @phryneas mentioned, this doesn't seem like an issue with Apollo Client itself, so I'm going to go ahead and close this issue. Thanks for the discussion!

**Closed by jerelmiller** 2023-05-10 17:04 UTC
