### ISSUE TITLE
Where is the documentation for 1.x.x?

### ISSUE THREAD

**Issue by PolGuixe** [apollographql/apollo-client#2660] opened 2017-12-03 11:31 UTC
I can't find the docs online.

**Comment by n1ru4l** [comment] 2017-12-05 10:57
Duplicate of #2505

**Comment by hwillson** [comment] 2018-05-11 20:10
As mentioned in https://github.com/apollographql/apollo-client/issues/2660#issuecomment-349269701, we'll close this as a duplicate of https://github.com/apollographql/apollo-client/issues/2505. Thanks!

**Closed by hwillson** 2018-05-11 20:10 UTC
