### ISSUE TITLE
useQuery returned same cached data with different variables

### ISSUE THREAD

**Issue by Sashkan** [apollographql/apollo-client#9900] opened 2022-07-13 11:42 UTC
I just setup a small hook using `react-router-dom` and `apollo-client`, for a very basic implementation:
- I have a list of items
- This list is based on a query which relies on an url parameter

This looks just like that:

```tsx
export const useList = () => {
  const { groupId, viewId } = useParams<{ groupId: string; viewId: string }>();


  const result = useListQuery({
    variables: { groupId, id: viewId },
    skip: !viewId,
    fetchPolicy: 'cache-and-network',
    nextFetchPolicy: 'cache-first',
  });


  return result;
};

export const useListQuery = (
  options?: QueryHookOptions<ListQuery, ListQueryVariables>
) => {
  return useQuery(LIST_QUERY, options)
}
```

Now, every time I navigate from one list page to another, I still get the old list content before the new one is displayed, resulting in a glitchy effect (previous data appears, then is immediately replaced by the new one)

I made sure that the variables were updated in the query, but still, it seems like apollo will always fetch from the cache for the last call on the query, regardless of the updated variables.

Is there a way to force invalidation? The only workaround I found so far is to set the fetch policy to `network-only`, which is obviously suboptimal...

**Comment by multimeric** [comment] 2022-07-27 03:38
You should also post your cache settings, ie the `new ApolloClient()` constructor, to make sure that isn't affecting it.

**Comment by Sashkan** [comment] 2022-08-17 14:23
Here's the client config:

```ts

    this.client = new ApolloClient({
      assumeImmutableResults: true,
      link: createPersistedQueryLink({ sha256 }).concat(
        ApolloLink.from([
          maintenanceLink,
          onError(({ graphQLErrors }) => {
            // TODO: handle errors
            if (graphQLErrors) {
              graphQLErrors.forEach(({ message, extensions }) => {
                if (
                  extensions?.code === 'UNAUTHENTICATED' ||
                  message === 'authentication-failed' ||
                  message === 'unauthorized-missing-user'
                ) {
                  logout(this.getClient()!).then(() => {
                    redirectTo(UserStatus.NOT_CONNECTED, this.history);
                  });
                }
              });
            }
          }),
          setContext(() => {
            return {
              credentials: 'include',
              headers: {
                authorization: `Bearer ${getAccessToken()}`,
              },
            };
          }),
          link,
        ]),
      ),
      cache,
      name: 'front'
      version: appConfig.version,
    });


```

**Comment by multimeric** [comment] 2022-08-17 14:28
Including the values of the variables you have used in that config (e.g. `cache`).

**Comment by Sashkan** [comment] 2022-08-17 14:52
My bad, I just updated the comment 🙏

**Comment by Hatko** [comment] 2024-08-06 08:29
Any updates on this issue?

**Comment by phryneas** [comment] 2024-08-06 09:30
I believe this might have been a misconception about `useQuery` and `react-router-dom`.

Generally:
The `useQuery` hook will never get data for the wrong variables from the cache. What is does, though, is that while your component is mounted, when you change variables, it holds on to the last data it had until it receives new data for the new `variables`. 
The purpose of this is to reduce flickering in your UI - if you go from the first page of a list to the second page, you likely want to keep the old data on the screen and just gray it out instead of going back to an almost-empty screen every time the user clicks "next" and having UI jump around.

Now, per default, if both your old page and your new page have the same component, `react-router-dom` does not unmount and remount your component - it simply changes props.
From an Apollo Client perspective, that looks like you are simply changing variables, there is no way it could distinguish between a "same page with variable change" and "different page" scenario here.

There are multiple things you can do here:

* check `result.networkStatus` instead of `result.loading` - this will give you more granular control over your loading states
* add a `key` to your page in the router. This will lead to React actually unmounting and remounting your component. You will start off with a new component, and the hook will be "freshly mounted" without previous data.
  See the React documentation on [Resetting state at the same position](https://react.dev/learn/preserving-and-resetting-state#resetting-state-at-the-same-position) with focus on [resetting state with a key](https://react.dev/learn/preserving-and-resetting-state#option-2-resetting-state-with-a-key)


As from our side, this is working as intended, I will close this issue. If you have further usage questions, please also visit [our Discord](https://discord.gg/graphos) and feel free to ask them in the #frontend channel :)

**Closed by phryneas** 2024-08-06 09:30 UTC
Labels: ⁉️ question
