### ISSUE TITLE
Second useQuery removes error state of first useQuery

### ISSUE THREAD

**Issue by tjveldhuizen** [apollographql/apollo-client#5248] opened 2019-08-29 13:49 UTC
**Intended outcome:**
I am trying to use the useQuery-hook in my React project. In my App, two components are included. Both do a (different) GraphQL-request via HTTP. The first endpoint needs a JWT-token, so it will return an error if it is not provided. The second endpoint is public, so should not respond with an error.

**Actual outcome:**
When I use only one of the two components, the application works as it is supposed to do. However, when both components are included things are acting weird: sometimes the 'error' value of the first GraphQL-call is emptied, resulting in the 'success' output being rendered without data.

**How to reproduce the issue:**
https://codesandbox.io/embed/apollo-client-error-template-2d0ex

Things are doing fine when the output states request 1 returned an error and request 2 returned data. However, when you keep refreshing the output, sometimes you'll see (in red) that the 'if (error)'-line of the first request is skipped however the response _is_ incorrect.

**Versions**

  System:
    OS: Windows 10
  Binaries:
    Node: 12.5.0 - D:\nodejs\node.EXE
    npm: 6.9.0 - D:\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.10015.0
  npmPackages:
    apollo-boost: ^0.4.4 => 0.4.4

**Comment by dylanwulf** [comment] 2019-08-29 14:17
Possible duplicate of https://github.com/apollographql/react-apollo/issues/3406

**Comment by benjamn** [comment] 2019-09-17 20:30
This appears to be fixed in the latest version of `@apollo/react-hooks` (3.1.1), according to your reproduction. Thanks very much for putting together that reproduction @tjveldhuizen!

**Closed by benjamn** 2019-09-17 20:30 UTC
Labels: :rocket: shipped, :rose: has-reproduction, 🐞 bug
