### ISSUE TITLE
[2.0] Use cache breaks react-apollo

### ISSUE THREAD

**Issue by hlehmann** [apollographql/apollo-client#2266] opened 2017-10-06 11:06 UTC
It's related to https://github.com/apollographql/react-apollo/issues/1192
But I think it's caused by apollo-client.

**Intended outcome:**
Scenario:
query1 + variables1 => data1
query1 + variables2 => data2
query1 + variables1 => data1

**Actual outcome:**
Same scenario:
query1 + variables1 => data1
query1 + variables2 => data2
query1 + variables1 => data2 instead of data1

**How to reproduce the issue:**
It breaks since apollo-client@2.0.0-beta.3 and it worked well with beta.2

I try to revert apollo-cache-inmemory, apollo-link, apollo-link-http with no impact so it's clearly cause by apollo-client

**Comment by jbaxleyiii** [comment] 2017-10-10 14:03
@hlehmann do you have a small reproduction for this? I'd love to take a look! Also, what version of react-apollo are you using?

**Comment by aortbals** [comment] 2017-10-10 15:08
@jbaxleyiii I believe https://github.com/apollographql/react-apollo/issues/1192, the discussion and explanation here https://github.com/apollographql/apollo-client/pull/2200#issuecomment-332338791, and https://github.com/apollographql/react-apollo/issues/1192 are all the same issue.

With the recycling behavior of ObservableQuery, in combination with a cache-only (no fetch) strategy, the ObservableQuery is not taking into account the variables passed to a query and returns the wrong data.

So, in the right circumstance, where the ObservableQuery is not torn down:

1. Load query `fuu` with variable `page: 1` 
1. Load query `fuu` with variable `page: 2` 
1. Load query `fuu` with variable `page: 1` - will return the wrong cached data

We are seeing this on the latest betas of 2.0 in a user interface that is nearly identical to what I describe above or also in [this description](https://github.com/apollographql/apollo-client/pull/2200#issuecomment-332324827).

```json
"apollo-cache-inmemory": "^0.2.0-beta.4",
"apollo-client": "^2.0.0-beta.4",
"apollo-link": "^0.7.0",
```

We're working around this by using `fetchPolicy: 'network-only'` at the moment, which will force a refetch, but isn't ideal and is just a temporary fix. This has currently one of the more significant blockers for us to migrate to 2.0. From my understanding, the solution proposed in https://github.com/apollographql/apollo-client/pull/2200 would fix the problem, or the implementation of a `prepareForReuse` API in conjunction with an update to react-apollo would also fix it.

**Comment by jbaxleyiii** [comment] 2017-10-10 18:31
@aortbals thanks for the detailed response! I will get a solution out for you ASAP and would love if you could try it out!

**Comment by aortbals** [comment] 2017-10-10 19:36
Awesome, thanks @jbaxleyiii. Looking forward to trying something out. Ping me if I can help!

**Comment by jbaxleyiii** [comment] 2017-10-11 03:58
@aortbals btw, what version of react-apollo are you using?

**Comment by seeden** [comment] 2017-10-11 08:50
@jbaxleyiii  it is not fixed in react-apollo 2.0. I reported same issue https://github.com/apollographql/react-apollo/issues/1192

**Comment by aortbals** [comment] 2017-10-11 12:04
@jbaxleyiii I'm using `react-apollo` `2.0.0-beta.0`. Personally, I've seen this issue only on the 2.x/beta series of releases.

**Comment by seeden** [comment] 2017-10-11 14:21
Maybe it is related to https://github.com/apollographql/apollo-client/issues/2285 as well

**Comment by jbaxleyiii** [comment] 2017-10-11 14:24
@seeden would you be able to help me with a small reproduction using the reproduction template? I included a [new test](https://github.com/apollographql/react-apollo/blob/apollo-client-2.0/test/react-web/client/graphql/queries/observableQuery.test.tsx#L472) in the 2.0 of react-apollo specifically for this last week but it looks like I'm missing how its being run in your (and others) app to fix the bug

**Comment by jbaxleyiii** [comment] 2017-10-11 14:25
@aortbals @seeden a few more questions:

- does this only happen when the watched component is unmounted then remounted (i.e page navigation)?
- does this happen when calling refetch manually?

**Comment by seeden** [comment] 2017-10-11 14:31
@jbaxleyiii no my component is mounted (I checked it).  graphql decorator just get a new variable. ( I am switching between users profiles = I am not the same route)
```js
@graphql(PROFILE_CONTAINER_QUERY, {
  options: ({ match: { params: { username } } }) => ({
    variables: {
      username,
    },
  }),
})
```

**Comment by jbaxleyiii** [comment] 2017-10-11 14:31
I may have been able to create a reproduction. Still investigating. This is my top priority today so expect a fix soon!

**Comment by jbaxleyiii** [comment] 2017-10-11 14:46
Live action play by play:

1. [Original working code with some of the 2.0 betas](https://codesandbox.io/s/jvlrl98xw3)
2. [Now broken version of the app with the latest](https://codesandbox.io/s/52rk91om8p)
3. Failing test written in react-apollo
4. Currently working on failing test in apollo-client

**Comment by jbaxleyiii** [comment] 2017-10-11 15:59
Thanks everyone for the issue report and help! I've fixed the bug [here](https://github.com/apollographql/apollo-client/commit/c9c642d785f0b7b83e82402a537dbb2498f25d0e), verified it in react-apollo and in a sample app. Working on a new release now.

Heads up that we are in the RC mode so you will need to switch from `@beta` for apollo-client and apollo-cache-inmemory to `@next`.

React Apollo 2.0 is still in beta but should be in RC soon!

**Comment by jbaxleyiii** [comment] 2017-10-11 16:09
[Working version of the app with the new RC](https://codesandbox.io/s/9o8p6z1oo4)

**Comment by hlehmann** [comment] 2017-10-11 16:43
It works well for me. Thx !

**Comment by aortbals** [comment] 2017-10-11 20:11
@jbaxleyiii it looks like a query like this is fixed:

```
query UsersQuery($id: ID) {
	users(id: $id) {
		id
		name
	}
}
```

However, when you use the variable nested, not at the root, it doesn't select the correct set of cached `items` out of the cache (I can see that multiple sets of `posts` are cached like `posts({"page":1})`, `posts({"page":2})` inside of a given user, but I'm seeing the same behavior as before with the wrong inner list being returned to the component.

```
query UsersQuery($page: Int) {
	users {
		id
		name
		posts(page: $page) {
			...PostFragment
		}
	}
}
```

Let me know if this is making sense. Thanks!

**Comment by seeden** [comment] 2017-10-12 13:54
@jbaxleyiii can you reopen this issue ?

**Comment by jbaxleyiii** [comment] 2017-10-19 22:02
@seeden @aortbals I also added a test for the nested path here https://github.com/apollographql/apollo-client/pull/2342/commits/a0a6462ec2b31a87aefd7ae4dcd51830506731b8

**Comment by jbaxleyiii** [comment] 2017-10-20 00:09
@seeden  can you try the newest rc (`rc.4`?)

**Comment by seeden** [comment] 2017-10-24 19:14
I tried 2.0.0 it is not working. :(

**Comment by atoy40** [comment] 2017-11-14 16:43
I'm using apollo-client without react and I have the same issue with :

**Comment by coun7zero** [comment] 2017-12-07 16:01
It still doesn't work!

**Comment by coun7zero** [comment] 2017-12-07 17:00
Hi, I'm using that dependencies:
```
 "apollo-cache-inmemory": "^1.1.3",
 "apollo-client": "^2.1.0"
```

I had a similar problem with cache and variables but what is surprising change `addTypename` to `false`  fixes the problem:

```
export const apolloClient = new ApolloClient({
  link: new HttpLink({ uri: '/graphql', fetch: fetch }),
  cache: new InMemoryCache({
    addTypename: false
  })
})
```

**Comment by hwillson** [comment] 2018-06-14 18:04
This should be fixed in recent versions of `apollo-client`. It not, definitely let us know. Thanks!

**Closed by hwillson** 2018-06-14 18:04 UTC
Labels: bug

**Comment by Destroy666x** [comment] 2018-11-13 14:49
@hwillson in 2.4.2 the workaround above was still needed in one case - some data in object array was missing after some consecutive similar requests.

The query looks like this: 
```graphql
query ($minLat: Float!, $maxLat: Float!, $minLng: Float!, $maxLng: Float!, $clusterType: String!, $areas: [String]!, $isics: [String]!, $multiplier: Float!) {
  businesses {
    aggregationByAreaAndIsic(locationBoundingBox: {minimalLatitude: $minLat, maximalLatitude: $maxLat, minimalLongitude: $minLng, maximalLongitude: $maxLng}, areaAggregation: {areaClusterTypes: [$clusterType], highlightedAreas: $areas}, isics: $isics) {
      areaBuckets {
        area {
          id
          location {
            latitude
            longitude
          }
        }
        isicBuckets {
          size
          isic {
            id
            root {
              id
            }
          }
        }
        size
      }
    }
    aggregationByGeohashGridAndIsic(areas: $areas, locationBoundingBox: {minimalLatitude: $minLat, maximalLatitude: $maxLat, minimalLongitude: $minLng, maximalLongitude: $maxLng}, isics: $isics, precisionDistanceMultiplier: $multiplier) {
      geohashGridBuckets {
        id: geohash
        location {
          latitude
          longitude
        }
        isicBuckets {
          isic {
            id
            root {
              id
            }
          }
          size
        }
        size
      }
    }
    size(areas: $areas, isics: $isics)
  }
}
```
