### ISSUE TITLE
Refetch query based on @connection directive

### ISSUE THREAD

**Issue by marcel-devdude** [apollographql/apollo-client#3366] opened 2018-04-24 13:25 UTC
**Intended outcome:**
Refetch a query based on the given key in the `@connection` directive.

**Actual outcome:**
Query is not being refetched and not accessible by the cache.

**How to reproduce the issue:**
I have a paged query like this:

```
query Comments {
  comments(first: $first, offset: $offset) @connection(key: "foobar") {
    edges: {
      ...
    }
  }
}
```

And a mutation like this:

```
<Mutation mutation={deleteComment} refetchQueries={['foobar']} />
```

I would expect, that i can use the "stable" Store-Key to address the query in the `refetchQueries` prop. I also tried to access the query in the `update` method in the mutation with `cache.readQuery('foobar')`. But it did not work as expected.

**Version**
- apollo-client@2.0.1

**Comment by hwillson** [comment] 2018-08-05 01:10
Closing as a duplicate of https://github.com/apollographql/apollo-client/issues/3228. Thanks!

**Closed by hwillson** 2018-08-05 01:10 UTC
