### ISSUE TITLE
Redux devtools' time travel not working

### ISSUE THREAD

**Issue by gfpacheco** [apollographql/apollo-client#1874] opened 2017-07-09 21:26 UTC
From the docs:

> If you don’t pass in an existing Redux Store into the ApolloClient constructor, then you will get integration by default with the Redux DevTools extension.

Other redux actions, dispatched manually, can be "undone" by time travel just fine.
But the ones dispatched by apollo-client just can't, not out of the box nor passing a redux store to the client.

**Intended outcome:**
Redux devtools extension time travel working

**Actual outcome:**
Redux time travel doesn't work

**How to reproduce the issue:**
- Install [redux devtools extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi);
- Clone the [error template](https://github.com/apollographql/react-apollo-error-template) and run (`npm install && npm start`).

**Comment by stubailo** [comment] 2017-07-10 04:05
Duplicate of #1800, let's keep discussion there!

**Closed by stubailo** 2017-07-10 04:05 UTC

**Comment by gfpacheco** [comment] 2017-07-10 04:12
Actually the issue I'm reporting is that time travel isn't working at all. While traveling through time neither the state is changed or the components re-rendered.

**Comment by stubailo** [comment] 2017-07-10 04:27
> CORRECTION: actions are not fired, graphql queries are not retriggered.

It sounds like it's the same issue - that it doesn't really work at all.

Either way, I think the changes to fix this are going to be the same, so it's best to have one issue about it. Having more people on the same thread makes it easier to prioritize and discuss.
