### ISSUE TITLE
When creating a record directly against local cache, Apollo behaves unexpectedly if one of the optional fields is missing 

### ISSUE THREAD

**Issue by yattias** [apollographql/apollo-client#1605] opened 2017-04-19 03:22 UTC
**Intended outcome:**
To create a record locally which will be synced at a later time to the server. The goal is to read from cache, append to the cached array and save directly to cache.

**Actual outcome:**
When creating the record locally as [described here](http://dev.apollodata.com/core/read-and-write.html#writequery-and-writefragment) Apollo "empties out" my local query cache.  

This issue only happens if I create a record locally which misses any of the fields specified by the original query.

**How to reproduce the issue:**

Use a query such as this to fetch data from server and into local cache:

```
  query fetchAssetsQuery {
    assets {
        contentState
        id
        createdAt
    }
```

Now create a new record locally which is missing the `createdAt` prop as such:

```js
      let assets = client.readQuery({
        query: fetchAssetsQuery
      }).assets;

    client.writeQuery({
      query: fetchAssetsQuery,
      data: {
        assets: [{
          id: id,
        }, ...assets]
      }
    });
```

Finally, sync to the server as such:
```js
      return mutate({
        variables: assetListInput: {
               assets: assets
        },
        updateQueries: {
          getUserAssets: (previousQueryResult, { mutationResult }) => {
            let currentAssets = previousQueryResult.assets;
            return { assets: currentAssets };
          }
        }
      })
```

This will result in the query turning into an empty array. To be more specific, `updateQueries` does not get executed here.

However, If I create the local record with the missing `createdAt` prop, this issue is resolved.

There are certain props that I'd like the server to create such as `createdAt`.

**Comment by Poincare** [comment] 2017-04-19 23:54
If I'm understanding correctly, this is intended behavior since if you update the store with a result that's missing `createdAt`, it's going to break the existing query observer on the page associated with the query containing the `createdAt` field.

**Comment by yattias** [comment] 2017-04-20 12:25
Hey @Poincare yes, that's exactly what I did however I raised the issue here because I think Apollo should be throwing an error or at least a warning in such a case. Took some time before I figured out what was actually happening.

**Comment by Poincare** [comment] 2017-04-20 14:02
@yattias I believe that an error should be thrown within the observer for your query as soon as the query breaks.   Are you sure this is not the case? If you're using react-apollo, maybe the error is being swallowed. 

If this is not the case, it would be great if you could contribute a failing unit test that shows this.

**Comment by cesarsolorzano** [comment] 2017-04-20 18:36
The problem with this error being swallowed has been extensively reported, closing this in favor of #1611

**Closed** 2017-04-20 18:37 UTC

**Comment by yattias** [comment] 2017-04-20 20:19
@Poincare the error is being swallowed somewhere. I will provide a unit test for this but it will take me a bit of time. Let's keep this open for now please.

**Comment by Poincare** [comment] 2017-04-20 20:26
I believe @cesarsolorzano is right. This issue can be closed since there is another one that describes exactly this problem.

**Comment by cesarsolorzano** [comment] 2017-04-20 20:55
@yattias  as a matter of fact, the error is being swallowed [here](https://github.com/apollographql/apollo-client/blob/2ee7971938eba4c19f7de93ff182a6d55d145b44/src/core/QueryManager.ts#L923-L930), although the solution to this isn't that simple. If you are interested about this, there's more information in the issue mentioned above. 🙂

**Comment by yattias** [comment] 2017-04-20 22:10
Got it. Cool. Just wanted to make sure it's being tracked.
