### ISSUE TITLE
ApolloClient[3.0.rc2]: typePolicy readField wrong storeFieldName 

### ISSUE THREAD

**Issue by Banou26** [apollographql/apollo-client#6489] opened 2020-06-25 09:39 UTC
**Intended outcome:**
When trying to read from the cache from a typePolicy using `readField`, like so `account({})`, it should call the specified typePolicy `read` function with the correct `existingData`

**Actual outcome:**
When trying to use `readField('account({})')`, the `storeFieldName` is `"account({}):account({})"` which makes the typePolicy read function be called with `undefined` as `existingData` instead of its actually stored data in `ROOT_QUERY:account({})`

**How to reproduce the issue:**
Define a typePolicy having the same read name as data already in the cache, e.g

```js
client.writeQuery({
  query: gql`
  {
    account {
      id
      bar
    }
  }`,
  data: {
    account: {
      id: 'foo',
      bar: 'bar',
      __typename: 'Account'
    }
  }
})

cache.policies.addTypePolicies({
  Query: {
    fields: {
      account: (existingData, { args, storeFieldName, toReference, readField, ...argss }) => {
        const acc =
          args?.id
            ? toReference({ __typename: 'Account', id: args.id })
            : existingData
        console.log('acc', existingData, acc, { ...argss, args, storeFieldName, toReference, readField })
        return acc
      },
      acc: (_, { readField }) => readField('account({})')
    }
  }
})
client.readQuery({ query: gql`{ acc @client { id } }` })
```

**Versions**
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - F:\softwares\yarn v1.22.0\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @apollo/client: ^3.0.0-rc.8 => 3.0.0-rc.8

**Comment by benjamn** [comment] 2020-06-25 15:20
For cases where `readField` needs arguments, you should pass named options instead of using the usual shorthand:
```ts
readField({
  fieldName: "account",
  args: {},
})
```
See #6306 for more details. I will close this issue now because I believe this is working as designed, but please feel free to comment if you have further questions.

**Closed by benjamn** 2020-06-25 15:20 UTC
