### ISSUE TITLE
3.5.0 output of useQuery is no longer memo'ed

### ISSUE THREAD

**Issue by FritsvanCampen** [apollographql/apollo-client#9204] opened 2021-12-15 14:16 UTC
In 3.5.0 the implementation of useQuery has been completely rewritten. Although no tests fail, the output behavior has changed (because there is no test that tests for it).

Previously, if the Component the useQuery hook is in was rerendered, the output of useQuery would not change. But as of 3.5.0 the output is an un-memo'ed plain object, meaning that it will _always_ change.

This to me seems like a pretty significant (and potentially breaking) change because it can affect memo'ing further down the Component hierarchy. It may also affect hooks that wrap the output of `useQuery` and cause their memo'ing to break.

Was this change made intentionally and deliberately? If not, I would recommend the old behavior is restored.

What is the Apollo teams' view on this?

**Comment by jbrawnjr** [comment] 2021-12-17 08:50
I have run into this issue as well. Upgrading from a `3.4.x` to a `3.5.x` version seems to have caused infinite render loops throughout my project due to the `tuple` from `useQuery()` being a new object on every render, instead of it only being a new object when a new response comes through.

I request that the old behavior be reinstated.

**Comment by jamesopti** [comment] 2021-12-19 16:46
> I have run into this issue as well. Upgrading from a `3.4.x` to a `3.5.x` version seems to have caused infinite render loops throughout my project due to the `tuple` from `useQuery()` being a new object on every render, instead of it only being a new object when a new response comes through.
> 
> I request that the old behavior be reinstated.

+10000 to this - Exact same thing happened to me. This is a huge breaking change that should prevent anyone from updating until fixed.

**Comment by jebax** [comment] 2021-12-21 13:28
+1 can't upgrade until this is fixed, it completely breaks our app.

**Comment by jebax** [comment] 2021-12-21 13:29
+1 can't upgrade until this is fixed, it completely breaks my app.

**Comment by hubiwan** [comment] 2021-12-23 23:53
Not sure what happened but I think the same issue applies to useMutation as well.

To illustrate that:
- call useMutation hook from a react custom hook and simply return the mutate function from the tuple
- call the custom from a react component, it will re-render indefinitely...

Think current behaviour is very annoying given this is a quite common pattern.

**Comment by jscarmona** [comment] 2022-01-06 17:01
+1

**Comment by jamesopti** [comment] 2022-02-02 00:33
Does 3.5.8 fix this?

**Comment by FritsvanCampen** [comment] 2022-02-02 19:48
> Does 3.5.8 fix this?

It does not. It does fix one of the 'bad' re-renders in `useLazyQuery`, but the behavior of `useQuery` is unchanged.

**Comment by marcin-piekarski** [comment] 2022-02-04 05:34
> I have run into this issue as well. Upgrading from a `3.4.x` to a `3.5.x` version seems to have caused infinite render loops throughout my project due to the `tuple` from `useQuery()` being a new object on every render, instead of it only being a new object when a new response comes through.
> 
> I request that the old behavior be reinstated.

Hey guys, we've recently upgraded from 3.4.17 to 3.5.8 and now all of a sudden, similar to [jbrawnjr](https://github.com/jbrawnjr) issue. We're now seeing infinite loops.

Downgrading fixes the issue.

Any ideas on when we might go back to the previous approach?

**Comment by lukebrandonfarrell** [comment] 2022-02-04 10:31
Yeah this is a problem, useQuery causes re-renders every few seconds with 3.5.X

**Comment by benjamn** [comment] 2022-02-04 15:51
Hi folks, if anyone has time, can you try writing a quick failing [`useQuery` test](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/__tests__/useQuery.test.tsx) to demonstrate exactly what you expect? If more than one person takes me up on this, that'd be a great way to make sure we're all talking about the same thing.

Guaranteeing referential identity for the result object of `useQuery` is not something we ever intended, but we're happy to look into restoring/improving that behavior if it was useful to you before.

**Comment by jamesopti** [comment] 2022-02-06 19:25
> Hi folks, if anyone has time, can you try writing a quick failing [useQuery test](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/__tests__/useQuery.test.tsx) to demonstrate exactly what you expect? If more than one person takes me up on this, that'd be a great way to make sure we're all talking about the same thing.

Here you go. Very simple reproduction case: https://github.com/apollographql/apollo-client/pull/9407

> Guaranteeing referential identity for the result object of useQuery is not something we ever explicitly intended, but we're happy to look into restoring/improving that behavior if it was useful to you before.

In my opinion, in any modern React app this is absolute table stakes functionality, especially if you're concerned about performance. There are hooks everywhere, and all sorts of things can cause a component to re-render. Thus the architecture of a hook that returns a value should be to, when asked, return the current value the caller asked for (at least using a shallow comparison). Often times, this will not change (and is similar to a pure function, although hooks are not purely functional).

Hunting down the root cause of unnecessary re-renders caused by hooks is a big part of improving performance of larger React apps.

```ts
const result = useQuery(someQuery);

useEffect(() => {
  // At least one of the keys of result must have changed
}, [result])
```


### The Underlying Problem

I took a deeper dive into the code and noticed 2 things contributing to this issue:
- A re-computation of `createWatchQueryOptions` [on every render](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/useQuery.ts#L316) in several places (this is easily memoized)
- An inline render assignment to a `useState` variable (`result`) 🙈 
  - It appears [this specific line](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/useQuery.ts#L223) is the culprit, where `result` is redefined on every render as a result of destructuring itself to grab the `partial` variable. I don't know if this was intentional or why `const partial = result.partial;` is not sufficient?
    ```ts
    let partial: boolean | undefined;
    ({ partial, ...result } = result);
    ```
  - This one is really bad. It looks like this is trying to handle `partialRefetch`, and I do see it labeled as `BAD BOY CODE BLOCK`, but it's hard to see how something like this wouldn't immediately cause widespread issues. I don't even know how React handles this internally.

The most recent commit in pull #9407 implements a fix for this, but it's hard for me to tell if it's a regression for the original `partialRefetch` hack or other parts of the code that consume this.

Hope this helps.

**Comment by FritsvanCampen** [comment] 2022-02-08 11:53
> Hi folks, if anyone has time, can you try writing a quick failing [useQuery test](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/__tests__/useQuery.test.tsx) to demonstrate exactly what you expect?

Please see PR:https://github.com/apollographql/apollo-client/pull/9412

This test tests the same behavior that [jamesopti](https://github.com/jamesopti)'s test tests but in a more concise way. `renderHook` is used to avoid having to use an inspector component (`Component:r24`).

My test sadly fails with a slightly obscure error message. I think `jest` is having trouble creating a debug message that contains a circular JSON object. If this is a problem the assert can be changed to:
```
expect(oldResult === result.current).toBe(true);
```

The attempted fix in https://github.com/apollographql/apollo-client/pull/9407 seems to be the right direction. Two things need to be memo'd:
1. The output of `useQuery`. It currently always returns a new object.
2. The properties of the return object need to be memo'd. One obvious problem here is `variables: createWatchQueryOptions(..).variables`, that will always produce a new value even though `variables` probably didn't change. I think the other properties `...obsQueryFields`, `client`, `called`, `previousData` and `result` are already memo'd correctly but it's worth investigating in more detail. Specific tests could be written for specific edge cases.

The underlying problem here seems to me that with React hooks it's not so easy to communicate how a hook behaves and how it should behave. Getting it wrong may cause an App to fail critically. I think static code analysis might be able to catch these situations. I hope React will work on resources to improve this situation.

Thanks.

**Comment by benjamn** [comment] 2022-03-10 23:07
We're hopeful the latest beta release, `@apollo/client@3.6.0-beta.9` or just `@apollo/client@beta`, restores the referential stability of `useQuery` result objects, thanks to the refactoring in #9459.

I incorporated both #9412 by @FritsvanCampen and #9407 by @jamesopti into my test suite for #9459, so thank you both again for those concrete test cases.

I'm happy to keep talking about any other regressions or differences in behavior, but I would suggest opening new issues (unless it's directly relevant to this issue, in which case please comment here).

Give the beta a try when you can!

**Closed** 2022-03-22 17:51 UTC
Labels: 🛬 fixed-in-prerelease, :rose: has-reproduction, 📟 regression, ⚛️ React-related

**Comment by RemyMachado** [comment] 2022-11-04 15:33
Are you sure this is fixed?

I'm still having a different reference to `data` on every render even without a refetch.

I'm using the latest release at the moment `v3.7.1`
