### ISSUE TITLE
New variables are not used after refetch(newVars)

### ISSUE THREAD

**Issue by makamekm** [apollographql/apollo-client#2285] opened 2017-10-11 11:21 UTC
Hello! I don't know how to make it better. Please help.
I use the function:

```
    async update() {
        let variables = {
            company: this.props.match.params.companyId,
            filter: this.filter, order: this.order, limit: this.pagiation.limit, offset: this.pagiation.offset
        };
        await this.props.refetch(variables);
    }
```

But I see in Network two queries and nothing happens.
The first one is right, but the second is the default data (like `variables: { company: props.match.params.companyId, filter: {}, order: [], limit: 10, offset: 0 }`). Why?

```
@ApolloReact.graphql(ApolloReact.gql"
    query Departments($company: ID!, $filter: DepartmentFilter!, $order: [DepartmentOrder], $limit: Int, $offset: Int) {
        company {
            get(id: $company) {
                id,
                name,
                color,
                departments {
                    list(filter: $filter, order: $order, limit: $limit, offset: $offset) {
                        departments {
                            id,
                            color,
                            name,
                            users {
                                id, avatar, username
                            },
                            tags {
                                name
                            },
                            date
                        },
                        count
                    }
                }
            }
        }
    }", {
    props: ({ ownProps, data: { loading, company, refetch } }) => ({
        company: company && company.get,
        departments: company && company.get && company.get.departments && company.get.departments.list.departments,
        count: company && company.get && company.get.departments && company.get.departments.list.count,
        loading: loading,
        refetch: refetch
    }),
    options: (props) => ({
        fetchPolicy: 'cache-and-network',
        variables: { company: props.match.params.companyId, filter: {}, order: [], limit: 10, offset: 0 }
    }),
})
```

**Comment by makamekm** [comment] 2017-10-11 11:52
But if I call `console.log(await this.props.refetch(variables));` this is what i need, but I want to see it in `props`. 

```
    async update() {
        let variables = {
            company: this.props.match.params.companyId,
            filter: this.filter, order: this.order, limit: this.pagiation.limit, offset: this.pagiation.offset
        };
        console.log(await this.props.refetch(variables));
    }
```

**Comment by jbaxleyiii** [comment] 2017-10-11 14:22
@makamekm what version of apollo client and react-apollo are you using?

**Comment by makamekm** [comment] 2017-10-11 16:05
"apollo-client": "1.9.3",
"react-apollo": "1.4.16"

**Comment by nyanpasu** [comment] 2017-10-24 05:18
I have also encountered similar behaviour.

When I call `this.props.data.refetch()`, without a variables argument, I see a network request for the query and `this.props.data` updating. However, if I call `this.props.data.refetch({ stuff })`, I still see a network request with the updated variables, but the corresponding props does not update. `this.props.data.refetch({ stuff })` does return a Promise resolving to the results, though.

**Comment by moimael** [comment] 2017-11-21 16:10
I'm still seeing this issue with latest apollo-client (2.0.3)

**Comment by Axure** [comment] 2017-12-09 03:05
I'm encountering this problem in apollo client 2.1.0, and apollo-angular 1.0.0. The network request is sent, but the data is not used. I tried to debug into apollo client, and I found out that the network request is actually fulfilled after the update of the observable, which is weird.

**Comment by tylerjbainbridge** [comment] 2017-12-19 19:51
I'm seeing this as well.

**Comment by ishancns** [comment] 2018-01-03 05:49
having the same issue , how to solve? props are not updated

**Comment by jhalvorson** [comment] 2018-01-15 10:26
Can confirm that I'm seeing the same issue with `2.0.4`

**Comment by BipinBhandari** [comment] 2018-01-18 05:55
Is this issue being solved?

**Comment by arsanjea** [comment] 2018-02-01 16:21
Hello, is this issue being worked on?

**Comment by marlonmleite** [comment] 2018-02-01 20:41
I have the same problem, the refetch happens and shows on the network with the correct data. But by analyzing the response data, it displays the old data.
Anyone solved it?

**Comment by zackify** [comment] 2018-03-04 21:49
Seeing this as well

**Comment by etripier** [comment] 2018-03-13 21:54
Hopefully this is helpful: With the latest `apollo-client` release (`apollo-client@2.2.7`), you can call `client.queryManager.clearStore()` right before you refetch and your props should update correctly.

**Comment by geminiyellow** [comment] 2018-06-13 08:15
same error, tell me why.

**Comment by lahed** [comment] 2018-06-22 18:54
Same error

**Comment by ShepelievD** [comment] 2018-07-28 17:43
@etripier didn't work fo me

**Comment by hwillson** [comment] 2018-09-05 14:30
Can anyone here provide a small runnable reproduction that clearly demonstrates this happening? Thanks!

**Comment by pl12133** [comment] 2018-11-14 17:48
@hwillson I am happy to have a reproduction that I believe covers the scenario described here: https://codesandbox.io/s/yvk8n4j4lx

My first guess was described in https://github.com/apollographql/apollo-client/issues/3948#issuecomment-433416971:

> ...For me this is happening because ObservableQuery.prototype.refetch is invoked once with the new variables, and then Query.prototype.componentWillReceiveProps calls ObservableQuery.prototype.updateQuery with the old variables. Since the Query component is involved, I believe this is related to react-apollo.

It seems like I was on the right track, because when I added `fetchPolicy: 'cache-and-network'` the bug reproduces. So putting all of that together, it appears this bug is caused by:

> Given a query using `fetchPolicy: 'cache-and-network';` when `refetch` is called with new variables, passing new props to the query component immediately after `refetch` has begun will cause the query to fire again with the old variables.

**Comment by joebernard** [comment] 2018-12-01 18:37
@pl12133 I'm seeing this same issue with `fetchPolicy: "network-only"`. Variables passed into `refetch` are ignored.

**Comment by gges5110** [comment] 2018-12-05 16:22
I am seeing the same issue with
"apollo-client": "^2.4.6",
"react-apollo": "^2.3.1",

**Comment by joebernard** [comment] 2018-12-06 03:56
I need to retract my last comment. My issue was related to an interaction with `react-navigation` and `apollo`. Now that it is resolved I can confirm this variables issue does present itself when `fetchPolicy: 'cache-and-network`.

**Comment by gges5110** [comment] 2018-12-06 20:34
Changing the fetchPolicy from 'network-only' to 'cache-first' which is the default fetchPolicy resolved my issue. Before it would trigger an extra fetch caused by Query.componentWillReceiveProps calling Query.updateQuery.

**Comment by danilobuerger** [comment] 2019-02-01 16:54
Reproduced with https://codesandbox.io/s/j3410pq2vv
Thanks @pl12133

**Comment by tushark1** [comment] 2019-04-06 11:23
I was facing the same problem, so as a workaround I'm able to pass new variables to refetch like this:

`refetch({
        ...variables,
        name: searchValue
      });`

**Comment by joebernard** [comment] 2019-05-02 13:16
I'm experiencing a similar issue with `refetch`. I set some breakpoints and notice that Apollo will first run the query with the new variables. It will then trigger the original query to run, which uses the original props. This overwrites the new results with the old/original results. Then, if I trigger `refetch` again with new variables, it will perform the query with the new variables and NOT attempt to run the original query. I get the expected behavior on this second attempt.

It looks like `refetch` is not using the variables, but it does. It just runs the original query immediately after making it seem like only the original variables were used.

I'm using the HOC implementation with `compose` and `graphql()`. I'm also using the `aws-appsync` package, which seems to be using an older version of `apollo-client` (2.4.6). All of these could be factors in what I'm seeing.

**Comment by JamieKudla** [comment] 2019-07-09 12:32
@joebernard I'm having the same issue on 2.6.3 using the same method (HOCs but without `aws-appsync`). I'm currently getting around it by using `withApollo()` and querying via `client.query()` in place of where the refetch was.

**Comment by jbaxleyiii** [comment] 2019-07-09 20:50
@joebernard Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. Can you open a new issue reporting your issues with a reproduction for us to take a look into?

**Closed by jbaxleyiii** 2019-07-09 20:50 UTC
Labels: :rose: has-reproduction, ✔ confirmed, 🐞 bug, 🙏 help-wanted

**Comment by pl12133** [comment] 2019-07-10 15:07
I have updated the versions of `apollo-client` and other packages in the reproduction and this bug is still present.

Please see https://codesandbox.io/s/j3410pq2vv

```json
  "dependencies": {
    "apollo-cache-inmemory": "1.6.2",
    "apollo-client": "2.6.3",
    "apollo-link-http": "1.5.15",
    "graphql": "14.4.2",
    "graphql-tag": "2.10.1",
    "react": "15.6.1",
    "react-apollo": "2.5.8",
    "react-dom": "15.6.1"
  }
```

@jbaxleyiii Could we revisit the original issue?

**Comment by somnaderi** [comment] 2019-09-25 17:59
I consider myself a React/Apollo novice, so what I'll describe as my solution should be taken with a grain of salt (and... my terminology may be off on some of these things). I'm guessing my use case is common (parent graphql HOCs w/ child graphql HOCs) and works successfully in a million other instances, so there's a good chance there's a nuanced detail that I'm unaware of that's specifically causing this problem.

Also, I'm still back on react-apollo v.2.2.4 / apollo-client v.2.4.5. Haven't acquainted myself with Hooks yet, so I don't know if they make HOCs unnecessary in newer versions.

I believe this same problem is also described in https://github.com/apollographql/react-apollo/issues/1929.

My problem:

I was using the graphql HOC in 2 components -- a ParentComponent and, within that component, a ChildComponent. The queries referenced for each had a fetch-policy of "network-only". The queries themselves were also different.

The ChildComponent is a paginated table that triggers a refetch when a page or rowsPerPage setting is changed. It has an initial set of variables for page / rowsPerPage. When a refetch is triggered, I pass in a new set of variables.

Console.log confirmed that, immediately post refetch, the new values were received correctly from the server. However, also immediately post refetch something else was triggered a refresh of ChildComponent with the initial variables set again. ChildComponent never unmounted, so I was surprised that the initial values were ever set again (again, I'm a React novice, so there's a chance I don't understand the lifecycles correctly).

Either way, the net result was that my table would remain unchanged with the initial page of data.

What worked for me:

I swapped the graphql HOC out of the ParentComponent and replaced it with the withApollo HOC and accessed the client directly. I had to rework some of the initial loading/error presentation logic, but the result was that my ChildComponent was no longer being reset to the initial parameters when the page was changed. I imagine doing it the other way (swapping ChildComponent to use withApollo) could have worked as well, but hard to say without knowing the root of the problem.

Hope this helps someone out there.

**Comment by ssteiger** [comment] 2020-02-08 17:23
This error is still present in "react-apollo": "3.1.3"

**Comment by ssteiger** [comment] 2020-02-10 15:33
**Temporary workaround:**

* always send **ALL** variables with each query
* set the ones we don't use to `undefined`

```javascript
export function fixSearch(_fields: Object) {
  return mapObject(_fields, val =>
    val == null || val === '' ? undefined : val
  )
}
```

```javascript
refetch(fixSearch(fields))
```

**Comment by victorkurauchi** [comment] 2020-05-01 16:36
I managed to get it working with the fetchPolicy change and also sending all the variables.

```
const { loading, data, error, fetchMore } = useQuery(
    QUERY_TRANSFERS, {
    variables: { 
      filter1: myfilter,
      cursor: null,
    },
    fetchPolicy: "network-only"
  });
```

and later on, load more:

```
fetchMore({
  variables: {
    filter1: dateFilter,
    cursor: endCursor,
  },
  updateQuery: myUpdateQueryFunction
})
```

**Comment by mschipperheyn** [comment] 2020-05-07 16:01
I have this problem as well. Refetching a query with the same variables (that delivers a different result bc it's random) does return new data visibly in the network debugger, but the cache is not being updated. adding `fetchPolicy: 'network-only'` does not help.

**Comment by ambuznego** [comment] 2020-06-17 18:12
Still experiencing this issue with `refetch` in `"react-apollo": "3.1.4"`. My workaround was to simply:
```
import { useApolloClient } from '@apollo/react-hooks';

client.query({ query: SEARCH_DISCOUNTS, variables })
   .then(response => {
      // do other stuff with the response
   });
```

**Comment by ivan-kleshnin** [comment] 2020-06-23 12:54
Please reopen the issue. `@apollo/client@3.0.0-rc.7` 
The cache is updated after `refetch` only the first time. Consequent fetches, as @mschipperheyn said, just ignore new data. Clearly something's broken there.

*Workarounded by injecting `random: Math.random()` field into the query.
Getting more bizarre.*

**Comment by geosigno** [comment] 2021-02-21 11:57
How can this issue be closed? I only see workarounds (thankfully good ones) but no proper fix has been released so far right?

**Comment by grahamb** [comment] 2021-03-25 20:54
Why is this issue closed? This is still a problem.

**Comment by artem-shev** [comment] 2021-07-01 19:02
still reproducible

**Comment by Jawmo** [comment] 2021-07-30 22:52
I am here also with this issue. After running refetch with a new variables object (only one variable), the network request shows a successful GraphQL request but nothing in the variables section as seen below. Also, upon printing the variable on the backend, it shows that nothing is getting through upon a refetch aside from the original variables that were used during the initial useQuery.

![image](https://user-images.githubusercontent.com/16947898/127718934-e3d2bf65-0008-4fc3-a4ad-05a11b4a3059.png)

**Comment by zmen** [comment] 2021-12-11 19:19
Any update? Still reproducible on ^3.5.6.

**Comment by Droniu** [comment] 2022-02-08 08:15
Still reproducible. Calling `refetch` with new variables results in two visible queries in the network debugger, but the second one contains original variables and overwrites the data fetched with new variables. Changing `fetchPolicy` doesn't solve the problem for me.

I got this working by storing variables as state and changing initial `useQuery` arguments based on state, and then calling `refetch` without any parameters.
```
"react-apollo": "^3.1.4"
```

**Comment by FernandVEYRIER** [comment] 2022-04-15 14:22
Same case as @Droniu here. My workaround was to use lazy queries instead.

**Comment by abhishekkovuri** [comment] 2023-01-05 13:05
This is a problem I faced,
Maybe instead of relying on refetch, we can use useLazyQuery for the same 
where initial we can trigger it in useEffect with an empty array as a dependency
and post that you can pass new variables in the useLazyQuery callback function.
