### ISSUE TITLE
useReactiveVar does not cause re-render

### ISSUE THREAD

**Issue by manzoorwanijk** [apollographql/apollo-client#7614] opened 2021-01-25 10:27 UTC
When using wrappers around `useReactiveVar`, it doesn't cause re-renders when the value changes.

Here is an example: [https://codesandbox.io/s/use-reactive-var-bug-g1chn](https://codesandbox.io/s/use-reactive-var-bug-g1chn)

That is the minimal reproducible code. We have a monorepo with a `data` package, which is basically a wrapper around `Apollo`, that's exactly what that `Apollo.tsx` tries to replicate.

**Comment by benjamn** [comment] 2021-01-25 17:18
@manzoorwanijk In your reproduction (thanks for that!), it looks like you're importing `useReactiveVar` from `@apollo/react-hooks` [here](https://codesandbox.io/s/use-reactive-var-bug-g1chn?file=/src/Apollo.ts). Can you try importing it directly from `@apollo/client`?

**Comment by manzoorwanijk** [comment] 2021-01-26 08:36
@benjamn I did that (as you can see in that demo), but it doesn't make any difference.

**Comment by dsonck92** [comment] 2021-01-28 20:35
@manzoorwanijk When I upgrade the dependencies and apply the suggested imports as they currently stand (which is import all from `@apollo/client`, it does work:

https://codesandbox.io/s/use-reactive-var-bug-forked-z17sy

**Comment by damien-monni** [comment] 2021-02-05 10:21
I am having the same issue. @apollo/client 3.2.7 works for me, updating to 3.3.7 breaks it.

**Comment by manzoorwanijk** [comment] 2021-02-05 13:35
Here is an updated sandbox which is very close to our implementation.

[https://codesandbox.io/s/use-reactive-var-bug-forked-q786o](https://codesandbox.io/s/use-reactive-var-bug-forked-q786o)

You can check in the console that the value of the reactive variable has changed, but it doesn't cause re-render.

**Comment by benjamn** [comment] 2021-02-05 18:20
@manzoorwanijk Thanks to your most recent reproduction, I can confirm that this bug is fixed in `@apollo/client@3.3.8` (just published). I'll go ahead and close this issue now, but please feel free to comment here if you're still having any problems.

**Closed by benjamn** 2021-02-05 18:20 UTC
Labels: ⚛️ React-related

**Comment by manzoorwanijk** [comment] 2021-02-05 18:42
@benjamn Yes, I can confirm the bug is fixed. Here is the updated sandbox. https://codesandbox.io/s/use-reactive-var-bug-forked-ybsw8

Thanks

**Comment by KonstantinLypskyi** [comment] 2021-04-20 14:27
Hey! I found an annoying problem. If we change the variable twice after waiting for the promise, then useReactiveVar will not have the actual value

This issue can be reproduced with the current version (3.3.15), but everything works fine in version 3.2.7.

The error can be reproduced here: https://codesandbox.io/s/long-architecture-qobw1?file=/src/App.jsx

**Comment by brainkim** [comment] 2021-04-20 15:34
@KonstantinLypskyi I opened an issue for you! Thanks for sharing.
