### ISSUE TITLE
Very difficult to debug errors when using Apollo client

### ISSUE THREAD

**Issue by elie222** [apollographql/apollo-client#1631] opened 2017-04-28 14:49 UTC
Not sure if this is just me and I'm missing something, but using Apollo is making debugging especially hard. This is the Chrome console for a React Native app. I see something is undefined, but I have no idea when in the app it is. Neither do I know what the problematic query is.

<img width="1412" alt="screen shot 2017-04-28 at 17 47 52" src="https://cloud.githubusercontent.com/assets/3090527/25533913/e621c358-2c3a-11e7-9df3-e4e5325146b5.png">

**Comment by helfer** [comment] 2017-04-28 18:03
@elie222 if you figure out what the root cause is, can you tell us what the error is that you expected to see?

**Comment by helfer** [comment] 2017-04-28 18:09
We definitely want to make it as easy as possible to debug things, so if there's a way we can improve the error message, we'll do it! 🙂

**Comment by elie222** [comment] 2017-04-29 17:29
I managed to find the root cause shortly after I posted the issue. I was
making a request for an item that didn't exist so a certain object was
`undefined` and calling `.teamIds` on it caused an error (that much is
clear from the screenshot).

The two things that were really annoying were:
1)  I had no easy way to find where the undefined object was in the code.
2) This isn't in the screenshot, but part of the same debugging of this
error, I was sometimes making an invalid graphql query with a required
`String!` field, but I provided `null` as the field. Apollo showed me this
error that I had to provide a String, but I had no idea which query was
problematic in my code.

**Comment by helfer** [comment] 2017-05-02 22:54
I think this should be much easier once #1638 is merged because you won't be able to write data of the wrong shape into the store any more. I'll close this now, but I think we should open separate specific issues for any errors where the error message isn't helpful in finding the root cause.

**Closed by helfer** 2017-05-02 22:54 UTC
Labels: usability

**Comment by margh** [comment] 2017-05-04 01:36
I've been running into this a lot and have tracked it down to this line:
https://github.com/apollographql/apollo-client/blob/master/src/data/writeToStore.ts#L157

if your graphql query doesn't match the server's schema then `writeResultToStore` calls this with an undefined result causing the property lookup to fail.

For whatever reason there's no GraphQL errors in the result so an undefined result gets written to the store here https://github.com/apollographql/apollo-client/blob/d685740a0ef643b13dbad92d5c6743e425bc27db/src/data/store.ts#L86

I'd like to dig deeper and make a PR or something but I'm pretty flat out atm :(

**Comment by helfer** [comment] 2017-05-04 02:19
@margh I think strict checking of writes will make debugging much easier. We're almost ready to merge it in #1638 :tada:

**Comment by jsrandom** [comment] 2017-11-06 20:01
I too would like to know if there are better debugging strategies.

I am using ionic with angular apollo client on android emulator:
    "apollo-angular": "^1.0.0-beta.1",
    "apollo-angular-link-http": "^1.0.0-beta.1",
    "apollo-cache-inmemory": "^1.0.0",
    "apollo-client": "^2.0.1",

and apollo-server-express for the server.

Although a wireshark trace of the client/server interaction appears to indicate the server responds correctly, the client ejects an error.

Any help appreciated - including suggestions for more appropriate place to post the issue.

**Code:**

`this.apollo.mutate<addUserMutation,addUserMutationVariables>({
        mutation: qlAddUser,
        variables: { 'cctoken': registerMember.cctoken},
      }).subscribe(({ data }) => {
        console.log('mutate got data: ', data);
      }, (error) => {
        console.log('mutate error sending the query', JSON.stringify(error));
      });
`

**Console Output shows error:**

 console.log: mutate error sending the query 
            {"graphQLErrors":[],"networkError":{"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown
            Error","url":null,"ok":false,"name":"HttpErrorResponse","message":"Http failure response for (unknown url): 
            0 Unknown Error","error":{"isTrusted":true}},"message":"Network error: Http failure response for (unknown 
            url): 0 Unknown 
            Error","__zone_symbol__currentTask":{"type":"eventTask","state":"notScheduled","source":"XMLHttpRequest.addEventListener:error","zone":"angular","runCount":0}}


**Wireshark client/server exchange:**

OPTIONS /graphql HTTP/1.1
Host: 10.0.2.2:3000
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://10.0.110.43:8101
User-Agent: Mozilla/5.0 (Linux; Android 7.0; Android SDK built for x86 Build/NYC; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.90 Mobile Safari/537.36
Access-Control-Request-Headers: accept, content-type
Accept: */*
Referer: http://10.0.110.43:8101/
Accept-Encoding: gzip, deflate
Accept-Language: en-US
X-Requested-With: io.ionic.starter

HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
Access-Control-Allow-Headers: Content-Type, Authorization, Content-Length, X-Requested-With
Content-Type: text/plain; charset=utf-8
Content-Length: 2
ETag: W/"2-4KoCHiHd29bYzs7HHpz1ZA"
Date: Mon, 06 Nov 2017 19:06:26 GMT
Connection: keep-alive

OKPOST /graphql HTTP/1.1
Host: 10.0.2.2:3000
Connection: keep-alive
Content-Length: 201
Accept: application/json, text/plain, */*
Origin: http://10.0.110.43:8101
User-Agent: Mozilla/5.0 (Linux; Android 7.0; Android SDK built for x86 Build/NYC; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.90 Mobile Safari/537.36
Content-Type: application/json
Referer: http://10.0.110.43:8101/
Accept-Encoding: gzip, deflate
Accept-Language: en-US
X-Requested-With: io.ionic.starter

{"operationName":"addUser","variables":{"cctoken":"tok_1BLF"},"query":"mutation addUser($cctoken: String!) {\n  addUser(cctoken: $cctoken) {\n    success\n    __typename\n  }\n}\n"}

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json
Date: Mon, 06 Nov 2017 19:06:26 GMT
Connection: keep-alive
Transfer-Encoding: chunked

3d
{"data":{"addUser":{"success":false,"__typename":"Success"}}}
0
