### ISSUE TITLE
Apollo is not requesting graphql in ssr (through next.js) : requests only for the first query

### ISSUE THREAD

**Issue by ziedHamdi** [apollographql/apollo-client#9066] opened 2021-11-16 11:51 UTC
**Intended outcome:**

I have volatile data that I want to be refreshed on each display

**Actual outcome:**

Queries are sent to the backend graphql server in development mode (next dev), but when the project is built and run (next start), only the first query is executed for each query: it seems the lib returns data from cache for all susequent requests.  

I didn't set any maxAge anywhere, so from what I understood, it should default to 0 and have all queries executed without caching.

**How to reproduce the issue:**

Here's my configuration code for the apollo client:

**/apollo/client.js**

    import {useMemo} from 'react'
    import {ApolloClient, HttpLink, gql} from '@apollo/client'
    import merge from 'deepmerge'
    import {cache} from './cache'
    import {isSSR} from "../constants/util";
    import isEqual from 'lodash/isEqual'
    import logger from "../lib/logger";
    
    export const APOLLO_STATE_PROP_NAME = '__APOLLO_STATE__'
    
    const typeDefs = gql`
      extend type Query {
        draftComplaints: [Complaint]
      }
    `;
    
    let apolloClient
    
    function createIsomorphLink() {
      if (typeof window === 'undefined') {
        const frontEndGraphQLUrl = process.env.NEXT_PUBLIC_FRONT_END_SSR_URL+'/api/graphql'
        logger.debug("server side next links are pointing to ", frontEndGraphQLUrl)
        return new HttpLink({
          uri: frontEndGraphQLUrl,
          headers: {ssr:true},
          credentials: 'same-origin',
        })
      } else {
        return new HttpLink({
          uri: '/api/graphql',
          headers: {ssr:false},
          credentials: 'same-origin',
        })
      }
    }
    
    function createApolloClient() {
      return new ApolloClient({
        ssrMode: typeof window === 'undefined',
        link: createIsomorphLink(),
        cache,
        typeDefs
      })
    }
    
    export function initializeApollo(initialState = null) {
      const _apolloClient = apolloClient ?? createApolloClient()
    
      // If your page has Next.js data fetching methods that use Apollo Client, the initial state
      // get hydrated here
      if (initialState) {
        // Get existing cache, loaded during client side data fetching
        const existingCache = _apolloClient.extract()
    
        // Merge the existing cache into data passed from getStaticProps/getServerSideProps
        const data = merge(initialState, existingCache, {
          // combine arrays using object equality (like in sets)
          arrayMerge: (destinationArray, sourceArray) => [
            ...sourceArray,
            ...destinationArray.filter((d) =>
                sourceArray.every((s) => !isEqual(d, s))
            ),
          ],
        })
    
        // Restore the cache with the merged data
        _apolloClient.cache.restore(data)
      }
      // For SSG and SSR always create a new Apollo Client
      if (isSSR()) return _apolloClient
      // Create the Apollo Client once in the client
      if (!apolloClient) apolloClient = _apolloClient
    
      return _apolloClient
    }
    
    export function useApollo(pageProps) {
      const state = pageProps[APOLLO_STATE_PROP_NAME]
      const store = useMemo(() => initializeApollo(state), [state])
      return store
    }
    
    export function addApolloState(client, pageProps) {
      if (pageProps?.props) {
        pageProps.props[APOLLO_STATE_PROP_NAME] = client.cache.extract()
      }
    
      return pageProps
    }

In my endpoint, I'm adding the connected user to the header then forwarding the request to a backend server. My issue is that in ssr, this code is not called after the first display

**/api/graphql.js**
    import {getSession} from "next-auth/client";
    
    
    function isTrueStr(str) {
        return str === true ||
            (str != null &&
            str.toString().toLowerCase() === 'true')
    }
    
    /**
     * typeof window == 'undefined' doesn't work here, so client HttpLink was enriched by a header boolean field 'ssr'
     * @param req
     * @returns {Promise<{"content-type": string, "infra-token": *}>}
     */
    
    async function prepareHeaders(req) {
        let infraToken = ""
        const ssr = isTrueStr(req.headers['ssr'])
        if (ssr == true) {
            //in SSR, we rely on client.query({context:{headers:{'infra-token':token}}})
            infraToken = req.headers['infra-token']
        } else {
            //in client rendering, we rely on the user that made the request
            const session = await getSession({req})
            infraToken = session?.infraToken
        }
        // logger.debug("api/graphql: {ssr: ", ssr, " Request token:", infraToken)
        let headers = {
            'content-type': 'application/json',
            'infra-token': infraToken ?? "",
            ssr
        }
        //On server-side, we must wrap our headers in a node-fetch Header class instance
        if (ssr) {
            const Headers = (await import('node-fetch')).Headers
            headers = new Headers(headers)
        }
        return headers;
    }
    
    export default async (_req, _res) => {
        let headers = await prepareHeaders(_req);
    
        const query = {
            method: 'POST', // *GET, POST, PUT, DELETE, etc.
            mode: 'cors', // no-cors, *cors, same-origin
            cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
            headers,
            redirect: 'follow', // manual, *follow, error
            body: JSON.stringify({
                operationName: _req.body.operationName,
                variables: _req.body.variables,
                query: _req.body.query
            }) // body data type must match "Content-Type" header
        };
        const graphqlBaseUrl = process.env.NEXT_PUBLIC_BACK_END_URL
        const res = await fetch(graphqlBaseUrl + '/api/graphql', query)
        const json = await res.json()
    
        console.log( "GRAPHQL QUERY: ", _req.body.operationName, " | variables: ", _req.body.variables )
        console.log( "GRAPHQL RESPONSE: ", JSON.stringify(json) )
    
        _res.statusCode = 200;
        _res.setHeader('content-type', 'application/json');
        _res.setHeader('cache-control', 'no-store, max-age=0');
        _res.json(json)
        _res.end()
    };
    
    export function prepareContext(session) {
        return {
            headers: {'infra-token': session?.infraToken ?? ""}
        };
    }

What I get in the output is only:

    debug:["server side next links are pointing to ","http://next_server:3000/api/graphql"]

Which is the correct endpoint (so the SSR link is correctly created, but the API is not called), seems Apollo is caching the response of the API call, which is definitely not the intended behavior for my case.
The issue is that I can't find a documentation talking about next.js or apollo caching data in ssr

You might think there's an issue with my cache code, but it doesn't enter to it neither: the line 

> console.log("merging: existing ", existing.count, " incoming: ",
> incoming.count)

 is not executed for the **complaintConnection** request

**/apollo/cache.js**
    import { InMemoryCache, makeVar } from '@apollo/client';
    
    export const draftComplaints = makeVar([])
    
    export const cache = new InMemoryCache({
        typePolicies: {
            Query: {
                fields: {
                    draftComplaints: {
                        read() {
                            return draftComplaints();
                        }
                    },
                    complaintConnection: {
                        keyArgs: ['filter'],
                        merge(existing = [], incoming) {
                            console.log("merging: existing ", existing.count, " incoming: ", incoming.count)
    
                            if(existing?.pageInfo  == null)
                                return incoming
    
                            if(existing.pageInfo.endCursor == incoming.pageInfo.endCursor)
                                return existing
    
                            return {
                                __typename: "ComplaintConnection",
                                count: existing.count,
                                edges: [...existing.edges, ...incoming.edges],
                                pageInfo: incoming.pageInfo
                            };
                        },
                    }
                }
            }
        }
    });

**Versions**

  System:
    OS: Linux 5.11 Alpine Linux
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  npmPackages:
    @apollo/client: ^3.4.17 => 3.4.17 
    apollo-server-micro: ^3.5.0 => 3.5.0

**Comment by ziedHamdi** [comment] 2021-11-17 09:25
Here are the logs to show the first request to the page executes the query but others only initialize the HttpLink without executing

debug:["server side next links are pointing to ","http://next_server:3000/api/graphql"]
GRAPHQL QUERY:  complaintConnection  | variables:  {}
GRAPHQL RESPONSE:  {"data":{"complaintConnection":{"count":2,"pageInfo":{"startCursor":"eyJwb3B1bGFyaXR5Ijo0NTQ3NjUuMTM4ODY2NjY2NjV9","endCursor":"eyJwb3B1bGFyaXR5Ijo0NTQ3NjQuNjI3MDE5MTY2NjZ9","hasNextPage":false,"hasPreviousPage":false,"__typename":"PageInfo"},"edges":[{"cursor":"eyJwb3B1bGFyaXR5Ijo0NTQ3NjUuMTM4ODY2NjY2NjV9","node":{"_id":"61925bc35fe68f001c4d03e4","entityId":"61925beb5fe68f001c4d03ed","stats":{"COMMENT":{"actionCount":0,"userCount":0,"__typename":"ComplaintStatsCOMMENT"},"USER_LIKE":{"userCount":0,"__typename":"ComplaintStatsUSER_LIKE"},"SAME_ISSUE":{"actionCount":11,"userCount":1,"USER_ACTION_EXPECTED":null,"USER_ACTION_REFUSED":null,"SHOP_ACTION_EXPECTED":1,"SHOP_ACTION_REFUSED":null,"USER_SATISFIED":0,"__typename":"ComplaintStatsSAME_ISSUE"},"__typename":"ComplaintStats"},"entity":{"name":"Dockery Lake Recreation Area","__typename":"ComplaintEntity"},"user":{"userId":"61925360aab0ed001c8afe34","userName":"Zied Hamdi","roleInShop":"USER","__typename":"ComplaintContributorsUser"},"title":"too many people four","desc":"crowded as a supermaket","video":"","attachments":[],"mainAttachmentIndex":0,"state":"OPEN","public":true,"interactionState":"SHOP_ACTION_EXPECTED","interactionSpecifier":null,"unanswered":true,"userActionRecap":{"COMMENT":null,"USER_LIKE":null,"SAME_ISSUE":{"lastState":{"value":"SHOP_ACTION_EXPECTED","text":null,"__typename":"ActionRecapState"},"__typename":"StringActionRecap"},"__typename":"ActionRecapList"},"createdAt":"2021-11-15T13:08:19.920Z","updatedAt":"2021-11-16T11:38:14.715Z","__typename":"Complaint"},"__typename":"ComplaintEdge"},{"cursor":"eyJwb3B1bGFyaXR5Ijo0NTQ3NjQuNjI3MDE5MTY2NjZ9","node":{"_id":"61925491423b0c001c43be12","entityId":"61925bb15fe68f001c4d03b8","stats":{"COMMENT":{"actionCount":0,"userCount":0,"__typename":"ComplaintStatsCOMMENT"},"USER_LIKE":{"userCount":0,"__typename":"ComplaintStatsUSER_LIKE"},"SAME_ISSUE":{"actionCount":1,"userCount":1,"USER_ACTION_EXPECTED":null,"USER_ACTION_REFUSED":null,"SHOP_ACTION_EXPECTED":1,"SHOP_ACTION_REFUSED":null,"USER_SATISFIED":0,"__typename":"ComplaintStatsSAME_ISSUE"},"__typename":"ComplaintStats"},"entity":{"name":"McDonald","__typename":"ComplaintEntity"},"user":{"userId":"61925360aab0ed001c8afe34","userName":"Zied Hamdi","roleInShop":"USER","__typename":"ComplaintContributorsUser"},"title":";klkjl","desc":"jhk","video":"","attachments":[{"url":"/complaintAttachment/619254ac423b0c001c43be15","thumbUrl":"/complaintAttachmentThumb/619254ac423b0c001c43be15","__typename":"ComplaintAttachments"}],"mainAttachmentIndex":0,"state":"OPEN","public":true,"interactionState":"SHOP_ACTION_EXPECTED","interactionSpecifier":null,"unanswered":true,"userActionRecap":{"COMMENT":null,"USER_LIKE":null,"SAME_ISSUE":{"lastState":{"value":"SHOP_ACTION_EXPECTED","text":null,"__typename":"ActionRecapState"},"__typename":"StringActionRecap"},"__typename":"ActionRecapList"},"createdAt":"2021-11-15T12:37:37.269Z","updatedAt":"2021-11-15T13:08:01.460Z","__typename":"Complaint"},"__typename":"ComplaintEdge"}],"__typename":"ComplaintConnection"}}}
merging: existing  undefined  incoming:  2
GRAPHQL QUERY:  trendingComplaintConnection  | variables:  {}
GRAPHQL RESPONSE:  {"data":{"trendingComplaintConnection":{"pageInfo":{"startCursor":"eyJwb3B1bGFyaXR5Ijo0NTQ3NjUuMTM4ODY2NjY2NjV9","endCursor":"eyJwb3B1bGFyaXR5Ijo0NTQ3NjQuNjI3MDE5MTY2NjZ9","hasNextPage":false,"hasPreviousPage":false,"__typename":"PageInfo"},"edges":[{"cursor":"eyJwb3B1bGFyaXR5Ijo0NTQ3NjUuMTM4ODY2NjY2NjV9","node":{"_id":"61925bc35fe68f001c4d03e4","entityId":"61925beb5fe68f001c4d03ed","stats":{"COMMENT":{"actionCount":0,"userCount":0,"__typename":"ComplaintStatsCOMMENT"},"USER_LIKE":{"userCount":0,"__typename":"ComplaintStatsUSER_LIKE"},"SAME_ISSUE":{"actionCount":11,"userCount":1,"USER_ACTION_EXPECTED":null,"USER_ACTION_REFUSED":null,"SHOP_ACTION_EXPECTED":1,"SHOP_ACTION_REFUSED":null,"USER_SATISFIED":0,"__typename":"ComplaintStatsSAME_ISSUE"},"__typename":"ComplaintStats"},"entity":{"name":"Dockery Lake Recreation Area","__typename":"ComplaintEntity"},"user":{"userId":"61925360aab0ed001c8afe34","userName":"Zied Hamdi","roleInShop":"USER","__typename":"ComplaintContributorsUser"},"title":"too many people four","desc":"crowded as a supermaket","video":"","attachments":[],"mainAttachmentIndex":0,"state":"OPEN","public":true,"interactionState":"SHOP_ACTION_EXPECTED","interactionSpecifier":null,"unanswered":true,"userActionRecap":{"COMMENT":null,"USER_LIKE":null,"SAME_ISSUE":{"lastState":{"value":"SHOP_ACTION_EXPECTED","text":null,"__typename":"ActionRecapState"},"__typename":"StringActionRecap"},"__typename":"ActionRecapList"},"createdAt":"2021-11-15T13:08:19.920Z","updatedAt":"2021-11-16T11:38:14.715Z","__typename":"Complaint"},"__typename":"ComplaintEdge"},{"cursor":"eyJwb3B1bGFyaXR5Ijo0NTQ3NjQuNjI3MDE5MTY2NjZ9","node":{"_id":"61925491423b0c001c43be12","entityId":"61925bb15fe68f001c4d03b8","stats":{"COMMENT":{"actionCount":0,"userCount":0,"__typename":"ComplaintStatsCOMMENT"},"USER_LIKE":{"userCount":0,"__typename":"ComplaintStatsUSER_LIKE"},"SAME_ISSUE":{"actionCount":1,"userCount":1,"USER_ACTION_EXPECTED":null,"USER_ACTION_REFUSED":null,"SHOP_ACTION_EXPECTED":1,"SHOP_ACTION_REFUSED":null,"USER_SATISFIED":0,"__typename":"ComplaintStatsSAME_ISSUE"},"__typename":"ComplaintStats"},"entity":{"name":"McDonald","__typename":"ComplaintEntity"},"user":{"userId":"61925360aab0ed001c8afe34","userName":"Zied Hamdi","roleInShop":"USER","__typename":"ComplaintContributorsUser"},"title":";klkjl","desc":"jhk","video":"","attachments":[{"url":"/complaintAttachment/619254ac423b0c001c43be15","thumbUrl":"/complaintAttachmentThumb/619254ac423b0c001c43be15","__typename":"ComplaintAttachments"}],"mainAttachmentIndex":0,"state":"OPEN","public":true,"interactionState":"SHOP_ACTION_EXPECTED","interactionSpecifier":null,"unanswered":true,"userActionRecap":{"COMMENT":null,"USER_LIKE":null,"SAME_ISSUE":{"lastState":{"value":"SHOP_ACTION_EXPECTED","text":null,"__typename":"ActionRecapState"},"__typename":"StringActionRecap"},"__typename":"ActionRecapList"},"createdAt":"2021-11-15T12:37:37.269Z","updatedAt":"2021-11-15T13:08:01.460Z","__typename":"Complaint"},"__typename":"ComplaintEdge"}],"__typename":"ComplaintConnection"}}}
merging: existing  undefined  incoming:  undefined
GRAPHQL QUERY:  entityGroupByVisitsConnection  | variables:  {}
GRAPHQL RESPONSE:  {"data":{"entityGroupByVisitsConnection":{"count":0,"pageInfo":{"startCursor":"","endCursor":"","hasNextPage":false,"hasPreviousPage":false,"__typename":"PageInfo"},"edges":[],"__typename":"entityGroupByVisitsConnection"}}}
debug:["server side next links are pointing to ","http://next_server:3000/api/graphql"]
debug:["server side next links are pointing to ","http://next_server:3000/api/graphql"]

**Comment by ziedHamdi** [comment] 2022-03-04 10:52
So I managed to fix the ssr bug by initiating my client with the followinf options:
```
  defaultOptions = {
    query: {
      fetchPolicy: 'no-cache',
      errorPolicy: 'all',
    }
  }
```
But I still have an issue: when I rerender a page, it doesn't query the graphql endpoint

**Comment by mlarcher** [comment] 2022-06-11 12:19
Thanks, this help me too. It seems that when ran in SSR (getServerSideProps in NextJS), 'network-only' policy is not respected and 'no-cache' is required to have a request on subsequent calls.
Looks like a bug to me according to what the docs say on the matter.

**Comment by lhguerra** [comment] 2022-06-14 21:09
I can confirm the bug. For now, disabling the cache works for me as well, but I'm not sure how to act when moving to production.

**Comment by mlarcher** [comment] 2022-06-14 21:38
> I can confirm the bug. For now, disabling the cache works for me as well, but I'm not sure how to act when moving to production.

we use `fetchPolicy: isBrowser() ? 'network-only' : 'no-cache',`, that should be enough as server don't need cache at all afaict

**Comment by ziedHamdi** [comment] 2022-06-15 13:38
I solved it by creating a brand new cache each time I have an ssr request,
this can be tricky to identify since cache was imported as a js file and
provided to the apollo constructor, I had to make an unit method for the
cache creation to control instances.

Best regards,
Zied Hamdi
CEO - weally.org
linkedin.com/in/zhamdi

Le mar. 14 juin 2022, 22:39, Matthieu Larcher ***@***.***> a
écrit :

**Comment by mlarcher** [comment] 2022-06-28 14:29
> > I can confirm the bug. For now, disabling the cache works for me as well, but I'm not sure how to act when moving to production.
> 
> we use `fetchPolicy: isBrowser() ? 'network-only' : 'no-cache',`, that should be enough as server don't need cache at all afaict

Actually it seems that the cache created server-side could be passed to the client-side, as we can see in https://github.com/vercel/next.js/blob/canary/examples/with-apollo/lib/apolloClient.js , so fixing this issue might be more urgent than it seemed at first glance (i.e. it can divide by 2 the number of calls on the API side)

**Comment by alessbell** [comment] 2022-06-29 16:49
@ziedHamdi thanks for the detailed report! An isolated reproduction of the issue in a separate GitHub repository/code sandbox would greatly help us investigate.

**Comment by ziedHamdi** [comment] 2022-07-22 18:55
> @ziedHamdi thanks for the detailed report! An isolated reproduction of the issue in a separate GitHub repository/code sandbox would greatly help us investigate.

Hi Alessia,

Thanks for reminding me of this bug, and sorry for the late reply, I was on a holiday disconnected trip.

I fixed the bug in my app since I realized I was creating a new client, but using the same cache (I used code from the official examples where cache is just imported)

This snippet was the cause as the line `import {cache} from './cache'` was reusing the same instance:

```
function createApolloClient() {
  return new ApolloClient({
    ssrMode: typeof window === 'undefined',
    link: createIsomorphLink(),
    cache,
    typeDefs
  })
}
``` 

I exported a new function `createCache` that I'm calling in SSR mode on each request. That solved my issue.

```
function createApolloClient() {
  return new ApolloClient({
    ssrMode: typeof window === 'undefined',
    link: createIsomorphLink(),
    typeof window === 'undefined' ? createCache : cache,
    typeDefs
  })
}
``` 


p.s: it could be a good idea to replace the sample code with a more SSR ready one, this bug was very hard to detect and understand as I had to dig into internals to realize what was happening.

So for me, the bug report was a false one, you can close it if you think nothing has to be done on your side.

**Comment by Usamamian27** [comment] 2023-01-16 12:56
I have been banging my head in the walls for 2 days, and finally your code comes to the rescue. (Thanks 👍 )

**Comment by florianzemma** [comment] 2023-02-02 15:45
Thank you you've made my day ! I was experiencing the same problem with ISR method GetStaticProps I though the revalidate was never triggered but I was wrong, Its the cache of the query who was always called because of the 'network-only'.
I have moved to 'no-cache' and it is working now

**Comment by rafaelsmgomes** [comment] 2023-06-07 02:38
Hi, I'm having the same problem but I don't think what was proposed here is a solution.

If you set default options to 'no-cache' then you disable the caching for all requests from the client, since they use the same createApolloClient function. 

I'm not sure how @ziedHamdi solved this issue. I would really appreciate if you can give an example of what that function looks like. 

I thought the whole point of server-side rendering is to cache that data and sending it to the frontend so a component that queries for that data does not need to make that query to the server.

Anyway, I'm unclear on how to solve that problem and I don't think that what is shown here is a solution, unless I'm missing something.

**Comment by phryneas** [comment] 2023-06-20 10:13
@rafaelsmgomes The main solution here is "create a new client and a new cache for every SSR request being made".

It's unfortunately far too easy in NextJs to create some kind of global variable and be unaware that this variable is shared between multiple requests.

If you are using the `pages` Router, make sure to create that Apollo Client instance on your `context` or `context.context` (app context) objects and only read it from there.

If you are using the `app` Router, please use our [`@apollo/experimental-nextjs-app-support`](https://github.com/apollographql/apollo-client-nextjs) package.

---

I will go ahead and close this issue, as I believe that the initial problem has been solved so far, and further questions are probably better brought up in separate issues.

**Closed by phryneas** 2023-06-20 10:13 UTC
Labels: 🐞 bug, 🥓 Server-side rendering (SSR)
