### ISSUE TITLE
[2.0.2] apollo-client returns empty data during mutation | bug

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-client#2496] opened 2017-11-06 20:04 UTC
I am not sure if it is related to apollo-client or react-apollo but I have this issue. During mutation I will get data without cached fields.

Here is steps how to reproduce it
1. I have one component with graphql query which is loading user by his username. It is working great. **data.user contains all information.**
```js
@graphql(gql`
  query getQuestionContainerData($username: String!) {
    user(username: $username) {
      id
      isViewer
      cover
    }
  }
`, {
  options: ({ match: { params: { username } } }) => ({
    variables: {
      username,
    },
  }),
})
```

2. Second component is changing users photo (it has one mutation)
```js
@graphql(gql`
  mutation ($signed: String!) {
    user: submitUserCoverS3DirectUpload(signed: $signed) {
      id
      canEdit
      cover
    }
  }
`, {
    name: 'submitUserCoverS3DirectUpload',
  })
```

3. First component **will receive empty data.user** (user is undefined) when second component starts mutation.
4. After success mutation first component will receive correct data.user with all data.

My question is why I receive empty data.user ? Apollo client already have this data and I do not any clean cache.

My current deps:
```
    "apollo-cache-inmemory": "^1.1.0",
    "apollo-client": "^2.0.2",
    "apollo-link": "^1.0.0",
    "apollo-link-http": "^1.1.0",
    "apollo-link-batch-http": "^1.0.0",
    "apollo-link-retry": "^1.0.0",
    "apollo-link-dedup": "^1.0.0",
    "react-apollo": "^2.0.0",
```

**Comment by jbaxleyiii** [comment] 2017-11-13 16:11
@seeden I'll try to make a reproduction and figure this out!

**Comment by bogdansoare** [comment] 2017-11-14 00:08
@jbaxleyiii I have the same issue, after mutation the data is empty

**Comment by bogdansoare** [comment] 2017-11-14 00:23
For me it happens when the component with the query is unmounted and then mounted again and after that I run the mutation

**Comment by jbaxleyiii** [comment] 2017-11-16 01:19
This should be fixed on master!

**Closed by jbaxleyiii** 2017-11-16 01:19 UTC

**Comment by nicholas-l** [comment] 2017-11-28 03:18
Is this published? Because I am getting a similar error, below is before and after a mutation that happens in a deeply nested child component from the query component. Loading is false and no error on data.

First is check if object is null (node)
Second line is props.data
Third line is props.data.error.
```
nodeviewer.jsx:74 data.node is null: false
nodeviewer.jsx:75 {variables: {…}, refetch: ƒ, fetchMore: ƒ, updateQuery: ƒ, startPolling: ƒ, …}error: (...)fetchMore: ƒ ()loading: falsenetworkStatus: 7node: { id: "R1RlY2hfQWRkcmVzczo1MzYxNDgwNw==", …} refetch: ƒ ()startPolling: ƒ ()stopPolling: ƒ ()subscribeToMore: ƒ ()updateQuery: ƒ ()variables: {objectId: "R1RlY2hfQWRkcmVzczo1MzYxNDgwNw=="}get error: ƒ 
nodeviewer.jsx:76 undefined
```
Mutation happened

```
nodeviewer.jsx:74 data.node is null: true
nodeviewer.jsx:75 {variables: {…}, refetch: ƒ, fetchMore: ƒ, updateQuery: ƒ, startPolling: ƒ, …}error: (...)fetchMore: ƒ ()loading: falsenetworkStatus: 7refetch: ƒ ()startPolling: ƒ ()stopPolling: ƒ ()subscribeToMore: ƒ ()updateQuery: ƒ ()variables: {objectId: "R1RlY2hfQWRkcmVzczo1MzYxNDgwNw=="}get error: ƒ ()__proto__: Object
nodeviewer.jsx:76 undefined
```

**Comment by vincentdesmares** [comment] 2018-03-02 00:17
I got the same issue and struggled a lot to find the source of it.

I traced it back to this [part of the code](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts) which swallowed an error:

```javascript
try {
  var data = this.dataStore.getCache().read({
    query: query,
    variables: variables,
    previousResult: lastResult ? lastResult.data : undefined,
    optimistic: true
  })
  return maybeDeepFreeze({ data: data, partial: false })
} catch (e) {
  return maybeDeepFreeze({ data: {}, partial: true })
}
```

The result of my mutation was missing a field that was present in the original request.

```graphql
query test {
   house {
      id
      length
      width
   }
}
```

```graphql
mutation test {
   updateHouse(id: 1) {
      id
      length
   }
}
```

`Width` being missing, an error was thrown, catch by the previous code, and the object `house` ended undefined.

I'm not sure of what I have done wrong.

I'm using the 2.1.0, so the code related to this PR is at least not covering all the cases.

@jbaxleyiii Can you reopen this issue?

**Comment by juanhenriquez** [comment] 2018-05-12 20:01
@vincentdesmares Same happens for me. I was missing a field in my mutation that was declared in the original query and this was causing that when the mutation completed successfully and the query gets called(the second time), the data that comes in the query was an empty object.

So the solution was put both the mutation and the query with the same fields.

Can you please take a look at this @jbaxleyiii ?

**Comment by ezchen92** [comment] 2019-06-07 22:51
I have spent multiple hours on this as well.

It was fixed by using a shared fragment. I had forgotten to add a field to my mutation that was on my query.

**Comment by NareshVadlamani** [comment] 2019-06-24 09:32
Me too getting the same issue , i am saving the data and returning the id to use as a foreign key to the another table . But i am not getting any response ,  the data is coming undefined . I am not sure is this issue or i did some mistake. Any suggestions will be appreciated.
