### ISSUE TITLE
Unable to get apollo client response headers

### ISSUE THREAD

**Issue by Suribabu-Balam** [apollographql/apollo-client#7890] opened 2021-03-24 10:56 UTC
**I am able to see the response headers in the network but unable to get those response headers.**

Please follow the below screenshots.

**Network Response Headers:**
![Screenshot from 2021-03-24 16-12-17](https://user-images.githubusercontent.com/81299732/112297377-d37eaf00-8cbb-11eb-93c5-b61eda5af318.png)

**Console Response Data(Empty headers):**
![Screenshot from 2021-03-24 16-14-19](https://user-images.githubusercontent.com/81299732/112297531-045ee400-8cbc-11eb-8227-7a10c95cc904.png)

**Actual tried Code:**
```js
const httpLink = new HttpLink({ uri: URL_SERVER_GRAPHQL })

// Setup the header for the request
const middlewareAuthLink = new ApolloLink((operation, forward) => {
  const token = localStorage.getItem(AUTH_TOKEN)

  const authorizationHeader = token ? `Bearer ${token}` : null
  operation.setContext({
    headers: {
      authorization: authorizationHeader
    }
  })
  return forward(operation)
})



//After the backend responds, we take the refreshToken from headers if it exists, and save it in the cookie.
const afterwareLink = new ApolloLink((operation, forward) => {
  return forward(operation).map(response => {
    const context = operation.getContext()
    const {
      response: { headers }
    } = context

    if (headers) {
      const refreshToken = headers.get('refreshToken')
      if (refreshToken) {
        localStorage.setItem(AUTH_TOKEN, refreshToken)
      }
    }

    return response
  })
})

const client = new ApolloClient({
  link: from([middlewareAuthLink, afterwareLink, httpLink]),
  cache: new InMemoryCache()
})
```

**Please help with this issue.**

Thanks in advance.

**Comment by brainkim** [comment] 2021-04-05 16:58
Thanks for opening this issue! I‘ll look into it. If you create a reproduction which shows the problem (on CodeSandbox or as a GitHub repository) that’d be incredibly useful, and speed up my investigation. Otherwise, no worries, and I’ll try to get to this when I can.

**Comment by Suribabu-Balam** [comment] 2021-04-06 06:03
Ok, I will provide the git hub repository URL.

**Comment by Suribabu-Balam** [comment] 2021-04-19 07:22
Hi,

Here is the GitHub repository URL: **https://github.com/Suribabu-Balam/apollo-headers**

Please check and let me know if anything is required.

**Comment by ayan4m1** [comment] 2021-04-23 05:50
Are you ensuring that you're specifying `Access-Control-Expose-Headers` in the response headers from the server?

**Comment by Suribabu-Balam** [comment] 2021-04-23 07:55
Hi @ayan4m1,

Yes, we are sending **Access-Control-Expose-Headers** from the server.

**Code Format:**

require("isomorphic-fetch");

fetch("https://*******.com/api/*****/graphql", {
  method: "POST",
  headers: {
    Authorization:
      "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJTVVBFUl9BRE1JTiIsInVzZXJuYW1lIjoic3VwZXJhZG1pbiIsImVtYWlsIjoiZm1pcy1kZXZAdGVjdG9yby5jb20iLCJ0ZW5hbnRJZCI6IlRFTjEiLCJpYXQiOjE2MDc0MDcyMTEsImV4cCI6MTYwNzQxMDgxMX0.0wr5E8-ikrkYYa9HzvEiyE0HbccyyFlD3Fu7GWHW28A",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: `
    query {
        appSettings{
          id
        }
    }`,
  }),
})
  .then((res) => console.log(res.headers))
  .then((res) => console.log(res));

**Comment by Suribabu-Balam** [comment] 2021-04-26 06:01
Hi @brainkim,
Any update regarding this issue...?
let me know if anything is required.

**Comment by brainkim** [comment] 2021-04-26 13:14
Hmmm. I’m not clear on what the misbehavior is? Your middlewareAuth link doesn’t ever seem to ever do anything because no `"AUTH_TOKEN"` is set in localStorage. Nor does the server ever set a `refreshToken` header? I imagine you’re working with code from [this guide](https://www.apollographql.com/docs/react/networking/advanced-http-networking/)? One thing is that headers objects don’t really show headers in the Chrome console for some reason. You’ll need to do something like `Array.from(headers.keys())` for instance, to see all of the header keys.

**Comment by Suribabu-Balam** [comment] 2021-04-28 07:05
Hi @brainkim,

We followed  [this guide](https://www.apollographql.com/docs/react/networking/advanced-http-networking/) that you mentioned and implemented, but can't get response headers.

We will try the above mentioned **Array.from(headers.keys())** method and  update you.

**Comment by Suribabu-Balam** [comment] 2021-05-07 16:55
Hi @brainkim,

We tried the above-mentioned method,

![image](https://user-images.githubusercontent.com/81299732/117479378-e56f9500-af7d-11eb-894e-de097c06d1ed.png)

- On the server-side, they passing x-refresh-token, x-server-date, and Access-Control-Expose-Headers but we get only the headers mentioned in the screenshot.
- We also need the remaining response headers, Due to the failure of retrieving the remaining response headers we facing an issue with our application.
- We need a quick response regarding this issue.

Thanks.

**Comment by Suribabu-Balam** [comment] 2021-05-17 06:03
Hi @brainkim,
Any update regarding this issue...?

**Comment by ru4sam326** [comment] 2021-05-19 04:40
Hi Team,

We are also facing this, Any update, please?

**Comment by ru4sam326** [comment] 2021-05-27 04:59
Can someone respond, It's a basic bug. Holding for a long time, Without reading the response headers, enterprise applications will not able to handle security and other features.

At least please provide a timeline for when this will be resolved.

**Comment by Suribabu-Balam** [comment] 2021-05-27 13:21
Hi @brainkim,
Any update regarding this issue...?

**Comment by hwillson** [comment] 2021-05-28 00:44
@Suribabu-Balam from your client side code example above, in your `afterwareLink`, you're calling the following:

```js
const refreshToken = headers.get('refreshToken')
```

I don't see `refreshToken` being set anywhere in the server reproduction you provided. Headers are working though; if you want to verify this, in your server reproduction, add the following 2 lines to the top of your `index.js` `context` function:

```js
const context = async ({ req, res }) => {
  res.append("Access-Control-Expose-Headers", "some-header");
  res.header("some-header", "some-value");
  ...
}
```

Then back in your client app, adjust your `afterwareLink` to add the following:

```js
const afterwareLink = new ApolloLink((operation, forward) => {
    ...
    if (authHeader) {
      console.log("Here comes the header ...", authHeader.get("some-header"))
    ...
```

If you run that, you'll see that the `some-header` value is logged properly on the client side. 

All of the above being said, this isn't a bug with Apollo Client, so I'll close this off. If you would like to continue this discussion, head over to our community forums: https://community.apollographql.com - thanks!

**Closed by hwillson** 2021-05-28 00:44 UTC
Labels: :rose: has-reproduction, 🔗 apollo-link

**Comment by ru4sam326** [comment] 2021-05-28 04:33
Hi @hwillson 

As already mentioned we are able to read headers from another client
and That is sample client how we are reading not the actual code of the API.

**Comment by hwillson** [comment] 2021-05-28 10:22
@ru4sam326 right, but we need a valid reproduction to be able to help troubleshoot things. The reproduction you supplied isn't working, but with the few tweaks I mentioned above, will work, and clearly shows that headers are working. We can't help troubleshoot your other application / API without access to it unfortunately.

**Comment by Suribabu-Balam** [comment] 2021-05-31 14:00
Hi Team,

As mentioned above,  **@hwillson** we have reproduced the issue and created the repository. Follow the repository URL as mentioned below.

**URL**: **https://github.com/Suribabu-Balam/response-headers**

 Check into this URL and waiting for your quick response.

Please Need your earliest attention **@hwillson @brainkim**.

Thanks.

**Comment by JLTG2020** [comment] 2021-06-08 02:25
I get this problem too, and I think this is a bug, because I get the headers in my chrome devtools, but apollo client response headers is nil

> Hi Team,
> 
> As mentioned above, **@hwillson** we have reproduced the issue and created the repository. Follow the repository URL as mentioned below.
> 
> **URL**: **https://github.com/Suribabu-Balam/response-headers**
> 
> Check into this URL and waiting for your quick response.
> 
> Please Need your earliest attention **@hwillson @brainkim**.
> 
> Thanks.

I get the same problem, And I found the solution here。
https://github.com/apollographql/apollo-client/issues/2514#issuecomment-492202972

**Comment by Suribabu-Balam** [comment] 2021-06-09 04:48
Hi Team,

We got the solution issue has been resolved.

**Thanks for the update @JLTG2020** 

Thanks.

**Comment by dylanwulf** [comment] 2022-10-27 15:02
@amitShimon1983 as posted above, use `Access-Control-Expose-Headers`. When accessing the header make sure to use the syntax `context.response.headers.get('...')`
