### ISSUE TITLE
Unexpected query result when working with a large data set 

### ISSUE THREAD

**Issue by mkaulig** [apollographql/apollo-client#4080] opened 2018-10-31 10:14 UTC
**Intended outcome:**

When writing data to the cache with `writeQuery()` a following call to `readQuery()` should always return the data last written to the cache.

**Actual outcome:**

When writing large data sets to the apollo store, all following reads seem to always return this large data set and not the newly written one. Calls to `writeQuery()` seem to have no effect after reading the large data set once with `readQuery()`.

**How to reproduce the issue:**

Write a list of 100000 entries to the apollo cache and read it. Replace the list with a list of one item. All following reads still return a list of 100000 items.

```
addAndReplaceObjects(1000);
readQuery(); // expect 1000 entries, works
addAndReplaceObjects(1);
readQuery(); // expect 1 entry, works

addAndReplaceObjects(100000);
addAndReplaceObjects(1);
readQuery(); // expect 1 entry, works

addAndReplaceObjects(100000);
readQuery(); // expect 100000 entries, works. This readQuery() call seems to break the following writes/reads
addAndReplaceObjects(1);
readQuery(); // expect 1 entry, broken: readQuery returns a list of 100000 entries
```

You can find a running reproduction in the following repository: https://github.com/mp-internal/apollo-cache-repro

**Versions**
  System:
    OS: macOS 10.14
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    apollo-cache-inmemory: 1.3.8 => 1.3.8
    apollo-client: 2.4.5 => 2.4.5
    apollo-link-http: 1.5.5 => 1.5.5

**Comment by benjamn** [comment] 2018-10-31 22:36
You should be able to fix this by running
```bash
npm install optimism@latest
```
since the latest version (0.6.8) is permitted by [the version constraint in `apollo-cache-inmemory/package.json`](https://github.com/apollographql/apollo-client/blob/31b0ee4a027c60394cf9297df8f9eeeda3918272/packages/apollo-cache-inmemory/package.json#L47).

I can confirm that your reproduction works correctly after that upgrade (thanks for making my job easy!), so I'm going to go ahead and close this issue, though please feel free to reopen it if the problem persists.

**Closed** 2018-10-31 22:37 UTC
