### ISSUE TITLE
Catching network errors doesn't stop a Query components children from rendering

### ISSUE THREAD

**Issue by Tam** [apollographql/apollo-client#3479] opened 2018-05-18 11:18 UTC
**Intended outcome:**
If I catch an error globally, it should prevent the query that threw the error from rendering.

**Actual outcome:**
The query continues to render it's children, which causes more errors because the data has undefined  properties that are being used in the template.

**How to reproduce the issue:**
Reproduction: https://codesandbox.io/s/p9zvm6r7mj

The error handling code:

```jsx
import ApolloClient from "apollo-boost";

const client = new ApolloClient({
  uri: "oh hi mark",

  onError: ({ networkError }) => {
    if (networkError) {
      // eslint-disable-next-line default-case
      switch (networkError.statusCode) {
        case 405:
          console.log(
            "Why doesn't this stop the query component rendering it's children?"
          );
          return null;
      }
    }
  },
});
```

**Version**

- apollo-client@2.3.0
- apollo-boost@0.1.5

**Issue Labels**

- [x] has-reproduction

**Comment by hwillson** [comment] 2018-06-14 15:32
Hi @Tam:

> The query continues to render it's children, which causes more errors because the data has undefined properties that are being used in the template.

I'm not seeing that happen in your reproduction. Your `Why doesn't this stop the query component rendering it's children?` error is caught and logged to the console, and the component stays in loading status. This is the intended (default) behavior, and can be modified by leveraging Apollo Client [error policies](https://www.apollographql.com/docs/react/features/error-handling.html#policies). Closing for now since this appears to be working as designed (let me know if I'm missing something). Thanks!

**Closed by hwillson** 2018-06-14 15:32 UTC
Labels: has-reproduction
