### ISSUE TITLE
comilation error in inMemoryCache.d.ts in jenkins production build

### ISSUE THREAD

**Issue by chennas** [apollographql/apollo-client#4326] opened 2019-01-18 01:22 UTC
Hello Team,

Getting compilation error in apollo-cache-inmemory/lib/inMemoryCache.d.ts file

please find the screen shot below. we are using the below versions of apollo libararies

![image](https://user-images.githubusercontent.com/8044128/51359365-0b12c080-1a8d-11e9-9d30-eb26493507b9.png)

Build Error below
![image](https://user-images.githubusercontent.com/8044128/51359386-2251ae00-1a8d-11e9-9936-7b92f9c09667.png)

**Comment by danilobuerger** [comment] 2019-01-18 16:37
What versions are you actually using? This just shows the version range.

**Comment by danilobuerger** [comment] 2019-01-18 16:38
Might be duplicate of #4327

**Comment by chennas** [comment] 2019-01-18 17:21
Hi Thanks for the reply,
We are not limiting to specific version, we are always relying on the latest version in the build machine, I have limited to 1.3.5 version in our build machine and verified, now we are not facing any build issues, not sure about the impact.

**Comment by benjamn** [comment] 2019-01-18 17:35
Pleas try `npm install apollo-cache-inmemory@1.4.1`!

**Comment by benjamn** [comment] 2019-01-18 18:04
Closing as a duplicate of https://github.com/apollographql/apollo-client/issues/4327 (thanks @danilobuerger).

**Closed by benjamn** 2019-01-18 18:04 UTC
