### ISSUE TITLE
reducer option ignored by query and watchQuery

### ISSUE THREAD

**Issue by daniel-nagy** [apollographql/apollo-client#1218] opened 2017-01-22 22:47 UTC
Both `ApolloClient::query` and `ApolloClient::watchQuery` list `reducer` as an option. The `query` method seems to ignore the option and `watchQuery` only calls the reducer if you create a subscription as well. I'm not sure if this is intended but it wasn't what I expected.

version: `0.8.3`
framework: React Native

#### Intended outcome

If I provide `reducer` as an option to `query` or `watchQuery` I would expect it to be invoked every time  a query returns a new result.

#### Actual outcome

My `reducer` is ignored unless I also add a subscription on the observable returned from `watchQuery`.

#### Reproduction

Create a query with `ApolloClient::query` and provide a `reducer` as an option.

```javascript
client.query({
  query: ...
  reducer(result, action) {
    // never called
  }
});

**Comment by calebmer** [comment] 2017-01-23 17:39
@daniel-nagy could you use `updateQueries` instead?

**Comment by helfer** [comment] 2017-01-23 22:30
Could this be a duplicate of #1129?

**Comment by helfer** [comment] 2017-01-26 01:31
Btw, `reducer` should not be an option on query, only on watchQuery. We're likely to remove this API in upcoming versions (at least temporarily) for the reasons mentioned in #1129.

**Comment by calebmer** [comment] 2017-03-17 20:05
Closing this issue. We don’t recommend using `reducer`. Please use `updateQueries` or `update` instead.

**Closed by calebmer** 2017-03-17 20:05 UTC

**Comment by m14t** [comment] 2017-05-02 23:48
@calebmer according to http://dev.apollodata.com/react/cache-updates.html#resultReducers
> We recommend using the reducer option, except when there’s a good reason to use updateQueries instead (eg. if it would make your app much easier to understand and maintain).

To me that sounds like `reducer` _is_ the preferred way?  If that's not the case would it be possible to update that doc?

https://github.com/apollographql/react-docs/blame/master/source/cache-updates.md#L291

**Comment by helfer** [comment] 2017-05-03 03:51
@m14t yeah, `reducer` isn't the recommended way any more. We think `update` is much more versatile and will be a stable API in the future. Would you mind making a PR to the docs to change that sentence? There's a "edit on GitHub" button on every page.

**Comment by m14t** [comment] 2017-05-03 17:01
Thanks for the speedy reply @helfer.  I'm actually quite new to Apollo and so re-writing that paragraph which does not currently reference `update` is a slightly nuanced tast for my current knowledge level.

**Comment by helfer** [comment] 2017-05-03 20:26
Haha, no worries, I hope you're liking it so far! I'll update the docs as soon as I get around to it.
