### ISSUE TITLE
updateQueries will only update cache if keys in mutation variables exactly match mutation signature

### ISSUE THREAD

**Issue by krksgbr** [apollographql/apollo-client#1123] opened 2017-01-05 00:38 UTC
Hi there!
I am new to graphql and apollo and building a small issue tracker to try them out.
I have come across this problem while trying to use updateQueries, to update a list after a mutation and I am not sure if this is intended behaviour or a bug:
if the payload of the mutation does not contain exactly the same keys as the parameters in the mutation signature, the return value of updateQueries will be ignored.

I have created a simple representation of the problem as follows:

**query**
```graphql
const query = gql`
    query issues{
        issues {
            id
            title
            description
            project{
                id
                title
            }
        }
    }
`;
```

**mutation**
```graphql
const mutation = gql`
    mutation createIssue($title: String!, $project: String!, $description: String){
        createIssue(title: $title, project: $project, description: $description){
            id
            title
            description
            project{
                id
                title
            }
        }
    }
`;
```

**mutation HOC**
```javascript
const withMutation = graphql(mutation, {
    props: ({ownProps, mutate}) => {
        return {
            createIssue: data => mutate({
                variables: data,
                updateQueries: {
                    issues: (prev, action) => {
                        console.log(action);
                        const {mutationResult} = action;
                        const newIssue = mutationResult.data.createIssue;
                        return {
                            issues: [newIssue, ...prev.issues]
                        }
                    }
                }
            })
        }
    }
});
```

**code calling mutation**
```javascript
const issue = {
    title: faker.hacker.phrase(),
    project: projectsIds[Math.floor(Math.random()*projectsIds.length)],
    description: 'test',
};

this.props.createIssue(issue).then(() => {
    console.log('created issue');
});
```

If I leave out the optional `description` key from the issue object, updateQueries will still run, but its return value will not be used to update the cache. 

Is this intended behaviour, and if so, what is the reason it should work this way?

Thank you.

**Comment by stubailo** [comment] 2017-01-05 06:09
I think that's not intended behavior - it seems like what might be happening is that Apollo is internally expecting the shape of the new data to match the query and then failing silently for some reason when it does not. So there are two issues:

1. It should throw or print an error if it is failing, and
2. It shouldn't fail in the first place

Do you mind sending a PR with a test for this? It should go next to the other tests for updateQueries.

**Comment by krksgbr** [comment] 2017-01-05 18:49
I must say I am not closely familiar with the internals of Apollo Client and I don't have a ton of experience with writing tests in general, but I can look into this during the weekend.
Is  [this](https://github.com/apollostack/apollo-client/blob/9bd6a01fd9c3de784e353b5de3f684266e1c96ef/test/mutationResults.ts) the right file to work with?

**Comment by helfer** [comment] 2017-01-06 12:20
@krksgbr I think you should see the same behavior when you just update a single query, so you can write the test in [this file](https://github.com/apollostack/apollo-client/blob/9bd6a01fd9c3de784e353b5de3f684266e1c96ef/test/fetchMore.ts) similar to the one that has "triggers new result from updateQuery" in the title, but instead do what you do in your case to make it fail. Thanks in advance for your efforts! 🙂

**Comment by dchambers** [comment] 2017-01-13 11:11
I'm seeing something very similar [over here](https://github.com/sapientglobalmarkets/graphql-contacts/blob/master/src/ContactForm/index.js#L78) where the update is just silently ignored. Would it be possible to warn users about rejected updates, rather than silently ignoring them?

**Comment by calebmer** [comment] 2017-01-13 14:09
@krksgbr thanks so much for your tests! I merged them into my current open PR trying to fix this (https://github.com/apollostack/apollo-client/pull/1174) and it looks like one of your two tests is fixed. I’m pretty sure that I know what needs to be done to fix the other one. Hopefully we can get a fix for this soon :+1:

**Comment by krksgbr** [comment] 2017-01-14 08:52
@calebmer
Great! So can I close my own PR then?

**Comment by rafrex** [comment] 2017-01-19 05:31
I think the issue I'm having is related to this. I have a `CurrentUser` query that the server returns an error for when there is no logged in user. When a user logs in I want to update the `CurrentUser` query with what's returned from the mutation.

With `updateQueries` the previous result is a blank object (because the server returned an error because no current user exists), and the query doesn't get updated with the mutation result. This could be because the object shapes don't match (i.e. this issue), or possibly because the previous result had `data.error.graphQLErrors...`.

I also tried implementing this with a `reducer` in the `CurrentUser` query instead, but the same problem occurred even though the correct data is available in `action.result.data...`.

```js
updateQueries: {
  CurrentUser: (prev, { mutationResult }) => {
    // prev is a blank object when the server returns an error for the previous result
    console.log(prev);
    return {
      viewer: {
        user: mutationResult.data.loginUser.user,
      },
    };
  },
},
```

**Comment by calebmer** [comment] 2017-01-19 19:03
@rafrex I don’t actually think this is the same issue. If it is you should be at least partially fixed by https://github.com/apollostack/apollo-client/pull/1174. Could you open a new issue so we can try to better understand your problem there?

**Comment by rafrex** [comment] 2017-01-19 20:12
@calebmer I opened a new issue #1201

**Comment by CodogoFreddie** [comment] 2017-02-05 20:39
I believe this is the right issue:
I'm also  unable to add an item to a collection using `updateQueries`, if that collection is empty to begin with.

**Comment by helfer** [comment] 2017-02-10 00:23
@CodogoFreddie do you have a small example / minimal reproduction? I'm guessing this isn't the same issue, but without a reproduction or failing test case it's pretty hard to tell.

**Comment by mkozhukharenko** [comment] 2017-04-27 10:32
I has the next issue and I think that it's the same that is discussing here:

docs says:
>  If you pass a query into your graphql() function then *your component* will fetch that query and *reactively listen to updates for the query in the store.*

When I’m updating store using `updateQueries`  or `update` with proxy - *the Store is updated, actually, and the my component is being rerendered. But no values comes into it* (undefined). 

I'll try to provide an example. It seems that the problem is in the query/mutation shape - but Apollo fails silently.

**Comment by bkniffler** [comment] 2017-05-03 16:18
@mkozhukharenko I'm having the same exact issue. After a lot of digging and trying, I found out that the query mutation fields need to match the query that you want to update via updateQueries, or else something weird happens and the value will be undefined.

**Comment by helfer** [comment] 2017-05-03 18:17
This will become much easier to debug with #1638 which we'll merge and release today or tomorrow (just working on adding more tests now)!

**Closed by helfer** 2017-05-03 18:17 UTC
Labels: bug
