### ISSUE TITLE
after useMutation cache.writeQuery  not update UI

### ISSUE THREAD

**Issue by menglingyu** [apollographql/apollo-client#7840] opened 2021-03-14 16:42 UTC
```
"@apollo/client": "^3.3.11",
  "@apollo/react-ssr": "4.0.0",
  "@nexus/schema": "^0.19.2",
  "@prisma/client": "2.15.0",
  "apollo-link-http": "1.5.17",
  "apollo-link-schema": "1.2.5",
  "apollo-server": "^2.19.2",
  "apollo-server-micro": "2.19.2"
```

```

export const CreateNewPost = gql`
  mutation createNewPost($content: String!) {
    createNewPost(content: $content) {
      ...PostFields
    }
  }
  ${POST_FIELDS}
`

...
 const [createNewPost] = useMutation(CreateNewPost, {
    update(cache, { data: { createNewPost } }) {
      const { postsQuery: posts } = cache.readQuery({ query: PostQuery })

      cache.writeQuery({
        query: PostQuery,
        data: [createNewPost, ...JSON.parse(JSON.stringify(posts))],
      })
    },
  })
```

**Comment by jcreighton** [comment] 2021-03-15 15:26
@menglingyu It helps if you can provide a reproduction. Looking at this code, I can _guess_ what the issue is but I can't provide a definite answer. Most often the cache not updating is because an object is being added to a list of references. [This comment](https://github.com/apollographql/apollo-client/issues/7731#issuecomment-783838017) might be helpful for understanding what _might_ be happening. Again, I could give a more definite answer with a reproduction.

**Comment by jcreighton** [comment] 2021-03-16 14:29
@menglingyu I'm going to close this issue but if you're still experiencing an issue, we can re-open!

**Closed by jcreighton** 2021-03-16 14:29 UTC
