### ISSUE TITLE
Memory leaking on SSR with version 3.5.10

### ISSUE THREAD

**Issue by libdor** [apollographql/apollo-client#9712] opened 2022-05-12 11:47 UTC
Have set Apollo Client version as ^3.4.16 for a while, but after the website went to live, New Relic stats showed that the memory usage increased on the server side steadily (Occurred on version 3.4.17 and 3.5.10)
Our system configuration is Node SSR and React + Express + Apollo Client on client side. 

**Intended outcome:**
The memory usage level should be stable at a certain level. The following screenshot shows the memory usage after the Apollo Client version was reverted back to 3.3.21.
<img width="943" alt="Apollo_clinet_3 3 21" src="https://user-images.githubusercontent.com/33384033/168042397-e78a5f3e-0202-4eb7-9823-f6769a5ef640.png">

**Actual outcome:**
The memory usage keeps climbing. The following screenshot shows the memory usage of Apollo Client version 3.5.10. The memory usage was reset after the new image was deployed.
<img width="1295" alt="Apollo_client_3 4 16" src="https://user-images.githubusercontent.com/33384033/168042959-4d471418-a4ba-4d66-bc1f-bdf028fdb647.png">

**How to reproduce the issue:** 
Haven't got the simplified source code to reproduce this, but the heapdump analysis pointed to the module of "@wry/trie" "^0.3.0", which is used by InMemoryCache. Since version 3.3.21 is the last version that is not dependent on trie, we reverted to this version. After the reversion, there was no more memory leaking issue.

**Versions**
System:
    OS: macOS 11.6.4
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - ~/workspace/node_modules/.bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
  npmPackages:
    @apollo/client: ^3.4.16 => 3.5.10 
    apollo: ^2.33.6 => 2.33.9

**Comment by chris-mo** [comment] 2022-06-17 21:58
Similar issue discussed in a diff issue, to which i posted something that MIGHT help you
https://github.com/apollographql/apollo-client/issues/7942#issuecomment-1159256285

**Comment by waneka** [comment] 2022-07-27 18:44
Chiming in to say "us too". We have an app that's been using `v3.5.5`. We downgraded to `v3.3.21` and our memory leak issue was resolved. Our memory usage chart looked identical to the chart posted by @libdor above ^, just steadily increasing.
I know nothing about Trie data structures but at a glance it looks like there might be some memory leak implications if nodes are not deleted properly.

**Comment by LevanArabuli** [comment] 2023-03-07 06:45
+1. We had similar memory leak in SSR with `3.5.10`. After downgrading it to `3.3.21` it's gone.
Are there any plans to fix this issue from Apollo team?

**Comment by phryneas** [comment] 2023-03-07 12:15
@LevanArabuli Reports on `3.5.10` are not really something we can address - the current version is `3.7.10`. 
Does it still occur for you in that version? 
Then we need some kind of reproduction. "In SSR" is an incredibly broad statement, with all the different kinds of SSR out there.

**Comment by zargold** [comment] 2023-12-22 17:37
We currently appear to have a growing memory consumption issue that appears to overlap with an upgrade to @apollo/client@npm:3.8.7 from `3.3.15` (in case we're still wondering if this is still a problem). Our app mostly makes a single call to a graphql server during NextJS SSR.

**Comment by phryneas** [comment] 2023-12-22 17:43
@zargold Could you please give our Apollo Client 3.9 beta a try? 
We did a big spike on memory leaks in 3.9, and that release fixes a lot of them. You can read more on that in [this blog post](https://www.apollographql.com/blog/apollo-3-9-beta-feature-spotlight-the-memory-story).

(Also, just to make sure: we recommend that in a SSR scenario like Next.js you create a new ApolloClient instance for each request - are you doing that?)

**Comment by zargold** [comment] 2024-01-19 19:14
Hi @phryneas it does seem to improve the memory leak issue on of our smaller projects where we tested it. (In that one memory consumption would increase gradually but slightly exponentially since the start of the day.) Since we upgraded to the beta version it seems to have subsided. So congratulations team. Looking very much forward to it getting out of beta so we can use it on our main app.

**Comment by phryneas** [comment] 2024-02-06 10:08
We have recently released Apollo 3.9 which I believe should have fixed this issue - so I'm going to close this.

If this issue keeps persisting in Apollo Client >= 3.9.0, please open a new issue!

**Closed by phryneas** 2024-02-06 10:08 UTC
Labels: :wilted_flower: needs-reproduction, 🥓 Server-side rendering (SSR), 🔍 investigate
