### ISSUE TITLE
Data in cache ignoring rename in query apollo

### ISSUE THREAD

**Issue by olegmalyarenko** [apollographql/apollo-client#7915] opened 2021-03-29 10:56 UTC
I have a mutation which returns a updated part of object 
` mutation saveInfo($request:updateInfo){
        update(request: $request){
            status
            message
            errors
            object{
                ...Info
            }
        }
    }${updateObject.info} `
    
    
  `  const updateObject = {
    info: gql fragment Info on Obj{
       info{
            name
            address{
                street
                city
                country
                zip:postal
            }
        }
    },
};`   

Before updating lines in cache have a structure like in schema and ignore renaming in query. For example:

`object{ 
     info {
      address {
      __typename:Address
     street: Test
    city: Test
    country:US
    postal:11111
    }
   } 
}`

After mutation date saving in cache corectly like in response : 
`object { 
     info {
      address  {
      street: Test
      city: Test
      country:US
      zip:11112
      __typename:Address
    }
   } 
}`

When I return on the main page and again go to the page with mutation It makes  additional query to all info  in despite of  options of query nextFetchPolicy: "cache-only", returnPartialData: true  and set in cache lines withot renaming fields again.  

If I remove renaming lines from the query and It equal to original schema , additional requests when I go to the page again don't send.  

Why cache want to ignore renaming in schema and how I can save renaming in query and don't have additional requests?

**Comment by benjamn** [comment] 2021-03-31 18:12
This is working as designed, but I'm happy to explain the reasoning.

Query field aliasing provides a way to query the same field (presumably using different arguments) multiple times within the same query selection set. You can use aliases to rename fields temporarily within a particular query, but that renaming is not permanent, because the cache intentionally stores the data using the _original_ name of the field.

This strategy keeps field data consolidated within the cache under a stable field name, with any field arguments serialized and appended to the original field name. In other words, since `InMemoryCache` can keep the different field values separated according to their arguments (not just their names), the cache doesn't need to preserve the temporary aliases that happened to be used by one particular query to disambiguate fields.

Another query might include the same field, without needing to use an alias, because there's no ambiguity between fields in the other query. It would be a shame if the cache couldn't tell these two queries are updating the same field data, just because one of the queries needed to use aliases and the other did not.

In the other direction, whenever you read a query from the cache, that query can use whatever aliases it wants to rename fields that may have been written into the cache using other queries with different aliases. For this system to work, there needs to be a stable internal name for the field, so you don't have to know about all the other queries in your application that might be using different aliases for that same field.

**Comment by hwillson** [comment] 2021-05-26 16:31
It doesn't sound like there is an outstanding issue here, so closing. Thanks!

**Closed by hwillson** 2021-05-26 16:31 UTC

**Comment by olegmalyarenko** [comment] 2021-05-26 19:37
Sorry, I missed the answer for the first message. I got necessary
info needed.

 Thanks for your answer!

ср, 26 мая 2021 г. в 19:32, Hugh Willson ***@***.***>:
