### ISSUE TITLE
fetchMore doesn't change loading state depending on network response (3.0.0-rc.10)

### ISSUE THREAD

**Issue by Prosen-Ghosh** [apollographql/apollo-client#6534] opened 2020-07-03 11:54 UTC
```js
const { loading, error, data, fetchMore } = useQuery(GET_BRANDS, {
    variables: {
        pagination: {
            skip: 0,
            limit: 10
        }
    }
});

const onPageChangeHandler = (page, pageSize) => {
    fetchMore({
        variables: {
            pagination: {
                skip: (page - 1) * pageSize,
                limit: pageSize
            }
        }
    });
}
```
**Intended outcome:**
- `loading` should change it's value `true/false` depending on network status.

**Actual outcome:**
`loading: false`

**Versions**
```
"@apollo/client": "^3.0.0-rc.10"
```

**Comment by benjamn** [comment] 2020-07-03 14:48
Thanks for reporting, but this is a duplicate of #6354 (it's a known issue).

**Closed by benjamn** 2020-07-03 14:48 UTC
