### ISSUE TITLE
Make a function to remove queries (clear some parts of the store)

### ISSUE THREAD

**Issue by Bastorx** [apollographql/apollo-client#4217] opened 2018-12-05 14:25 UTC
Problem describe here: https://stackoverflow.com/questions/48596265/deleting-apollo-client-cache-for-a-given-query-and-every-set-of-variables/52996159#52996159

Example
```
cache.removeQuery({
    query: GET_DATA
})
```

Based on readQuery / writeQuery

**Comment by danilobuerger** [comment] 2019-01-17 19:33
Duplicate of https://github.com/apollographql/apollo-feature-requests/issues/4

**Closed by danilobuerger** 2019-01-17 19:33 UTC
