### ISSUE TITLE
TypeError: Attempted to assign to readonly property. getting data from graphql query

### ISSUE THREAD

**Issue by savita-malaghan** [apollographql/apollo-client#7551] opened 2021-01-06 10:01 UTC
Hi i am trying to get data from aws-server using apollo/client and graphql query. It is saying error like **Query.props.children
**  are  [Unhandled promise rejection: TypeError: Attempted to assign to readonly property.] what might be cause to getting error like this.

**Comment by alex-golubtsov** [comment] 2021-01-08 22:09
I believe this was made intentionally. Instead of reassigning response data, make a copy of it.

**Comment by andycarrell** [comment] 2021-01-18 03:03
Hi I'm getting a similar issue when passing apollo data to `Chart.js` - I've tracked it down to [this internal clone function](https://github.com/chartjs/Chart.js/blob/1b6226342a6425a5926662b127ee17a7809952e6/src/helpers/helpers.core.js#L159-L183):

```js
/**
 * Returns a deep copy of `source` without keeping references on objects and arrays.
 * @param {*} source - The value to clone.
 * @returns {*}
 */
export function clone(source) {
	if (isArray(source)) {
		return source.map(clone);
	}

	if (isObject(source)) {
		const target = Object.create(null);
		const keys = Object.keys(source);
		const klen = keys.length;
		let k = 0;

		for (; k < klen; ++k) {
			target[keys[k]] = clone(source[keys[k]]);
		}

		return target;
	}

	return source;
}
```

The function looks like it is copying the data, but the error still throws?

**Comment by hwillson** [comment] 2021-05-18 15:43
This doesn't sound like an Apollo Client issue, but if anyone thinks it is and can provide a small runnable reproduction using `@apollo/client@latest`, we'll take a look. Thanks!

**Closed by hwillson** 2021-05-18 15:43 UTC
