### ISSUE TITLE
Pagination using useSuspenseQuery and React transition is broken

### ISSUE THREAD

**Issue by pvandamme** [apollographql/apollo-client#11315] opened 2023-08-28 15:20 UTC
I have a paginated query that I use with `useSuspenseQuery`. 
When I call the `fetchMore` function inside a `startTransition`, an unexpected re-render with **only** the new data happens before the final re-render with all the data merged together.

I've made a reproduction link so you can try it out : https://stackblitz.com/edit/stackblitz-starters-fqmtck?file=src%2Fcomponents%2FPaginatedQuery.tsx

### Reproduction steps

1 - Go to the stackblitz link
2 - Open your console
3 - Click "Fetch More"
4 - Look at logs

**Comment by phryneas** [comment] 2023-10-24 09:08
Hi there, I'm sorry - it seems that something went wrong when transferring this earlier. I transferred it now.

**Comment by finkef** [comment] 2024-02-27 15:12
Is there any workaround available currently?

**Comment by none23** [comment] 2024-02-27 15:51
@finkef 
Well, with @apollo/client v3.9.5, deleting line 243 in `node_modules/@apollo/client/react/internal/cache/QueryReference.js`  seems to fix the issue for me.
But I wouldn't do it in an app I care about)

**Comment by finkef** [comment] 2024-02-27 15:55
@none23 Thanks!

I just came up with this workaround, but wouldn't expect the best performance. It appears that `readQuery` always gets the correct data.

```ts
import { useApolloClient } from "@apollo/client"
import { useSuspenseQuery as useApolloSuspenseQuery } from "@apollo/experimental-nextjs-app-support/ssr"
import { startTransition, useCallback, useMemo } from "react"

export const useSuspenseQuery: typeof useApolloSuspenseQuery = (
  ...args: Parameters<typeof useApolloSuspenseQuery>
) => {
  const client = useApolloClient()
  const { data, fetchMore, ...rest } = useApolloSuspenseQuery(...args)

  const newFetchMore = useCallback(
    (...fetchMoreArgs: Parameters<typeof fetchMore>) => {
      return new Promise((resolve, reject) => {
        startTransition(() => {
          fetchMore(...fetchMoreArgs)
            .then(resolve)
            .catch(reject)
        })
      })
    },
    [fetchMore],
  )

  const actualData = useMemo(() => {
    return client.readQuery({
      query: args[0],
      variables: (args as any)[1]?.variables,
    })
  }, [data])

  return {
    data: actualData,
    fetchMore: newFetchMore,
    ...rest,
  } as any
}

```

**Comment by jerelmiller** [comment] 2024-03-04 22:25
Hey @pvandamme 👋 

I finally got around to fixing this issue with #11638. I've tried this with your reproduction and this solves it.

Would you mind trying this snapshot release to make sure it works on your end?

```
npm i @apollo/client@0.0.0-pr-11638-20240304221457
```

Note: You'll need a more modern version of the Next.js app support package since it uses some internals of Apollo Client from newer versions.

**Closed** 2024-03-05 18:43 UTC
Labels: 🐞 bug, :rose: has-reproduction, ⏲️ react-suspense
