### ISSUE TITLE
v3.8.3 useLazyQuery fires 2 times -unsure why

### ISSUE THREAD

**Issue by billnbell** [apollographql/apollo-client#11201] opened 2023-09-08 03:35 UTC
### Issue Description

We are getting 2 calls in Apollo Client when using useLazyQuery. It is exactly the same call, and passes the Authentication: Bearer header. I confirmed we are only calling the 1st parameter 1 time. And even put in a console.log('FIRE'); and only get 1 of these calls. No idea why. Any thing we can see internally to Apollo Client to debug the Apollo Client?

Using latest React 18 and NextJS.

These calls are pretty large responses. And calling it 2 times is really slowing down the site.

Thanks.

### Link to Reproduction

None

### Reproduction Steps

See above. I think they're maybe a better way to find out why it is being called 2 times.

**Comment by jerelmiller** [comment] 2023-09-08 03:44
Hey @billnbell 👋 

Would you be able to provide a minimal reproduction of the issue? Without code samples or a reproduction to play with, its very difficult to determine what might be happening here. Any more information you can provide would be super helpful. Thanks!

**Comment by billnbell** [comment] 2023-09-08 05:56
OK - I will send more. But any debug mode I can see internal into this call ? useLazyQuery

**Comment by phryneas** [comment] 2023-09-08 08:29
You could provide us a [https://www.replay.io/](Replay) of the issue occuring, but please keep in mind that that replay will contain your authentication headers, so don't record it in a production environment.

Otherwise, maybe you can also share a code snippet with us that shows us how you are using it?

**Comment by KataevAS** [comment] 2023-09-12 11:45
I'm having this problem with an extra request after removing one of the variables properties. 
<img width="600" alt="image" src="https://github.com/apollographql/apollo-client/assets/38090158/8e1d0340-b6f4-4148-bf40-823976a21ca6">

if the fetchPolicy property is set to "no-cache"

1) Use getDataWithVariable
2) Use function getDataWithoutVariable after function getDataWithVariable
3) Look at tab network and see it:
![image](https://github.com/apollographql/apollo-client/assets/38090158/8ec36c97-ea98-4971-a3dc-372367a0cccc)

getData makes three requests instead of two. After removing one of the properties useLazyQuery made a query with the previous value of this field.

**Comment by KataevAS** [comment] 2023-09-12 14:16
https://github.com/apollographql/apollo-client/blob/53b7370b76465f92e439e02e3431d1c13dc58d7a/src/react/hooks/useLazyQuery.ts#L98

I think, we can remove "variables" from the default state of options, since we overwrite them by passing them to the function, is that right?

**Comment by alessbell** [comment] 2023-09-12 15:46
@billnbell @KataevAS if you downgrade to the latest version in the 3.7.x series, are you still able to reproduce this?

**Comment by KataevAS** [comment] 2023-09-12 16:18
> @KataevAS could you try 3.7.10 as well? There was a few fixes to `useLazyQuery` in 3.7.11 and I'm curious if any of those changes introduced this regression or if this has existed for longer. Thanks!

@jerelmiller 3.7.10 same thing here

**Comment by KataevAS** [comment] 2023-09-12 16:22
<img width="1129" alt="image" src="https://github.com/apollographql/apollo-client/assets/38090158/c0ceddd8-032f-455f-a943-e85d12a7638b">


I did this for a test and it solved the problem, since by passing variables to the useLazyQuery function I expect them to be completely replaced. I think, they are replaced after calling forceUpdate now.

**Comment by billnbell** [comment] 2023-09-13 03:03
Is this a fix?

**Comment by KataevAS** [comment] 2023-09-13 07:24
@billnbell this is a hot fix that solved the problem for me.
@alessbell what do you think about this?

**Comment by KataevAS** [comment] 2023-09-13 10:18
@phryneas yes I can. Look at the console please https://codesandbox.io/s/gracious-water-w6259q?file=/src/index.jsx

**Comment by phryneas** [comment] 2023-09-13 10:28
@KataevAS that's certainly important information - thank you!

**Comment by KataevAS** [comment] 2023-09-13 10:34
@phryneas can I submit my edits for review?

**Comment by phryneas** [comment] 2023-09-13 10:37
@KataevAS A PR would be welcome, but please be aware that we haven't looked into this deep enough yet and might in the end prefer another solution, so I can't 100% guarantee that we'd go with the PR at this point.

I can trigger you a package build from that PR, though, so you can continue running an Apollo Client version without local patches :)

**Comment by KataevAS** [comment] 2023-09-13 12:07
This solution does not work if we need to store in each request the variables passed during hook initialization

**Comment by KataevAS** [comment] 2023-09-13 13:08
@billnbell we can use the "reobserve" function now

```
const [getFn, { data, reobserve }] = useLazyQuery(SCHEMA)

getFn({
  variables: {
    id: 1
  }
})

reobserve({
  variables: {}
})
```

**Comment by billnbell** [comment] 2023-09-24 02:41
what can we do to get this fixed?

**Comment by KataevAS** [comment] 2023-10-17 06:10
@phryneas  I think this might be interesting for you. Look at the console. https://codesandbox.io/s/elastic-khorana-lgvyf5?file=/src/index.jsx It is important that the variables match

**Comment by billnbell2** [comment] 2023-10-17 06:41
what is the issue?

**Comment by phryneas** [comment] 2023-10-17 07:45
@KataevAS in your case, one of the two queries (both to the same field with the same argument) is missing an `id`, so the normalized cache cannot correctly save that data, the second query overrides data from the first query and the first query has to run again.
If you add an `id` field (as you should always, to every entity!), your double request goes away.

**Comment by KataevAS** [comment] 2023-10-24 13:00
@phryneas сould this be related? https://codesandbox.io/s/silly-mayer-6pr822?file=/src/index.jsx

**Comment by KataevAS** [comment] 2023-11-03 06:42
> what can we do to get this fixed?

A solution might be to pass null values ​​of all used variables to useLazyQuery.
https://codesandbox.io/s/pensive-stitch-gp3gcg

**Comment by jerelmiller** [comment] 2024-02-02 21:53
Hey all 👋 

I've got a fix for this issue in https://github.com/apollographql/apollo-client/pull/11403. @KataevAS I was able to use your [reproduction](https://codesandbox.io/s/silly-mayer-6pr822?file=/src/index.jsx) to validate the PR fixes the issue. If you're curious, I've created a [separate repo](https://github.com/jerelmiller/issue-11201-useLazyQuery-double-call) that shows the fix in practice since CodeSandbox was giving me some weird behavior and logging more than necessary.

I'm hoping to get this in the next patch release early next week. Thanks!

**Closed** 2024-02-07 16:45 UTC
Labels: :rose: has-reproduction, 🔍 investigate
