### ISSUE TITLE
Apollo client stopped working after update: `InMemoryCache is not a constructor`

### ISSUE THREAD

**Issue by jnatten** [apollographql/apollo-client#10102] opened 2022-09-13 11:26 UTC
After upgrading @apollo/client (from 3.4.0 to 3.6.9) our application crashes when attempting to construct `InMemoryCache`.

It produces this error:
 ```
TypeError: L.InMemoryCache is not a constructor
    at /app/build/server.js:164594:23
    at Q (/app/build/server.js:164599:13)
    at yg (/app/build/server.js:196934:13)
    at kg (/app/build/server.js:197019:19)
    at Nh (/app/build/server.js:198722:46)
    at /app/build/server.js:198903:11
    at o.handle_request (/app/build/server.js:33044:11)
    at o (/app/build/server.js:32888:48)
    at a (/app/build/server.js:62153:26)
    at /app/build/server.js:75457:49
```
[Razzle/webpack config here](https://github.com/NDLANO/ndla-frontend/blob/fd962f75a3a764f004d700b93f534eb138842eb4/razzle.config.js) (with the most intersting part on line 57, i think).

If i remove the `appConfig.externals = []` from our config the build starts working as expected again, however then i need to include node_modules separately from our build output directory. This increases our total build size quite drastically. It also complicates our build pipeline somewhat so i would really like to avoid it if at all possible.

It also works if i downgrade to `"@apollo/client": "3.4.17"`, so it seems like there is a change from 3.4->3.5 that breaks my build somehow 🤔 

All help appreciated!

**Comment by bignimbus** [comment] 2022-09-15 02:32
Hi @jnatten 👋🏻  thanks for opening this issue!  Do any of the suggestions in https://github.com/apollographql/apollo-client/issues/9242 help narrow down the cause?  In that thread there's a reference to the `3.5.4` changelog that might be related: https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#notices .  Looking forward to hearing from you!

**Comment by jnatten** [comment] 2022-09-15 08:23
Hi @bignimbus , thanks for the response!
Nothing in https://github.com/apollographql/apollo-client/issues/9242 helps as far as i can tell.
I believe the change that affects us was introduced in 3.5.0 since it happens from v3.4.17->v3.5.0
Out of 3.4.x, 3.5.0, 3.5.3, 3.5.4 and 3.6.9 the 3.4.x versions are the only ones that work.

I'm guessing this is our problem
> Since Apollo Client v3.5.0, CommonJS bundles provided by @apollo/client use a .cjs file extension rather than .cjs.js, so Node.js won't interpret them as ECMAScript modules

But i can't really figure out how to handle that with webpack 🤔

**Comment by bignimbus** [comment] 2022-09-15 14:33
Thanks for the quick reply @jnatten!  It sounds like this may be a webpack configuration question.  I'll close this issue for the time being but please do feel free to tag me with additional details if there's more to investigate and we can consider re-opening.  Have a great rest of the week!

**Closed by bignimbus** 2022-09-15 14:33 UTC
Labels: 🏓 awaiting-contributor-response

**Comment by jnatten** [comment] 2022-09-15 17:00
I'm new to node/js modules and such, but it looks like node doesn't support the commonjs from "main", and our webpack config resolves to that first.

It seems to have been fixed in our configuration by setting [resolve.mainFields](https://v4.webpack.js.org/configuration/resolve/#resolvemainfields) to prioritize `module` for our `node` target.

for completeness:
```javascript
if (target == 'node' && !dev) {
  resolve.mainFields = ['module', 'main'];
}
```
