### ISSUE TITLE
Should a query using pollInterval automatically refetch other queries?

### ISSUE THREAD

**Issue by kamilbonna** [apollographql/apollo-client#9886] opened 2022-07-06 12:26 UTC
Hi,

I've stumbled on an issue with auto refetching. I'm not really sure if its an intended behavior or a bug so I'm posting this as a question. 

I fetch list of items that I render on a screen using `GET_ITEMS` query (`first` and `last` arguments are used for pagination):
```ts
  const { loading, error, data, refetch, fetchMore } = useQuery<...>(GET_ITEMS, {
    fetchPolicy: 'cache-and-network',
    errorPolicy: 'all',
    notifyOnNetworkStatusChange: true,
    variables: {
      first: 0, // give me first page of results
      last: PAGE_SIZE
    }
  })
```
Then when I click on an item from the list, new UI shows up with the item details. These details are fetched using `GET_ITEM_DETAILS` query:
```ts
  const { data, error, loading, refetch } = useQuery<...>(GET_ITEM_DETAILS, {
    fetchPolicy: 'no-cache',
    variables: { itemId },
    errorPolicy: 'all',
    pollInterval: POLL_FREQUENCY
  })
```
My problem is that when I use polling each `GET_ITEM_DETAILS` query also triggers `GET_ITEMS` query which interferes with my pagination. Interestingly, with no polling `GET_ITEMS` query is not refetched and the same applies to custom polling (using `setInterval` and `refetch` function):
```ts
  useEffect(() => {
    const interval = setInterval(() => {
      refetch()
    }, POLL_FREQUENCY)
    return () => clearInterval(interval)
  }, [])
```

How can I prevent this auto-refetch from happening?

**Comment by MrDoomBringer** [comment] 2022-07-06 15:02
Hi @kamilbonna, thanks for submitting your question to the repository, and welcome! 

I don't believe this is intended behavior, `pollInterval` should only execute its own query. Would you be willing to create a reproduction using https://github.com/apollographql/react-apollo-error-template or https://codesandbox.io/s/github/apollographql/react-apollo-error-template and linking to it here? 

All the best, 
Emmanuel, Intern :-)

**Comment by MrDoomBringer** [comment] 2022-07-28 20:22
Hey!

Because we don't have any extra information on this, we'll be closing it for now. `pollInterval` will re-run overlapping queries, so depending on the exact implementation this behavior might be expected. Let me know if you have a reproduction and I'll be happy to reopen this!

All the best,
Emmanuel, Intern :-)

**Closed by MrDoomBringer** 2022-07-28 20:22 UTC
Labels: 🏓 awaiting-contributor-response
