### ISSUE TITLE
Breaking change with @defer changes and apollo angular package

### ISSUE THREAD

**Issue by gmiklich** [apollographql/apollo-client#10162] opened 2022-10-04 21:06 UTC
**Intended outcome:**
My angular project utilizing @graphql-codegen, apollo-angular, and @apollo/client should build properly

**Actual outcome:**
Where the code attempts to perform a mutation and manipulate the result, there is a typescript error stating that "property 'data' does not exist on type 'MutationResult<...'".

This is because the `MutationResult` interface in the apollo-angular package extends the `FetchResult` type in @apollo/client.  When making changes to the @apollo/client types to support `@defer` (specifically [here](https://github.com/apollographql/apollo-client/commit/f2bb0995e64671135bc6de25bc02010d9b61e616#diff-5e2dbe69feb4479799e4247c4d09edd3c9f6255ce84522aece23a5478cf2644aR85)), `FetchResult` was changed from an interface to a type, and more importantly, it is set equal to a union type.

The above will cause a "An interface can only extend an object type or intersection of object types with statically known members" error if the apollo-angular package uses apollo-client v3.7.0.  That is what "removes" the data property from the mutation result object.

**How to reproduce the issue:**
I don't have a reproduction, but if you try to define your own MutationResult like the apollo-angular package does, I assume you'll get the error.  That, or go about it the long way and have a project with the packages I outlined above, create a mutation, and try to access the data property of the result.

This issue is also brought up in the apollo-angular project's github repo:
https://github.com/kamilkisiela/apollo-angular/issues/1818

**Versions**
"@apollo/client": "3.7.0",
"apollo-angular": "3.0.1",
"@graphql-codegen/cli": "2.13.2",

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 7.5.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.34)

**Comment by KillerCodeMonkey** [comment] 2022-10-10 06:44
same issue and setup here.

The "MutationResult" just has the "loading" property.

**Comment by dylanwulf** [comment] 2022-10-11 04:42
Hello, just a friendly reminder to please wrap `@defer` inside of backticks (` `` `) to avoid accidentally tagging the github user named `defer`. Thanks!

**Comment by andrii-lundiak** [comment] 2022-12-06 15:59
First I surprised I get MutationResult issue (as @KillerCodeMonkey  mentioned above) in my Angular project, second, when I upgrade to latest version of `apollo-angular`, @apollo/client` and `graphql` as documentation says, I then end up with my Angular project requireing React library :) Isn't it funny :) ?

**Comment by bignimbus** [comment] 2022-12-06 16:03
Hi all, the latest version of `apollo-angular` should provide a workaround but I'll leave this open since there still may be something actionable on our end.  Thanks!

**Comment by andrii-lundiak** [comment] 2022-12-06 16:13
Yeah, but Angular project build is failing.

**Comment by bignimbus** [comment] 2022-12-06 16:26
Thanks for sharing @andrii-lundiak 👀  It's interesting that these files are being imported into your project, I wouldn't expect the `react/` modules to be imported in an Angular app.  If you share more details the community may be able to help narrow down whether the issue is in the application code, `@apollo/client`, or `apollo-angular`

**Comment by andrii-lundiak** [comment] 2022-12-06 16:48
@bignimbus here are my prod and dev deps:

```
 "dependencies": {
    "@angular-material-components/color-picker": "^8.0.0",
    "@angular/animations": "14.0.1",
    "@angular/cdk": "14.0.1",
    "@angular/common": "14.0.1",
    "@angular/compiler": "14.0.1",
    "@angular/core": "14.0.1",
    "@angular/forms": "14.0.1",
    "@angular/material": "14.0.1",
    "@angular/material-moment-adapter": "14.0.1",
    "@angular/platform-browser": "14.0.1",
    "@angular/platform-browser-dynamic": "14.0.1",
    "@angular/router": "14.0.1",
    "@apollo/client": "^3.7.1",
    "@microsoft/applicationinsights-web": "^2.8.3",
    "@ng-select/ng-select": "9.0.0",
    "@ngx-loading-bar/core": "^6.0.2",
    "@ngx-loading-bar/http-client": "^6.0.2",
    "@piwikpro/ngx-piwik-pro": "^1.0.1",
    "@sentry/browser": "^7.20.0",
    "@swimlane/ngx-datatable": "^20.0.0",
    "@types/file-saver": "2.0.2",
    "apollo-angular": "^4.1.1",
    "bootstrap": "^4.5.3",
    "cookieconsent": "^3.1.1",
    "d3": "4.10.2",
    "d3-svg-annotation": "2.0.0",
    "dragula": "3.7.2",
    "file-saver": "2.0.2",
    "graphql": "^16.6.0",
    "graphql-ws": "^5.11.2",
    "hammerjs": "^2.0.8",
    "lodash-es": "^4.17.21",
    "moment-mini": "2.22.1",
    "moment-range": "^4.0.2",
    "ng2-dragula": "1.5.0",
    "ng2-nouislider": "^1.8.3",
    "ngx-color-picker": "^12.0.1",
    "ngx-cookie": "4.0.2",
    "ngx-cookieconsent": "^2.2.3",
    "nouislider": "^15.4.0",
    "rxjs": "6.6.3",
    "sass": "^1.44.0",
    "sockjs": "^0.3.24",
    "sockjs-client": "^1.5.0",
    "subscriptions-transport-ws": "^0.11.0",
    "ts-helpers": "1.1.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
}
 ```

``` 
"devDependencies": {
    "@angular-devkit/build-angular": "14.0.1",
    "@angular-devkit/schematics": "14.0.1",
    "@angular-eslint/builder": "14.0.1",
    "@angular/cli": "14.0.1",
    "@angular/compiler-cli": "14.0.1",
    "@babel/core": "7.6.2",
    "@types/chai": "^4.2.14",
    "@types/d3": "4.10.1",
    "@types/file-saver": "2.0.2",
    "@types/hammerjs": "^2.0.40",
    "@types/jasmine": "^4.0.1",
    "@types/jasminewd2": "^2.0.10",
    "@types/karma-coverage": "^2.0.1",
    "@types/lodash": "^4.14.172",
    "@types/lodash-es": "^4.17.4",
    "@types/moment": "^2.13.0",
    "@types/node": "^12.19.8",
    "@typescript-eslint/eslint-plugin": "^5.44.0",
    "@typescript-eslint/parser": "^5.44.0",
    "babel-loader": "8.0.6",
    "eslint": "^8.28.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "^2.7.1",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jasmine": "^4.1.3",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-security": "^1.5.0",
    "eslint-plugin-sonarjs": "^0.13.0",
    "husky": "^4.3.8",
    "jasmine-auto-spies": "^6.9.8",
    "jasmine-core": "~4.0.1",
    "karma": "~6.3.17",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "^2.2.0",
    "karma-jasmine": "~4.0.2",
    "karma-jasmine-html-reporter": "^1.7.0",
    "karma-junit-reporter": "^2.0.1",
    "lint-staged": "9.4.3",
    "prettier": "^2.6.2",
    "sass-lint": "1.13.1",
    "ts-node": "9.0.0",
    "typescript": "~4.7.2",
    "webpack-bundle-analyzer": "^4.5.0"
}
```

**Comment by alessbell** [comment] 2023-01-12 20:00
Hi all 👋  It looks like the fix has been made in `apollo-angular`: https://github.com/kamilkisiela/apollo-angular/releases/tag/v4.1.0

From the release notes:
> - Support @apollo/client v3.7.X
> - Fix typescript issue with MutationResult type https://github.com/kamilkisiela/apollo-angular/issues/1818

Can anyone confirm that upgrading to 4.1.0 fixes this issue? If it does not, a runnable reproduction would be helpful. Thanks!

**Comment by alessbell** [comment] 2023-01-13 11:43
@andrii-lundiak glad to hear it! I appreciate the confirmation 🙂 In that case I will be closing out this issue, thanks all.

**Closed** 2023-01-13 11:43 UTC
Labels: ⛑ TypeScript, 🏓 awaiting-contributor-response, 🌤 has-workaround, ⏩ @defer
