### ISSUE TITLE
The variables in the cache are not identical with SSR.

### ISSUE THREAD

**Issue by negezor** [apollographql/apollo-client#8855] opened 2021-09-28 11:30 UTC
**Intended outcome:**

The variables in the cache are identical to those retrieved using SSR.

**Actual outcome:**

The variables in cache are sorted in a different order. The apollo client does not find the cache and makes new requests. If you look at the ROOT_QUERY cache through the Apollo Client Devtools, there will be two different keys:
```json
// After cache.extract().ROOT_QUERY['...']
teams({"activity":{"include":[],"exclude":[]},"contributor":{"include":[],"exclude":[]},"first":20,"orderBy":{"field":"UPDATED_AT","direction":"DESC"}})

// After hydration in the client
teams({"activity":{"include":[],"exclude":[]},"contributor":{"include":[],"exclude":[]},"first":20,"orderBy":{"field":"UPDATED_AT","direction":"DESC"}})
teams({"activity":{"exclude":[],"include":[]},"contributor":{"exclude":[],"include":[]},"first":20,"orderBy":{"direction":"DESC","field":"UPDATED_AT"}})
```
```ts
const cache = new InMemoryCache({});

if (!isServer) {
  cache.restore(JSON.parse(window.__APOLLO_STATE__));
}

const apolloClient = new ApolloClient({
  link,
  cache,
  ssrMode: isServer,
  ssrForceFetchDelay: 1000,
  connectToDevTools: process.env.NODE_ENV !== 'production'
});
```
```ts
const { result } = useFetchTeamsQuery({
  activity: {
    include: [],
    exclude: []
  },
  contributor: {
    include: [],
    exclude: []
  },
  first: 20,
  orderBy: {
    field: 'UPDATED_AT',
    direction: 'DESC'
  }
});
```

**How to reproduce the issue:**

**Versions**

```
System:
  OS: Linux 4.19 Arch Linux
Binaries:
  Node: 16.10.0 - /usr/sbin/node
  Yarn: 1.22.11 - /usr/sbin/yarn
  npm: 7.24.0 - /usr/sbin/npm
```
`@apollo/client`: `3.4.15`
`graphql`: `15.6.0`

**Comment by benjamn** [comment] 2021-09-28 18:04
@negezor This is surprising because Apollo Client and `InMemoryCache` definitely do attempt to serialize field arguments in a stable/sorted way. Do you think you could provide more of a [reproduction](https://github.com/apollographql/react-apollo-error-template/), or try other `@apollo/client` versions (like 3.3.21, the last before 3.4.0) to see if this might be a regression? Do you have any `keyArgs` configuration for the `Query.teams` field?

**Comment by negezor** [comment] 2021-09-29 18:27
I tried to [reproduce](https://github.com/negezor/react-apollo-error-template) the error, but I can't reproduce the error. I also tried to install different versions, but the result was the same. I'm not using `keyArgs` for the `Query.teams` field.

I am using [Nuxt.js (Vue)](https://github.com/nuxt/nuxt.js) and [@vue/apollo-composable](https://github.com/vuejs/vue-apollo/tree/v4/packages/vue-apollo-composable). There is a community module [@nuxtjs/apollo](https://github.com/nuxt-community/apollo-module), but it does not support Apollo 3. I manually configured Apollo, everything works except for a cache error in SSR. Can the hook library affect the cache result?

**Comment by brainkim** [comment] 2021-09-29 18:38
@benjamn This might have to do with the way we serialize variables in our SSR stuff, though if the user is using Vue.js, I’m not sure how relevant that is (https://github.com/apollographql/apollo-client/blob/main/src/react/ssr/RenderPromises.ts#L105).

**Comment by negezor** [comment] 2021-09-29 19:36
@brainkim I serialize the cache like this
```ts
JSON.stringify(cache.extract());
```

**Comment by bignimbus** [comment] 2022-12-05 20:54
Somehow the linked PR didn't automatically close this so I'll do it manually :) let us know if you need more support here!

**Closed by bignimbus** 2022-12-05 20:54 UTC
Labels: 🏓 awaiting-contributor-response, 💸 caching, 🥓 Server-side rendering (SSR)
