### ISSUE TITLE
GraphQL error results in infinite retries which crashes the browser

### ISSUE THREAD

**Issue by michelalbers** [apollographql/apollo-client#3856] opened 2018-08-27 10:13 UTC
**Intended outcome:**

When an error during a graphQL query inside a <Query /> component occurs it should display the error.

**Actual outcome:**

It tries to refetch with very short intervals which will crash the browser.

**How to reproduce the issue:**

Create a standard Apollo Client with ```apollo-boost``` and write an erroneous query which is used inside a <Query /> component. Default fetch policies used.

**Versions**

  System:
    OS: macOS High Sierra 10.13.5
  Binaries:
    Node: 9.11.1 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0
    Safari: 11.1.1
  npmPackages:
    apollo-cache-inmemory: ^1.2.9 => 1.2.9 
    apollo-client: ^2.4.1 => 2.4.1 
    apollo-link-error: ^1.1.0 => 1.1.0 
    apollo-upload-client: ^8.1.0 => 8.1.0 
    react-apollo: ^2.1.11 => 2.1.11

**Comment by hwillson** [comment] 2018-08-27 10:18
Any chance you could provide a small runnable reproduction that shows this happening?

**Comment by uuau99999** [comment] 2018-08-28 03:33
Same issue on react-apollo 2.1.11. Instead I use the graphql hoc to wrap the target component. It seems that it will automatically retry the query when receiving an error.

**Comment by superbull** [comment] 2018-08-30 23:13
I also meet the same issue, and found that it may not caused by apollo client. It might caused by react.

Here is my code:

```jsx
<Query query={QUERY_INFO}>
  {({ loading, error, data }) => {
    if (loading) {
      return <div>Loading</div>;
    }

    return <div>{data.info}</div>;
  }}
</Query>
```

If the graphql server throws an error, the variable `data` will be `undefined`, this will throws an error:
```
Uncaught TypeError: Cannot read property 'info' of undefined
```

After that there will be another error:
```
The above error occurred in the <Query> component:
...
...
React will try to recreate this component tree from scratch using the error boundary you provided, App.
```

So React will try to recreate the `Query` component, so the query will run again and again.

The quick solution is to add an error check to the code:
```jsx
<Query query={QUERY_INFO}>
  {({ loading, error, data }) => {
    if (loading) {
      return <div>Loading</div>;
    }
    
    if (error) {
        return <div>error</div>
    }
    return <div>{data.info}</div>;
  }}
</Query>
```

**Comment by michelalbers** [comment] 2018-09-03 14:47
@superbull Thank you so much for this hint! I added a ```componentDidCatch``` statement and logged the error. Turns out I used smth like:

```JavaScript
({error, data, loading}) => (
  If (error) return <span>Sorry, {error} occured</span>
)
```

while ```error``` is an object which results in a react expection which tells you to not use objects. The correct way to solve this is to use:

```JavaScript
({error, data, loading}) => (
  If (error) return <span>Sorry, {error.message} occured</span>
)
```

Notice the **.message** there.

Thank you! This can be closed.

**Comment by anymost** [comment] 2018-09-07 02:56
@superbull The same issue I met， the only thing need to do is ensuring data is not null

**Comment by james-ff** [comment] 2018-09-07 13:45
Have seen this since migrating from `graphql(QUERY_NAME, { name: 'queryName' })`to the component version that sits in the render function of a component:

```js
<Query query={QUERY_NAME}>
{({loading, error, data}) => {
  return // Render here
}
</Query>
```

The issue is exaclty as @superbull identifies. The Query component too easily gets into an infinite render loop, which can be hard to pin down because the console locks up with all the errors. For me I found it when not rendering an error message for an error. 

I also see it when trying to conditionally render a component (I call PreRender, which handles loading and error messages in one place) that is generated by a function (I'm guessing it is the fact that a function is used in the render that causes it to loop).

```js
if (Utils.shouldPreRender({ loading, error, data, valid: (data.EXPECTED_RESULT != null) })) {
  return <PreRender {/* props here */} />
}
```

```js
const PreRender = ({ loading, error, data, valid = false, notFound = 'Entity' }) => {
  console.log(loading, error, data)
  if (loading) { return <Loading /> }
  if (error) { return <Error error={error} /> }
  if (data == null || !valid) { return <NotFound notFound={notFound} /> }
  return null
}
```

Currently I have to repeat this code for every Query component...

```js
if (loading) { return <Loading /> }
if (error) { return <Error error={error} /> }
if (data == null || data.EXPECTED_RESULT == null) { return <NotFound notFound={`entity`} /> }
```

Not sure what a solution might look like, but stopping infinite renders would be great.

**Comment by danilobuerger** [comment] 2019-01-29 18:42
Closing as per OP request:
> Thank you! This can be closed.

**Closed by danilobuerger** 2019-01-29 18:42 UTC
Labels: reproduction-needed
