### ISSUE TITLE
Regression in BatchHttpLink with v3.7.0: queries hang and are not issued on network requests

### ISSUE THREAD

**Issue by vieira** [apollographql/apollo-client#10205] opened 2022-10-18 16:55 UTC
**Intended outcome:**
All pending queries should be dispatched to the network.

**Actual outcome:**
Queries are not dispatched to the network, they just hang, `loading` returned from `useQuery` returns true indefinitely. This issue first appeared in v3.6.x (#9690) and was fixed in v3.6.7. The issue does NOT occur in v3.6.9 and v3.6.10 but occurs in v3.7.0.

Not sure if the regression was introduced when backporting (#9807) or by some other change.

**How to reproduce the issue:**
Using BatchHttpLink as a terminating link and having a page with a buch of queries should exhibit the issue.

**Versions**
v3.7.0

(Note: this has previously affected v3.6.x prior to v3.6.7. Can confirm it does not occur with v3.6.9 and v3.6.10)

**Comment by oddeirik** [comment] 2022-11-01 14:52
Seeing the same thing as vieira: using the BatchHTTPLink in 3.7.0 or 3.7.1 makes some of the queries never execute and they are left in a loading state.

When reverting to 3.6.9 (previously used version), or removing the usage of the BatchHTTPLink, it works again.

**Comment by EvHaus** [comment] 2022-11-17 17:28
We just ran into the same issue ourselves. A few observations:

- It seems to only occur with many parallel requests happening. With a default batch size of 10 we would see certain requests simply fail to get called. It's like Apollo doesn't fire them at all. Setting the batch size to something smaller (like 3) would ensure all requests go through.
- The issue was present on 3.7.1 in addition to 3.7.0. Rolling back to 3.6.10 made the issue go away.

**Comment by vpotapchuk** [comment] 2023-01-13 11:51
We also faced the issue. After some investigation we found out that this happens when we don't send the same `context` (in our case we send context in one case, but not the other).
Very easy to reproduce, I think this minimal repro would be enough if only the BatchHttpLink were used:
https://codesandbox.io/s/sharp-sound-1d0ojj?file=/src/App.js:618-914

It's still present in 3.7.3

**Comment by vpotapchuk** [comment] 2023-01-13 12:08
@bignimbus will my extra info above speed up resolving this?

**Comment by bignimbus** [comment] 2023-01-25 19:16
Hi @vpotapchuk 👋🏻  the linked PR https://github.com/apollographql/apollo-client/pull/10408 is almost ready to ship.  I appreciate the link but since it doesn't demonstrate the problem as-is we'll need to modify it in order to do a manual test of the PR, which is fine.  Are you able to pull the branch in the PR and test in your app locally?

**Closed** 2023-01-26 17:34 UTC
Labels: :rose: has-reproduction, 🔍 investigate, 🏓 awaiting-team-response

**Comment by bignimbus** [comment] 2023-01-26 17:36
Hi all, the fix should go out in the next patch (`3.7.6`).  If you get a chance to validate against our `main` branch in the meantime, that would be great!

**Comment by modi98** [comment] 2023-01-31 05:37
Hey, I just confirmed on your latest changes, this solved the issue, thanks

**Comment by vpotapchuk** [comment] 2023-02-15 12:05
Hey, I also just tested the 3.7.7, everything works correctly for us now! Great job!

@bignimbus Sorry for not answering earlier, I realized I have some problems with github notifications...
