### ISSUE TITLE
onError is not called when using testing-library/react-hooks

### ISSUE THREAD

**Issue by brandon-leapyear** [apollographql/apollo-client#6137] opened 2020-04-10 21:11 UTC
**Intended outcome:**
I am writing a custom hook using Apollo React hooks, setting onError to do `console.error` if an error occurs, but otherwise only dealing with successful data. I then want to test the error state of the custom hook using `renderHook` from `@testing-library/react-hooks` and `MockedProvider`. I would expect `onError` to be called if an error occurs, with the same value as the `error` key in the `useQuery` result.

**Actual outcome:**
`onError` is never actually called

**How to reproduce the issue:**
The following jest test fails on the last assertion on `onErrorData`
```tsx
import { useQuery } from '@apollo/react-hooks'
import { MockedProvider } from '@apollo/react-testing'
import { act, renderHook } from '@testing-library/react-hooks'
import gql from 'graphql-tag'
import _ from 'lodash'
import React, { useState } from 'react'

type MyQuery = {
  name: string
}

const MyQueryDocument = gql`
  query {
    name
  }
`

const useFoo = () => {
  const [onErrorData, setOnErrorData] = useState()
  const { data, error } = useQuery<MyQuery>(MyQueryDocument, {
    onError: setOnErrorData
  })

  return { data, error, onErrorData }
}

test('onError should be called', async () => {
  const mocks = [
    {
      request: {
        query: MyQueryDocument,
      },
      error: new Error('this is an error'),
    },
  ]

  const { result } = renderHook(() => useFoo(), {
    wrapper: ({ children }) => (
      <MockedProvider mocks={mocks}>
        <>{children}</>
      </MockedProvider>
    )
  })

  await act(() => new Promise(_.defer))

  expect(result.current.data).toBeUndefined()
  expect(result.current.error?.message).toBe('Network error: this is an error')
  expect(result.current.onErrorData?.message).toBe('Network error: this is an error')
})
```

**Versions**
```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/leapyear/lyalpha/node_modules/.bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 72.0.2
    Safari: 13.1
```

**Comment by waldinho** [comment] 2020-05-29 01:27
i am facing a similar issue, did you manage to find a fix?

**Comment by brandon-leapyear** [comment] 2020-06-01 16:09
No, we just have a skipped test with a link to this issue :(

**Comment by adnanfajlur** [comment] 2020-06-09 09:38
same issue here

**Comment by afonsoduarte** [comment] 2020-07-08 13:58
I can also reproduce this

**Comment by victor-guoyu** [comment] 2020-07-22 16:27
+1

**Comment by BogdanAndronchik** [comment] 2020-09-23 11:32
+1

**Comment by ardok** [comment] 2020-11-12 00:10
Spent the last 3 hours ripping my hair off and finally found this.
Wondering why it keeps going to `onCompleted` callback instead of `onError`.

Any updates on this?

**Comment by ahmadelgabrii** [comment] 2020-12-14 18:17
any updates on this?

**Comment by emil45** [comment] 2021-04-22 14:47
any update?

This is not working also, it's not triggering the `onError` of `useQuery`

```
jest.spyOn(axios, 'get').mockImplementation(() => {
		return Promise.reject('error');
	});
```

**Comment by ashfahan** [comment] 2021-08-08 01:58
solution found https://github.com/tannerlinsley/react-query/discussions/2196#discussioncomment-659468

**Comment by brandonchinn178** [comment] 2021-08-08 02:26
> solution found [tannerlinsley/react-query#2196 (comment)](https://github.com/tannerlinsley/react-query/discussions/2196#discussioncomment-659468)

Does apollo-client also have retries? I dont recall that being a default configuration

**Comment by ashfahan** [comment] 2021-08-08 02:36
> > solution found [tannerlinsley/react-query#2196 (comment)](https://github.com/tannerlinsley/react-query/discussions/2196#discussioncomment-659468)
> 
> Does apollo-client also have retries? I dont recall that being a default configuration

sorry i thought i was on react-query repo 🤦🏻‍♂️ although as far i have looked into apollo right now its looks so similar to how react query works in terms of operations, i must have some algo for retry api call as react-query have in it

**Comment by jonathanfilbert** [comment] 2022-05-23 10:08
For everyone still looking for an answer. This works for me. 
**Make sure to NOT include the error inside of the result key in the mock**.

So instead of writing:
```
export const mock = (errorMessage: string) => {
  return {
    request: {
      ...
    },
result: {
    errors: [new GraphQLError(errorMessage)],
},
  };
};
```

Turn it to:
```
export const mock = (errorMessage: string) => {
  return {
    request: {
      ...
    },
    errors: [new GraphQLError(errorMessage)],
  };
};
```

Then, and only then, your `onError` callback will get invoked during the tests.

Cheers! 🥳

**Comment by zebapy** [comment] 2022-08-12 17:13
☝️ ☝️ ☝️  **This may not be ideal for your test cases**.

You're setting the network response error when some may want to test _graphql_ errors

It results in an error like:
```
graphQLErrors: [],
networkError: GraphQLError [Object] {
  message: 'my error message',
  extensions: [Object]
},
```

This makes my implementation for onError fail because I want to handle graphql errors, not network errors

```ts

  function onError(error?: ApolloError) {

    if (!error?.graphQLErrors.length) {
      return;
    }

    const err = error.graphQLErrors[0];

    if (err.extensions?.code === "CONFLICT") {
      setErrors(...);
    } 

    dispatchError(error);
  }

```

**Comment by alessbell** [comment] 2023-03-08 18:31
That's a good call out, @zebapy -- here's an example of a test that calls `onError` when a GraphQL error is returned from our Apollo Client test suite: https://github.com/apollographql/apollo-client/blob/router-subs/src/react/hooks/__tests__/useQuery.test.tsx#L1847:L1888

Since the original issue was opened several years ago and this seems to no longer be a problem, I'm going to close this out. Thanks!

**Closed by alessbell** 2023-03-08 18:31 UTC
Labels: ⚛️ React-related
