### ISSUE TITLE
Query doesn't update when data changes

### ISSUE THREAD

**Issue by ashtonsix** [apollographql/apollo-client#3747] opened 2018-07-27 03:49 UTC
**Context:**

Hi, one of my endpoints is very slow; so I made the relevant resolver return early; on the client I poll for a subset of the data which I know will soon change.

```js
const INSTANCE_LIST = gql`
  query {
    viewer {
      id
      instances {
        id
        createdAt
        instanceType
        prettyName
        hashCode
        url
        color
        primaryStorageSize
        startupStage
        startupDnsComplete
      }
    }
  }
`

const STARTUP_STAGE_ONLY = gql`
  query {
    viewer {
      instances {
        id
        startupStage
        startupDnsComplete
      }
    }
  }
`

const InstanceList = () => (
  <Query query={INSTANCE_LIST}>
    {({data, refetch}) => {
      const instances = data?.viewer?.instances || []
      const inFlux = instances.some(i => {
        return i.startupStage !== 'done' || !i.startupDnsComplete
      })

      return (
        <>
          {inFlux && (
            <Query query={STARTUP_STAGE_ONLY} pollInterval={1500}>
              {() => null}
            </Query>
          )}
          {instances
            .slice()
            .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
            .map((instance, index) => (
              <OneInstance
                key={instance.id}
                instance={instance}
                index={index}
              />
            ))}
        </>
      )
    }}
  </Query>
)
```

**Intended outcome:**

When the data changes, the parent `<Query />` component will re-render and have up-to-date information.

**Actual outcome:**

Although the client cache updates, the parent `<Query />` component keeps rendering stale data, even after remounting.

**How to reproduce the issue:**

It'll take me a little time to put an example together, which I can do. But it'd be great to know if this is already a known issue before investing the time.

**Versions**

```
  System:
    OS: Linux 4.15 Ubuntu 16.04.4 LTS (Xenial Xerus)
  Binaries:
    Node: 10.1.0 - ~/.nvm/versions/node/v10.1.0/bin/node
    npm: 6.1.0 - ~/.nvm/versions/node/v10.1.0/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0.1
  npmPackages:
    apollo-server: 2.0.0-rc.10 => 2.0.0-rc.10 
    apollo-server-express: 2.0.0-rc.10 => 2.0.0-rc.10
```

**Comment by wmertens** [comment] 2018-07-27 06:06
Just a hunch - can you try naming the queries, with different names? `query all {` vs `query bootstrap {`

**Comment by ashtonsix** [comment] 2018-07-27 16:53
Woah, named queries and devtools? You're blowing my mind with this whole new world of stuff I didn't know about. :heart_eyes:

The devtools were reporting "There is a network error: {"type":"WriteError"}", but without any details. The error seemed to come from [here](https://github.com/apollographql/apollo-client/blob/e0ba90671e241184f12ce86370e0e3d84bc73552/packages/apollo-cache-inmemory/src/writeToStore.ts#L42), so I opened up the file inside node_modules, added a console.log and tried again. Here's the error I got:

![screenshot of error](https://user-images.githubusercontent.com/6740947/43334566-9632dea8-91c5-11e8-997a-8a826992eb73.png)

With this guidance I realised `id` was missing from the selection set for `viewer`, added it & the issue was resolved!

The problem then, is this error wasn't very visible; and once found, there weren't enough details to help diagnose the issue without editing node_modules.

**Comment by elie222** [comment] 2019-01-20 23:34
These silent errors should definitely be made more clear. Only found this through Apollo dev tools and still only seeing the generic error message there too.

**Comment by elie222** [comment] 2019-01-20 23:55
My issues seems to have been calling this:

```gql
	user {
		name
	}
```

Having previously called this:

```gql
      user {
        _id
        name
        username
      }
```

Using the same user fields in each place makes the error go away (or commenting one of them out).

Not actually sure what the issue is, but it gave me the client WriteError

**Comment by corysimmons** [comment] 2019-05-15 18:36
```
const STARTUP_STAGE_ONLY = gql`
  query {
    viewer {
      instances {
        id
        startupStage
        startupDnsComplete
      }
    }
  }
`
```

Try adding an `id` to `viewer` so Apollo can differentiate `viewers` that are in the store? This worked for me anyway.

**Comment by marcelkooi** [comment] 2020-05-14 18:36
Ran into a similar issue, had to add an `id` field within the query. Definitely would have been helpful to have a warning or something mentioned in the docs since this isn't an obvious solution to the problem IMO

**Comment by hwillson** [comment] 2021-04-27 14:02
Closing as this isn't a bug (if anyone thinks we should handle warnings differently to help make troubleshooting easier, please open a [feature request ](https://github.com/apollographql/apollo-feature-requests)). Thanks!

**Closed by hwillson** 2021-04-27 14:02 UTC
