### ISSUE TITLE
Add error message when reducer results don't match query results

### ISSUE THREAD

**Issue by Siyfion** [apollographql/apollo-client#1273] opened 2017-02-08 13:00 UTC
I stumbled on this issue the other day and it took me a while to realise what was going wrong.

In the example below `insertCategory` is a mutation which returns a new category, however one field (`name`) has been omitted (by mistake).

As a result, the reducer that handles the `insertCategory` action tries to merge the new category into the store with the results of the query. Running the `update` code manually shows the resulting  array as having the new category at the front, however when the `dataQuery` `props` function is next triggered, *all* the data is suddenly gone.

Clearly the error is due to the missing field, but no error message was generated at all, making it a *very* tricky bug to track down. 

```jsx
const dataQuery = gql`
  query getData {
    productCategories {
      _id
      siteId
      notSaved
      name
    }
  }
`;

const insertCategory = gql`
  mutation insertCategory {
    insertCategory {
      _id
      siteId
      notSaved
    }
  }
`;

const CategoriesSectionContainer = compose(
  graphql(dataQuery, {
    props: ({ data }) => {
      if (data.loading) return { loading: true };
      if (data.error) return { error: data.error };
      return {
        categories: data.productCategories,
      };
    },
    options: {
      reducer: (previousResult, action) => {
        if (action.type === 'APOLLO_MUTATION_RESULT' && action.operationName === 'insertCategory') {
          const insertedCategory = action.result.data.insertCategory;
          return update(previousResult, {
            productCategories: {
              $unshift: [insertedCategory],
            },
          });
        }
        return previousResult;
      },
    },
  }),
  graphql(insertCategory, {
    props: ({ mutate }) => ({
      insertCategory: () => mutate({ variables: {} }),
    }),
  }),
)(CategoriesSection);
```

**Comment by helfer** [comment] 2017-02-09 01:06
Thanks @Siyfion. I think the main thing we need to do is improve the error messages for when the data returned by updateQueries or reducer does not match the shape required. I think there might be some work we have to do with fragments there.

**Comment by Siyfion** [comment] 2017-02-09 13:55
Agreed, it was undoubtedly my code that had the bug... But the silently-failing nature of it caused a large headache in terms of trying to track it down!

**Comment by HriBB** [comment] 2017-02-09 14:34
@Siyfion thanks for the heads up. @helfer any idea how to debug this in the meantime?

**Comment by helfer** [comment] 2017-02-10 01:05
@Siyfion I think we're still not 100% sure where the error gets swallowed, because we do have some tests specifically for that. The best way to help us fix this would be if you could make a PR with a failing test case that reproduces the thing you're seeing in your app. Could you do that? 🙂

**Comment by Siyfion** [comment] 2017-02-14 16:26
Easiest way I can find to reproduce this is to modify the GitHunt-React example in the following way:

Remove the `createdAt` field from the mutation results in `SubmitComment.graphql`.
```graphql
mutation submitComment($repoFullName: String!, $commentContent: String!) {
  submitComment(repoFullName: $repoFullName, commentContent: $commentContent) {
    ...CommentsPageComment
  }
}

fragment CommentsPageComment on Comment {
  id
  postedBy {
    login
    html_url
  }
  content
}
```

And replace `CommentsPage.js` with this version without the subscription (for simplicity).
```js
import React from 'react';
import { graphql } from 'react-apollo';
import update from 'immutability-helper';
import { filter } from 'graphql-anywhere';

import RepoInfo from '../components/RepoInfo';
import Comment from '../components/Comment';

import SUBMIT_COMMENT_MUTATION from '../graphql/SubmitComment.graphql';
import COMMENT_QUERY from '../graphql/Comment.graphql';

// helper function checks for duplicate comments, which we receive because we
// get subscription updates for our own comments as well.
// TODO it's pretty inefficient to scan all the comments every time.
// maybe only scan the first 10, or up to a certain timestamp
function isDuplicateComment(newComment, existingComments) {
  return newComment.id !== null && existingComments.some(comment => newComment.id === comment.id);
}

class CommentsPage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      errors: false,
      canSubmit: true,
    };
    this.submitForm = this.submitForm.bind(this);
  }

  submitForm(event) {
    event.preventDefault();
    const { entry, currentUser, submit } = this.props;

    const repoFullName = entry.repository.full_name;
    const commentContent = this.newCommentInput.value;

    if (commentContent) {
      this.setState({ canSubmit: false });

      submit({
        repoFullName,
        commentContent,
        currentUser,
      }).then((res) => {
        this.setState({ canSubmit: true });

        if (!res.errors) {
          this.newCommentInput.value = '';
        } else {
          this.setState({ errors: res.errors });
        }
      });
    }
  }

  render() {
    const { loading, currentUser, entry } = this.props;
    const { errors, canSubmit } = this.state;

    if (loading) {
      return <div>Loading...</div>;
    }

    const repository = entry.repository;

    return (
      <div>
        <div>
          <h1>Comments for <a href={repository.html_url}>{repository.full_name}</a></h1>
          <RepoInfo entry={filter(RepoInfo.fragments.entry, entry)} />
          {currentUser ? <form onSubmit={this.submitForm}>
            <div className="form-group">

              <input
                type="text"
                className="form-control"
                ref={input => (this.newCommentInput = input)}
                placeholder="Write your comment here!"
              />
            </div>

            {errors && (
              <div className="alert alert-danger" role="alert">
                {errors[0].message}
              </div>
            )}

            <button type="submit" disabled={!canSubmit} className="btn btn-primary">
              Submit
            </button>
          </form> : <div><em>Log in to comment.</em></div>}
        </div>
        <br />
        <div>
          <div>
            {entry.comments.map(comment => (
              <Comment
                key={comment.postedBy.login + comment.createdAt + repository.full_name}
                username={comment.postedBy.login}
                content={comment.content}
                createdAt={comment.createdAt}
                userUrl={comment.postedBy.html_url}
              />
            ))}
          </div>
        </div>
      </div>
    );
  }
}

CommentsPage.propTypes = {
  loading: React.PropTypes.bool.isRequired,
  currentUser: React.PropTypes.shape({
    login: React.PropTypes.string,
  }),
  entry: React.PropTypes.shape({
    id: React.PropTypes.number,
    comments: React.PropTypes.arrayOf(
      React.PropTypes.shape({
        postedBy: React.PropTypes.shape({
          login: React.PropTypes.string.isRequired,
        }),
        createdAt: React.PropTypes.number,
        content: React.PropTypes.string.isRequired,
      })
    ),
    repository: React.PropTypes.shape({
      full_name: React.PropTypes.string,
      html_url: React.PropTypes.string,
    }),
  }),
  submit: React.PropTypes.func.isRequired,
};

const withMutations = graphql(SUBMIT_COMMENT_MUTATION, {
  props: ({ ownProps, mutate }) => ({
    submit: ({ repoFullName, commentContent }) =>
      mutate({
        variables: { repoFullName, commentContent },
        updateQueries: {
          Comment: (prev, { mutationResult }) => {
            const newComment = mutationResult.data.submitComment;
            if (isDuplicateComment(newComment, prev.entry.comments)) {
              return prev;
            }
            return update(prev, {
              entry: {
                comments: {
                  $unshift: [newComment],
                },
              },
            });
          },
        },
      }),
  }),
});

const withData = graphql(COMMENT_QUERY, {
  options: ({ params }) => ({
    variables: { repoName: `${params.org}/${params.repoName}` },
  }),
  props: ({ data: { loading, currentUser, entry } }) => ({
    loading, currentUser, entry,
  }),
});

export default withData(withMutations(CommentsPage));
```

**Comment by cesarsolorzano** [comment] 2017-04-20 18:36
Closing in favor of #1611

**Closed by cesarsolorzano** 2017-04-20 18:36 UTC
Labels: help wanted, warning
