### ISSUE TITLE
Apollo Client Beta 3 : @react/react-ssr causing error , ModuleNotFoundError: Module not found: Error: Can't resolve 'apollo-client' in 'F:\BootstrapNext\bootnext\node_modules\@apollo\react-hooks\lib'

### ISSUE THREAD

**Issue by panindra2017** [apollographql/apollo-client#6241] opened 2020-05-05 03:57 UTC
I am working Apllo client beta 3 withNext js and using ssr mode but i am not able to get success as i am getting above error :
and my ERROR : [ error ] ./node_modules
/@apollo
/react-hooks/lib/react-hooks.esm.js Module not found: Can't resolve 'apollo-client' in 'F:\BootstrapNext\bootnext\node_modules\
@apollo
\react-hooks\lib' ModuleNotFoundError: Module not found: Error: Can't resolve 'apollo-client' in 'F:\BootstrapNext\bootnext\node_modules\
@apollo
\react-hooks\lib' at F:\BootstrapNext\bootnext\node_modules\webpack\lib\Compilation.js:925:10 at F:\BootstrapNext\bootnext\node_modules\webpack\lib\NormalModuleFactory.js:401:22 at F:\BootstrapNext\bootnext\node_modules\webpack\lib\NormalModuleFactory.js:130:21 at F:\BootstrapNext\bootnext\node_modules\webpack\lib\NormalModuleFactory.js:224:22 at F:\BootstrapNext\bootnext\node_modules\neo-async\async.js:2830:7 at F:\BootstrapNext\bootnext\node_modules\neo-async\async.js:6877:13 at F:\BootstrapNext\bootnext\node_modules\webpack\lib\NormalModuleFactory.js:214:25 at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\Resolver.js:213:14 at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\Resolver.js:285:5 at eval (eval at create (F:\BootstrapNext\bootnext\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1) at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7 at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\Resolver.js:285:5 at eval (eval at create (F:\BootstrapNext\bootnext\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1) at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\Resolver.js:285:5 at eval (eval at create (F:\BootstrapNext\bootnext\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1) at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43 ModuleNotFoundError: Module not found: Error: Can't resolve 'apollo-client' in 'F:\BootstrapNext\bootnext\node_modules\
@apollo
\react-hooks\lib' at F:\BootstrapNext\bootnext\node_modules\webpack\lib\Compilation.js:925:10 at F:\BootstrapNext\bootnext\node_modules\webpack\lib\NormalModuleFactory.js:401:22 at F:\BootstrapNext\bootnext\node_modules\webpack\lib\NormalModuleFactory.js:130:21 at F:\BootstrapNext\bootnext\node_modules\webpack\lib\NormalModuleFactory.js:224:22 at F:\BootstrapNext\bootnext\node_modules\neo-async\async.js:2830:7 at F:\BootstrapNext\bootnext\node_modules\neo-async\async.js:6877:13 at F:\BootstrapNext\bootnext\node_modules\webpack\lib\NormalModuleFactory.js:214:25 at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\Resolver.js:213:14 at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\Resolver.js:285:5 at eval (eval at create (F:\BootstrapNext\bootnext\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1) at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7 at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\Resolver.js:285:5 at eval (eval at create (F:\BootstrapNext\bootnext\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1) at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\Resolver.js:285:5 at eval (eval at create (F:\BootstrapNext\bootnext\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1) at F:\BootstrapNext\bootnext\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43 [ info ] bundled successfully, waiting for typecheck results... [ ready ] compiled successfully - ready on http://localhost:3000 and
Warning while installing 
@apollo
/reat-ssr :
warning " > 
@apollo
/client@3.0.0-beta.44" has incorrect peer dependency "graphql@^14.5.4". warning "
@apollo
/client > graphql-tag@2.10.3" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0". warning "
@apollo
/react-ssr > 
@apollo
/react-common@3.1.4" has unmet peer dependency "apollo-client@^2.6.4". warning "
@apollo
/react-ssr > 
@apollo
/react-common@3.1.4" has unmet peer dependency "apollo-utilities@^1.3.2". warning "
@apollo
/react-ssr > 
@apollo
/react-common@3.1.4" has incorrect peer dependency "graphql@^14.3.1". warning "
@apollo
/react-ssr > 
@apollo
/react-hooks@3.1.5" has unmet peer dependency "apollo-client@^2.6.4". warning "
@apollo
/react-ssr > 
@apollo
/react-hooks@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
REACT HOOS SSR ( "
@apollo
/react-ssr": "^3.1.5",) Trying to call dependency "apollo-client@^2.6.4". instead of 
@apollo
/client "
@apollo
/client": "^3.0.0-beta.44", how to fix it

**Comment by 3nvi** [comment] 2020-05-06 09:04
Please follow the template next time, since it's very illegible. 

Why don't you let us know what you installed? Did you do `npm i @apollo/client` or what? Where did you encounter that issue? What did you try to import? 

The information you give is a bit generic, we need to know steps to potentially reproduce it

**Comment by miller-productions** [comment] 2020-05-13 10:37
Possibly a dupe of #5808

**Comment by hwillson** [comment] 2020-05-21 12:30
This does sound like a dupe of https://github.com/apollographql/apollo-client/issues/5808 - thanks @miller-productions! 

@panindra2017 if https://github.com/apollographql/apollo-client/issues/5808 doesn't help, let us know. Thanks!

**Closed by hwillson** 2020-05-21 12:30 UTC
