### ISSUE TITLE
"Warning: useLayoutEffect does nothing on the server" appeared since updating to @latest version.

### ISSUE THREAD

**Issue by zakariamofaddel** [apollographql/apollo-client#8124] opened 2021-05-04 07:02 UTC
***If reverting @apollo/client to @3.3.14, warning disappears**
I'm extensively using the getStaticProps method by nextJS in my application and everything was running smoothly, but once I did an update of all the packages, I started seeing this annoying warning.
I reverted to a previous commit and updated packages one by one, thinking it was a material-ui problem. But the warning appeared only after updating @apollo/client.

**Intended outcome:**
Updating packages, from 3.3.14 to @3.3.16.

**Actual outcome:**
This is the warning I started getting after the update:
![Screenshot 2021-05-04 at 09 54 05](https://user-images.githubusercontent.com/66852346/116969491-08205600-acbf-11eb-8e22-f2d8146d407e.png)

And I noticed mismatches started appearing in the console. This is a rehydration problem probably, but it wasn't there before updating...
example mismatch:
![Screenshot 2021-05-04 at 14 38 43](https://user-images.githubusercontent.com/66852346/116998287-a5db4b80-ace6-11eb-9efb-e96ad210cc95.png)

My package.json file:
![Screenshot 2021-05-04 at 09 54 33](https://user-images.githubusercontent.com/66852346/116969534-1b332600-acbf-11eb-9b32-d3d098254932.png)

My Apollo Initialization (from zeit/nextjs apollo example) (The APOLLO_STATE_PROP_NAME variable is just a string = "__APOLLO_STATE__"):
![Screenshot 2021-05-04 at 09 55 50](https://user-images.githubusercontent.com/66852346/116969559-25edbb00-acbf-11eb-88c6-520d2f462865.png)

**Versions**
Run the following command in your project directory, and paste its (automatically copied to clipboard) results here:

`npx envinfo@latest --preset apollo --clipboard`:

![Screenshot 2021-05-04 at 09 59 24](https://user-images.githubusercontent.com/66852346/116969737-6e0cdd80-acbf-11eb-8fa7-b30922e57703.png)

All the additional packages are not used, I'm only using @apollo/client at the moment.

**Comment by benjamn** [comment] 2021-05-04 13:24
@zakariamofaddel Thanks for reporting this! Assigning to @brainkim since this looks like a consequence of #8022.

**Comment by brainkim** [comment] 2021-05-04 14:07
@zakariamofaddel Sorry about this! I haven’t used React in a while so I jumped on the opportunity for a synchronous effect hook to fix some other weird reactiveVar issues.

> And I noticed mismatches started appearing in the console. This is a rehydration problem probably, but it wasn't there before updating...

Is this something that only appears when you switch versions or could it possibly due to code changes you made as well?

**Comment by zakariamofaddel** [comment] 2021-05-04 14:31
No worries @brainkim !

> Is this something that only appears when you switch versions or could it possibly due to code changes you made as well?
I have developed for the past 6 hours, after reverting to @3.3.14, and I haven't encountered any of the issues previously mentioned. No warnings, no mismatches.

**Comment by brainkim** [comment] 2021-05-04 19:35
@zakariamofaddel I’m doing some testing and it feels as though the only reason the new `useLayoutEffect()`-backed `useReactiveVar()` might be causing client/server mismatches is because you’re calling the reactive var during rendering, which is a React no-no. Of course, I could be wrong about this, but that means that even if we squelch the `useLayoutEffect` warnings, you might continue to have client/server mismatch errors. We’ll try to have a fix which squashes the warnings soon, but in the meantime, 1. can you make sure you’re not calling reactive variables in the render function? and 2. can you create a small reproduction for the client/server mismatch if this isn’t the case?

**Closed** 2021-05-04 21:13 UTC
Labels: ⚛️ React-related, 📟 regression

**Comment by zakariamofaddel** [comment] 2021-05-05 06:50
Thank you for your speed and work, very much appreciated!
I am using a lot the useReactiveVar hook, but I'm not sure at this point if I am doing it the right way, since I'm using functional components, and as [this React article](https://www.robinwieruch.de/react-function-component) states the whole function body is what the render function was in class components:
>Note: If you are familiar with React Class Components, you may have noticed that a Functional Component is a React Component without render function. Everything defined in the function's body is the render function which returns JSX in the end.

I'm always using the hook at the top of my functional components, this way:
![Screenshot 2021-05-05 at 09 44 29](https://user-images.githubusercontent.com/66852346/117105413-9f9cac00-ad86-11eb-9695-926010393a2a.png)

If I am doing this the correct way and it was not the cause of the mismatch, I will try to create a reproduction repo as soon as possible!

**Comment by Mihai-github** [comment] 2021-09-01 08:42
Hi, 
   Any updates on this issue? 
   I am facing the same problem with the warnings and I cannot make anything to stop them and I am not sure if this may be an issue that can affect my project or not 

This is my implementation (it's a bit different from the one that is above):

import {ApolloClient, InMemoryCache, HttpLink, from} from '@apollo/client';
import {onError} from 'apollo-link-error';
import {useMemo} from 'react';
import {NotificationManager} from 'react-notifications';

const errorLink: any = onError(({graphQLErrors, networkError}: any) => {
    if (graphQLErrors) {
        graphQLErrors.forEach(({message, locations, path}: any) =>
            console.log(
                `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
            ),
        );
    }
    if (networkError) {
        NotificationManager.error(
            'We could not connect to servers backend',
            `Connection problems`,
            3000,
        );
        console.log(networkError.errors);
    }
});

const httpLink = new HttpLink({
    uri: process.env.APP_BACKEND_URI,
});

const link = from([errorLink, httpLink]);

let apolloClient: any;

export function createApolloClient() {
    return new ApolloClient({
        ssrMode: typeof window === 'undefined', // set to true for SSR
        cache: new InMemoryCache(),
        link,
        connectToDevTools: true,
    });
}

export function initializeApollo(initialState = null) {
    const _apolloClient = apolloClient ?? createApolloClient();

    // If your page has Next.js data fetching methods that use Apollo Client,
    // the initial state gets hydrated here
    if (initialState) {
        // Get existing cache, loaded during client side data fetching
        const existingCache = _apolloClient.extract();

        // Restore the cache using the data passed from
        // getStaticProps/getServerSideProps combined with the existing cached data
        _apolloClient.cache.restore({...existingCache, ...initialState});
    }

    // For SSG and SSR always create a new Apollo Client
    if (typeof window === 'undefined') return _apolloClient;

    // Create the Apollo Client once in the client
    if (!apolloClient) apolloClient = _apolloClient;
    return _apolloClient;
}

export function useApollo(initialState) {
    const store = useMemo(() => initializeApollo(initialState), [initialState]);
    return store;
}

export * from './queries';

I Hope will be solved soon or find a temp solution at least.
