### ISSUE TITLE
jest test hanging with two useSubscriptions

### ISSUE THREAD

**Issue by gderidder** [apollographql/apollo-client#7139] opened 2020-10-09 09:38 UTC
Check this issue:
https://spectrum.chat/apollo/react-apollo/jest-test-hanging-with-two-usesubscriptions~ec0a1a79-71e3-4b5f-8ef4-bc3943046c73

I now experience the same issue, so is this a bug?

**Intended outcome:**
Jest test reporting success or error.

**Actual outcome:**
Jest test is hanging / keeps running.

**How to reproduce the issue:**
I have a component which has two useSubscription hooks in it. If I comment out either of them the test passes, doesn't matter which one. But if both are present the test just runs forever (no failure ... just runs and runs).

The component works correctly in a browser, just the test doesn't.

The test doesn't run at all when both useSubscription hooks are present, i.e. if I put a console.log as the first line in the test (before the render even) it doesn't show in the output.

Also, this only happens if there's an await in the test somewhere.

**Versions**
Apollo client: 3.1.4
Jest: 26.5.0

**Comment by brainkim** [comment] 2021-03-30 01:33
Thanks for reporting this issue! This seems to be a duplicate of https://github.com/apollographql/apollo-client/issues/7780 and https://github.com/apollographql/apollo-client/issues/7493. Or rather, I should say, those bugs are duplicates of your issue, given that this issue was written first! I’m slowly understanding what’s happening here (I’m like at why 3 of the [5 why’s](https://en.wikipedia.org/wiki/Five_whys)) and we’ll probably have a fix within two weeks at most.

I’m closing this in favor of those two issues because those issues have reproducible examples, but know that 1. we’re grateful that you opened the issue and 2. this is being worked on. Please feel free to let me know your thoughts!

**Closed by brainkim** 2021-03-30 01:33 UTC
Labels: ♾ Infinite, ⚛️ React-related, 🔗 apollo-link

**Comment by lawrencecushman** [comment] 2021-03-30 22:48
Anyone know of any workarounds?
