### ISSUE TITLE
useQuery calls onCompleted on unmounted components

### ISSUE THREAD

**Issue by benasher44** [apollographql/apollo-client#9899] opened 2022-07-11 18:10 UTC
**Intended outcome:**
Make a query with useQuery and have it not call onCompleted on a component that isn't mounted

**Actual outcome:**
onCompleted was called, which resulted in us calling setState in an un-mounted component

**How to reproduce the issue:**
We don't have a firm reproduction, but we notice errors like this sporadically when upgrading from 3.6.2 to 3.6.9:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in CandidatePullOut (at CandidatePullOut.tsx:41) [index.js:1](http://localhost:3001/Users/basher/code/ashby/frontend/node_modules/react-error-overlay/lib/index.js)
    e index.js:1
    get <ourlogger>.tsx:81
    onCompleted <call to setState in onCompleted in component using useQuery>.tsx:68
    handleErrorOrCompleted useQuery.ts:510
    setResult useQuery.ts:502
    onNext useQuery.ts:159
    notifySubscription module.js:132
    onNotify module.js:176
    next module.js:225
    iterateObserversSafely iteration.ts:13
    iterateObserversSafely iteration.ts:13
    reportResult ObservableQuery.ts:879
    next ObservableQuery.ts:830
    iterateObserversSafely iteration.ts:13
    iterateObserversSafely iteration.ts:13
    next Concast.ts:172
    notifySubscription module.js:132
    onNotify module.js:176
    next module.js:225
    promiseQueue asyncMap.ts:34
```

**Versions**
@apollo/client 3.6.9

**Comment by alessbell** [comment] 2022-07-27 14:25
Hi @benasher44 - I'm having trouble reproducing this. Do you have a codesandbox/minimal reproduction you might be able to share? Thanks!

**Comment by benasher44** [comment] 2022-07-27 14:32
I don't, sorry. I only have stack traces :(

**Comment by benasher44** [comment] 2022-07-27 14:33
No worries if you want to close this, as a result!

**Comment by alessbell** [comment] 2022-07-28 18:44
No worries! I'll leave this open for now, one other question: you mentioned you started seeing these traces when upgrading from 3.6.2 to 3.6.6, can you confirm you're currently running 3.6.9?

**Comment by benasher44** [comment] 2022-07-28 18:59
No we're running 3.6.2. We couldn't upgrade due to other (seemingly) internal changes that impacted number (or timing) of react renders, so we're stuck on 3.6.2

**Comment by alessbell** [comment] 2022-07-28 19:06
Got it, thanks for clarifying - I asked because this issue lists 3.6.9 at the bottom. One last question for now (and thanks for the additional info!): the issue you described with the number/timing of (re-)renders, did you start observing those at 3.6.6?

**Comment by benasher44** [comment] 2022-07-28 20:24
Whoops! Sorry everything should say 3.6.9 — that's the version we upgraded to and tested. Apologies for the confusion there

**Comment by alessbell** [comment] 2022-07-28 21:15
No problem! Thanks for clarifying :)

**Comment by alessbell** [comment] 2022-08-09 18:54
After looking at this some more, I'm going to go ahead and close this ticket out.

Absent a reproduction, the existing behavior of `onComplete` as a callback that executes when a query finishes executing behaves as described. Don't hesitate to re-open with more information or a reproduction in the future. Thanks!

**Closed by alessbell** 2022-08-09 18:54 UTC
Labels: 🐞 bug, 📟 regression
