### ISSUE TITLE
undefined is not an object (evaluating 'o.currentObservable.query.fetchMore')

### ISSUE THREAD

**Issue by charlypoly** [apollographql/apollo-client#6271] opened 2020-05-13 09:17 UTC
Hi Apollo team!

Our product is facing this error very often:

![image](https://user-images.githubusercontent.com/1252066/81794014-6d0cfa00-950a-11ea-9575-7de0c5e7b684.png)

Our application allows to switch between many workspaces which is associated to a unique apolloclient instance (different ApolloLink for authentication headers), when doing so, the active apollo client of the React app is changing

We think that it might be what is triggering the error, explanation:

The errors comes from `QueryData` (`this.currentObservable` is `undefined`):

https://github.com/apollographql/apollo-client/blob/19b7ad5245f9011b05509d4b8ad9423f378915ac/src/react/data/QueryData.ts#L466-L469

`this.currentObservable` can be `undefined` only if a `cleanup()` is called, cf:

https://github.com/apollographql/apollo-client/blob/19b7ad5245f9011b05509d4b8ad9423f378915ac/src/react/data/QueryData.ts#L100-L104

`cleanup()` is called from `refreshClient()` (from `OperationData`, extended by `QueryData`) which is [used everywhere](https://github.com/apollographql/apollo-client/search?q=refreshClient%28%29&unscoped_q=refreshClient%28%29) to ensure a valid client when performing an operation:

https://github.com/apollographql/apollo-client/blob/0340c48429b20f621d552af748527798bf6f26c5/src/react/data/OperationData.ts#L46-L68

**How to reproduce the issue:**
Given a query `getAlerts` that does polling using `fetchMore()` in a workspace A:

1. in workspace A, with Apollo client instance 1, trigger `getAlerts` query
2. go to workspace B, with Apollo client instance 2, trigger `getAlerts` query
3. go back to workspace A, with Apollo client instance 1, trigger `getAlerts` query ➡️ **error**

**Versions**

- `apollo-client@2.6.8`
- `apollo-cache-inmemory@1.6.5`
- `apollo-cache@1.3.4`
- `apollo-link@1.2.13`
- `apollo-link-context@1.0.19`
- `apollo-link-error@1.1.12`
- `apollo-link-http@1.5.16`
- `apollo-link-http@1.5.16`

**Comment by hwillson** [comment] 2020-05-15 12:17
@wittydeveloper Can you confirm which version of Apollo Client you're using?

**Comment by wittydeveloper** [comment] 2020-05-15 12:19
@hwillson Sure, we use `apollo-client@2.6.8`

**Comment by hwillson** [comment] 2020-05-15 18:52
Thanks @wittydeveloper - a few additional questions:

1. How are you toggling your `ApolloClient` instance - e.g. are you toggling `client` instances before passing them through `ApolloProvider`? Or are you passing different `client` instances into `useQuery` through its `client` option?

2. Are you using `fetchMore` anywhere, or are you seeing this error without using `fetchMore`?

**Comment by wittydeveloper** [comment] 2020-05-17 10:08
Hi @hwillson,

1.  we do change the `client=` passed to `<ApolloProvider>`
2. yes, we have queries that use `fetchMore()` every 5min to poll new pages.

I guess the issue here is that those queries should use a direct `ApolloClient` instead of the context one that ends up being deleted when switching client?

**Comment by felippepuhle** [comment] 2020-09-23 19:06
Hey! How is it going?

We don't have dynamic  `ApolloClient` instances and we're still facing this issue... 

We're using `InteractionManager` to `refetch` some queries, and it seems something related to it.
If we get rid of the `InteractionManager` it seems to work, but it may decrease animations performance.

Is there anything we can do to help?

Thanks!

**Comment by toniton** [comment] 2020-12-07 22:07
This seemed to work for me. 👇 
https://github.com/apollographql/apollo-client/issues/6904#issuecomment-740208227

**Comment by hwillson** [comment] 2021-04-30 18:57
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by tabvn** [comment] 2021-05-05 08:51
Same error TypeError: undefined is not an object (evaluating '_this.currentObservable.fetchMore')


"@apollo/client": "^3.3.16",

this also happend with nextjs and react-native

**Comment by brainkim** [comment] 2021-05-05 13:39
We can look into this! The original issue is very detailed, so thanks for that! The one thing is this will get looked at faster if there were a runnable reproduction demonstrating the bug 🤗

**Comment by extjbhlego** [comment] 2021-08-19 09:15
Can confirm that it happens on 3.3.16 for us, too. I can't help with a reproduction repo at the moment, just wanted to confirm the problem

**Comment by benjamn** [comment] 2021-08-20 15:16
@extjbhlego @tabvn Have you been able to try the latest version, `@apollo/client@3.4.8`?

**Comment by DrWorkhard** [comment] 2021-11-16 09:22
I've experienced the same error message in the following context:

When I receive an error, I pass it to a react component which shows an error message along with an "action". This action should trigger a refetch of the data.

the following code snipped was prone to the error:

`
  function refetchFeedInfos() {
    fetchMore({variables: {nextToken: '-1'}});
    lastNextToken.current = '-1';
  };

  if (error) {
    return <ErrorCards error={error} action={() => refetchFeedInfos()} />;
  }
`

I updated it like so and do not experience the error anymore:

`
  const refetchFeedInfos = () => {
    fetchMore({variables: {nextToken: '-1'}});
    lastNextToken.current = '-1';
  };

  if (error) {
    return <ErrorCards error={error} action={() => refetchFeedInfos()} />;
  }
`

I think the reason is the arrow function has access to the creating function's context. Now I have no idea if this solves the OPs question. But it did solve my issue.

**Comment by alessbell** [comment] 2023-12-18 19:13
Without a reproduction here it's difficult to know for certain, but we haven't seen any similar reports recently. Closing this issue out, if the same issue occurs please open a new issue with a runnable reproduction and we can investigate. Thanks!

**Closed by alessbell** 2023-12-18 19:13 UTC
Labels: :wilted_flower: needs-reproduction, ⚛️ React-related
