### ISSUE TITLE
fetchPolicy: 'cache-and-network' and @client not fetching from the cache

### ISSUE THREAD

**Issue by rcacheira** [apollographql/apollo-client#3177] opened 2018-03-20 15:35 UTC
I’m checking that when setting the following default options on ApolloClient:
```
defaultOptions: {
  query: { fetchPolicy: 'cache-and-network', errorPolicy: 'all' },
  mutate: { errorPolicy: 'all' },
  watchQuery: { fetchPolicy: 'cache-and-network', errorPolicy: 'all' }
}
```
a query marked with `@client` is not returning the info from the cache unless a resolver to the query is implemented or marked with the following options `options: { fetchPolicy: 'cache-only' }`.

I exposed this on slack channel and I got the following response from Dennis Bækgaard, maybe it can help:
> I just tried appending it to a query and experience the same behaviour. Havn't seen if I can actually get it to resolve from the cache if I implement a resolver, but without one it at least, it always seems to fetch from the remote store.
> Don't know if this helps, but after a short view of the source, it looks to me that it has to happen in QueryManager.ts:301 - Inside that conditional is the only place it actually diffs with the cache. Of the conditionals, the only one I can see could cause problems is the FetchType

**Version**
- apollo-cache-inmemory@1.1.7
- apollo-client@2.2.3
- apollo-link@1.1.0
- apollo-link-schema@1.0.3
- apollo-link-state@0.4.0
- react-apollo@2.0.4

**Comment by uNScope** [comment] 2018-04-10 11:12
I have a same problem. 

QueryManager.ts line 360
```
const shouldDispatchClientResult =
      !shouldFetch || fetchPolicy === 'cache-and-network';

if (shouldDispatchClientResult) {
      this.queryStore.markQueryResultClient(queryId, !shouldFetch);
}
```
In function markQueryResultClient with fetch policy  'cache-and-network' second argument always pass 'false' and it fetch from remote storage instead of fetch from cache. When I replace '!shouldFetch' on 'true' everything became good.

**Comment by asafigan** [comment] 2018-07-13 18:41
Idk, if this is actually a bug. I was printing out the results of the query and I found that on the second watch it returns the result from the cache but also returns loading true.

The problem is if loading should be true in this case or is it better for loading to be false or to have a new value loaded for something like that.

**Comment by rstrand** [comment] 2019-01-16 18:01
@asafigan I also see this behaviour - the data is returned from the query but`loading` is true. I agree the behaviour of `loading` is confusing as most apollo examples just show a loading message when `loading` is true and ignore the returned data.

`networkStatus` isn't much help either as it is always 1 even on a cache hit. There is more discussion in issue #3660.

**Comment by jbaxleyiii** [comment] 2019-07-09 21:06
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Closed by jbaxleyiii** 2019-07-09 21:06 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage
