### ISSUE TITLE
useSuspenseQuery "A valid resource ID is required" - possible bug? 

### ISSUE THREAD

**Issue by MitchEff** [apollographql/apollo-client#11001] opened 2023-06-22 00:55 UTC
I'm just following the guide to incorporate the new Apollo client for NextJS, and all seems to _work_ so far. However, my first usage of `useSuspenseQuery` gives me:
```
react-dom.development.js:16356 Uncaught Error: A valid resource ID is required.
    at updateDehydratedSuspenseComponent (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:16356:17)
    at updateSuspenseComponent (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:16056:16)
    at beginWork$1 (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:17369:14)
    at beginWork (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:25672:14)
    at performUnitOfWork (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:24523:12)
    at workLoopSync (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:24239:5)
    at renderRootSync (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:24204:7)
    at performConcurrentWorkOnRoot (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23343:74)
    at workLoop (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:261:34)
    at flushWork (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:230:14)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:537:21)
```

My code's really quite simple (and my client set-up is identical to the docs):
```
'use client'

import { useSuspenseQuery } from "@apollo/experimental-nextjs-app-support/ssr"

import Header from 'src/components/header/header'
import Menu from 'src/components/menu/menu'

import { ACCOUNT_QUERY } from '@graphql/queries/account'

import s from './layout.module.sass'
import { Suspense } from 'react'

export const dynamic = "force-dynamic"

export default function Layout({ children }) {
    const { data } = useSuspenseQuery(ACCOUNT_QUERY)

    const { account } = data

    return (
        <Suspense fallback={<div>Loading...</div>}>
            <div className={s.Outer}>
                <Header account={account} />
                <aside>
                    <Menu data={data} />
                </aside>
                <main>
                    <div>
                        {children}
                    </div>
                </main>
            </div>
        </Suspense>
    )
}
```

I didn't want to log this as a bug per se, as I'm unclear if it is - there's no documentation around the error I'm getting, and it doesn't appear with a traditional `useQuery`. Is this a bug, or some undocumented issue in how I'm using it?

**Comment by jerelmiller** [comment] 2023-06-22 05:48
@MitchEff thats a weird error. I've never seen this before either.

Something I notice right away is that your Suspense boundary is rendered by the `Layout` component, which also suspends via `useSuspenseQuery`. Can you move the `<Suspense />` boundary so that it wraps the `<Layout />` component?

```tsx
<Suspense fallback={<div>Loading...</div>}>
  <Layout />
</Suspense>
```

See if perhaps that fixes this issue and let us know!

**Comment by MitchEff** [comment] 2023-06-23 04:23
No bueno, unfortunately. I've changed it to this, and I still get the same error (also seems to happen even if I remove `<Suspense>` entirely). 

I've changed it back to `useQuery` for now, and just prevented rendering until the query resolves. 

```
'use client'

import { useSuspenseQuery } from "@apollo/experimental-nextjs-app-support/ssr"

import Header from 'src/components/header/header'
import Menu from 'src/components/menu/menu'

import { ACCOUNT_QUERY } from '@graphql/queries/account'

import s from './layout.module.sass'
import { Suspense } from 'react'

export const dynamic = "force-dynamic"

export default function Layout({ children }) {

    return (
        <Suspense fallback={<div>Loading123123123</div>}>
            <Inner>
                {children}
            </Inner>
        </Suspense>
    )
}

const Inner = ({
    children
}) => {
    const { data } = useSuspenseQuery(ACCOUNT_QUERY)

    const { account } = data

    return (
        <div className={s.Outer}>
            <Header account={account} />
            <aside>
                <Menu data={data} />
            </aside>
            <main>
                <div>
                    {children}
                </div>
            </main>
        </div>
    )
}
```

**Comment by jerelmiller** [comment] 2023-06-23 05:24
Hey @MitchEff 👋 

I'm looking at this again and I had a thought... this error looks like it could be a GraphQL error. Could you check your server response to see if perhaps your request is returning an error?

One big difference with `useSuspenseQuery` vs `useQuery` (aside from suspending) is that errors are automatically thrown by the hook, which means you'll need an error boundary to catch that error. I see you're using an `ACCOUNT_QUERY` (singular) with no variables, so perhaps the GraphQL server is missing something there? (just a thought)

If you want to do a quick check without creating an error boundary, you can prevent `useSuspenseQuery` from throwing by setting the `errorPolicy` to `all`. This will return the error in the `error` property returned from `useSuspenseQuery`.

```ts
const { data, error } = useSuspenseQuery(ACCOUNT_QUERY, { errorPolicy: 'all' });

console.log(error);

// keep in mind if there are errors, `data` might be `undefined`, so you may need to access
// it differently beyond this point in the code
```

Not sure if this is it, but just a hunch!

**Comment by MitchEff** [comment] 2023-06-23 05:39
Thanks a ton for helping out, Jerel! 

I'm kinda guessing it may be `useSuspenseQuery`-related, as swapping it back to `useQuery` doesn't give any errors. 
I'll probably just stick with that for the time being, and maybe take another stab a little down the line. It may be some NextJS app router quirk too. There's been a few of those lately.

**Comment by alessbell** [comment] 2023-06-26 15:27
@MitchEff sorry to hear you're still not having luck with `useSuspenseQuery`.

Since you're using Next.js, I assume you've seen our examples folder in the [`apollo-client-nextjs`](https://github.com/apollographql/apollo-client-nextjs) repo with `useSuspenseQuery` demos like [this one](https://github.com/apollographql/apollo-client-nextjs/blob/f875cbc74f536e389dbb57bd71343cc0a5ccc763/examples/hack-the-supergraph-ssr/app/page.tsx#L6), but if not you may want to take a look. If you do have a reproduction, feel free to post it here and I'd be happy to re-open the issue, but for now I'll close this out. Thanks!

**Closed by alessbell** 2023-06-26 15:27 UTC
Labels: ⁉️ question
