### ISSUE TITLE
Type inference broken in 3.8

### ISSUE THREAD

**Issue by jxdp** [apollographql/apollo-client#11150] opened 2023-08-15 00:48 UTC
### Issue Description

In our codebase we heavily rely on type inference when using Apollo, with lots of custom hooks that look along the lines of:

```ts
const useSomethingQuery = (options?: QueryHookOptions<SomethingQuery, SomethingQueryVariables>) =>
  useQuery(
    gql`
      query Something($args: Args) {
        ...
      }
    `,
    options,
  );
```

where the types are generated using graphql codegen. 

Before updating to 3.8, this works exactly as expected–`useQuery` is able to infer the types correctly from `options`, which means we do not need to also add the exact same types twice.

After updating to 3.8, this inference is broken. We have to specify the types twice like so:

```ts
const useSomethingQuery = (options?: QueryHookOptions<SomethingQuery, SomethingQueryVariables>) =>
  useQuery<SomethingQuery, SomethingQueryVariables>(
    gql`
      query Something($args: Args) {
        ...
      }
    `,
    options,
  );
```

This a very unfortunate regression that, in our case, is sufficiently annoying to prevent upgrading (which is a shame, because I was keen to give the new suspense hooks a try).

### Link to Reproduction

https://

### Reproduction Steps

Update to 3.8.x, observe typescript being very unhappy.

**Comment by jerelmiller** [comment] 2023-08-15 00:59
Hey @jxdp 👋 

So sorry to hear about the regression! FWIW we spent a lot of time iterating on the new suspense hooks with and without inference so I'd encourage you to give them a try (here are the [type tests](https://github.com/apollographql/apollo-client/blob/b0a45ebdc075a8fdbc186b620536f7b608081d2e/src/react/hooks/__tests__/useSuspenseQuery.test.tsx#L9877-L10323) to give you an idea). In fact, I'm willing to bet you'll have a better time with those hooks than `useQuery` 🙂.

I'm willing to bet #10506 might have had something to do with it. We added a fix to ensure that variables weren't accidentally widened when passing extra variables that weren't included in your query. This change was released in [`3.8.0-alpha.7`](https://github.com/apollographql/apollo-client/releases/tag/v3.8.0-alpha.7). Would you be willing to install `v3.8.0-alpha.6` or earlier and see if this type issue goes away? This should at least tell us if #10506 is responsible.

**Comment by jxdp** [comment] 2023-08-15 01:27
> v3.8.0-alpha.6

Thank you @jerelmiller. I've tried installing a few of the `alpha` versions and you're exactly right–it is with `alpha.7` that the type errors begin.

So I'll be sticking with `alpha.6` for now–hopefully it is only a minor tweak that is required!

**Comment by plausible-phry** [comment] 2023-08-15 02:04
My assumption here would be that your inline `gql` call is not typed correctly, but just returning a `DocumentNode` of unknown type.

Generally, I know this is not what you want to hear, but I would say that this might be a good thing that this is failing - let me try to explain:

The idea of that change was that types only flow in one direction: from the query to the options.  
So if you pass in a `TypedDocumentNode<SomeQuery, SomeQueryVars>`, the options are automatically seen as `QueryHookOptions<SomeQuery, SomeQueryVars>`.  
But if you pass in `QueryHookOptions<SomeQuery, SomeQueryVars>`, we still know nothing about the `query`. 

In the past, that flow worked in both directions, but it had a big problem: If those types were mismatching, they "widened".  
So if you passed in `TypedDocumentNode<QA, AV>` and `QueryHookOptions<QB, BV>`, the result ended up being `QA & QB` with variables `AV & BV`. 
As a result, users never saw a warning if you passed in variables that were actually not part of your query.

So, why am I saying "this is a good thing" in your case? Because it highlights that you have no actual type safe connection between your query and variables!

Someone could accidentally mix up a type in your `QueryHookOptions` that doesn't match up with your query, and you would never get a type error out of it.

Now, for you there are a few ways out of it, I would recommend one of those two:  
Either you could change from `gql` to the `graphql` helper function of GraphQL Codegen. That would make your `query` typesafe and actually show you errors if your query and variable ever mismatched
Alternatively, you could switch up your pattern here - the thing is that since GraphQL codegen automatically generates `TypedDocumentNodes` for you, there is no real need to write custom hooks like this any more at all. This example is perfectly typesafe:

```js
import { SomeQueryDocument } from './generated-types'

useQuery(SomeQueryDocument, { ... })
```
Because the `SomeQueryDocument` already contains all the necessary type information, you do not need to declare a custom hook at all, and can just use the generated Document with `useQuery` and our other hooks. It also has the benefit that unlike your hooks, the `gql` helper does not need to do extra execution work every time the hook is called.

**Comment by jxdp** [comment] 2023-08-15 09:53
> My assumption here would be that your inline `gql` call is not typed correctly, but just returning a `DocumentNode` of unknown type.
> 
> Generally, I know this is not what you want to hear, but I would say that this might be a good thing that this is failing - let me try to explain:
> 
> The idea of that change was that types only flow in one direction: from the query to the options. So if you pass in a `TypedDocumentNode<SomeQuery, SomeQueryVars>`, the options are automatically seen as `QueryHookOptions<SomeQuery, SomeQueryVars>`. But if you pass in `QueryHookOptions<SomeQuery, SomeQueryVars>`, we still know nothing about the `query`.
> 
> In the past, that flow worked in both directions, but it had a big problem: If those types were mismatching, they "widened". So if you passed in `TypedDocumentNode<QA, AV>` and `QueryHookOptions<QB, BV>`, the result ended up being `QA & QB` with variables `AV & BV`. As a result, users never saw a warning if you passed in variables that were actually not part of your query.
> 
> So, why am I saying "this is a good thing" in your case? Because it highlights that you have no actual type safe connection between your query and variables!
> 
> Someone could accidentally mix up a type in your `QueryHookOptions` that doesn't match up with your query, and you would never get a type error out of it.
> 
> Now, for you there are a few ways out of it, I would recommend one of those two: Either you could change from `gql` to the `graphql` helper function of GraphQL Codegen. That would make your `query` typesafe and actually show you errors if your query and variable ever mismatched Alternatively, you could switch up your pattern here - the thing is that since GraphQL codegen automatically generates `TypedDocumentNodes` for you, there is no real need to write custom hooks like this any more at all. This example is perfectly typesafe:
> 
> ```js
> import { SomeQueryDocument } from './generated-types'
> 
> useQuery(SomeQueryDocument, { ... })
> ```
> 
> Because the `SomeQueryDocument` already contains all the necessary type information, you do not need to declare a custom hook at all, and can just use the generated Document with `useQuery` and our other hooks. It also has the benefit that unlike your hooks, the `gql` helper does not need to do extra execution work every time the hook is called.

@plausible-phry appreciate the detailed response and suggestions.

However, there are still various reasons to create custom hooks. Sometimes there is custom logic (omitted in the example above), but even if not we still prefer to extract the details of setting up a query/mutation to a custom hook to reduce the visual noise it otherwise introduces and to facilitate re-use. 

Totally understand the rationale behind the changes here and believe the intention is correct, however I do not think it makes a great deal of sense to force consumers to _only do it this way_. Without looking at the code, it seems like the same outcome could be achieved by only enabling these extra checks when a consumer opt-in by _choosing_ to use a `TypedDocumentNode`.

Sometimes it isn't even possible to use a `TypedDocumentNode`. For example, we have a `useQueryAll` hook which accepts a generically-typed `options` and auto-paginates the query:

```ts


/**
  * `TData` must extend:
  * 
  *  <field> {
  *    pageInfo { hasNextPage hasPreviousPage startCursor endCursor }
  *    edges { cursor node { id } }
  *    totalCount
  *  }
  */

type KeyOf<T, TData extends Record<string, unknown>> = keyof {
  [K in keyof TData]: TData[K] extends T ? K : never;
};

export const useQueryAll = <
  TData extends Record<string, Connection>,
  TVariables extends OperationVariables & {page?: Maybe<PaginationArgs>},
>(
  field: KeyOf<Connection, TData>,
  document: DocumentNode,
  options: QueryHookOptions<TData, TVariables>,
): Pick<
  QueryResult<TData, TVariables>,
  "called" | "client" | "data" | "error" | "loading" | "networkStatus" | "refetch"
> => {
  const {data, loading, fetchMore, refetch, client, called, networkStatus} = useQuery(document, {
    ...options,
    pollInterval: 0,
  });

  // etc ...
}
```

Using typed-`options` has honestly worked incredibly well for us, and presumably for many others. I hope you agree that it is worth preserving the _option_ to do things this way!

**Comment by jxdp** [comment] 2023-08-15 12:48
> I think we can look into doing that with a normal `DocumentNode`, although I'm not 100% sure if it is possible: there is a certain risk that on a mismatch TypeScript will jump back to that "fallback overload" - a TypedDocumentNode is just a DocumentNode after all - and go back to the old behavior, removing most type safety without the user really noticing.
> 
> I'm currently answering from vacation, and my colleagues are out at React Rally, but once we're all back we will discuss this and experiment around with it.
> 
> Thanks for bringing this up.

Thanks for taking the time–please enjoy your vacation!

**Comment by plausible-phry** [comment] 2023-08-17 13:04
> Thanks for taking the time–please enjoy your vacation!

Thanks :blush: 

I just want to get back on this really quick, because I'm not sure if I brought that point across enough: your current approach is really unsafe on a type level and close to `any`-casting the query. You can do very small changes with a very big type safety improvement.

Imagine this hook from your example that I added a typo to:

```js
const useSomethingQuery = (options?: QueryHookOptions<SomethingQuery, SomethingsQueryVariables>) =>
  useQuery(
    gql`
      query Something($args: Args) {
        ...
      }
    `,
    options,
  );
```

Did you spot the typo? Autoimport imported `SomethingsQueryVariables` instead of `SomethingQueryVariables`.
You probably have a query for a singular `Something` and a query for a list of `Somethings` in your codebase, so this can happen easily. 

TypeScript wouldn't complain here - since your inline query here could be a query for anything.

You can achieve type safety in one of two ways here:

The [`graphql` helper function of the codegen "client preset"](https://the-guild.dev/graphql/codegen/plugins/presets/preset-client):

```diff
+import { graphql } from './generated-types'

const useSomethingQuery = (options?: QueryHookOptions<SomethingQuery, SomethingsQueryVariables>) =>
  useQuery(
-    gql`
+    graphql(`
      query Something($args: Args) {
        ...
      }
-    `,
+    `,
    options,
  );
```

or by letting the codegen do it's thing and importing the code-generated `Document` which has types.

```diff
+const SomethingQuery = gql`
+      query Something($args: Args) {
+        ...
+      }
+`

+import { SomethingQueryDocument } from './generated-types'

const useSomethingQuery = (options?: QueryHookOptions<SomethingQuery, SomethingsQueryVariables>) =>
  useQuery(
-    gql`
-      query Something($args: Args) {
-        ...
-      }
-    `,  
+    SomethingQueryDocument,
    options,
  );
```

By the way, like this you could e.g. also put the query in an accompanying `.graphql` file and because the `Document` is already "precompiled", you don't need to parse it in the browser and don't need to ship the `graphql-tag` package as part of your bundle.
You save browser CPU time and bundle size that way!


I left the typo in both of these, and if you try them out you will find that in both cases, TypeScript will warn you about it.

---

Given that both of these options are a pretty small refactor compared to the type safety (and even bundle size & browser CPU time) gains you can get from them, I am currently playing with the thought of re-adding the ability to do this, but at the same time I want to make it very clear that given the alternatives we want to discourage this approach.

As an API consumer, what are your personal feelings if we added an overload to re-enable the old inference behaviour, but at the same time deprecated that overload and added a deprecation note pointing to a documentation page that summarized what I wrote above? 
Your code would still compile fine, but you'd have a strike-through in your IDE in some places, trying to guide you to a more typesafe approach.  
Would you think that would be helpful?  
Would you consider it "too condescending"?

**Comment by jxdp** [comment] 2023-08-18 02:18
@plausible-phry Thank you for the detailed thoughts!

Here are my own thoughts:
- for generic hooks, there isn't a generated document node that can be passed in. As a consumer who writes custom generic hooks, I want to define an interface for the variables/data and let inference do its thing, but I do _not_ want to hand-roll generic document node objects (if this is even possible)
- In theory adding back + deprecating solves this problem for now (or at the very least buys some time to figure out what makes sense going forwards)
- personally, I would be disappointed to see type-inference being deprecated because it works well (enough). Custom hooks will still be required either way, which means adding types to the options will still be required as well. I think it would be a poor choice to force consumers to add types twice, but I accept that this is purely an opinion

**Comment by plausible-phry** [comment] 2023-08-18 03:47
I'm on mobile right now and will respond with more detail in the evening, but can you give an example of such a generic hook? Are you dynamically creating Graphql queries in runtime here?

Generally: a deprecation would not mean that we would remove it anytime soon, it's just the only visible "discouraging" indicator we have at our disposal (apart from a TS error) to indicate "you probably shouldn't use this in most use cases" to nudge people towards more typesafe patterns where it's possible.

**Comment by jxdp** [comment] 2023-08-18 10:02
> I'm on mobile right now and will respond with more detail in the evening, but can you give an example of such a generic hook? Are you dynamically creating Graphql queries in runtime here? Generally: a deprecation would not mean that we would remove it anytime soon, it's just the only visible "discouraging" indicator we have at our disposal (apart from a TS error) to indicate "you probably shouldn't use this in most use cases" to nudge people towards more typesafe patterns where it's possible.

Some of the generic hooks that we have found useful to create are:
- utility hooks that provide extended functionality, such as `useQueryAll` which performs auto-pagination on any query where the generated Variables and Data types satisfy required interfaces, see https://github.com/apollographql/apollo-client/issues/11150#issuecomment-1678680738 for the signature.
- variant hooks that wrap the basic hooks and provide preferred defaults, extra validation of the provided options, etc. A common thing is error handling for mutations–we do not want to manually instrument every mutation with the same boilerplate code, it makes a lot more sense to bundle it into the hook.

The hooks Apollo provides are excellent as primitives for building more complex functionality that does exactly what _we_ want.

FWIW, inferring the types from `Options<Data, Var>` is completely equivalent explicitly to writing `useQuery<Data, Var>(document)`.

**Comment by plausible-phry** [comment] 2023-08-20 14:13
Phew, lots to unpack, I apologize in advanced if this answer is lacking in any way - I'm in the process of packing for a flight for tomorrow, but I promised you an answer, so I also don't want to let you wait for too long :)

I think the more we discuss, this really boils down to "use TypedDocumentNode" vs "not use TypedDocumentNode". Let me try to summarize my reasoning for this here:

We essentially have three "inference modes" we can think about:

* typed Document and typed Options: if these types are not equivalent, we should always expect this to error - otherwise, they will be equal, so it doesn't matter which of the two is used for inference.
* typed Document and untyped Options - inference here works nicely right now
* untyped Document and typed Options - the case we are discussing here. This only happens if you make the choice "DocumentNode" instead of "TypedDocumentNode".

Here I'm going to pick up your sentence:

> What is actually true is that using "untyped" document nodes is less type-safe than using "typed" document nodes.

I agree loudly here.

As a result, in my eyes this also means that *only looking at implicit inference patterns*, the scenario we are discussing in this PR is less typesafe than using inference that includes a TypedDocumentNode.

I agree that specifically specifying a generic with an untyped DocumentNode is equally unsafe - and if I were to design `useQuery` today, I would probably try to discourage *that* from the start - but TypeScript being TypeScript, we don't have the luxury of "internal generics" that cannot be user-specified, so this pattern of "unsafely manually specifying generic types" is something that is unfortunately deeply baked into the language - even if the TypeScript team themselves repeatedly states that using it this way is inherently unsafe and akin to an any-assertion.

But that said, we are going very deep into philosophic arguments here, so I'll try to get back to being a bit more pragmatic:  
I would love to discourage this pattern in newly written code, as it is - compared to using a TypedDocumentNode - essentially equal to an any-assertion. We can only do that by making this "unsafety" visible to the user in some way - hence my idea of a `@deprecated` marker. 
We could also add a dozen :warning: emojis to the overload signature docblock, but I'm not sure how many people would actually get to see that :thinking: 

Still, I want to make sure that for the bulk of situations, there is a good alternative pattern (that we maybe even could support with a codemod?) - while I want to equally make sure that existing code continues working as it did before.

Looking at your example hook, I don't really see why it wouldn't work with Document-driven inference instead of Options-driven inference, but that probably boils down to this sentence of yours:

> But that is a separate choice that we as consumers have to make; using typed document nodes has trade-offs that not every team wants to accept.

I have to admit that I have never encountered a negative tradeoff of a TypedDocumentNode so far (assuming you use the codegen, but even if you don't I prefer them even for hand-written queries).  
Could you elaborate a bit what your arguments against a TypedDocumentNode are?

**Comment by plausible-phry** [comment] 2023-08-20 14:19
PS: in the meantime I'd love to enable you to already switch to 3.8 - I believe if you throw this snippet anywhere into your codebase, your current way of using inference should be re-enabled:

```ts
declare module '@apollo/client' {
  export function useQuery<
    TData = any,
    TVariables extends OperationVariables = OperationVariables,
  >(
    query: DocumentNode & { __apiType?: never },
    options: QueryHookOptions<
      TData,
      TVariables
    >
  ): QueryResult<TData, TVariables>
}
```

**Comment by jxdp** [comment] 2023-08-21 13:43
@plausible-phry

At the end of the day, it is up to the Apollo team to decide what you want to support going forward.

Are we now _required_ to use generated typed document nodes?
Are you also going to deprecate JS support because of type-safety concerns? (I am being facetious but I hope you see the point I'm making.)

`useQuery<Data, Var>(untypedNode, ...)` is completely equivalent to `useQuery(untypedNode, typedOptions)`. Disallowing (or deprecating) the latter will not make the API any more type-safe, but it will make it less flexible.

I think it's awesome that you can make the types even stricter using a `TypedDocumentNode`, but I don't see why that should have any impact on the existing inference. Ideally it would work optimistically to infer from whatever types are available, which means if somebody _is_ using a `TypedDocumentNode` then they get the "safest" experience.

**Comment by plausible-phry** [comment] 2023-08-23 04:33
@jxdp it's a bit of a "how do we teach and encourage best practices" problem here :/

I agree that on the one side, it's good to have a lot of different ways of expressing something.  
On the other hand, it makes it more difficult for people who are looking at all the options for the first time to identify which is the safest one to go for. Many people will try something, see it works, and never consider that there are other options available that might be more typesafe.  
Likewise, there are a lot of people sticking to old coding styles that just never encountered `TypeDocumentNode`, and never will encounter it, until we find a way of making them more aware of it.

So, in that way, we are doing a lot of our users a disservice by not trying to find ways to make them aware of the "best way possible".  
It's the maintainers dilemma: we cannot make everyone happy, while having to try to provide the most values to most users.

> useQuery<Data, Var>(untypedNode, ...) is completely equivalent to useQuery(untypedNode, typedOptions)

I still kinda disagree with that.  
Using the explicit type arguments inline with `useQuery` makes it very obvious that this line uses a user-provided type that might not be accurate.  
Using the typed options moves that declarations away from `useQuery`, potentially dozens of lines. If it's not on the screen anymore, at some point the user will forget about the manual typing they did elsewhere, and assume that inference will be right - even if it's not necessarily.

> Are we now required to use generated typed document nodes?

No, but in my personal opinion, people that have the option of using it *should* use it.

I also really want to get to know more here about why people might not be able to use `TypedDocumentNode`, so I'll echo my question from my last post in the hope that you can give us some additional insights here:

> Could you elaborate a bit what your arguments against a TypedDocumentNode are?

Like, in what scenarios would someone not be able to use it?

---

I am currently thinking of deprecating this overload, but maybe adding a way to disable the deprecation for a codebase. Not 100% sure if that would work, but maybe that can be a good compromise here.

**Comment by jxdp** [comment] 2023-08-23 22:48
@plausible-phry 

>Using the explicit type arguments inline with useQuery makes it very obvious that this line uses a user-provided type that might not be accurate.

But it is exactly the same level of accuracy. The only difference is how the developer has chosen to annotate the types; if you are doing something _inline_ (e.g. using `useQuery` directly in a component) then it is convenient to specify `useQuery<Data,Args>(...)`, but if you are creating the hook outside of a component then it is much more convenient to rely on inference _because you have to add type annotations to the options regardless_.


I feel like perhaps the use case I am describing is not coming across, so below I outline all the ways in which we do (or hypothetically could) use the `3.7.x` API:


```tsx

const SomeConcreteQuery = gql`query ...`

// A: inline option types 
//   - we do _not_ use this pattern, but it would technically work–I don't know why you'd ever do it this way
const MyComponent = () => {
  const options: HookOptions<ConcreteQueryData, ConcreteQueryVar> = {...}
  const result = useQuery(SomeConcreteQuery, options); // result types inferred
  return <>...</>;
}

// B: inline hook types
//   - very useful in simple scenarios (which are common!)
const MyComponent = () => {
  const result = useQuery<ConcreteQueryData, ConcreteQueryVar>(SomeConcreteQuery, {
     variables: {...}, // options types inferred
  });
  return <>...</>;
}

// C: creating reusable hooks from specific operations using typed options
// - sometimes we do this for queries we want to use in several places
// - it is (almost) exclusively how we use mutations 
const useConcreteQuery = (options: HookOptions<ConcreteQueryData, ConcreteQueryVar>) => {
  // arbitrary logic, pre-processing, validation, etc
  const result = useQuery(SomeConcreteQuery, options);
  // in 3.8, we'd have to duplicate the types and write:
  //   result = useQuery<ConcreteQueryData, ConcreteQueryVar>(SomeConcreteQuery, options)
  return result; // or some transformation of the result
}

// with the changes in `3.8.x`, we would have to change all instances
// of the above to add the types on the hook _as well_

const MyComponent = () => {
  const result = useConcreteQuery({
     variables: {...}, // typed as expected
  });
  return <>...</>;
}

// D: create reusable hooks for a _generic_ operation
//  - when you need a reusable hook, but it needs to work for many different (but similar) operations

interface RequiredData {
  // whatever
}
interface RequiredVars {
  // whatever
}

interface AdditionalOptions {
  // whatever
}

const useGenericHook = <Data extends RequiredData, Var extends RequiredVars>(doc, options: HookOptions<Data, Var>, additionalOptions: AdditionalOptions) => {
  return ... // non-trivial logic using the underlying Apollo hooks
}


const SomeOtherQuery = gql`query ...`
const YetAnotherQuery = gql`query ...`


const MyComponent = () => {
  const result1 = useGenericHook<ConcreteQueryData, ConcreteQueryVar>(ConcreteQuery, {
     variables: {...}, // typed as expected
  });
  const result2 = useGenericHook<SomeOtherQueryData, SomeOtherQueryVar>(SomeOtherQuery, {
     variables: {...}, // typed as expected
  });
  const result3 = useGenericHook<YetAnotherQueryData, YetAnotherQueryVar>(YetAnotherQuery, {
     variables: {...}, // typed as expected
  });
  return <>...</>;
}
```


IMO, what you're saying basically only concerns A and B which are common but are also the simplest possible usage pattern.

Type inference isn't important in such simple cases, but it makes a huge difference for more advanced use cases–essentially writing libraries around the Apollo hooks.

**Comment by jxdp** [comment] 2023-08-24 09:53
> I know you don't want to hear it, but A,B,C and D are possible with nice inference if you would be using `TypedDocumentNode`

Yes, but only by duplicating types, e.g.:

```ts
// D
const useGenericHook = <Data extends RequiredData, Var extends RequiredVars>(
  doc: TypedDocumentNode<Data, Var>,
  options: HookOptions<Data, Var>,
) => { ... }
```

> so I am really really really interested for your reasons why you insist on not using that. This is my third time asking. 

I believe I already gave one reason, which is wanting to avoid a runtime dependence on generated _objects_. Depending on generated objects at runtime is akin to having a runtime dependency on the generator, which we do not want. The bar for generated _objects_ (i.e. a runtime dependency) is **much** higher than for generated _types_ (i.e. a build dependency).

Again, the question is not whether things are possible using `TypedDocumentNode`, it is whether `TypedDocumentNode` is _required_. If they are not required then TypeScript should work fine without it–needing to copy/paste types all over the place is not what I would consider "working fine".

**Closed** 2023-09-05 09:21 UTC
Labels: 🐞 bug, ⛑ TypeScript
