### ISSUE TITLE
Receive data success but loading still TRUE

### ISSUE THREAD

**Issue by huynguyen2903** [apollographql/apollo-client#4730] opened 2019-04-19 18:11 UTC
![image](https://user-images.githubusercontent.com/40721082/56437287-f9012200-6308-11e9-9983-d537022599a5.png)
I received data from sever with no error but loading status still return true and never change to false. How I can fix it?
I'm using  `fetchPolicy="cache-and-network"`

**Comment by OurMajesty** [comment] 2019-04-22 12:49
probably duplicate of https://github.com/apollographql/react-apollo/issues/2899  
did you try react-apollo@2.4.1 ?

**Comment by mikevercoelen** [comment] 2019-08-02 10:55
Confirmed, we can't easily downgrade since most of our app components are built with `@apollo/react-hooks` which requires at least `2.6.2`

**Comment by hwillson** [comment] 2020-08-13 12:03
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!

**Closed by hwillson** 2020-08-13 12:03 UTC
Labels: 🏓 awaiting-response
