### ISSUE TITLE
Subscription is stopped after a message with errors is received

### ISSUE THREAD

**Issue by Emilios1995** [apollographql/apollo-client#6024] opened 2020-03-05 17:33 UTC
**Intended outcome:**
If one message from a subscription comes with errors from the server (for example if a non-nullable field was resolved to `null`) the subscription should stay subscribed for getting future messages.

**Actual outcome:**
The subscription is immediately stopped, I can see the `stop` message being sent over the `ws` connection. Is this intended behaviour? Is it somehow configurable?

**How to reproduce the issue:**
Open a subscription and send a GraphQL error from the server.

**Versions**
  System:
    OS: macOS 10.15.3
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3 
    apollo-cache-inmemory: ^1.4.3 => 1.6.3 
    apollo-client: 2.6.8 => 2.6.8 
    apollo-link: ^1.2.11 => 1.2.13 
    apollo-link-context: ^1.0.14 => 1.0.19 
    apollo-link-error: ^1.1.1 => 1.1.12 
    apollo-link-http: ^1.5.14 => 1.5.16 
    apollo-link-state: ^0.4.2 => 0.4.2 
    apollo-link-ws: ^1.0.19 => 1.0.19 
    apollo-utilities: ^1.1.3 => 1.3.3 
    react-apollo: 2.5.8 => 2.5.8 
    reason-apollo: 0.18.0 => 0.18.0 
    reason-apollo-hooks: https://github.com/Astrocoders/reason-apollo-hooks => 6.0.0

**Comment by DarrenAllen** [comment] 2020-07-14 20:46
@Emilios1995  I'm hitting this issue now as well. Any luck finding a workaround to this?

**Comment by xlucvvs** [comment] 2020-11-13 16:53
I'm having the same problem. Any solution?

**Comment by imprevo** [comment] 2021-02-12 05:37
I'm having the same issue with `apollo-client@2.6.10` and `apollo-link-ws@1.0.20`.
I tried to set `errorPolicy` to `ignore`, but it didn't help.
The only workaround is to catch the error on the server side. But this doesn't cover all cases. Any help?

**Comment by hwillson** [comment] 2021-04-29 19:08
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Comment by imprevo** [comment] 2021-06-09 11:28
I've upgraded my app to `@apollo/client3.3.15`. I'm still having the same issue.
I just throw error from a resolver as described above. You can see the error in payload and the stop message.
I also tried [shouldResubscribe](shouldResubscribe) option. It didn't help.

![image](https://user-images.githubusercontent.com/16841577/121345536-2c6ef280-c94f-11eb-9f1e-cd4a97938bf5.png)

**Comment by Mrtblg** [comment] 2021-08-12 13:40
Any news about this ?
Same problem here with latest version of apollo server and client.

I think we should at least have a props to control if an error message should close the subscription or not

**Comment by moonkev** [comment] 2021-11-17 16:32
@hwillson Is it possible to reopen this ticket?  I can confirm this is still an issue in 3.4.11.

**Comment by Stealthx9** [comment] 2021-11-23 15:52
I have the same problem. After an Error the Subscription is stuck

![image](https://user-images.githubusercontent.com/27856193/143057566-8aaeec1c-ab4b-4463-b1bf-8216c2cb033f.png)

**Comment by fredicious** [comment] 2022-04-15 11:20
Same issue here, this issue should be re-opened.

**Comment by RachelScodes** [comment] 2022-11-16 02:07
any update on this?

**Comment by jpvajda** [comment] 2022-12-13 19:44
Closing this issue. We'll work from #9109 as the main issue as this is related.

**Closed by jpvajda** 2022-12-13 19:44 UTC
Labels: 👯‍♂️ duplicate
