### ISSUE TITLE
[3.0] Querying data that is already in the cache sets loading to true

### ISSUE THREAD

**Issue by od1k** [apollographql/apollo-client#5757] opened 2020-01-06 17:23 UTC
We pre-cache a lot of data in our app so that switching between different screens can be instantaneous - without flickering and loading states.

**Intended outcome:**
When running some query:
```js
  const {
    loading,
    data
  } = useQuery(SOME_QUERY);
```
we expect that `loading` will be `false` if data is already in the cache (with default or `cache-only` `fetchPolicy`).

**Actual outcome:**
`loading` is `true` even when the requested data is in the cache.

I cannot tell if this is expected behaviour or not but it is definitely different from Apollo Client 2.6.

**How to reproduce the issue:**
I've created a reproduction that demonstrates this issue https://github.com/od1k/apollo-client-issue-1.

`master` branch contains a reference implementation with Apollo Client 2.6 which works as expected.
Branch `3.0` is updated to use Apollo Client 3 and exhibits the aforementioned behaviour.

Checkout branch `3.0`, start the app, verify that the data is in the cache using Apollo DevTools. 
Click `Show clock speed` button. The app will crash and the Console will contain a log showing that `loading` is set to `true`.

Verify that the app works as expected with Apollo Client 2.6 by checking out the `master` branch and repeating the procedure.

**Versions**
```
  System:
    OS: macOS 10.15.1
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 59.0.1
    Safari: 13.0.3
  npmPackages:
    @apollo/client: ^3.0.0-beta.19 => 3.0.0-beta.19 
```

**Comment by benjamn** [comment] 2020-01-17 15:54
This appears to be fixed in the latest version, `@apollo/client@3.0.0-beta.23`, likely due to #5791. Please feel free to reopen if the problem persists, and thanks for the reproduction!

**Closed by benjamn** 2020-01-17 15:54 UTC
Labels: :rose: has-reproduction, 🛬 fixed-in-prerelease
