### ISSUE TITLE
`refetch` promise with `fetchPolicy` 'cache-and-network' immediately resolves

### ISSUE THREAD

**Issue by amannn** [apollographql/apollo-client#5597] opened 2019-11-18 16:20 UTC
**Intended outcome:**

Calling `refetch()` on a query result that has `fetchPolicy: 'cache-and-network'` should return a promise that resolves once the request to the network has completed.

**Actual outcome:**

The promise resolves immediately, while the request to the network is still fired.

**How to reproduce the issue:**

Call `refetch` on a query with `cache-and-network` fetch policy and compare when the promise resolves and when the network request comes back.

I guess this happens because of these lines:
https://github.com/apollographql/apollo-client/blob/c00252f2d923d23285b76a24a2b5c151f9e87b96/packages/apollo-client/src/core/QueryManager.ts#L440-L444

However even for the `cache-first` fetch policy, the promise resolves after a network roundtrip:

https://github.com/apollographql/apollo-client/blob/c00252f2d923d23285b76a24a2b5c151f9e87b96/packages/apollo-client/src/core/ObservableQuery.ts#L307-L313

Would you be open to a PR that fixes this?

**Versions**

```

  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0.3
    Safari: 13.0.3
  npmPackages:
    @apollo/react-testing: ^3.1.3 => 3.1.3 
    apollo-cache-inmemory: 1.6.3 => 1.6.3 
    apollo-client: 2.6.4 => 2.6.4 
    apollo-link: 1.2.13 => 1.2.13 
    apollo-link-error: 1.1.12 => 1.1.12 
    apollo-link-http: 1.5.16 => 1.5.16 
    apollo-link-token-refresh: 0.2.7 => 0.2.7 
    react-apollo: ^3.1.3 => 3.1.3 
    react-apollo-network-status: 3.0.0 => 3.0.0 
  npmGlobalPackages:
    apollo-client: 2.5.1
    react-apollo: 3.1.3
```

**Comment by Pajn** [comment] 2019-11-19 07:55
This is the same as #5595, it's really nice if you have a fix for this!

**Comment by amannn** [comment] 2019-11-19 09:00
@Pajn Ah, right! It would be good to have confirmation from a core maintainer first though, as the code looks like this behaviour is intentional.

**Comment by seeruk** [comment] 2020-05-06 16:43
Also just ran into this issue - quite a frustrating one because I'm trying to add hide a modal after a mutation and subsequent refetch finishes, but instead the modal closes as soon as the mutation finishes, and the user is left waiting for the query to finish with no indication that the query is even happening.

**Comment by alxhotel** [comment] 2020-07-07 17:11
+1

**Comment by streamliner18** [comment] 2020-07-12 00:50
Same issue, +1

**Comment by skaplan** [comment] 2020-08-19 20:35
+1

**Comment by brandon-yetman** [comment] 2020-10-13 14:44
Same issue +1

**Comment by ivan-kleshnin** [comment] 2020-10-14 04:49
I think this is based on a wrong understanding of Apollo Fetch policies:

https://www.apollographql.com/docs/react/data/queries/#configuring-fetch-logic

> Calling refetch() on a query result that has fetchPolicy: 'cache-and-network' should return a promise that resolves once the request to the network has completed.

No it shouldn't. The behavior you describe is `cache-first` policy.

> The promise resolves immediately, while the request to the network is still fired.

^ and this is an exact description of `cache-and-network` behavior.

**Comment by devmao** [comment] 2020-10-30 16:54
+1

**Comment by hsavit1** [comment] 2020-12-01 23:24
+1

**Comment by macrozone** [comment] 2020-12-18 16:20
this can't be intentional and i am surprised that this has not been fixed. Its clear to me that anyone who uses `refetch` expects that it returns the most recent data. It's why we use `refetch` in the first place!

**Comment by hwillson** [comment] 2021-04-28 15:23
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Comment by hsavit1** [comment] 2021-04-28 15:32
@hwillson this is still a problem

**Comment by brainkim** [comment] 2021-04-28 15:39
@hsavit1 We’re doing a little spring cleaning because a lot of issues refer to old versions and are slightly outdated. I’ll make sure to look into this.

**Comment by brainkim** [comment] 2021-04-28 17:17
BTW if someone has a quick reproduction on this (https://github.com/apollographql/react-apollo-error-template), it does wonders for how quickly I can get to it :)

**Comment by brainkim** [comment] 2021-05-19 05:14
I tested this on latest 3.3.19 and this wasn’t a problem.

Here’s the reproduction I used:

```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';
import { gql, useQuery } from '@apollo/client';
import { graphql, setupWorker } from 'msw';

const userStore = [
  {
    __typename: 'User',
    id: 'a',
    name: 'evan you',
    hits: 0,
  },
  {
    __typename: 'User',
    id: 'b',
    name: 'donald knuth',
    hits: 0,
  },
  {
    __typename: 'User',
    id: 'c',
    name: 'hal abelson',
    hits: 0,
  }
];

const handlers = [
  graphql.query('getUsers', (_, res, ctx) => {
    return res(ctx.data({ users: userStore }));
  }),
  graphql.query('getSpecificUser', async (req, res, ctx) => {
    await new Promise((resolve) => setTimeout(resolve, 2000));
    const user = userStore.find(user => user.id === req.variables.id);

    if (!user) {
      return res(ctx.errors([{ message: `Cannot find user ${user}` }]));
    }

    try {
      return res(ctx.data({user: {...user}}));
    } finally {
      user.hits++;
    }
  }),
];

const worker = setupWorker(...handlers);
worker.start();
worker.printHandlers();

const GET_SPECIFIC_USER = gql`
  query getSpecificUser($id: String!) {
    user(id: $id) {
      id
      name
      hits
    }
  }
`;

function App() {
  const {loading, error, data, refetch} = useQuery(GET_SPECIFIC_USER, {
    variables: { id: 'b' },
    fetchPolicy: 'cache-and-network',
  });

  const onClick = async () => {
    console.log("REFETCHING");
    debugger;
    await refetch();
    console.log("REFETCHED");
  };

  return (
    <div>
      <button onClick={onClick}>Refetch</button>
      {
        loading
        ? <div>Loading</div>
        : error
        ? <div>Error: {error.toString()}</div>
        : <div>User: {JSON.stringify(data || null)}</div>
      }
    </div>
  )
}

const client = new ApolloClient({
  uri: '/graphql',
  cache: new InMemoryCache(),
});

ReactDOM.render(
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>,
  document.getElementById('root'),
);
```

```json
{
  "name": "apollo-client-8063",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "@apollo/client": "file:../../Projects/apollo-client/dist/apollo-client-3.3.19.tgz",
    "msw": "^0.28.2",
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@vitejs/plugin-react-refresh": "^1.3.1",
    "typescript": "^4.1.2",
    "vite": "^2.3.3"
  },
  "msw": {
    "workerDirectory": "public"
  }
}
```

As far as I can tell, the latest behavior is to wait for the network before settling the `refetch()` promise. If you believe this is an error hit me up with a reproduction of your own and I will reopen.

**Closed by brainkim** 2021-05-19 05:14 UTC
Labels: :wilted_flower: needs-reproduction
