### ISSUE TITLE
useMutation data is always undefined, only works in onCompleted

### ISSUE THREAD

**Issue by lsbyerley** [apollographql/apollo-client#7556] opened 2021-01-08 19:58 UTC
**Intended outcome:**
I am using the below mutation to update a tile object. The data in the `onCompleted` callback is correctly returning the updated data object. The data I'm returning in my wrapper is always undefined now. This seems to have recently changed and I'm not sure why

```
const useUpdateTile = () => {
  const [mutation, { data, loading, error }] = useMutation(UPDATE_TILE, {
    errorPolicy: 'all',
    onCompleted: (data) => {
      console.log('LOG: mutation updateTile completed', data);
    },
  });

  console.log('LOG: mutation updateTile', data);

  return {
    updateTile: (input) => {
      mutation({
        variables: {
          input,
        },
      });
    },
    loading,
    error,
    data: data?.updateTile || {},
  };
};
```

![Screen Shot 2021-01-08 at 2 52 48 PM](https://user-images.githubusercontent.com/3066258/104058092-31255400-51c1-11eb-86a7-66533088e30d.png)

**Actual outcome:**

I expect the data returned from the useMutation to contain the updated data object instead of being undefined. This was recently working as intended.

**How to reproduce the issue:**
Haven't been able to replicate in a codesandbox environment, it must be some other factor.
https://codesandbox.io/s/competent-visvesvaraya-ifzp9?file=/src/App.js

**Versions**
```
System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.10 - ~/mycode/node_modules/.bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 68.11.0
    Safari: 13.1.2
  npmPackages:
    @apollo/client: 3.3.6 => 3.3.6 
```

**Comment by sfratini** [comment] 2021-06-17 04:28
Seems to be solved by this, but I cant see a release with it https://github.com/apollographql/apollo-client/pull/8018

**Comment by dylanwulf** [comment] 2021-06-17 14:47
@sfratini The change in that PR is available in v3.3.16: https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-3316

**Comment by sfratini** [comment] 2021-06-24 02:13
FYI this is still an issue on 3.3.20.

**Comment by benjamn** [comment] 2021-06-25 18:14
@sfratini I don't see it when I update to 3.3.20 in https://codesandbox.io/s/nostalgic-firefly-rjhw7. Could you tweak that reproduction until it demonstrates the issue you're seeing?

**Comment by sfratini** [comment] 2021-06-26 01:13
> @sfratini I don't see it when I update to 3.3.20 in https://codesandbox.io/s/nostalgic-firefly-rjhw7. Could you tweak that reproduction until it demonstrates the issue you're seeing?

Actually I take that back. It does work, it just seems to show the data and then reset the value to undefined but it could just be my environment refreshing the state.

**Comment by brainkim** [comment] 2021-08-18 20:16
Closing because it seems like this has been fixed at some point by some person 😶

**Closed by brainkim** 2021-08-18 20:16 UTC
Labels: :rose: has-reproduction

**Comment by ichabanivan** [comment] 2022-04-25 07:48
How have you fixed that?

**Comment by up209d** [comment] 2022-05-18 01:53
The problem still insists and is inconsistent
