### ISSUE TITLE
fetchPolicy: 'network-only' returned inaccurate data, fetchPolicy: 'no-cache' returned correct data

### ISSUE THREAD

**Issue by kokokenada** [apollographql/apollo-client#10230] opened 2022-10-25 15:53 UTC
**Intended outcome:**
We observed the correct data in Chrome's network tab, yet when inspecting the JavaScript objects immediately after the promise resolved, an incorrect value was observed.    The attribute in question was a bool and was true in the JS object and false in the network tab. 

We worked around the issue by changing the fetch-policy from  'network-only' to fetchPolicy: 'no-cache'. 

There should be no difference between fetchPolicy: 'network-only' and fetchPolicy: 'no-cache', yet making that change fixed the problem we were observing.

**Actual outcome:**

 We worked around the issue by changing the fetch-policy from  'network-only' to fetchPolicy: 'no-cache'. 

**How to reproduce the issue:**
This is tough to do.  This is a big project and it was observed only with production data. Attempts at simpler replications failed. Opening a ticket to compare notes and to see if anyone has observed similar.

**Versions**
    "@apollo/client": "3.6.9",
System:
    OS: macOS 11.4
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/apps/hrh/csa/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 14.1.1

**Comment by dylanwulf** [comment] 2022-10-25 16:52
Hello, it's hard to tell for sure without more information but I've seen this issue several times before. Data discrepancies like this are usually caused by an `id` field which is not unique. Apollo client assumes that if a field is named `id` or `_id`, then it will be globally unique among ALL objects with the same `__typename`. For example, if you have `{ id: '1', someBool: true, __typename: 'MyObjectWithBool' }` and `{ id: '1', someBool: false, __typename: 'MyObjectWithBool' }` then Apollo client will assume these two objects are one and the same, and merges them together in the cache. Apollo client makes this assumption because it is a very commonly implemented pattern for GraphQL APIs to have globally unique id values. There's an easy way to fix this: [disable cache normalization](https://www.apollographql.com/docs/react/caching/cache-configuration/#disabling-normalization) for any types that do not have unique `id` fields. In my example with `MyObjectWithBool`, it would look something like this:
```js
const cache = new InMemoryCache({
    typePolicies: {
        MyObjectWithBool: {
            keyFields: false,
        },
    },
    ...otherCacheOptions,
});

const client = new ApolloClient({ cache, ...otherClientOptions });
```

**Comment by dylanwulf** [comment] 2022-10-25 16:59
See also: #10157, #10113, #9929

**Comment by dylanwulf** [comment] 2022-12-07 16:55
@ivari `network-only` is a bit of a weird one, it does still use the cache once the query has been successfully completed. If you want to make sure your query never gets any data from the cache you can use `no-cache` instead.

**Comment by jerelmiller** [comment] 2022-12-16 17:46
Hey @ivari 👋 

It seems like https://github.com/apollographql/apollo-client/issues/10230#issuecomment-1341272391 addresses your issue so I'm going to go ahead and close this. If you need more assistance, feel free to reopen this issue. Thanks!

**Closed by jerelmiller** 2022-12-16 17:46 UTC
Labels: :wilted_flower: needs-reproduction, 🔍 investigate
