### ISSUE TITLE
Apollo v3.6.8 and above throw `Uncaught TypeError: Cannot read properties of undefined (reading 'shift')` when running multiple writeFragment calls in a loop

### ISSUE THREAD

**Issue by mogzol** [apollographql/apollo-client#10262] opened 2022-11-04 21:16 UTC
**Intended outcome:**

This issue occurs when my app makes multiple calls to `client.writeFragment` in a loop, like this:

```javascript
for (const asset of result.model) {
  apolloClient.writeFragment({
    id: asset.id,
    fragment: UPDATE_ASSET_FRAGMENT,
    fragmentName: "UpdateAssetFields",
    data: asset,
  });
}
```

I would expect this to work fine, and it does work fine on all versions of Apollo prior to v3.6.8

**Actual outcome:**

On v3.6.8 of Apollo and later, on the second iteration of that loop (so the second `writeFragment` call), the following error is thrown:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'shift')
    at Object.complete (Concast.js:42:1)
    at Concast.removeObserver (Concast.js:113:1)
    at ObservableQuery.tearDownQuery (ObservableQuery.js:458:1)
    at ObservableQuery.js:33:1
    at cleanupSubscription (module.js:88:1)
    at Subscription.unsubscribe (module.js:203:1)
    at useQuery.js:115:34
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
```

**How to reproduce the issue:**

Unfortunately I'm not entirely sure how to reproduce this (EDIT: see first comment below for reproduction). I tried creating a new basic Apollo project with a single component and query and then running multiple writeFragments, but couldn't get the error to happen. I can tell you that it does happen reliably in my own app, and the change that caused it was this MR: https://github.com/apollographql/apollo-client/pull/9791

Specifically the change to ObservableQuery.ts on line 839:
```diff
- this.concast.removeObserver(this.observer, true);
+ this.concast.removeObserver(this.observer); 
```

If I add the second `true` argument back in, then the error is no longer thrown and everything works properly.

**Versions**

```
  System:
    OS: macOS 13.0
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 106.0.2
  npmPackages:
    @apollo/client: 3.6.8 => 3.6.8 
```

**Comment by mogzol** [comment] 2022-11-07 22:34
I've been investigating this more and have managed to reproduce the issue, see here: https://codesandbox.io/s/apollo-typeerror-demo-qygfem?file=/src/App.jsx

The issue seems to be caused by the `@export` query directive, which my app relies heavily on.

**Comment by Camsteack** [comment] 2023-01-29 22:23
Any update on this ? It's basically not possible to use the `@export` directive with React 18 ?

**Comment by mogzol** [comment] 2023-01-30 19:26
I would also appreciate an update on this. This is still preventing me from updating beyond Apollo 3.6.7 or upgrading my app to React 18.

**Comment by benjamn** [comment] 2023-02-06 20:58
@mogzol @Camsteack Fix incoming! https://github.com/apollographql/apollo-client/pull/10526

**Comment by jerelmiller** [comment] 2024-02-09 17:53
Hey all 👋 

It looks like this issue was fixed with [3.7.8](https://github.com/apollographql/apollo-client/releases/tag/v3.7.8) via https://github.com/apollographql/apollo-client/pull/10526. I've confirmed this by upgrading the [reproduction](https://codesandbox.io/p/sandbox/apollo-typeerror-demo-forked-fqqs7p?file=%2Fsrc%2FApp.jsx%3A43%2C1) and verifying the error has gone away. As such, I'm going to go ahead and close this issue. Thanks!

**Closed by jerelmiller** 2024-02-09 17:53 UTC
Labels: 🐞 bug, :rose: has-reproduction
