### ISSUE TITLE
`ReferenceError: __DEV__ is not defined` after update to `3.4.5` with `Next.js` app

### ISSUE THREAD

**Issue by FlorentD** [apollographql/apollo-client#8674] opened 2021-08-20 08:18 UTC
**Intended outcome:**
After updating to `3.4.5`, on our `Next.JS@11.1.0` app, we expect that our app launch with any problem. 

**Actual outcome:**
On our production bundle (everything works fine on dev mode), we got this message on runtime `ReferenceError: __DEV__ is not defined`. We had the same problem with the `3.4.0`, but it has been fixed on `3.4.1` following this issue #8557.
Something may have changed between `3.4.4` and `3.4.5`, and still here on `3.4.8`.

**How to reproduce the issue:**
Our repo is private but let me know if you want me to setup a simple exemple with NextJS / Apollo to have some tests. We have this problem on our every nextJS app using `@apollo/client>3.4.4`.

**Versions**

```
 System:
    OS: macOS 11.5.2
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0.1
    Safari: 14.1.2
  npmPackages:
    @apollo/client: 3.4.5 => 3.4.5
```

**Comment by benjamn** [comment] 2021-08-20 16:35
@FlorentD Can you share a stacktrace leading to the `ReferenceError`?

**Comment by FlorentD** [comment] 2021-08-23 10:14
@benjamn sorry for the delay, With production build and sourcemaps I've got this : 
```
index.js:416 ReferenceError: __DEV__ is not defined
    at g (createHttpLink.js:18)
    at Module.19487 (http.js:3)
    at r (bootstrap:21)
    at ?f000:5
    at route-loader.js:207
```

**Comment by FlorentD** [comment] 2021-08-25 16:30
Hello @benjamn. I'm not sure if `3.4.9` should fix this problem (I guess) but we still have the same error.

**Comment by benjamn** [comment] 2021-08-27 23:40
The problem seems fixed for me by `@apollo/client@3.4.10`, but I'll let @FlorentD and/or @freshollie confirm before I close the issue again. 🙏

**Comment by FlorentD** [comment] 2021-08-28 07:47
Hello @benjamn ! 
I can confirm `@apollo/client@3.4.10` fix the problem on our apps. No crash anymore !
A **BIG** thank you !

**Comment by oyed** [comment] 2021-08-28 11:58
Hmm, I just found this issue - this just started happening to me _after_ upgrading to `v3.4.10` using Vite & Vue.

**Comment by lauraseidler** [comment] 2021-08-30 10:49
Same issue here, the upgrade to `3.4.10` _causes_ the issue for me, using Vite & React, also only in production builds. `3.4.9` is fine.

**Comment by benjamn** [comment] 2021-08-30 13:53
@oyed @lauraseidler Could either of you provide a small reproduction?

**Comment by mikecousins** [comment] 2021-08-30 17:08
Yup, 3.4.10 blows up vite. I'll see if I can work up a sandbox for it.

**Comment by eugene1g** [comment] 2021-09-02 01:05
Same thing here: Vite (latest, `2.5.3`), breaks the production build with `3.4.10` in it with the error `ReferenceError: __DEV__ is not defined`. It works fine in dev mode. Apollo Client `3.4.9` works well, so for now we're staying on that version. Sorry, I don't have a clean reproduction example, only a +1 for the topic.

**Comment by lauraseidler** [comment] 2021-09-02 08:58
Hey @benjamn, here's a reproduction: https://github.com/lauraseidler/vite-apollo-3.4.10 - I've had TypeScript in there at first, but removed it now - the problem appears either way.

**Comment by Arenukvern** [comment] 2021-09-08 19:16
> Same thing here: Vite (latest, `2.5.3`), breaks the production build with `3.4.10` in it with the error `ReferenceError: __DEV__ is not defined`. It works fine in dev mode. Apollo Client `3.4.9` works well, so for now we're staying on that version. Sorry, I don't have a clean reproduction example, only a +1 for the topic.

I fixed vite error by defining __DEV__ in index.html 
I've tried to define it in main by it seems like vite removes it.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
    <script>
      this['__DEV__'] = false
    </script>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
```

**Comment by davidbarral** [comment] 2021-09-09 07:15
Vite users can use a function in vite.config.js and set a [define](https://vitejs.dev/config/#define) option:

```
export default ({ mode }) => ({
  define: {
    "__DEV__":  mode === "development",
  },
});
```

**Comment by benjamn** [comment] 2021-09-09 21:36
@davidbarral That sounds like the best solution ultimately, but I'm still hopeful we can make this work out-of-the-box with no configuration.

**Comment by dchenk** [comment] 2021-09-10 03:18
> Vite users can use a function in vite.config.js and set a [define](https://vitejs.dev/config/#define) option

@davidbarral's solution worked for me with this `vite.config.ts` file:
```
import { ConfigEnv, defineConfig } from 'vite';
import viteSSR from 'vite-ssr/plugin';
import reactRefresh from '@vitejs/plugin-react-refresh';

export default defineConfig((env: ConfigEnv) => ({
  plugins: [
    viteSSR(),
    reactRefresh()
  ],
  define: {
    '__DEV__': (env.mode === 'development').toString()
  },
}));
```
The relevant parts are that you need to pass a function to `defineConfig` and to specify the `define` object.

**Comment by davidbarral** [comment] 2021-09-10 06:48
> @davidbarral That sounds like the best solution ultimately, but I'm still hopeful we can make this work out-of-the-box with no configuration.

Yep, I hope so too 😃

**Comment by gunters63** [comment] 2021-09-10 07:27
Using a define __DEV__ in vite unfortunately doesn't work for me. One of my indirect dependencies (npm module `warning`) has a line like this:

````
var __DEV__ = process.env.NODE_ENV !== 'production';
````

which of course breaks the build:

````
[commonjs] Unexpected keyword 'false' (17:4) in D:/proj/AtlasCopco/EnsoUi/node_modules/.pnpm/warning@4.0.3/node_modules/warning/warning.js
````

The workaround with defining __DEV__ in index.html works fine.

**Comment by benjamn** [comment] 2021-09-10 23:22
Alright, @lauraseidler's reproduction from https://github.com/apollographql/apollo-client/issues/8674#issuecomment-911417247 (thanks for that!) seems to be fixed (by #8767), so I encourage everyone using Vite (or having similar problems) to try updating to `@apollo/client@3.4.11` or `@apollo/client@3.5.0-beta.12`.

If #8767 turns out to be the full solution, this regression was due to aggressive tree-shaking by Vite, but was fixable on the Apollo Client side, so you shouldn't need to configure anything to make it work now.

**Comment by mikecousins** [comment] 2021-09-10 23:57
Confirmed working for us.

**Comment by FlorentD** [comment] 2021-09-11 15:06
…and still work on Next.js! :-D

**Comment by benjamn** [comment] 2021-09-13 13:27
Based on early feedback, I'm optimistic this is fixed now. Thanks to everyone for surfacing your issues and being patient while we iron out the kinks in this new `__DEV__` system, especially in its relationship to popular build tools. Happy to reopen if similar issues persist.

**Closed by benjamn** 2021-09-13 13:27 UTC
Labels: 🐞 bug, 🛠 tooling, size/small, 2021-09

**Comment by alanquigley-toast** [comment] 2021-09-21 23:44
I noticed some strange behaviour around fastRefresh, tracked down to https://github.com/apollographql/apollo-client/pull/7952, but this seemed to be fixed already?. Turns out __DEV__ always returns false, so the fastRefresh fix is never applied.

We have a micro-frontend architecture, its possible during development that two applications with their own versions of Apollo can be on a page at the same time. Would this cause __DEV__ to be set to false, Im struggling to find the any point where __DEV__ gets set to false

**Comment by escapedcat** [comment] 2021-09-28 04:05
Wanted to update from `3.4.11` → `3.4.13` (or `3.4.12`) and getting this error now as well/still:  
```sh
node_modules/@apollo/client/utilities/globals/global.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEV__'.
```

**Comment by loick** [comment] 2023-01-15 10:38
Hi there, I'm still seeing this issue on Next13, using the "old" Next12 middlewares on Vercel. Do you have any workaround for this? 

Thanks 🙏
