### ISSUE TITLE
useSubscription "loading" and "data" out of sync when used with other hooks

### ISSUE THREAD

**Issue by christophediprima** [apollographql/apollo-client#7198] opened 2020-10-20 13:21 UTC
I am using version 3.2.4 of @apollo/client and there is no way of using a useEffect to check when loading moves from true to false with new data when you have other hooks changing state. 
You simply get `loading` back to `false` and the old data as soon as you are using other hooks that changes the state of your component.

**Comment by christophediprima** [comment] 2020-10-22 14:26
We finally found a work around for this issue. 

We don't use the returned values of the `useSubscription` hook anymore but manually maintain a state containing `loading` and `data`. We have a usEffect hook, that sets the `loading` state to `true` when subscription variable changes and we set it back to `false` with the new `data` in the `onSubscriptionData` that way we can be sure that when `loading` moves from `true` to `false` we have the new data with it.

```javascript
const [subscriptionState, setSubscriptionState] = React.useState({
    data: undefined,
    loading: true,
});
  
const prevSubscriptionVariables = usePrevious(subscriptionVariables);

useEffect(() => {
   if (!equals(subscriptionVariables, prevSubscriptionVariables)) {
      setSubscriptionState({
         data: undefined,
         loading: true,
      });
   }
},
[subscriptionVariable, prevSubscriptionVariable]);

 useSubscription(CAPTURE_AGGREGATE_SUBSCRIPTION, {
    onSubscriptionData: ({subscriptionData}) => {
      setSubscriptionState({
        data: subscriptionData.data,
        loading: false,
      });
    },
    variables: subscriptionVariables,
  });

const previousSubscriptionState = usePrevious(subscriptionState)
useEffect(() => {
   if(previousSubscriptionState.loading && !subscriptionState.loading){
      console.log("Here is your new data after changing variable", subscriptionState.data)
   }
}, [subscriptionState, previousSubscriptionState]);
```

Hope this will help someone and that this will be fixed soon in the `useSubscription` hook. I had a look the hook trying to figure out why it was happening but couldn't find out a solution.

**Comment by mzbyszynski** [comment] 2020-11-25 20:19
We are running into this same bug. As far as I can tell this problem is caused because the `useSubscription` hook stores the most recent data returned by the subscription in state, but it doesn't store or update that state when the variables change. In that case a render is triggered and the hook returns `{ loading: true, data: undefined }`, but still has the previous data in state. If another render is triggered after that by anything other than data being returned from the subscription, then the old data `useSubscription` still has in state will be returned. 

I *think* the right way to fix this would be for `useSubscription` to also store the `loading: true` state change in state, or at least update the `data` stored in state to `undefined` when loading starts, so that after a variable change the hook would return `data: undefined` until some new data actually came through the subscription.

I tried making this change to `useSubscription.ts` but it broke a lot of unit tests so I'm not super confident about it. In any event it would be a bigger than 20 line change so I think even if it is the correct fix, it would qualify as a [Big PR](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#big-prs).

Would love to get some feedback from someone more familiar with the `useSubscription` and the `SubscriptionData` class. Maybe @hwillson?

**Comment by christophediprima** [comment] 2021-05-19 10:01
@mzbyszynski do you have something new about this?

**Comment by devaublanc** [comment] 2021-06-29 11:38
@christophediprima Same issue here 

**TEST OK (expected behavior)**

```typescript
export const SearchProducts = ({ route }: Props) => {


  const [selectedCategory, setSelectedCategory] = useState<string | null>('');


  const { data, loading } = useSubscription<
    categorySubcategoriesSubscription,
    categorySubcategoriesSubscriptionVariables
  >(CATEGORY_SUBCATEGORIES_SUBSCRIPTION, {
    variables: {
      warehouseId: "1735cdf5-1332-4407-8e72-705114e55b58",
      categoryId: selectedCategory,
    },
    skip: !selectedCategory

  });
 
 console.log('===DEBUG===', data?.subcategories, selectedCategory, loading)

  if (loading) return <Loader />


  return (
    <ScrollView contentContainerStyle={{ paddingTop: 100 }}>

      <Button
        title="A"
        onPress={() => { setSelectedCategory('7914b7b4-5c35-4b02-9592-f44567b22566') }} />
      <Button
        title="B"
        onPress={() => { setSelectedCategory('76ffd6e1-0498-46a8-aeb2-4caac26b48a6') }} />
     
      <Text>SELECTED CATEGORY : {selectedCategory}</Text>

      {data?.subcategories.map(cat => {
        return <Text key={cat.id}>{cat.name}</Text>
      })}

    </ScrollView>
  );
};
```

Press CATEGORY A
```
render 1
data: undefined
loading: true

render 2
data: {...data CATEGORY_A...}
loading: true
```

Press CATEGORY B
```
render 1
data: undefined
loading: true

render 2
data: {...data CATEGORY_B...}
loading: false
```


=======================================================================================
**TEST KO by adding the useEffect: with bad old state data and wrong loading state**

```typescript
export const SearchProducts = ({ route }: Props) => {


  const [selectedCategory, setSelectedCategory] = useState<string | null>('');
  const [foo, setFoo] = useState<number>();


  const { data, loading } = useSubscription<
    categorySubcategoriesSubscription,
    categorySubcategoriesSubscriptionVariables
  >(CATEGORY_SUBCATEGORIES_SUBSCRIPTION, {
    variables: {
      categoryId: "A",
    },
    skip: !selectedCategory

  });

 
// We add this useEffect to do the wrong behavior
  useEffect(() => {
    setFoo(Math.round(Math.random() * (100 - 1) + 1));
  }, [selectedCategory])

 console.log('===DEBUG===', data?.subcategories, selectedCategory, loading)

  if (loading) return <Loader />




  return (
    <>

      <Button
        title="CATEGORY A"
        onPress={() => { setSelectedCategory('A') }} />
      <Button
        title="CATEGORY B"
        onPress={() => { setSelectedCategory('B') }} />
     
      <Text>SELECTED CATEGORY : {selectedCategory}</Text>

      {data?.subcategories.map(cat => {
        return <Text key={cat.id}>{cat.name}</Text>
      })}

    </>
  );
};
```

Press CATEGORY A
```
render 1
data: undefined
loading: true

render 2
data: {...data CATEGORY_A...}
loading: true
```

Press CATEGORY B
```
render 1
data: undefined
loading: true

render 2
data: {...data CATEGORY_A...} // old state data
loading: false

render 3
data: {...data CATEGORY_B...}
loading: false
```

**Comment by Avi-Cohen-Nehemia** [comment] 2022-03-21 14:51
Hey 👋🏼
I'm dealing with the same issue right now, is this going to be fixed? I see there is an open PR for this from July last year

**Comment by Amir-Pasha-Bagheri** [comment] 2022-12-13 06:43
> Hi, I am facing the same issue.
> 
> ```
>   const { newPostData, newPostLoading, newPostError } = useSubscription(  
> 	NEW_POST,
> 	{
> 		onSubscriptionData: (data) => {
> 			console.log("onSubscriptionData", data);
> 		},
> 	}   
>   );
> ```
> 
> the `newPostData, newPostLoading, newPostError` are always undefined, but inside the onSubscriptionData, it actually has the data I wanted.

You have forgotten to write data , loading and error behind them , it should be like

`const { data : newPostData, loading : newPostLoading, error : newPostError } = useSubscription`

**Comment by phryneas** [comment] 2024-08-01 11:08
We recently released a rewrite of `useSubscription` in [Version 3.11](https://github.com/apollographql/apollo-client/releases/tag/v3.11.0).

Data is now synchronized using `useSyncExternalStore`, just like in `useQuery` - and I believe the bug you were surfacing here should not happen anymore.

If you find any problems with `useSubscription` after 3.11, please open a new issue. I'm closing this issue since the code that originally caused this issue is not part of the library anymore.

**Closed by phryneas** 2024-08-01 11:08 UTC
Labels: 🛎 subscriptions, 🏓 awaiting-team-response
