### ISSUE TITLE
Feature idea: conditional refetchQueries

### ISSUE THREAD

**Issue by trevordmiller** [apollographql/apollo-client#2143] opened 2017-09-11 18:10 UTC
Currently, Apollo outputs a `unknown query with name {Query} asked to refetch` warning whenever a mutation is run that has a `refetchQuery` that hasn't been run yet (which occurs often, since users can start on different routes). 

![image](https://user-images.githubusercontent.com/5497885/30068421-058b3f80-921b-11e7-8331-378c7e7ca715.png)

It would be great if `refetchQuery` only ran if the related query has already run at least once instead of showing this warning.

I'm using the query name as a string for the `refetchQueries` arg like:

```
  graphql(
    gql`
      mutation {
        someMutation {
          someField
        }
      }
    `,
    {
      options: {
        refetchQueries: ['SomeQuery', 'AnotherQuery'],
      },
    }
  ),
```

**Comment by trevordmiller** [comment] 2017-09-18 22:27
@stubailo, @helfer any thoughts on this? Is there something I'm missing? Thank you so much for your great work, apollo-client is fantastic!

**Comment by johncrisostomo** [comment] 2017-10-06 08:26
I am also experiencing the same thing. They are errors and I still have the intended side effect; the yellow warning line is jut annoying :(

**Comment by jbaxleyiii** [comment] 2017-10-10 14:49
hmm, this is an interesting issue. I'll see if I can improve this with the 2.0 or immediately following. Do you have a sample app / reproduction I can use to see this?

**Comment by trevordmiller** [comment] 2017-10-10 16:28
@jbaxleyiii That would be fantastic, thank you. I don't have a sample app, but to reproduce just make some route-level components that use `refetchQueries` like this:

```
graphql(
  gql`
    mutation {
      someMutation {
        someField
      }
    }
  `,
  {
    options: {
      refetchQueries: ['SomeQuery', 'AnotherQuery'],
    },
  }
),
```

Then refresh the app at different routes and the routes with refetchQueries for other routes will throw the errors.

**Comment by jbaxleyiii** [comment] 2017-10-11 05:57
@trevordmiller so the warnings are there as a help to prevent things like one off spelling mistakes where you are trying to update a query but it doesn't exist yet. I think I understand the use case you have though to generically try and refetch a few possible queries even if they haven't been run yet.

I think its probably best to remove the warning since the use case is more important to support than warnings for mistaken code

**Comment by johncrisostomo** [comment] 2017-10-11 06:05
The verbatim warning that it throws is:

```
Warning: unknown query with name <query name in refetch array> asked to refetch
```

I also think that just removing this warning will sort this because everything works fine and it doesn't stop or crash anything, it's just that the yellow warning line stacks up on React Native (iOS simulator). :)

**Comment by jbaxleyiii** [comment] 2017-10-11 07:42
Fixed in what will be `beta-7` https://github.com/apollographql/apollo-client/pull/2281

**Closed by jbaxleyiii** 2017-10-11 07:42 UTC

**Comment by trevordmiller** [comment] 2017-10-11 16:29
@jbaxleyiii Thank you so much!
