### ISSUE TITLE
Type Error on Safari

### ISSUE THREAD

**Issue by gilbert** [apollographql/apollo-client#2961] opened 2018-02-05 18:52 UTC
apollo-client is throwing a strange, nondescript error when making a client-side graphql query. This is only happening in Safari:

<details>
<summary>Error: Network error: Type error</summary>
ApolloError — ApolloError.js:36
currentResult — ObservableQuery.js:89
dataForChild — react-apollo.browser.umd.js:542
render — react-apollo.browser.umd.js:592
finishClassComponent — react-dom.development.js:7873
performUnitOfWork — react-dom.development.js:10224
workLoop — react-dom.development.js:10288
callCallback — react-dom.development.js:542
dispatchEvent
invokeGuardedCallbackDev — react-dom.development.js:581
invokeGuardedCallback — react-dom.development.js:438
renderRoot — react-dom.development.js:10366
performWorkOnRoot — react-dom.development.js:11014
performWork — react-dom.development.js:10967
requestWork — react-dom.development.js:10878
scheduleWorkImpl — react-dom.development.js:10732
enqueueForceUpdate — react-dom.development.js:6250
forceUpdate — react.development.js:255
forceRenderChildren — react-apollo.browser.umd.js:510
next — react-apollo.browser.umd.js:485
error — zen-observable.js:176
forEach
error — ObservableQuery.js:328
(anonymous function) — QueryManager.js:275
(anonymous function) — QueryManager.js:649
forEach
(anonymous function) — QueryManager.js:648
forEach
broadcastQueries — QueryManager.js:643
(anonymous function) — QueryManager.js:217
promiseReactionJob
</details>

.

Digging deeper, I found the cause of the issue to be [this line](https://github.com/apollographql/apollo-link/blob/7c381e985a44a3e4f41551c9c7860f6e630d6466/packages/apollo-link-http/src/httpLink.ts#L242):

    fetcher(contextURI || uri, fetcherOptions)

Here's what I found upon console logging each item:

- fetcher - `function fetch { [native code] }`
- contextURI - `undefined`
- uri - `http://localhost:3003/graphql`
- fetcherOptions - `{}`

Note that **this is a CORS request**. It works fine in chrome. However, I can't figure out why it's not working in safari. When I write `fetch('http://localhost:3003/graphql', {})` inside the safari js console, it works perfectly. For some reason it's a problem as an apollo request.

Also note that if `fetch` [throws a TypeError](Checking_that_the_fetch_was_successful), it means there's a network error or misconfigured CORS. But I'm not seeing the request at all on the server (I'm logging all requests), so I'm not sure what's happening.

**Version**
- apollo-client@2.2.1

**Comment by hwillson** [comment] 2018-05-12 09:29
We're not able to reproduce this issue, so if it's still happening please point us towards a small runnable reproduction. Closing for now - thanks!

**Closed by hwillson** 2018-05-12 09:29 UTC
Labels: can't-reproduce

**Comment by dai-shi** [comment] 2018-05-12 14:12
@gilbert I had the same error today, but it's not a CORS request.
After digging into it, I found `fetch('...', { credentials: null })` causing the error.

Because I'm using `apollo-link-rest`, the problem is probably from https://github.com/apollographql/apollo-link-rest/blob/c92eafe785fa2a799a01cc1dc10f57b0028b916b/src/restLink.ts#L710 setting it even if it's `null`.

This is my workaround.
```
const customFetch = (url, options) => {
  if (options.credentials === null) {
    delete options.credentials;
  }
  return fetch(url, options);
};
```

----
I'm not quire sure if this issue is also in `apollo-link-http`. It looks like in https://github.com/apollographql/apollo-link/blob/a79f47e8ae81ee2444d547315be61dbafea37dcb/packages/apollo-link-http-common/src/index.ts#L204 the credentials is `undefined` by default, which doesn't raise the error.

So, this is just for your information.

**Comment by dai-shi** [comment] 2018-05-12 14:27
Oops, I wasn't careful enough.

> fetcherOptions - `{}`

So, it's a different case. Sorry about that.
