### ISSUE TITLE
useQuery returns undefined data after clearStore()

### ISSUE THREAD

**Issue by Paduado** [apollographql/apollo-client#6695] opened 2020-07-25 01:23 UTC
**Intended outcome:**
I'm fetching a query like this:
```js
let headers;

if (logged) {
  headers = {
    authorization: `Bearer test`
  };
}

const { data } = useQuery(QUERY, {
  context: {
    headers
  }
});
```
I was hoping that when I changed the headers of the request a refetch would happen, but I'm getting the previous cached response instead.

So I thought that by doing `client.clearStore()` before changing the `logged` flag would result in the cache being cleared and a fresh network request to be sent.

**Actual outcome:**
A new network request is being sent and completed successfully, however the `data` property of the response comes with the value `undefined`.

**How to reproduce the issue:**
[Sandbox](https://codesandbox.io/s/apollo-clearstore-issue-9qfvb)

**Comment by dminkovsky** [comment] 2020-07-25 18:13
Possibly a dupe of #6044 and discussed here https://github.com/apollographql/apollo-client/issues/6359?

**Comment by hwillson** [comment] 2021-05-04 15:42
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!

**Closed by hwillson** 2021-05-04 15:42 UTC
