### ISSUE TITLE
Cursor jumping to end of controlled input when using `writeQuery`.

### ISSUE THREAD

**Issue by jkyle** [apollographql/apollo-client#6827] opened 2020-08-12 16:03 UTC
**Intended outcome:**

Hey, y'all! We are using data from a query as the `value` for a controlled input and using `apolloClient.writeQuery` to update the data in the Apollo cache. In version `3.0.0-beta.44` and prior, this was working as we'd expect:

![v3 0 0-beta 44 controlled input](https://user-images.githubusercontent.com/100188/90024366-65c8ca00-dc7a-11ea-8389-7e2a4f76225a.gif)

Notice the cursor remains in-place as new characters are added to the input.

The relevant change handler looks like this:

```js
  const onHandleChange = (personId, value) => {
    const people = data.people.map((person) =>
      person.id === personId ? { ...person, name: value } : person
    );

    apolloClient.writeQuery({
      query: ALL_PEOPLE,
      data: { people },
    });
  };
```

And the code for the inputs:

```js
{data.people.map((person) => (
  <li key={person.id}>
    <input
      value={person.name}
      onChange={(e) => onHandleChange(person.id, e.target.value)}
    />
  </li>
))}
```

**Actual outcome:**

Since version `3.0.0-beta.45` (up to the most recent release), the same code results in a situation where each keystroke causes the cursor to jump to the end of the input:

![v3 1 controlled input](https://user-images.githubusercontent.com/100188/90024731-d243c900-dc7a-11ea-9bff-01fa8eedcfa1.gif)

**How to reproduce the issue:**

I've reproduced the issue in this fork of `react-apollo-error-template`: https://github.com/jkyle/react-apollo-error-template

Specifically in [App.js](https://github.com/jkyle/react-apollo-error-template/blob/master/src/App.js):
1. Use a property from a query as the `value` of a controlled input.
2. Use `apolloClient.writeQuery` to update that value in the cache from the `onChange` of the controlled input.

We've tried wrapping the controlled input in a component with a `React.memo`, and also using a `useCallback` (adding a `readQuery` to remove a dependency on `data.people`). Neither had any impact on the issue. My best guess so far is that something in PR #6107 is causing the problem, but we might be missing something obvious.

(Note: I created a [`v3.0.0-beta.44`](https://github.com/jkyle/react-apollo-error-template/blob/v3.0.0-beta.44/) branch that installs that version of `v3.0.0-beta.44` of Apollo to compare.)

**Versions**

```
  System:
    OS: macOS Mojave 10.14.3
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.13.1/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Firefox: 79.0
    Safari: 12.0.3
  npmPackages:
    @apollo/client: ^3.1.0 => 3.1.0 
```

**Comment by benjamn** [comment] 2020-08-12 21:54
This is likely the same issue as #3338, which was ultimately due to https://github.com/facebook/react/issues/955. The [final recommendation](https://github.com/facebook/react/issues/955#issuecomment-469352730) to call `setState` synchronously from the event handler doesn't help here, because writing to the cache triggers a broadcast that ultimately causes the `<input/>` to rerender in a different tick of the event loop (asynchronously rather than synchronously).

Instead of trying to make the rerendering happen synchronously, you can make the selection state more robust to rerendering by wrapping your `<input/>` in a React component:
```js
function SelectionPreservingInput({ value, onChange }) {
  const inputRef = React.useRef(null);
  const selectionRef = React.useRef({
    start: 0,
    end: 0,
  });

  function saveSelection() {
    selectionRef.current.start = inputRef.current.selectionStart;
    selectionRef.current.end = inputRef.current.selectionEnd;
  }

  function restoreSelection() {
    inputRef.current.selectionStart = selectionRef.current.start;
    inputRef.current.selectionEnd = selectionRef.current.end;
  }

  React.useEffect(restoreSelection);

  return <input
    value={value}
    ref={inputRef}
    onChange={function (event) {
      saveSelection();
      return onChange.call(this, event);
    }}
  />;
}
```
Given this wrapper component, try replacing your `<input ... />` component with `<SelectionPreservingInput ... />`. Thanks to your reproduction, I can report that it seems to work pretty well, though I'm sure you can find ways to improve this code if you decide to keep using it.

If typing ever becomes too slow because you're writing to the cache on every keystroke, you might try using a tool to throttle the event handler, like [`debounce`](https://www.npmjs.com/package/debounce).

**Comment by jkyle** [comment] 2020-08-13 14:17
Thanks for the reply @benjamn. That makes sense, and explains how the fix in #6107 (_Prevent new data re-render attempts during an existing render._) might be what started started causing this issue for us.

We were hoping to use Apollo as our primary solution for state management without needing to rely on React's various state hooks or Redux for local state (for editing forms and whatnot). That workaround for managing selection state does seem to work, but might a bit too much of a hack to use across our whole app. 

The documentation makes it seem like managing local state like this is a goal of Apollo Client. I'm curious if there's a best practice for editing data in a form before calling a mutation to send changes back to the server that we might be missing?

Thanks again for all y'all's work!

**Comment by jkyle** [comment] 2020-08-13 17:43
Big fan of that talk! I think someone mentioned it during Apollo Space Camp a couple months ago. I think our best bet will be to transfer the data from the Apollo cache to Reactspace local state for editing, and then call a mutation later to update the cache. Something like a `useState` or `useReducer`:

```js
  const { loading, data } = useQuery(ALL_PEOPLE);
  const [people, setPeople] = useState([]);

  useEffect(() => {
    if (data?.people) {
      setPeople(data.people);
    }
  }, [data]);

  const onHandleChange = (personId, value) => {
    setPeople((previousPeople) =>
      previousPeople.map((person) =>
        person.id === personId ? { ...person, name: value } : person
      )
    );
  };
```

Thanks again for the feedback!

**Comment by hwillson** [comment] 2021-05-05 15:05
It doesn't sound like there is an outstanding issue here, so closing. Thanks!

**Closed by hwillson** 2021-05-05 15:05 UTC
Labels: ⚛️ React-related, 🌤 has-workaround
