### ISSUE TITLE
apollo-boost onError handler missing forward function?

### ISSUE THREAD

**Issue by ovaris** [apollographql/apollo-client#4011] opened 2018-10-16 06:40 UTC
**Intended outcome:**
Implement custom onError handler that refreshes JWT token when "unauthenticated" error is received.
Following this example: https://blog.apollographql.com/full-stack-error-handling-with-graphql-apollo-5c12da407210

**Actual outcome:**
`onError` handler is not called with `forward` function,
throwing `TypeError: forward is not a function`

**How to reproduce the issue:**
Just pass this for ApolloClient (imported from apollo-boost):
```
onError: ({ graphQLErrors, networkError, operation, forward }) => {
    if (graphQLErrors) {
      graphQLErrors.forEach(async err => {
        console.log(`[GraphQL error]: ${err.extensions.code}`);
        if (err.extensions.code === 'UNAUTHENTICATED') {
          const oldHeaders = operation.getContext().headers;
          operation.setContext({
            headers: {
              ...oldHeaders,
              authorization: await refreshAccessToken(),
            },
          });
          console.log('CONTEXT', operation, forward);
          return forward(operation);
        }
      });
    }
    if (networkError) {
      console.log(`[Network error]: ${networkError}`);
    }
  },
```
**Versions**
```

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 9.10.0 - /usr/local/bin/node
    Yarn: 1.9.4 - ~/nnn/nnn/node_modules/.bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 12.0
  npmPackages:
    apollo-boost: ^0.1.16 => 0.1.16 
    apollo-cache-inmemory: ^1.3.5 => 1.3.5 
    apollo-link-error: ^1.1.1 => 1.1.1 
    react-apollo: ^2.2.4 => 2.2.4 
  npmGlobalPackages:
    apollo-codegen: 0.19.1
    apollo: 1.6.0
```

**Comment by a-di-ez** [comment] 2019-02-14 13:36
+

**Comment by gajus** [comment] 2019-03-13 12:08
FYI, I cannot replicate the issue.

**Comment by abernix** [comment] 2019-07-12 18:28
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already, though it's difficult to determine quickly if that's the case or not without a runnable or cloneable reproduction of the problem.  It appears that others are unable to reproduce this as well.

If this is still a problem, we welcome anyone who is experiencing the problem (or anyone who comes across this issue and is able to assist) to build a reproduction of the problem into a runnable CodeSandbox reproduction](https://codesandbox.io/), using the latest versions of the appropriate packages, and sharing the link to that reproduction in this issue.

I'm happy to re-open if this is still occurring and someone can provide a reproduction!

**Closed by abernix** 2019-07-12 18:28 UTC
