### ISSUE TITLE
replacing/removing redux

### ISSUE THREAD

**Issue by ahmad2smile** [apollographql/apollo-client#2832] opened 2018-01-08 09:36 UTC
I convinced my team to setup apollo server for a react native app but when I dove into the documentation for apollo client 2.0 there were horrors of the earth.

I'm using

redux-persist
redux-forms
react-navigation (with redux)
redux-saga (which I was willing to kill)

How I can possibly replace all of these just cause you decided that a faster cache implementation was worth sacrificing redux without any considerations for the community.

Going against redux would be the biggest mistake by @apollographql

**Comment by n1ru4l** [comment] 2018-01-08 09:53
Duplicate of #2273 

The apollo cache is pluggable. Therefore you can implement your own cache which uses redux. 

Someone already did this (I did not use it, since I am fine without redux): https://github.com/rportugal/apollo-cache-redux

**Comment by Poincare** [comment] 2018-01-26 11:08
I believe @n1ru4l  has answered this question, so I'm going to go ahead and close this issue. Please just reopen it in case there is something that still needs to be discussed.

**Closed by Poincare** 2018-01-26 11:08 UTC
