### ISSUE TITLE
FetchMore result not passed to component if using union types

### ISSUE THREAD

**Issue by lucasfeliciano** [apollographql/apollo-client#1568] opened 2017-04-10 10:31 UTC
Issue from: https://github.com/apollographql/react-apollo/issues/602 that @rpylipow reported.

I wasn't quite sure if this belongs here or apollo-client as it somewhat relates to [apollographql/apollo-client#1523](https://github.com/apollographql/apollo-client/issues/1523 "Union types & fetchMore not working together"), however my `fetchMoreResult` returns the expected results. The issue is that the new result isn't passed into my component if I'm using Union types.

**Intended outcome:**  
I'm attempting to use `fetchMore` with limit/offset. My query contains union types. I'd expect that after I concat `fetchMoreResult` with my previous result it would be passed into my component.

**Actual outcome:**  
The new result isn't passed into the component. I have an `author` prop which indicates the author of the post. It can be an individual user or a company (each entity has unique properties). If I remove the `author` prop from my `GetPosts` query, everything works as expected with the `newResult` being passed into my component. This leads me to believe that the union type is the culprit.

**How to reproduce the issue:**

```js
import React from 'react';
import { View, Text } from 'react-native';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

const GetPosts = gql`query GetPosts($limit: Int, $offset: Int) {
  posts(limit: $limit, offset: $offset) {
    _id
    message
    createdAt
    scheduledAt
    authorType 
    author {
      ... on User {
        _id
        avatarUrl
        profile {
          firstName
          lastName
        }
      }
      ... on Company {
        _id
        name
        logo80
      }
    }
  }
}
`;

class TestComponent extends React.Component {
  render() {
    // I would expect this to log the new props after press "loadMore"
    console.log(this.props)
    return (
      <View style={{marginTop: 40}}>
        <Text onPress={this.props.loadMore}>Push me</Text>
      </View>
    )
  }
}

export default graphql(GetPosts, {
  options: () => ({
    variables: {
      offset: 0,
      limit: 1
    }
  }),
  props: ({ ownProps, data }) => {
    return {
      ...ownProps,
      posts: data.posts,
      loadMore: () => {
        return data.fetchMore({
          variables: {
            offset: 1,
            limit: 1
          },
          updateQuery: (previousResult, { fetchMoreResult }) => {            
            if (!fetchMoreResult) {
              return previousResult;
            }
            const newResult = Object.assign({}, previousResult, {
              posts: [...previousResult.posts, ...fetchMoreResult.posts]
            });
            // This logs exactly what I expect it to log, but it isn't re-rendered into the component.
            console.log(newResult);

            return newResult;
          },
        })
      }
    };
  }
})(TestComponent);
```

### Version

*   apollo-client@^1.0.1
*   react-apollo@^1.0.0
*   graphql-tag@^2.0.0

**Comment by nicolo-paganin** [comment] 2017-04-10 14:48
yes, same problem for me.

**Comment by yury-dymov** [comment] 2017-04-20 23:35
same problem for me, but everything works fine with apollo-client 0.9.0 and below

**Comment by yury-dymov** [comment] 2017-04-29 03:30
Tested with v1.1.2: issue is still there

**Comment by helfer** [comment] 2017-04-29 05:38
Have you guys tried the steps that @dfee outlined in #1555? I think the root cause here is the same. I'm working on making the error message much better.

**Comment by helfer** [comment] 2017-05-02 21:25
Closing this in favor of #1555 which is a different issue, but same root cause. The PRs that landed over the weekend and will land today are going to make this much much easier to debug.

**Closed by helfer** 2017-05-02 21:25 UTC

**Comment by lucasfeliciano** [comment] 2017-05-03 07:20
@helfer Indeed using the fragment matcher not only fix this issue also fix other issues related to caching.
