### ISSUE TITLE
skip in useQuery hook doesn't work as expected

### ISSUE THREAD

**Issue by JayMGurav** [apollographql/apollo-client#6190] opened 2020-04-25 05:58 UTC
**Intended outcome:**

I was trying to make request conditional, using "skip" in "useQuery" hook, here a brief code of that

![gqlerror](https://user-images.githubusercontent.com/42145480/80272094-220a7e80-86e4-11ea-9bd4-80e485bddaad.jpg)

here the second query GET_COURSE_BY_ID should be "skipped" if the bought is true,
that's well and good when logged in the console, I get courseDetails as undefined if bought is true,
but the thing is it actually makes the network request and sends back the requested data!!

here's what I get in the console

![console](https://user-images.githubusercontent.com/42145480/80272153-80376180-86e4-11ea-80e5-5a48f035c06e.jpg)

As expected 👍, courseDetails is undefined if bought is true, But as seen in the network tab it still actually makes a network request and return back the data for courseDetails it so happens that it just makes it undefined later;

![req](https://user-images.githubusercontent.com/42145480/80272265-5d597d00-86e5-11ea-80cc-e0823361fcf1.jpg)

The first request - for CHECK_COURSE_BOUGHT
![req1](https://user-images.githubusercontent.com/42145480/80272267-634f5e00-86e5-11ea-9289-44ed1f18a0c3.jpg)

The second request -for GET_COURSE_BY_ID
![req2](https://user-images.githubusercontent.com/42145480/80272270-68141200-86e5-11ea-8aed-2f40563d6033.jpg)

**Actual outcome:**

 The network request should not be made!!, It should be "skipped" else what is the use of using it. if it is later on just reassigning the data to undefined.

**How to reproduce the issue:**

Just fallow the code above

**Versions**

  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - F:\softwares\yarn\bin\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    apollo-link-context: ^1.0.20 => 1.0.20 
     @apollo/client: "^3.0.0-beta.43",

**Comment by joonhocho** [comment] 2020-05-08 01:47
I get the same bug. `skip` is not respected

**Comment by haneetsingh** [comment] 2020-05-18 17:05
I also get the same issue with `skip` not getting evaluated.

**Comment by jengel-rackner** [comment] 2020-05-20 12:36
It's failing for me as well

**Comment by macrozone** [comment] 2020-05-29 00:06
skip seem to be broken in apollo-client version 3. using ^3.0.0-beta.50

**Comment by dobrynin** [comment] 2020-06-12 01:37
+1

**Comment by layerssss** [comment] 2020-06-13 22:57
seems still broken in `"@apollo/client": "^3.0.0-rc.4"`

**Comment by buzinas** [comment] 2020-06-16 00:07
Yep, broken. See https://github.com/apollographql/react-apollo/issues/3492#issuecomment-644385154.

**Comment by buzinas** [comment] 2020-06-26 03:17
As a work-around, I'm using `fetchPolicy: skip ? 'cache-only' : 'cache-first'`, but this is a nasty bug.

**Comment by ganzp87** [comment] 2020-07-05 08:04
> As a work-around, I'm using `fetchPolicy: skip ? 'cache-only' : 'cache-first'`, but this is a nasty bug.

@buzinas It works, although that is a workaround, but it's very weird.
I wonder if they think this problems are real things

**Comment by Taraluktus** [comment] 2020-07-15 12:58
Still having this issue (truthy skip values are ignored) with final version 3.0.0

But I was able to bisect it, maybe that helps the AC contributors (@benjamn @hwillson):

```console
9793b7d9159fae3e82f989be3db6d923fd811893 is the first bad commit
commit 9793b7d9159fae3e82f989be3db6d923fd811893
Author: Ben Newman <ben@benjamn.com>
Date:   Thu Apr 30 12:04:17 2020 -0400

    Refactor ObservableQuery#reobserve to use Reobserver class.

 src/core/ObservableQuery.ts | 198 +++++++++-----------------------------------
 src/core/QueryManager.ts    |  55 ++++++------
 src/core/Reobserver.ts      | 142 +++++++++++++++++++++++++++++++
 3 files changed, 208 insertions(+), 187 deletions(-)
 create mode 100644 src/core/Reobserver.ts
```

Bisect range was from tag v3.0.0-beta.45 (good) till tag v3.0.0-beta.46 (bad).

**Comment by sapkra** [comment] 2020-07-15 13:52
If it is the exactly the same problem the fix is already merged and will come in the next release:
https://github.com/apollographql/apollo-client/issues/6122#issuecomment-657906722
https://github.com/apollographql/apollo-client/blob/master/CHANGELOG.md

**Comment by Taraluktus** [comment] 2020-07-15 13:56
@sapkra  Thanks for mentioning it!
I've only tested until 3.0.0-final, will report back if this fixes it for me.

**Comment by hwillson** [comment] 2020-07-15 15:16
This should now be fixed in `@apollo/client@3.0.1` (reference: #6589). Let us know if not - thanks!

**Comment by Taraluktus** [comment] 2020-07-15 15:30
Unfortunately, this still happens for me with 3.0.1 (fetchPolicy "network-only", skip: true)

**Comment by vjsingh** [comment] 2020-07-15 15:31
@hwillson I believe this bug is about stopping the actual request, whereas it appears your fix only changed the behavior of `onCompleted`.

**Comment by buzinas** [comment] 2020-07-15 15:33
Yep, still broken @hwillson.

**Comment by Taraluktus** [comment] 2020-07-15 15:39
I am working around this for now with manually setting fetchPolicy to "standby" if the condition for skip is truthy, aditionally to setting skip.
But I'm not sure what "standby" is really meant for, did not found any explanation in the documentation.

**Comment by buzinas** [comment] 2020-07-15 15:43
I'm using a similar work-around (using `cache-only`) to make sure `fetch` isn't triggered, but this should be fixed.

**Comment by buzinas** [comment] 2020-07-15 15:43
This is the commit that broke it, btw:
https://github.com/apollographql/apollo-client/commit/9793b7d9159fae3e82f989be3db6d923fd811893

cc @hwillson, @sapkra  ^

The `onCompleted` hook was a separate issue. Please reopen this.

**Comment by MichaelBurgess** [comment] 2020-07-16 13:48
Still seeing this as an issue in 3.0.1.

**Comment by Taraluktus** [comment] 2020-07-19 10:34
@hwillson Yes, please re-open this.

**Comment by brunomarchioro** [comment] 2020-07-20 20:09
Hi @hwillson! This problem appears in my projects too, please re-open this issue.

**Comment by sirugh** [comment] 2020-07-21 15:37
This is happening for us as well using 3.0.2.

**Comment by Taraluktus** [comment] 2020-07-27 07:02
Any news on this? Could this be re-opened, please?

**Comment by Karandashyk** [comment] 2020-07-27 09:21
The is still breaking our app even with workaround. 
The behaviour should be to SKIP when fetchPolicy: "network-only", skip: true.
Have all packages updated.
Reopen the issue, please.

**Comment by jimisaacs** [comment] 2020-08-01 02:04
Also happening with me with network only same description as @Karandashyk 
Upgraded to `@apollo/client` 3.1.1 without any change.
Please reopen the issue.

**Comment by 278kunal** [comment] 2020-09-08 10:42
Facing the same issue on `2.6.8`

**Comment by MichaelBurgess** [comment] 2020-09-15 09:25
Seeing this issue again in `3.2.0`. It was good for me in `3.1.5`. I've rolled back to `3.1.5` for now.

**Comment by Taraluktus** [comment] 2020-09-15 12:58
@MichaelBurgess I don't have the skip issue outlined in this thread at `3.2.0` (had it before `3.1.2`), so it might be another issue.

**Comment by MichaelBurgess** [comment] 2020-09-15 13:50
Hmmm actually I may have found a change in behaviour which has led to this. At the point of seeing the issue, `skip` was set to true and `query` was also null, as I don't yet have enough context to know which dynamic query to use, hence `skip: true`.

In `3.1.5` that would be fine, but seems like in `3.2.0` it barfs if the query is null and skip is true?

```
Argument of null passed to parser was not a valid GraphQL DocumentNode. You may need to use 'graphql-tag' or another method to convert your operation into a document
```

I don't see any documented change for that, so I'll raise a new issue in case either the release notes need updating, or it was an unintended side-effect of another change.

**Comment by nateq314** [comment] 2020-09-23 20:48
Seeing this here with 3.1.1. What's the latest status?

**Comment by gitpash** [comment] 2020-10-09 11:22
3.2.2 seems fixed for us

**Comment by Hatko** [comment] 2020-10-15 13:41
The issue is still reproducible on 3.2.4

**Comment by joshuarobs** [comment] 2020-10-16 04:20
Any updates on the issue?

**Comment by jean9696** [comment] 2020-10-19 07:20
We experience the same issue with`3.2.4`

**Comment by Hatko** [comment] 2020-10-19 08:58
@hwillson Should the issue be reopened due to many ppl still experiencing it?

**Comment by sirugh** [comment] 2020-10-19 20:58
I would recommend that folks open a new issue with a repro link for codesandbox. Probably the best way to get eyes on something.

**Comment by sanchan** [comment] 2021-04-23 02:27
Still failing on `3.3.11`, this bug is celebrating its first birthday in 2 days, yay! :D

**Comment by gajus** [comment] 2021-05-15 21:48
Just in case, this is not fixed in 3.3.16.

**Comment by juanjoman** [comment] 2021-07-22 14:59
Not working for me on 3.3.21, any solution to this?

**Comment by thomastvedt** [comment] 2021-09-03 09:34
This works now in "@apollo/client": "^3.3.21"

**Comment by dustin-rcg** [comment] 2021-09-13 21:03
Why does useQuery still parse the query when `skip` is true?

**Comment by switz** [comment] 2021-10-02 17:56
Still happening to me on `"@apollo/client": "^3.4.15"`

**Comment by Richacinas** [comment] 2021-11-03 10:05
I'm getting a duplicate query for the `useQuery` that is using a `skip` value.

When it is true, then it doesn't fire but as soon as it gets false, then I get 2 queries at the same time.

**Comment by halotest** [comment] 2021-11-11 19:22
Still a problem `"@apollo/client": "^3.4.16"`.

**Comment by kedarguy** [comment] 2022-01-02 08:50
Still a problem at "@apollo/client": "^3.5.6"

**Comment by mikecann** [comment] 2022-02-22 06:14
This is definately still happening. Seems to happen when you are making the same query in multiple places in your react tree. 

Should 100% be re-opened as this is kind of a big deal.

**Comment by chuanqisun** [comment] 2022-03-10 17:14
Still happening on 3.5.7

**Comment by egemenuzunali** [comment] 2022-03-16 17:11
I can confirm it is still not working properly in "^3.5.10", query is being executed right away

**Comment by lluisemper** [comment] 2022-04-11 10:12
Not really sure why...

This works for me:
 ``` 
 const [skip, setSkip] = useState(true);

   useEffect(() => {
      if (profile?.id) {
         setSkip(false);
      }
   }, [profile]);

   const { data: dataProjects } = useQuery(GET_PROJECTS, {
      variables: {
         onlyFeaturedProjectsOfId: profile?.id,
      },
      skip,
   });
   
   ```
   
   This does not: 
   ```
   const { data: dataProjects } = useQuery(GET_PROJECTS, {
      variables: {
         onlyFeaturedProjectsOfId: profile?.id,
      },
      skip: !profile?.id,
   });
   ```

**Comment by alchemist09** [comment] 2022-04-27 12:56
I'm using Apollo 3.5.5 and I'm experiencing the same issue. Passing a literal boolean value to skip works, but passing an expression that evaluates to boolean fails.

This works
```
const { loading, error, data, refetch } = useQuery(GET_REPOSITORIES_OF_ORGANIZATION, { 
  variables: {
    organizationLogin
  },
  skip: true
})
```

This doesn't work
```
const { loading, error, data, refetch } = useQuery(GET_REPOSITORIES_OF_ORGANIZATION, { 
   variables: {
     organizationLogin
   },
   skip: organizationLogin === '' ? true : false
})
```
Hard-coding a value to that field negates its usefulness by making it unable to programmatically change when a query should or should not run

**Comment by VagishVela** [comment] 2022-05-04 08:41
@alchemist09 Not sure why it is closed but we hit the same issue with skip. Trying to figure it out. But no idea why it's doing this. Our issue is more we require a user to do the query, so when there is no user there is no jwt so it comes up with a 500 error.

**Comment by VagishVela** [comment] 2022-05-04 10:06
A solution I found was:
```
  const [loadQuery, { data }] = useLazyQuery(QUERY, { skip: !user });
  useEffect(() => {
    if (user) {
      loadQuery();
    }
  }, [user]);
```

This doesn't load my query until after the user comes in. I left the skip in the first line, but I can probably remove it.
@alchemist09 hopefully this helps you.

**Comment by egemenuzunali** [comment] 2022-05-04 16:22
> A solution I found was:
> 
> ```
>   const [loadQuery, { data }] = useLazyQuery(QUERY, { skip: !user });
>   useEffect(() => {
>     if (user) {
>       loadQuery();
>     }
>   }, [user]);
> ```
> 
> This doesn't load my query until after the user comes in. I left the skip in the first line, but I can probably remove it. @alchemist09 hopefully this helps you.

Skip is not available for useLazyQuery. So it doesn't do anything. The reason why your query is not being executed is because that is the nature of useLazyQuery. It won't execute until you call it. However it is not async.

**Comment by alchemist09** [comment] 2022-05-04 22:07
> A solution I found was:
> 
> ```
>   const [loadQuery, { data }] = useLazyQuery(QUERY, { skip: !user });
>   useEffect(() => {
>     if (user) {
>       loadQuery();
>     }
>   }, [user]);
> ```
> 
> This doesn't load my query until after the user comes in. I left the skip in the first line, but I can probably remove it. @alchemist09 hopefully this helps you.

Well, as @egemenuzunali has stated, `skip` isn't available for `useLazyQuery`, so you won't need to pass in that particular option, but rather rely on the check within `useEffect` to test if `user` evaluates to a truthy value. Something like:

```
 const [loadQuery, { data }] = useLazyQuery(QUERY);
     useEffect(() => {
        if (user) {
           loadQuery();
        }
    }, [user]);
```

I'm going through the comments on #6752 which claims to have fixed the issue but it seems many people are still experiencing the problem.

**Comment by bsk26** [comment] 2022-06-10 16:23
We're seeing this issue on 3.6.6 with 
```
    fetchPolicy: 'cache-and-network',
    nextFetchPolicy: 'cache-first',
```

I really don't understand how this issue keeps being closed without actually being fixed. I've generally found Apollo to be very reliable but we wasted a bunch of time tracking down this issue: it seems skip is sometimes respected, but likely fails on the second network query. We missed this failure in our initial testing -- again, I wrongly trusted the @apollo/client code to be reliable

**Comment by alchemist09** [comment] 2022-06-11 00:21
I think the person(s) closing it hasn't really tested it under the different scenarios because the problem is quite prevalent now. What's even more worrying is that subsequent releases of Apollo Client still ship with the same problem. Since the client relies on HTTP protocol to execute requests, a check needs to be placed before the request-making code executes. The main purpose for the check will be to determine if 'skip' is true.

**Comment by josegoval** [comment] 2022-06-23 06:34
Still happening in `3.6.9`, even with `skip: true`.

When I set `skip: true` the request is made, but the data is`undefined`. I think it should skip completely the request.

**Comment by gabrielmicko** [comment] 2022-06-23 14:15
Same issue!

**Comment by RonaldDiaz** [comment] 2022-06-23 16:23
> A solution I found was:
> 
> ```
>   const [loadQuery, { data }] = useLazyQuery(QUERY, { skip: !user });
>   useEffect(() => {
>     if (user) {
>       loadQuery();
>     }
>   }, [user]);
> ```
> 
> This doesn't load my query until after the user comes in. I left the skip in the first line, but I can probably remove it. @alchemist09 hopefully this helps you.

Worked for me. No need to use `skip`

**Comment by alchemist09** [comment] 2022-06-23 18:00
> > A solution I found was:
> > ```
> >   const [loadQuery, { data }] = useLazyQuery(QUERY, { skip: !user });
> >   useEffect(() => {
> >     if (user) {
> >       loadQuery();
> >     }
> >   }, [user]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This doesn't load my query until after the user comes in. I left the skip in the first line, but I can probably remove it. @alchemist09 hopefully this helps you.
> 
> Worked for me. No need to use `skip`

`skip` is not available as an option for `useLazyQuery` which returns a query function that you determine explicitly when it executes, unlike `useQuery` which automatically runs when the component mounts. So this example doesn't address the actual problem faced in this scenario despite working for isolated cases.

**Comment by mattlubner** [comment] 2022-06-23 18:17
> `skip` is not available as an option for `useLazyQuery` which returns a query function that you determine explicitly when it executes, unlike `useQuery` which automatically runs when the component mounts. So this example doesn't address the actual problem faced in this scenario despite working for isolated cases.

Minor point of clarification – according to the docs, once `useLazyQuery`'s execute function has been called, the hook behaves just like the `useQuery` hook.

`useLazyQuery` doesn't support explicitly determining when the query executes, because after the execute function has been called at least one time, any changes to hook arguments could trigger additional query executions.

AFAIK, the only way to explicitly determine when the query is executed is by manually calling `apolloClient.query()` (eg. within a `useEffect` hook).

_From the [Apollo docs](https://www.apollographql.com/docs/react/api/react/hooks/#result-tuple) (emphasis added):_

> Function that can be triggered to execute the suspended query. **After being called, useLazyQuery behaves just like useQuery.** The useLazyQuery function returns a promise that fulfills with a query result when the query succeeds or fails.

**Comment by paulopontovaz** [comment] 2022-07-15 08:28
`skip` also doesn't work for me with the regular useQuery.

In my case, I'm using the hooks generated by `graphql-code-generator`, but I think that doesn't influence the behavior so I'm saying it just as an FYI.

I guess I'll have to resort to the useLazyQuery + useEffect solution.

**Comment by Karabur** [comment] 2022-07-29 13:41
`@apollo/client@3.6.9` still broken. 
`skip: true` and request fired anyway.

**Comment by feline87** [comment] 2022-08-14 18:33
Yup, it still doesn't skip no matter what even with literal true (using version 3.6.9)

**Comment by feline87** [comment] 2022-08-14 18:48
> `useLazyQuery` doesn't support explicitly determining when the query executes, because after the execute function has been called at least one time, any changes to hook arguments could trigger additional query executions.
> 

What if you pass the variables to the returned function isntead of useLazyQuery itself? doesn't that allow you to control your queries better?

**Comment by bsk26** [comment] 2022-08-15 16:07
> I guess I'll have to resort to the useLazyQuery + useEffect solution.

I'd recommend just conditionally setting the cache policy. It is a simpler (and thus better) workaround.

**Comment by Miladxsar23** [comment] 2022-09-18 08:09
it works. the problem is that somebody didn't note about "Apollo active queries" and think that it absolutely makes a network request but it is not so. if you set skip to "true" then note to "Network" tab in dev tools in browser , you get that there isn't any network request about that query but if you note to tab "QUERIES" in Apollo dev tools see lots of active queries  there that doesn't mean that all of them make network requests.

**Comment by Hakall** [comment] 2022-11-05 14:11
Seing this issue today as well.
Setting skip to true doesn't seem to work, i see the request on Network tab.

**Comment by FernandVEYRIER** [comment] 2022-12-20 18:34
Still the case with `skip: true`, the query runs but the data is empty. I think the desired behavior would be not to run the query at all.

**Comment by jerelmiller** [comment] 2023-01-04 23:43
Hey all 👋 ! It seems there has been quite a few comments about this issue since it was initially closed. I'm going to go ahead and reopen since judging by its comments, it seems that an issue still persists. I'm hoping we can dig into this a bit further very soon. Thanks for your patience!

**Comment by jerelmiller** [comment] 2023-01-05 00:59
From what I can find, this issue appears to be fixed from `v3.6.9` on. https://github.com/apollographql/apollo-client/issues/9673 appears to have been split out from this issue, which included a [reproduction](https://codesandbox.io/s/apollo-client-3-6-3-skip-bug-5zbl63) of the bug. This appears to have been fixed in https://github.com/apollographql/apollo-client/pull/9823, which was released in `v3.6.9`. In fact, if you open the reproduction and update the `@apollo/client` version to any version after `v3.6.9`, you'll see the network request no longer fires when the query is skipped, as expected.

I'm inclined to say this has been addressed by #9823, however I need some help getting a reproduction and/or failing test to demonstrate the continued buggy behavior. I've created a branch with some [additional tests](https://github.com/apollographql/apollo-client/compare/use-query-skip-issue) around the `skip` behavior, but I'm unable to reproduce the problems talked about in this issue with the latest code in `main`. If there is some condition that isn't covered either by the existing test suite, or the additional tests in my [branch](https://github.com/apollographql/apollo-client/compare/use-query-skip-issue), please let me know so we can dig into this further. Thanks!

**Comment by rwilliams3088** [comment] 2023-01-05 22:04
+1. Ran into this issue today. As a work around, I added a $skip variable to my query and used the @skip directive.

**Comment by thomastvedt** [comment] 2023-03-04 10:20
This is really strange... Yesterday this issue re-appeared. But today it works again, and I didn't change anything in my code. 
Maybe this is a [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug)? 😅

I'm on version: `"@apollo/client": "^3.7.9"`.
My code that failed yesterday, and works today...:

```
  const { data: dataListItem, loading: loadingListItem } =
    useGetRetailerListItemQuery({
      variables: retailerId
        ? {
            retailerId: retailerId,
          }
        : undefined,
      fetchPolicy: 'cache-first',
      skip: !retailerId, // BUG: open bug in apollo client... will fire even if skip is true
    });
```

I didn't change anything in my query code, but did some changes around url parameter parsing, maybe affecting how the component is rendered and how many times the component is rendered 🤔. 

Note that I'm using [graphql-codegen](https://the-guild.dev/graphql/codegen) to generate apollo helpers. (not the newest version)

```
    "@graphql-codegen/add": "^3.2.3",
    "@graphql-codegen/cli": "^2.16.5",
    "@graphql-codegen/introspection": "^2.2.3",
    "@graphql-codegen/typescript": "^2.8.8",
    "@graphql-codegen/typescript-apollo-client-helpers": "^2.2.6",
    "@graphql-codegen/typescript-operations": "^2.5.13",
    "@graphql-codegen/typescript-react-apollo": "^3.3.7",
```

**Comment by AaronWatson2975** [comment] 2023-03-14 15:51
Possibly related to this, I can confirm I'm seeing something similar on `3.7.10`, the easiest way for me to reproduce it is to set `skip` to `true` and just call `refetch`, the request still runs and seems to ignore the `skip`.  

I noticed on `3.5.5` I did not see this issue, and on `3.6.0`, `3.7.0`, and `3.7.10` I do see it (didn't test other versions).

I was about to make a Code Sandbox and open an issue, but then I saw this, and thought I'd post my findings here before opening a potential duplicate.

**Comment by jerelmiller** [comment] 2023-03-15 00:48
@AaronWatson2975 interestingly, in my mind, I would expect that `refetch` _would_ execute the query, regardless of `skip`, since you are explicitly telling Apollo that you want to fetch. I tend to see `skip` as a means to tell the _hook_ whether to automatically fetch or not.

Unfortunately our [docs](https://www.apollographql.com/docs/react/data/queries#skip) are a bit ambiguous, so its left up to interpretation. I'll see if we can make find a way to communicate the expected behavior for `refetch`, `fetchMore`, etc when `skip` is true.

Regardless, I think we can all agree that at least the hook should behave properly, so if we are seeing fetches from the hook while `skip` is truthy, then that is definitely the sign of a bug. 

---

@rwilliams3088 @thomastvedt @STGlancyPS if any of you could help create a reproduction with recent versions of Apollo, that would help tremendously. I'm afraid there isn't much we can do without one. I tried creating [additional tests](https://github.com/apollographql/apollo-client/compare/use-query-skip-issue) for everything I could think of, but I had no luck reproducing the issue.

**Comment by AaronWatson2975** [comment] 2023-03-15 13:09
@jerelmiller thanks for the quick response.  I had a feeling it might be intended behaviour but I wasn't sure, and I know it worked that way before `3.6`.  Now that I know it's expected, I can plan for it, so thank you!

Not sure if this helps with the original issue, but I made a 40 ish line CodeSandbox to reproduce my `refetch` issue, and when I was testing it with the latest version of Apollo Client (at the time of writing this, `3.7.10`, I was not able to detect any network requests when `skip` was `true`, only detectable when I refetched it, so I was not able to reproduce the original issue here.

Here's the code if anyone else wants to play around with it (it was originally built to show the refetch issue, but if you check the network tab when it loads, you won't find network requests until the timer gets hit and refetch is called).  So if you just remove the refetch code you'll notice there aren't any network requests (or that's what I saw when I ran it anyway).

Thanks again!  🙏 

```
import {
  ApolloClient,
  InMemoryCache,
  useQuery,
  ApolloProvider,
  gql
} from "@apollo/client";

const Component = () => {
  const query = gql`
    query GetLocations {
      locations {
        id
        name
      }
    }
  `;

  const { refetch, data: { locations = [] } = {} } = useQuery(query, {
    skip: true
  });

  setTimeout(() => {
    console.log("attempting a refetch, check network tab");
    refetch();
  }, 5000);

  return <p>{`Check network tab.  Location length: ${locations.length}`}</p>;
};

export default function App() {
  const client = new ApolloClient({
    uri: "https://flyby-router-demo.herokuapp.com/",
    cache: new InMemoryCache()
  });

  return (
    <ApolloProvider client={client}>
      <div className="App">
        <Component />
      </div>
    </ApolloProvider>
  );
}
```

**Comment by kylewinkler** [comment] 2023-05-26 13:50
Chiming in here to say still broken 3 years later.

**Comment by phryneas** [comment] 2023-05-26 13:59
To add to this: the only reproduction (by buzinas above) we got for this is fixed (I just checked with our latest stable release, 3.7.10), so it's not like this had been around unsolved for three years.  
It is very likely that there are multiple different bugs showing that behaviour - but without any additional reproductions, we cannot do anything.

**Comment by kylewinkler** [comment] 2023-05-26 14:40
Sure, I will gather more information in a little bit. I understand that I haven't proven to you that it is the same bug but for the sake of all of our intelligence I will play it safe and incline myself to believe that exhibiting the same behavior as the previous comments and allowing the same workarounds, that this bug is still not fixed lol.

But, time will tell.

**Comment by phryneas** [comment] 2023-07-10 13:36
@tobiaswaltl could you please provide a reproduction of this that shows the problem? 

The only reproduction provided in this issue is fixed in recent versions - you might be encountering a similar problem, but we really need a reproduction for it.

**Comment by tobiaswaltl** [comment] 2023-08-02 09:47
As a workaround I tried to set the `pollInterval` to `undefined` when the condition for `skip` evaluates to `true`. But, like `skip`, this is ignored and the polling is continued. I.e. it seems it's nothing `skip`-specific causing this bug.

**Comment by phryneas** [comment] 2023-08-02 09:54
@tobiaswaltl  Sorry for the late response. 
Yeah, I think what you see with polling here might be another skip-related bug. (The original bug didn't include polling.)
I'll make a new open issue out of your comment so we can better track that.

**Comment by jerelmiller** [comment] 2024-02-15 00:58
Hey all 👋 

It's been a bit of time since the last reply on this issue. I'd like to give this one more chance at a reproduction before we close this. All signs on our end indicate this has been fixed in recent versions of the client. We've created a separate tracking issue for the bug reported in https://github.com/apollographql/apollo-client/issues/6190#issuecomment-1630980185 at https://github.com/apollographql/apollo-client/issues/11120. I've got a branch setup with some [additional tests](https://github.com/apollographql/apollo-client/compare/use-query-skip-issue) that all pass with the various ways `skip` can be set. We've done everything we can do on our end in good faith to try and figure out what's going on.

At this point, if you are still seeing this issue on recent versions of the client, we are going to require a runnable reproduction or failing test case that demonstrates this issue, otherwise we plan to close this as completed. Thanks!

**Comment by MrMossevig** [comment] 2024-02-20 10:18
Hi,

I'm not sure if I can give you a runnable reproduction or failing test case, but I came across this issue just now. In my case the skip is not honoured at all, even if it is set explicitly to true:
```
/* Getting all organizations */
const { result: orgResult, loading: orgLoading} = useQuery(GET_ALL_ORGS, {
  skip: true
});
```

I am not an expert so I have no idea whether it's a user fault (me) or a problem with the package, but I'm happy to jump on a call on discord or wherever if you want to see.
Using Vue3 with:

"node_modules/@vue/apollo-composable": {
      "version": "4.0.1",

"node_modules/@apollo/client": {
      "version": "3.9.5",

**Comment by phryneas** [comment] 2024-02-20 17:08
Hi @MrMossevig! 
I believe your case might be different - the `useQuery` hook of `@vue/apollo-composable` is a completely different api than the `useQuery` hook of `@apollo/client`.  
I believe that `useQuery` hook [just doesn't have a `skip` option](https://v4.apollo.vuejs.org/guide-composable/query.html#options).

**Comment by jerelmiller** [comment] 2024-02-23 19:21
Hey all 👋 

We are going to go ahead and close this issue since it appears this has been resolved. 

If you do encounter a similar bug, please open a new issue with a reproduction and we'd be happy to assist. Thanks!

**Closed by jerelmiller** 2024-02-23 19:21 UTC
Labels: 🏓 awaiting-contributor-response, ⚛️ React-related
