### ISSUE TITLE
Context parameter has no effect when using ApolloClient.mutate

### ISSUE THREAD

**Issue by gabrieldonadel** [apollographql/apollo-client#9998] opened 2022-08-09 13:51 UTC
**Intended outcome:**

In order to set custom headers for a specific mutation the `context` parameter should work when using ApolloClient.mutate.

e.g.

```js
  await client.mutate({
    mutation: TestDocument,
    variables: { testId },
    context: {
      headers: {
        'custom-header': 'should work',
      },
    },
  })
```

**Actual outcome:**

context is not set when using the client object directly and thus there is no way to add custom variables to the request header. The only way I could get this working was by using the `useMutation` hook but the problem with this approach is that it limits where we can make requests. Ideally we should be able to add custom headers either by using the hook or by using the client

**How to reproduce the issue:**

Run any mutations using the client instance instead of the `useMutation` hook and you'll be able to reproduce this issue, then observe the network request headers

```js
  await client.mutate({
    mutation: TestDocument,
    variables: { testId },
    context: {
      headers: {
        'custom-header': 'should work',
      },
    },
  })
```

**Versions** 
```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 14.17.6 - ~/.volta/tools/image/node/14.17.6/bin/node
    Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
    npm: 6.14.15 - ~/.volta/tools/image/node/14.17.6/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @apollo/client: 3.6.8 => 3.6.8
    apollo3-cache-persist: ^0.13.0 => 0.13.0

**Comment by MrDoomBringer** [comment] 2022-08-09 17:26
Hi @gabrieldonadel !

I gave this a try on my own machine using the [fullstack-tutorial repo](https://github.com/apollographql/fullstack-tutorial), and it seemed to work properly. 
![image](https://user-images.githubusercontent.com/29008542/183717959-b30f2f0c-a453-4aca-b091-f8a1355d7b83.png)
![image](https://user-images.githubusercontent.com/29008542/183718062-4d4e63d0-a84f-4c28-b4f2-64a5a0644c19.png)

Perhaps there's something else causing this issue. Would it be possible for you to upload a reproduction to a repository so we could take a deeper look? Thanks!

All the best,
Emmanuel, Intern :-)

**Comment by MrDoomBringer** [comment] 2022-08-30 15:37
Hey @gabrieldonadel, it looks like this might not be a bug, so for the time being I'll go ahead and close this issue. Definitely let me know if we want to keep this open though!

All the best,
Emmanuel, Intern :-)

**Closed by MrDoomBringer** 2022-08-30 15:37 UTC
Labels: 🏓 awaiting-contributor-response

**Comment by anatoleblanc** [comment] 2022-11-07 16:03
Hi, 

I am having the same issue on a react-native app.

I cannot manage to set the authorization header for a mutation. 

Have you found a solution @gabrieldonadel ?

thx a lot!
