### ISSUE TITLE
Error is thrown on every store update

### ISSUE THREAD

**Issue by rgoldfinger** [apollographql/apollo-client#1576] opened 2017-04-11 23:10 UTC
Apollo is throwing a previously handled error on every store update.

Here's what's happening:
I'm getting an (expected) 401 back from a resolver:
![screen shot 2017-04-11 at 3 08 41 pm](https://cloud.githubusercontent.com/assets/5637592/24932968/c627d576-1ec8-11e7-88d0-ec6962fcf912.png)

This error is handled in a `graphql` HOC:
```
const withEverythingTheComponentNeeds = graphql(gql`
  query AppLanding {
    app_landing_user: me {
      id
      ...
    }
  }`, {
    props: ({ data }) => {
      if (data.error) {
        return {};
      }
      return { user: data.app_landing_user, loading: data.loading };
    },
  }
);
```

Nothing is logged to the console here, as expected.

However, as more queries are made and the store updates, this error gets thrown repeatedly:
![screen shot 2017-04-11 at 3 15 06 pm](https://cloud.githubusercontent.com/assets/5637592/24933166/c357c922-1ec9-11e7-84f7-fb70f3c80348.png)

It looks like it's thrown again because the `fetchPolicy` is 'cache-only':
<img width="859" alt="screen shot 2017-04-12 at 7 45 40 am" src="https://cloud.githubusercontent.com/assets/5637592/24963687/2359e28a-1f54-11e7-8d1b-01adc9a42156.png">
Setting the `fetchPolicy` in the HOC does not seem to change the fetch policy here.

The error is thrown again once `isNetworkRequestInFlight` returns false.

**Intended outcome:**
Error is never thrown.

**Actual outcome:**
Error is thrown repeatedly

**How to reproduce the issue:**
?? Happy to help debug this.

**Comment by helfer** [comment] 2017-04-12 18:59
Thanks @rgoldfinger, I'd really like to debug this. Could you build a quick reproduction using the [react-apollo-error-template](https://github.com/apollographql/react-apollo-error-template)?

**Comment by rgoldfinger** [comment] 2017-04-12 21:01
Sure, I will try to get a repro soon. Meanwhile, after some debugging, it looks like it's happening while the component that made the query is unmounted. Once it's re-mounted the errors stop.

**Comment by rgoldfinger** [comment] 2017-04-13 19:02
Got a repro: https://github.com/rgoldfinger/react-apollo-error-template

**Comment by stevewillard** [comment] 2017-04-22 03:43
Just wanted to say that I'm seeing the same issue with roughly the same code as the above repro

**Comment by helfer** [comment] 2017-05-02 18:26
If this is due to query recycling it should be fixed by #1636 once I release it 🙂

**Comment by rgoldfinger** [comment] 2017-05-03 14:57
Thanks @helfer, I tried this on my repo and in the error template, and unfortunately it doesn't seem to have fixed the issue.

**Comment by helfer** [comment] 2017-05-03 19:02
@rgoldfinger Hm... 😕  Could you update your reproduction to use the newest versions? Thanks!

**Comment by rgoldfinger** [comment] 2017-05-03 20:55
Looks like `react-apollo` is still on 1.0.x. https://github.com/apollographql/react-apollo/blob/master/package.json#L132 

Unless I'm missing something, I think this needs to be updated before I can get this repo on the latest version. I guess this could be why it didn't look like it was fixed.

**Comment by rgoldfinger** [comment] 2017-05-03 21:22
Updated the repro, it's still happening.

**Comment by rgoldfinger** [comment] 2017-05-16 18:48
I updated the repro to `1.2.0`, and it's down from throwing three errors to 1. I don't think that it should throw any because it's handled in the HOC.

**Closed** 2017-07-29 14:30 UTC
Labels: bug, no-recent-activity
