### ISSUE TITLE
Optimistic option on ApolloClient.readQuery

### ISSUE THREAD

**Issue by danieljvdm** [apollographql/apollo-client#2450] opened 2017-11-01 16:48 UTC
Pre 2.0 I believe that `client.readQuery` would also return optimistic mutation results. After upgrading to 2.0 most of my optimistic code broke since I use it in tandem with subscriptions. In the subscription (for a new message) I would read the store and check if an optimistic result was there (designated by a negative ID) and not do anything with the subscription if that were the case. Now that doesn't work anymore. I did some digging and saw that the `apollo-cache` package now has an `optimistic: boolean` param in the `readQuery` function which would solve my issues but it doesn't seem to be accessible to the `apollo-client` package. Is this intentional or just a missing API that needs to be written?

**Comment by Goluis** [comment] 2017-11-03 18:33
I also experienced the same issue but here is a workaround:
```js
client.initProxy().readQuery({ ...options }, true)
```
it will do a query to the cache as `client.readQuery`, but now you're allowed to pass a second prop called `optimistic` which will include the optimistic results, you actually can't do it with `client.readQuery` cause the implementation looks like this:
```js
readQuery(options) {
  return this.initProxy().readQuery(options)
}
```

**Comment by danieljvdm** [comment] 2017-11-03 19:59
Wouldn't an easier workaround be simply `client.cache.readQuery`?

**Comment by Goluis** [comment] 2017-11-03 20:09
it's the same as the result of `this.initProxy()` so yes, you'll need to pass `true` as the second prop to query in the optimistic results too

**Comment by jbaxleyiii** [comment] 2017-11-06 14:14
@danieljvdm definitely not intentional at all! There is a PR open [here](https://github.com/apollographql/apollo-client/pull/2429) to renable this, if its not worked on early this week I will add it to my work and make this adjustment!

Would you be able to share some sample code that is now broken, write a failing test, or create a reproduction for me to verify the change?

Sorry for any inconvenience this caused!

**Comment by nevir** [comment] 2018-03-15 22:01
IMO optimistic should be the _default_ behavior, too.  It's the least surprising option

**Comment by hwillson** [comment] 2018-08-10 19:51
https://github.com/apollographql/apollo-client/pull/2429 addresses this and was merged. Thanks!

**Closed by hwillson** 2018-08-10 19:51 UTC
Labels: bug
