### ISSUE TITLE
Use zen-observable as ESM

### ISSUE THREAD

**Issue by abdonrd** [apollographql/apollo-client#5961] opened 2020-02-18 14:43 UTC
The last version of `zen-observable` has an ESM export: [`esm.js`](https://github.com/zenparsing/zen-observable/blob/master/esm.js).

You can also check it at unpkg:
https://unpkg.com/browse/zen-observable@0.8.15/

It would be great that Apollo Client uses that instead of the CJS export ([`index.js`](https://github.com/zenparsing/zen-observable/blob/master/index.js)).

That way, `zen-observable` works directly in the browser.

**Comment by benjamn** [comment] 2020-02-18 15:47
[Here](https://github.com/apollographql/apollo-client/blob/da8c3c351a5e2e8649baab5359034c7afd1b9377/src/utilities/observables/Observable.ts#L1)'s where we `import Observable from "zen-observable"`. As you can see, we're not doing anything that would force your bundler to import the CommonJS entry point, and the [version constraint](https://github.com/apollographql/apollo-client/blob/da8c3c351a5e2e8649baab5359034c7afd1b9377/package.json#L72) in our `package.json` (`^0.8.14`) permits installing the latest version of `zen-observable`, which is just 0.8.15. In short, I don't think Apollo Client is standing in the way of using the new ESM entry point. Let me know if there's something concrete you want us to do here.

**Comment by billyjanitsch** [comment] 2020-02-19 00:20
The problem is that zen-observable [doesn't actually point to its ESM build](https://unpkg.com/browse/zen-observable@0.8.15/package.json) in its package.json so a bundler can't know that it has one. That package would need to add `"module": "esm.js"` to its package.json for this to work.

I wonder if this is also the cause of https://github.com/apollographql/apollo-client/issues/5686, although I don't know what would have changed between apollo-boost and @apollo/client to cause this in one but not the other.

**Comment by benjamn** [comment] 2020-02-19 14:00
ESM support is a very recent addition to `zen-observable`, so I'm sure they would appreciate an issue/PR to add the `"module": "esm.js"` entry point. You can certainly link back to this issue as supporting evidence, but I believe it's their responsibility to follow the same conventions that other dual CJS/ESM packages follow.

**Comment by bennypowers** [comment] 2020-06-04 07:14
There's a use case of apollo-client without a bundler that's worth considering here. Buildless workflows and even smaller applications that use unbundled CDN and http2.

I believe post-3.0 ac is moving away from observable, but in the mean time it would be nice to have an all-browser option to cover those use cases.

**Comment by abdonrd** [comment] 2020-07-20 13:40
@benjamn since the maintainer has not responded for a long time... Would you be interested in changing the package if I publish it under a scope? Something like `@abdonrd/zen-observable`. Just with [this PR](https://github.com/zenparsing/zen-observable/pull/74) to use an ESM build.

**Comment by benjamn** [comment] 2021-01-25 21:47
@abdonrd Thanks for following through and opening that PR! Since there's been no response, I'm moving ahead with a wrapping strategy, using the package name `zen-observable-ts`: #7615. If your PR ever gets merged (🤞 ), we can go back to using `zen-observable` directly.

These changes should be released in [Apollo Client v3.4](https://github.com/apollographql/apollo-client/pull/7399) (the next minor version).

**Comment by PowerKiKi** [comment] 2021-01-25 23:55
What about finally moving to rxjs, which is a very capable, well maintained and tree shake library ?

It is so good that it is already used in Apollo client tests code (!). Moving to rxjs would unify your codebase while reducing bundle size of Angular projects, most likely not increasing React project size. And last but not least it would reduce your maintenance work.

I'm more than willing to create a pr for that, if you give me the go.

**Comment by PowerKiKi** [comment] 2021-01-25 23:57
I guess the answer to my question is #5749

**Comment by abdonrd** [comment] 2021-02-09 10:18
Closed by https://github.com/apollographql/apollo-client/pull/7615, right?

**Comment by benjamn** [comment] 2021-02-17 17:43
@abdonrd Yes! However, please note that #7615 is only in the v3.4 betas at this point.

**Closed by benjamn** 2021-02-17 17:43 UTC
Labels: :bulb: idea, :christmas_tree: dependencies, 📦 bundle size, 🙃 upstream, 🛬 fixed-in-prerelease

**Comment by abdonrd** [comment] 2021-02-17 18:45
@benjamn yes, looking forward to the release!

I'm very glad to read that there will be a solution for `fast-json-stable-stringify`! 👏🏻 

"_this little package called react_". Yeah, little package 😂 
Personally I think the best option would be to remove React from `@apollo/client` (that works for any) and have something like `@apollo/client/react` with React. But yes, for now I use `@apollo/client/core`.
