### ISSUE TITLE
refetch does not replace the original cache

### ISSUE THREAD

**Issue by linxianxi** [apollographql/apollo-client#6925] opened 2020-08-28 04:38 UTC
Did you rewrite refetch?
I tried v3.1.3 and v3.2.0-beta.6

**Comment by linxianxi** [comment] 2020-08-28 06:21
I tried version 2, is OK!    Version 3 doesn't work！

**Comment by linxianxi** [comment] 2020-08-28 06:49
I only used cache.writequery when adding data, delete did not。

After the first request, a piece of data is deleted, and the original cache is replaced after the refetch. If it is not on page 1, it will not jump to page 1. Version 2 will jump to page 1.

After the first request, add a piece of data, add it to the cache, and then delete it. The data requested by a refetch does not replace the current cached data. Note: Deletion does not use writeQuery. Fetch replaces the cache if the data is deleted from the request and not just added to the cache.

In version 2, in all cases the refetch jumps to the first page and replaces the original cache

**Comment by anasqadrei** [comment] 2020-08-30 23:02
I have the same issue. Refetch doesn't reset cache (which I believe it should). My case is similar to code in this question:

https://stackoverflow.com/questions/63108804/rn-apollo-client-3-0-handle-refetch-with-merge-function

**Comment by linxianxi** [comment] 2020-08-31 01:28
Refetch should refetch the request and replace the cache.

Instead of refetch, I temporarily use window.location.href = window.location.href

**Comment by nhanpdnguyen** [comment] 2020-08-31 07:49
I think I have the same issue:
- I used `useQuery` and `refetch` (in `useEffect`) in 1 component to fetch the data.
- In another component, I used `readQuery` to read the cache but the cache is not getting updated properly, sometimes it is but sometimes it is not (look likes having some kind of race conditions)

**Comment by linxianxi** [comment] 2020-08-31 08:15
@benjamn

**Comment by BowlingX** [comment] 2020-08-31 23:42
Same issue here with `v3.1.3` and the following query configuration:
```
    fetchPolicy: "cache-and-network",
    nextFetchPolicy: "cache-first",
```

`refetch` will not force a refetch (as it respects the given `fetchPolicy`). 
I think `refetch` should always do a network request and refresh the cache, or let one specify a `fetchPolicy` in a second parameter?

e.g. `refetch(variables, { fetchPolicy: 'cache-and-network'})`

**Comment by BowlingX** [comment] 2020-08-31 23:49
As a workaround you can use `fetchMore` with the same variables. this worked for me.

**Comment by linxianxi** [comment] 2020-09-01 01:16
> As a workaround you can use `fetchMore` with the same variables. this worked for me.

I'm using a table, in version 2, refetch reloads the table, version 3 doesn't, and fetchMore doesn't either, I need to reload the component

**Comment by dallonf** [comment] 2020-09-09 21:22
`fetchMore` is indeed a good workaround - but something is seriously bugged with `refetch`!

**Comment by benjamn** [comment] 2020-09-10 19:38
@linxianxi What approach are you using to delete the data, if not `writeQuery`? Also, how long after the initial request are you doing the `refetch`? Like, immediately, or in response to user input, or something else?

**Comment by linxianxi** [comment] 2020-09-11 01:28
> @linxianxi What approach are you using to delete the data, if not `writeQuery`? Also, how long after the initial request are you doing the `refetch`? Like, immediately, or in response to user input, or something else?

Add a piece of data using writeQuery, and then initiate a request to delete a piece of data, without changing the cache, and use refetch to retrieve the data

**Comment by anasqadrei** [comment] 2020-09-11 01:43
In one of my cases, I query a `listComments` in one of the components. When a user clicks to delete a comment in another component, I initiate a mutation `deleteComment` with `listComments` in the `refetchQueries` and `awaitRefetchQueries: true`. 

In the `merge` function, I find the `existing` = list of comments _with_ the deleted comment and `incoming` = list of comments _without_ the deleted comment. I end up with duplicate objects.

Shouldn't `incoming` = null in this case?

**Comment by dallonf** [comment] 2020-09-11 13:14
I used `cache.modify` to delete data, which caused the data in the React component to immediately disappear, as expected. Calling `refetch` caused a network request, but the data never made it back to the component - or, based on my logs, even to the `merge` function of the field that was deleted. `writeQuery` had similar results.

**Comment by gregoryforel** [comment] 2020-10-03 10:42
I have the feeling that it happens also with `pollInterval`. If you add data manually to the cache with `writeQuery`, and that query has polling set, it should remove the newly added data immediately after the first poll, but doesn't. Here is an example of this issue, as well as the one described in this thread with refetch / fetchMore.
[codesandbox](https://codesandbox.io/s/playing-with-apolloclient-3-cache-forked-zoejq?file=/src/useUserList.ts)

**Comment by Badbreaddead** [comment] 2020-11-02 15:15
I have this problem too. Is it going to be addressed any time soon? or should we use fetchMore?

**Comment by hinsxd** [comment] 2021-01-07 16:55
Bump. Same issue here.

**Comment by charle692** [comment] 2021-01-07 16:58
I don't think using `fetchMore` is a solution here. Semantically `fetchMore` suggests that we are going to be loading more data and appending it to the existing.

`refetch` should clear the cache or at minimum it should be detectable from inside the `merge` function so that we can manually omit existing cache entries.

I just ran into this while migrating away from the deprecated `updateQuery` and instead using a custom merge function.
I'm willing to help out and implement something if we can decide on a direction/intended behaviour for this.

**Comment by DavidGolodetsky** [comment] 2021-01-18 09:35
Same issue

**Comment by gregoryforel** [comment] 2021-01-18 16:29
> I don't think using `fetchMore` is a solution here. Semantically `fetchMore` suggests that we are going to be loading more data and appending it to the existing.
> 
> `refetch` should clear the cache or at minimum it should be detectable from inside the `merge` function so that we can manually omit existing cache entries.
> 
> I just ran into this while migrating away from the deprecated `updateQuery` and instead using a custom merge function.
> I'm willing to help out and implement something if we can decide on a direction/intended behaviour for this.

Agreed, it's a workaround. But so far, I haven't seen any other solution that works other than using fetchMore.
I'm surprised this isn't solved yet, as it wasn't an issue before hence is a newly introduced bug.

**Comment by JeffJankowski** [comment] 2021-01-20 00:35
> I'm surprised this isn't solved yet, as it wasn't an issue before hence is a newly introduced bug.

Agreed. I think these various regressions should be taking priority..

**Comment by SeanSanker** [comment] 2021-01-28 12:32
Same issue here

**Comment by wprod** [comment] 2021-02-02 15:19
Same issue

**Comment by panutat** [comment] 2021-02-13 06:42
Please fix this thank you

**Comment by mvincent7891** [comment] 2021-03-19 18:40
Same issue.

**Comment by CaleBanfield** [comment] 2021-04-20 04:57
Same issue here.

i.e. in an infinitely scrolling component:
1. We load the first 20 results
2. The user then does a search and let's say 3 results are returned

In this case, all 20 results are still displayed but the first 3 results are replaced by the results returned by the search.

**Comment by gregoryforel** [comment] 2021-05-05 15:12
I've updated to `@apollo/client@3.4.0-beta.23`, and it seems to work.
Here's the [codesandbox](https://codesandbox.io/s/playing-with-apolloclient-3-cache-forked-zoejq?file=/src/index.tsx)
If you don't see any data, the graphql api might be revoked. To generate a new one, go to [fakeql.com](https://fakeql.com), and generate a new one. (A blog api for instance)
Then copy the url in the `index.tsx` file.

**Comment by hwillson** [comment] 2022-01-04 11:50
This should be resolved in `@apollo/client@latest` - let us know if not.

**Closed by hwillson** 2022-01-04 11:50 UTC

**Comment by christiansaavedra** [comment] 2022-01-20 05:02
> This should be resolved in `@apollo/client@latest` - let us know if not.

Im still having this issue

**Comment by Yair-Ohana** [comment] 2022-11-27 15:25
> This should be resolved in `@apollo/client@latest` - let us know if not.

Having the same exact issue, any updates there?
